### ISSUE TITLE
gapi.client.youtube is not loaded in my react file

### ISSUE THREAD

**Issue by MPanahandeh** [DefinitelyTyped/DefinitelyTyped#19380] opened 2017-08-27 23:24 UTC
I have used this commands: 
separately once ===>   npm install --save @types / gapi.youtube

and once with ==> npm install --save @types /gapi

but it seems it does not detect gapi.client.youtube interface

see error below:
RROR in [at-loader] ./src/components/App.tsx:32:41
    TS2339: Property 'youtube' does not exist on type 'typeof client'.

**Comment by MPanahandeh** [comment] 2017-08-27 23:28
wrong place

**Comment by phartley** [comment] 2018-04-27 17:39
I'm having the same problems on an Angular project. Any movement on this?

**Comment by pranavjindal999** [comment] 2018-09-15 15:45
I'm having same issue despite installing both types and declaring it in compiler options

![image](https://user-images.githubusercontent.com/5094327/45588068-693b6580-b92c-11e8-99d3-f4a08e80fa63.png)

**Comment by masscreation** [comment] 2019-05-06 19:29
Has there been any change on this?

**Comment by alexturpin** [comment] 2019-12-27 03:01
The issue is also documented here https://github.com/Bolisov/google-api-typings-generator/issues/2. Unfortunately, the resulting PR was closed before it could be merged https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21303#issuecomment-355133151.

Here is the workaround I'm using:
```
// gapi-youtube.d.ts file in my own project
declare namespace gapi.client.youtube {
	const activities: youtube.ActivitiesResource;
	const captions: youtube.CaptionsResource;
	const channelBanners: youtube.ChannelBannersResource;
	const channelSections: youtube.ChannelSectionsResource;
	const channels: youtube.ChannelsResource;
	const commentThreads: youtube.CommentThreadsResource;
	const comments: youtube.CommentsResource;
	const fanFundingEvents: youtube.FanFundingEventsResource;
	const guideCategories: youtube.GuideCategoriesResource;
	const i18nLanguages: youtube.I18nLanguagesResource;
	const i18nRegions: youtube.I18nRegionsResource;
	const liveBroadcasts: youtube.LiveBroadcastsResource;
	const liveChatBans: youtube.LiveChatBansResource;
	const liveChatMessages: youtube.LiveChatMessagesResource;
	const liveChatModerators: youtube.LiveChatModeratorsResource;
	const liveStreams: youtube.LiveStreamsResource;
	const playlistItems: youtube.PlaylistItemsResource;
	const playlists: youtube.PlaylistsResource;
	const search: youtube.SearchResource;
	const sponsors: youtube.SponsorsResource;
	const subscriptions: youtube.SubscriptionsResource;
	const superChatEvents: youtube.SuperChatEventsResource;
	const thumbnails: youtube.ThumbnailsResource;
	const videoAbuseReportReasons: youtube.VideoAbuseReportReasonsResource;
	const videoCategories: youtube.VideoCategoriesResource;
	const videos: youtube.VideosResource;
	const watermarks: youtube.WatermarksResource;
}
```

**Comment by orta** [comment] 2021-06-07 13:22
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:22 UTC
