### ISSUE TITLE
Definitions for x3dom

### ISSUE THREAD

**Issue by doczoidberg** [DefinitelyTyped/DefinitelyTyped#1883] opened 2014-03-20 11:03 UTC
definition files for x3dom would be awesome
 http://www.x3dom.org/ 
 https://github.com/x3dom/x3dom

**Comment by zacnomore** [comment] 2020-03-11 12:44
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/1883

**Closed** 2024-02-13 21:42 UTC
Labels: Definition:Request
