### ISSUE TITLE
[@types/react-redux] 6.0.10 fails to resolve thunks

### ISSUE THREAD

**Issue by rhys-vdw** [DefinitelyTyped/DefinitelyTyped#30740] opened 2018-11-21 23:18 UTC
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @surgeboris

Hi @surgeboris, I see that your recent changes intend is to "properly support thunks". However they seem to have had the exact opposite effect in our code base!

This code works in 6.0.9:

```ts
export const OrderForm = connect(
  (state: State) => ({
    order: getOrder(state),
    initialOrder: Order.createEmpty(),
    isConfirming: isConfirming(state),
    externalQuote: getExternalQuote(state),
    panelQuote: getPanelQuote(state),
  }),
  {
    onCancel: cancelOrder,
    fetchExternalQuote,
    fetchPanelQuote,
    fetchQuoteQueued,
    confirmOrder,
    createOrder,
  }
```

The new error in 6.0.10:

```
Argument of type 'typeof OrderForm' is not assignable to parameter of type 'ComponentType<Matching<{ order: Readonly<PermittedOrderParams>; initialOrder: PermittedOrderParams; isConfirming: boolean; externalQuote: Readonly<ThirdPartyQuote>; panelQuote: Readonly<PanelQuote>; } & { ...; }, Props>>'.
  Type 'typeof OrderForm' is not assignable to type 'ComponentClass<Matching<{ order: Readonly<PermittedOrderParams>; initialOrder: PermittedOrderParams; isConfirming: boolean; externalQuote: Readonly<ThirdPartyQuote>; panelQuote: Readonly<PanelQuote>; } & { ...; }, Props>, any>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'Matching<{ order: Readonly<PermittedOrderParams>; initialOrder: PermittedOrderParams; isConfirming: boolean; externalQuote: Readonly<ThirdPartyQuote>; panelQuote: Readonly<PanelQuote>; } & { ...; }, Props>' is not assignable to type 'Readonly<Props>'.
        Types of property 'confirmOrder' are incompatible.
          Type 'ThunkAction<void, State, void, Action<any>>' is not assignable to type '(usabilityTestId: number, priceInCents: number) => void'.
```

This was all working perfectly before, in fact 6.0.9 (which I'll be sticking to for now) was fantastic in that I was able to remove many of my type hacks. With your new version I'm forced to go back to my old tricks:

```ts
const mapDispatchToProps = {
  onCancel: cancelOrder,
  fetchExternalQuote,
  fetchPanelQuote,
  fetchQuoteQueued,
  confirmOrder,
  createOrder,
}

export const OrderForm = connect(
  (state: State) => ({
    order: getOrder(state),
    initialOrder: Order.createEmpty(),
    isConfirming: isConfirming(state),
    externalQuote: getExternalQuote(state),
    panelQuote: getPanelQuote(state),
  }),
  {
    onCancel: cancelOrder,
    fetchExternalQuote,
    fetchPanelQuote,
    fetchQuoteQueued,
    confirmOrder,
    createOrder,
  }
  // :'(
  mapDispatchToProps as Pick<ImplProps, keyof typeof mapDispatchToProps>
)(Impl)
```

**Comment by rhys-vdw** [comment] 2018-11-21 23:19
Alternatively you could provide some guidance on how these types are intended to be used?

**Comment by threehams** [comment] 2018-11-22 07:40
I've just hit this in a very new project. This action creator:
```
export const clickTile = (x: number, y: number) => {
  return (dispatch: Dispatch, getState: () => State) => {
    const state = getState();
    if (selectTile(state, { x, y }).status !== "dug") {
      return dispatch(updateTile(x, y));
    }
  };
};
```

is added to this connect:
```
export const Tile = connect(
  (state: State, props: Pick<Props, "x" | "y">) => {
    return selectTile(state, { x: props.x, y: props.y });
  },
  { clickTile, startSelection },
)(TileBase);
```
When moused over:
![dispatch inference](https://user-images.githubusercontent.com/1399894/48888186-acabc780-ede6-11e8-9445-0d37f6c52ebe.png)
The typings are cutting out the outer function, not the thunk.

**Comment by surgeboris** [comment] 2018-11-22 07:49
@threehams Correct, that's the usecase I haven't thought about.

I'll address it with the follow up PR. I'm going to expand type definition to check if the function returned by ThunkActionCreator also returns a function, and if it is - I'll cut the inner one.

**Comment by rhys-vdw** [comment] 2018-11-22 07:51
@surgeboris 

> I suspect that in your codebase the problem is in ImplProps. Can you post it here along with the ConfirmOrder actual type signature?

// `Props` is aliased as `ImplProps`
```ts
interface Props {
  availableCountries: ReadonlyArray<string>
  isConfirming: boolean
  panelQuote: Readonly<PanelQuote>
  externalQuote: Readonly<ThirdPartyQuote>
  usabilityTestId: number
  confirmOrder: (usabilityTestId: number, priceInCents: number) => void
  createOrder: (
    usabilityTestId: number,
    targetPanel: Panel,
    order: Readonly<PermittedOrderParams>
  ) => void
  order: Readonly<PermittedOrderParams>
  fetchQuoteQueued: () => void
  fetchPanelQuote: (
    usabilityTestId: number,
    order: Readonly<PermittedOrderParams>
  ) => void
  fetchExternalQuote: (
    usabilityTestId: number,
    order: Readonly<PermittedOrderParams>
  ) => void
  initialOrder: Readonly<PermittedOrderParams>
  onCancel: () => void
}
```

And these are the action creator thunks:

```ts
export const fetchExternalQuote = (
  usabilityTestId: number,
  order: Readonly<PermittedOrderParams>
): AsyncThunkAction<State> => async dispatch => {
  // ...
}

export const fetchPanelQuote = (
  usabilityTestId: number,
  order: Readonly<PermittedOrderParams>
): AsyncThunkAction<State> => async dispatch => {
 // ...
}

export const confirmOrder = (
  usabilityTestId: number,
  princeInCents: number
): ThunkAction<State> => dispatch => {
 // ...
}

export const createOrder = (
  usabilityTestId: number,
  targetPanel: Panel,
  order: Readonly<PermittedOrderParams>
): AsyncThunkAction<State> => async dispatch => {
 // ...
}
```

And for completeness here is my `AsyncThunkAction` helper:
```ts
import { ThunkAction as ReduxThunkAction } from "redux-thunk"
import { Action } from "redux"

export type ThunkAction<State, Return = void> = ReduxThunkAction<
  Return,
  State,
  void,
  Action<any>
>
export type AsyncThunkAction<State, Return = void> = ThunkAction<
  State,
  Promise<Return>
>
```

**Comment by rhys-vdw** [comment] 2018-11-22 07:53
@surgeboris 

> You can take a look at the test I wrote.

Your test is has a specific `Promise` return type. I wonder if this is why it passes? I haven't had a chance to look into it.

**Comment by surgeboris** [comment] 2018-11-22 07:57
> Your test is has a specific Promise return type. I wonder if this is why it passes? I h
@rhys-vdw I did not understood the issue fully. Now that you've posted complete information - your issue is about parametrized thunks, which is something I haven't thought about.

I'll try to address it in the follow up PR once I'll have some spare time for that (ETA end of the week to land the PR, and I'm not sure when exactly it will be merged).

**Comment by Kovensky** [comment] 2018-11-22 08:38
This is happening even with non-parametrized thunks. The problem is that the unwrapping is expanding to be the thunk function itself (the thing that receives dispatch, getState, etc from the store) instead of being the action creator returning the thunk's result.

This does cause invoking the function to have the correct return type (hooray), but it has the wrong parameter types.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/73085/48890817-3908c980-ee7d-11e8-9e27-6ec255685bf3.png">

```ts
declare const mapped: WithThunkActionCreators<typeof dispatch>
const dispatch = {
  foo(): ThunkAction<true, void, void, AnyAction> {
    return dispatch => {
      dispatch({ type: 'foo' })
      return true
    }
  }
}
const result = mapped.foo()
```

**Comment by surgeboris** [comment] 2018-11-22 08:47
> This is happening even with non-parametrized thunks. The problem is that the unwrapping is expanding to be the thunk function itself (the thing that receives dispatch, getState, etc from the store) instead of being the action creator returning the thunk's result.

Thank you very much for clarification. It's definitely an oversight from my side.

> This does cause invoking the function to have the correct return type (hooray), but it has the wrong parameter types.

It's because the initial concern and in my codebase was about return types, and I focused to much on it, forgetting about proper types for the parameters. I'll address that as quickly as possible.

**Comment by Kovensky** [comment] 2018-11-22 08:59
I think we need TS 3.1 features to correctly type the result; it should be something like

```ts
type UnwrappedThunk<T extends (...args: any[]) => any> =
  T extends (...args: infer A) => (dispatch: (action: any) => any, getState: () => any, extra: any) => infer R
    ? (...args: A) => R
    : T
```

**Comment by rhys-vdw** [comment] 2018-11-22 11:12
Thanks @surgeboris :-)

**Comment by surgeboris** [comment] 2018-12-12 14:11
Should work in @types/react-redux@6.0.11

Can you check and (if issue is resolved) close this issue?

**Comment by jony89** [comment] 2019-08-05 11:08
This issue still exists, for async function provided to mapDispatchToProps the outer function is omitted.

**Comment by orta** [comment] 2021-06-07 13:14
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:14 UTC
