### ISSUE TITLE
[@types/color] Type parameter 'T' has a circular default

### ISSUE THREAD

**Issue by lifenautjoe** [DefinitelyTyped/DefinitelyTyped#41835] opened 2020-01-24 12:57 UTC
- [X] I tried using the `@types/color` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/color
  - Authors: @@jameswlane @BeeeQueue

```

 ERROR  ERROR in /Users/lifenautjoe/Documents/code/okuna/okuna-web/node_modules/@types/color/index.d.ts(13,40):                              nuxt:typescript 13:54:14
13:40 Type parameter 'T' has a circular default.
    11 | type ColorParam = Color | string | ArrayLike<number> | number | { [key: string]: any };
    12 |
  > 13 | interface Color<T extends ColorParam = ColorParam> {
       |                                        ^
    14 |     toString(): string;
    15 |     toJSON(): Color<T>;
    16 |     string(places?: number): string;
```

**Comment by BeeeQueue** [comment] 2020-01-24 13:08
What typescript version are you on?

**Comment by BeeeQueue** [comment] 2020-01-24 13:11
Duplicate of #41612

**Comment by orta** [comment] 2021-06-07 13:08
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:08 UTC
