### ISSUE TITLE
[@types/ramda]: Please update ts-toolbelt to latest version (or stop using it altogether)

### ISSUE THREAD

**Issue by KSXGitHub** [DefinitelyTyped/DefinitelyTyped#41510] opened 2020-01-10 12:35 UTC
Version of `ts-toolbelt` used by `@types/ramda` declares global modules and names, it causes errors of duplication when I want to use `ramda` with other packages that also use `ts-toolbelt` or having two packages in my monorepo use `ramda`.

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TheHandsomeCoder, @donnut, @mdekrey, @mrdziuban, @sbking, @afharo, ...

If you do not mention the authors the issue will be ignored.

**Comment by mattrothenberg** [comment] 2020-04-15 14:12
@Igorbek I can confirm that `@types/react-query` is also affected by this. I have an application that uses both react-query _and_ ramda. Typescript fails to compile, due to the global namespace pollution that @KSXGitHub describes.

**Comment by Igorbek** [comment] 2020-04-15 15:10
Ah, that's sad. I can move from using it and use `typescript-tuple` instead.

**Comment by mattrothenberg** [comment] 2020-04-15 15:22
Thanks @Igorbek !

**Comment by KSXGitHub** [comment] 2020-04-15 16:14
> Ah, that's sad. I can move from using it and use `typescript-tuple` instead.

You may not need to. `typescript-tuple` has fewer features, and I don't think the latest version of `ts-toolbelt` still uses global namespace.

**Comment by Igorbek** [comment] 2020-04-15 16:36
I totally admire `ts-toolbelt` has more features but in terms of tuples, `typescript-tuple` has some superior features like working with finite/infinite tuples more precisely. Anyway, `ts-toolbelt` needs to be updated for the latest version in `ramda`.

**Comment by KSXGitHub** [comment] 2020-04-15 16:40
> `typescript-tuple` has some superior features like working with finite/infinite tuples more precisely

Well thanks. I'm flattered.

**Comment by millsp** [comment] 2020-09-18 12:23
@KSXGitHub, is this still a problem?

**Comment by KSXGitHub** [comment] 2020-09-18 12:29
@millsp IIRC, I worked around this problem by stop using ramda (I wrote my own library), so I don't know.

**Comment by millsp** [comment] 2020-09-18 12:50
I can confirm that it's fixed, you can close the issue

**Comment by KSXGitHub** [comment] 2020-09-18 12:56
@millsp I'm not sure. Even the latest version of `ts-toolbelt` still has `declare module "..."`. I'm pretty sure this problem will occur again in the future.

**Comment by millsp** [comment] 2020-09-18 13:05
I see. Sorry about that. Will fix soon

**Comment by millsp** [comment] 2020-09-18 13:34
Not actually. The problem was caused by `declare module "index"` which I changed to `declare module "ts-toolbelt"`. This is exactly how the upcoming type bundling feature is going to work https://github.com/microsoft/TypeScript/pull/39277. No problem.

**Comment by orta** [comment] 2021-06-07 13:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:09 UTC
