### ISSUE TITLE
@types/superagent error TS2304: Cannot find name 'XMLHttpRequest'.

### ISSUE THREAD

**Issue by yeiniel** [DefinitelyTyped/DefinitelyTyped#12044] opened 2016-10-17 21:40 UTC
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

Today my builds start failing due to errors on @type/superagent. I start lowering the version number until i found that the problem start with version 2.0.34. Before that no error is produced by the Typescript compiler (using Version 2.1.0-dev.20161017)

With @types/superagent@2.0.34 the error is:
  node_modules/@types/superagent/index.d.ts(79,12): error TS2304: Cannot find name 'XMLHttpRequest'.

And with @types/superagent@2.0.35 the error is:
  node_modules/@types/superagent/index.d.ts(79,12): error TS2304: Cannot find name 'XMLHttpRequest'.

I hope this info help you guys.

**Comment by vvakame** [comment] 2016-10-19 12:45
Do you use `--lib dom` option for tsc?

**Comment by yeiniel** [comment] 2016-10-19 15:01
No i don't. And i'm not sure if this helps but in reality my direct dependency is supertest. I use it for unit testing server side code.

**Comment by andyfleming** [comment] 2016-10-25 08:17
@vvakame — Adding `"dom"` to my `compilerOptions.lib` array in `tsconfig.json` did the trick. This seems a little counterintuitive. Should this be the expected behavior or is this just a temporary workaround?

**Comment by vvakame** [comment] 2016-10-25 15:22
disclaimer: I'm not superagent user.
I think it is expected behaviour.

https://www.npmjs.com/package/superagent
> elegant & feature rich browser / node HTTP with a fluent API

work around.

```
interface XMLHttpRequest {}
```

**Comment by ShaharHD** [comment] 2017-02-23 15:18
The only issue I have with adding `"dom"` to my `tsconfig.json` is that I didn't have a `lib` section in my file, and now that I have it I need to include other libs by default like `"es2016"`.

Maybe there's an automated way to fix this? which doesn't require modifying `tsconfig.json`?

**Comment by phra** [comment] 2017-04-16 22:37
adding `["dom", "es2017"] to lib fixed this.

**Comment by zephyrec** [comment] 2017-04-16 23:16
The only issue I have with adding "dom" to my tsconfig.json is that i'm writting server side code. Therefore it doesn't make any sense to me to add that lib. XMLHttpRequest is not shipped with Node.js and the superagent package did not throw and error on Node.js. The problem is with the @typings package not using XMLHttpRequest conditionally i think.

**Comment by baronfel** [comment] 2017-05-01 17:10
ran into this today as well.  If we can't conditionally provide/exclude certain types, should we consider providing two versions of these types for node and dom usage?

**Comment by JasonKleban** [comment] 2017-06-21 01:21
You can add a superagent.d.ts file with these contents:

```

// error TS2304: Cannot find name 'XMLHttpRequest'
declare interface XMLHttpRequest {}
// error TS2304: Cannot find name 'Blob'
declare interface Blob {}
```

**Comment by timruffles** [comment] 2017-06-23 15:05
@vvakame it's really not 'expected behaviour' for a library designed for node *or* DOM use to require typings for both in both environments. Using this library requires people to add typings that could easily cause bugs, as you will not see compiler warnings when accessing browser globals in node.

**Comment by bajtos** [comment] 2017-09-22 07:42
We have been bitten by this in https://github.com/strongloop/loopback-next too. By adding `dom` lib, the global namespace is suddenly polluted with types like `Request` that don't exist in Node.js 

We are writing HTTP server stack, so we usually do `import {ServerRequest as Request} from 'http'`. However, when this line is accidentally omitted, or `ServerRequest` is not aliased as `Request`, then TypeScript happily compiles our code and the error is spotted at runtime only. In other words, TypeScript is no longer able to catch errors at compile time, which defeats the purpose.

**Comment by jwalton** [comment] 2018-04-26 16:46
I'm just starting a new project, and I thought I would be clever and get around this by switching from supertest to chai-http, but chai-http uses @types/supertest.  -_-

**Comment by pbassut** [comment] 2018-09-30 05:57
Any updates on this?

**Comment by inakianduaga** [comment] 2018-12-08 08:58
A simple workaround is to use a different typescript configuration for running the tests that extends your original and tweaks it. So you create the file `tsconfig.test.json`:

```json
{
  "extends": "./tsconfig.prod.json",
  "compilerOptions": {
    "lib": ["dom", "..."] // supertest requires dom for type definitions to work
  }
}
```

(alternatively you could just set compiler flag `skipLibCheck:true` instead of tweaking the libs and that will skip typechecking for all `node_modules`)

If you're using `ts-jest` you can tell it to use your config via 

```json
"jest": {
        "globals": {
            "ts-jest": {
                "tsConfig": "tsconfig.test.json"
            }
        }
}
```

**Comment by carnesen** [comment] 2019-03-07 21:27
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33517 fixes this issue but that PR is prevented by being merged by an error 
```
chai-http depends on superagent but has a lower required TypeScript version
```
I interpret this to mean that @types/superagent can't update it's TypeScript requirement to 3.0+ until all the @types packages that depend on @types/superagent have also updated their TypeScript requirement to 3.0+. To me that seems like a flaw in the @types system because it pegs my TypeScript version to the oldest TypeScript version of all the things that depend on me. 

Is anyone out there able to confirm my understanding of that error message and if so is there any way around it?

 Absent a better permanent fix like in that PR, I resolved the issue in my application doing like so:
```
/// <reference lib="dom" />
import request = require('supertest');
```
That "triple-slash" lib directive will work in TypeScript version 3.0+.

**Comment by duro** [comment] 2019-04-05 20:43
It's been almost 2.5 years since this issue was opened! How can we get this resolved.

**Comment by bajtos** [comment] 2019-04-08 12:46
FWIW, the problem goes away when you enable TypeScript's compiler option `skipLibCheck`.

When `skipLibCheck` is enabled, TypeScript will not check any `.d.ts` files - both from dependencies like `@types/superagent` but also any `.d.ts` files you may have in your project. You can remove `dom` from your libs and the compiler will not complain anymore.

As a nice side effect, `skipLibCheck` usually significantly improves build speed too.

**Comment by G-Rath** [comment] 2019-04-08 19:51
@bajtos This can open you up to errors, as it reduces type safety.

**Comment by SalathielGenese** [comment] 2019-04-09 21:12
- `lib: [ "es6" ]` worked
- `target: "es2016+"` also worked for me

**Comment by rjmunro** [comment] 2019-04-10 15:04
@G-Rath Unless I misunderstand, it's not going to reduce type safety of your code, only of d.ts files, most of which are likely part of node modules and not your code anyway.

**Comment by carnesen** [comment] 2019-04-10 15:37
Regarding skipLibCheck, that is not a viable workaround IMO. From https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck "depending on what the errors were, the compiler may recover from them in a way that causes problems elsewhere in the code to go unnoticed (for example, by replacing an erroneous type with any), hence suppressing type errors (whether by --skipLibCheck, //@ts-ignore, or any other means) is a risky practice"

**Comment by G-Rath** [comment] 2019-04-10 18:32
@carnesen you bet me to it - that was the exact stackoverflow question I was going to quote :joy:

@rjmunro there you go 😃

**Comment by Hufschmidt** [comment] 2019-04-11 07:36
I think the cleanest solution really is the PR #33517 by @carnesen which adds the `dom` library as external reference to the `superagent` type definition, since the references to `Blob` and `XMLHttpRequest` are required by the `superagent` type definitions but not by its implementation, depending on the way its used (_browser vs node_).

The only real downside is that the lib reference requires typescript version 3.0.0 which has now been release roughly 9 month ago.
I'm not sure if this would only affect chai-http (see [Travis-CI](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/500455918?utm_source=github_status&utm_medium=notification) or if there are other dependencies that would need their typescript version to be bumped to 3.0.0

**Comment by vdhpieter** [comment] 2019-06-19 09:43
Any updates? It's again 2 months later... 

After reading all of this the cleanest solution currently available is from @carnesen but does not work for me :-( 
```ts
/// <reference lib="dom" />
import request = require('supertest');
```

I also checked his PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33517) but the TravisCI error does not make sense because `chai-http` does not require a TS version lower than 3.0...

I'm pretty new to TypeScript so if I'm doing something wrong let me know. I just submitted exactly the same code @carnesen  did in a new PR to dig deeper in the Travis CI logs (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36282)

**Comment by mikeyamato** [comment] 2019-06-21 16:48
> // error TS2304: Cannot find name 'XMLHttpRequest'
> declare interface XMLHttpRequest {}
> // error TS2304: Cannot find name 'Blob'
> declare interface Blob {}

@JasonKleban where does this file go? In `node_modules` > `superagent`? I've been trying to figure this out and I'm at my wits' end.

**Comment by JasonKleban** [comment] 2019-06-21 17:25
@mikeyamato - I can't remember where I used it successfully, but not in node_modules since you don't manage those files yourself.  Instead it's probably just alongside your other source files.  You would have tried that first, I assume.  No change?

You can also experiment with the tsconfig.json typings folder setting?

**Closed** 2019-07-03 16:40 UTC
Labels: @types

**Comment by fiznool** [comment] 2020-01-06 14:05
With the merging of #36282, there is a new problem. When using superagent in a node-only project, the introduction of the triple-slash directive

``` ts
/// <reference lib="dom" />
```

results in the DOM typings being transparently added to the project. Since this is a node-only project, however, there is no DOM, and so code such as

``` ts
window.setTimeout()
```

should result in a TypeScript error. Since the DOM typings are silently included, this is not the case, and can lead to subtle bugs in the codebase.

Is there a way that we can include node-only or browser-only typings into a project, so we can choose which to use?

**Comment by SerCeMan** [comment] 2020-01-19 04:53
Another side effect of having a dependency is `dom` is that it prevents `supertest` (`superagent`) to be used in a project with `lib: webworker`, ref: https://github.com/microsoft/TypeScript/issues/20595.  As far as I can see, this has not been mentioned before.

**Comment by smprime** [comment] 2020-06-29 08:03
$ npm i @types/superagent@latest -D

Should do the trick!

**Comment by thesmarthub** [comment] 2021-04-29 18:05
> $ npm i @types/superagent@latest -D
> 
> Should do the trick!

This is straight forward and it just works.

**Comment by shlomo-artlist** [comment] 2022-01-16 14:37
I've given up - I removed `@types/supertest` and `@types/superagent` from all my projects.
To me, it's remarkable that such a mainstream library in the NodeJS + TS community would not want to support normal expected behavior, and will tell us to make dangerous workarounds like allowing Browser types or ignoring declaration files.

**Comment by carnesen** [comment] 2022-01-16 15:14
@shlomo-artlist Keep in mind that this is open-source software maintained by unpaid volunteers. You're welcome to contribute constructive suggestions/fixes if you have the time and energy, but announcing your rage quit isn't particularly helpful or motivating. In any case, the latest `@types/superagent` no longer includes the `dom` library by triple-slash reference nor does it require the `dom` types. It does however require `@types/node` >=v15.7.0  or >=v14.18.0. See also https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58124#discussioncomment-1951079

**Comment by shlomo-artlist** [comment] 2022-01-16 15:38
I'm sorry about the tone - it wasn't intended to be angry.  I didn't find any solution to this issue that I can use with my limitations, and I wanted to let other people know about it too, so they won't feel like they miss something here.

We use NodeJS v14.16.1 in all our projects, and we can't upgrade them right now, nor we can use any of the above suggestions. So currently we cannot use this essential library with typescript, which makes it hard for us to use this library at all. Is there any other version that can support older node versions? 

I did not know this is working on some node versions.
I will update the comment to be more informative rather than "angry". 
Thanks.

**Comment by carnesen** [comment] 2022-01-16 16:20
@shlomo-artlist No worries, I edited my comment too. Thank you for summarizing the state of affairs. The dependency on `@types/node` >=v15.7.0 or >=v14.18.0 arises from references to the ambient type `Blob` first introduced in those versions. Probably we could make the new `dom`-less types more `@types/node` backwards-compatible by instead declaring `Blob` ourselves in `@types/superagent` e.g.:

```
interface Blob {
    readonly size: number;
    readonly type: string;
    arrayBuffer(): Promise<ArrayBuffer>;
    slice(start?: number, end?: number, contentType?: string): Blob;
    stream(): NodeJS.ReadableStream;
    text(): Promise<string>;
}
```

cc @alecgibson

**Comment by jan-san** [comment] 2022-01-17 08:46
@shlomo-artlist did you try this with node v14.18?

While `Blob` was added to node in v14.18.0, it hasn't been added to @type/node@14 yet it seems - in the v16 types, it's defined [in buffer.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/919bec8e612d6ead92be449786963050b2cf62e0/types/node/v16/buffer.d.ts#L119), but there's no mention of it in [the corresponding v14 definition file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v14/buffer.d.ts).

This would mean that `@types/node` >=v15.7.0 for things to work out of the box

**Comment by alecgibson** [comment] 2022-01-17 08:52
@jan-san we're using this with `@types/node` `14.18.5` — what error are you seeing?

**Comment by jan-san** [comment] 2022-01-17 09:18
@alecgibson I still get this build error:
> node_modules/@types/superagent/index.d.ts:34:29 - error TS2304: Cannot find name 'Blob'.

Same with `@types/node` `14.18.6`, which has been released today.
Where is the definition of `Blob` coming from in your project? I cannot find any reference to it in the node type package (`grep -R Blob node_modules/@types/node/` returns no match)

**Comment by alecgibson** [comment] 2022-01-17 10:02
@jan-san it looks like in my build it's _somehow_ being dragged in from `node/stream/consumers.d.ts`, where it "is not, and should not be, exported." 🙈 😱 

<img width="944" alt="Screenshot 2022-01-17 at 09 57 51" src="https://user-images.githubusercontent.com/12036746/149748342-48857820-a09b-439a-a7c7-f954d02f1aab.png">

At any rate, you're right — the `Blob` type is missing from `@types/node`, so I've raised https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58233

Let's see what happens there; if it doesn't get merged for some reason, then we may have to do as @carnesen suggests and include the typing directly in `@types/superagent` itself.

**Comment by jan-san** [comment] 2022-01-19 03:37
@alecgibson thanks a lot for getting that PR merged on `@types/node`. I just tried it again with the updated types, but still get the same error.

That's because `Blob` is not defined as a global inside `@types/node`, but inside the `buffer` module. So we'd still need to import that type in `@types/superagent`:
```js
import { Blob } from 'buffer';
```

**Comment by alecgibson** [comment] 2022-01-19 11:34
@jan-san I've raised https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58312

**Comment by alecgibson** [comment] 2022-01-26 08:12
@jan-san `Blob` fix has been merged in `@types/superagent`.

**Comment by asmith2306** [comment] 2022-01-26 09:58
> @jan-san `Blob` fix has been merged in `@types/superagent`.

Hi, will there a release version that contains this fix?  Currently using "@types/superagent": "^4.1.15".  Thanks.
