### ISSUE TITLE
[d3-array][d3-contour] no exported member 'ThresholdArrayGenerator'

### ISSUE THREAD

**Issue by bvuong** [DefinitelyTyped/DefinitelyTyped#29550] opened 2018-10-09 02:51 UTC
Hello, #25450 seems to have been released as a patch for d3-array and d3-contour even though it is a breaking change. Is there any way this can be released as a backwards-compatible minor version or major version change instead? Thanks!

For more context, my project depends on `d3-ng2-service`, which is pinned to a minor version. This change now causes the error:
```
ERROR in node_modules/d3-ng2-service/index.d.ts(2,65): error TS2305: Module '"/root/project/client/node_modules/d3-ng2-service/src/bundle-d3"' has no exported member 'ThresholdArrayGenerator'.
```
I don't think there is any workaround on my end since I don't have any control over `d3-ng2-service`, but please let me know if there is!

_Originally posted by @bvuong in https://github.com/DefinitelyTyped/DefinitelyTyped/commit_comment/create#commitcomment-30821791_

**Comment by mzhu11** [comment] 2018-10-09 15:10
We have the same issue with d3-ng2-service, the error is as below
`d3-ng2-service/src/bundle-d3"' has no exported member 'ThresholdArrayGenerator'.`

**Comment by Ledragon** [comment] 2018-10-31 11:13
cc @denisname @tomwanzek 
The afore mentioonned breaking change seems to have more impact than expected, anything we can do on our side?

**Comment by denisname** [comment] 2018-10-31 16:57
This problem has been solved. Use @types/d3-array 1.2.4.

**Comment by Ledragon** [comment] 2019-01-03 14:41
@bvuong @mzhu11 can you confirm the problem is fixed, and close the issue if it is?

**Comment by orta** [comment] 2021-06-07 16:37
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 16:37 UTC
