### ISSUE TITLE
jest: jest.fn, Mock, MockInstance, SpyInstance are not properly typed (requires breaking change)

### ISSUE THREAD

**Issue by fgrandel** [DefinitelyTyped/DefinitelyTyped#32901] opened 2019-02-08 13:35 UTC
### Breaking Change

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

 - Authors: @antoinebrault 

Just as a follow-up to our discussion (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32864#discussion_r254924337), I open this ticket, so I we can properly discuss the issue and track progress.

Currently the types mentioned in the title of this issue are all typed `Xyz<SomeReturnType, SomeParamArray>` rather than being typed `Xyz<SomeFunction>` which is the intention of the underlying jest API.

This introduces redundancy and error potential.

IMO it would be better to template the mentioned types with a single parameter extending from a generic function type and derive return type and argument type where needed (via `ReturnType<F>`, `ArgsType<F>`). See the sample code in the PR referenced above.

**Update**: As @antoinebrault  has correctly pointed out this still requires migration from 23.x (other than I first assumed), as the return type `<T>` will have to be replaced by the function type `<F>`. Still the fact that this fixes mocking of functions with generics is a strong argument in favour of this change (see my next comment).

**Comment by jerico-dev** [comment] 2019-02-09 15:31
There is another problem being introduced by the return type + args type approach: additional meta-information like generics is lost, e.g. templated functions cannot be properly mocked:

```
someMethod<T>(...): T {  ... }
```

The `Mock<X, Y ...>` solution will now infer `T` to be `{}` for `someMethod()` rather than the actual type in any given context.

The solution with `fn<F>()` and `Mock<F>` will forward the full definition of `someMethod()` to sub-types. Specifically the definition of `Mock<F>` as `F & MockInstance<F>` resolves this problem (tested).

I can provide an executable example of this if the above wasn't clear enough as I just stumbled upon this problem in my own code.

So this is now not only a regression but a bug. My existing code can no longer be migrated from 23.x to 24.x. Hope this makes up an even stronger argument why this is a regression and not a feature.

**Comment by jerico-dev** [comment] 2019-02-11 13:21
@antoinebrault: Could you review the PR - it's probably not mergeable yet but I'd like to know whether it goes in the right direction.

**Comment by antoinebrault** [comment] 2019-02-11 14:07
> @antoinebrault: Could you review the PR - it's probably not mergeable yet but I'd like to know whether it goes in the right direction.

I'll look at it tonight.

> @NickyMeuleman: Can you try whether this PR fixes your upgrade problem?

It shouldn't, because T was always the ReturnType. It was never a function like your PR.

**Comment by jerico-dev** [comment] 2019-02-19 14:13
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @Hotell @sebald @andys8 @geovanisouza92 @aldentaylor 

Could one of the maintainers please comment or close the issue as "won't fix" if the attached PR is not acceptable?

**Comment by SimenB** [comment] 2019-02-19 17:04
Jest maintainer here 👋 I don't really know TS beyond basic usage, but I thought I'd chime in on

>Currently the types mentioned in the title of this issue are all typed `Xyz<SomeReturnType, SomeParamArray>` rather than being typed `Xyz<SomeFunction>` which is the intention of the underlying jest API.

That seems suboptimal - it's indeed better to infer the arguments and return types from a function rather than specifying them separately. `jest.fn()` is conceptually just a function, and it's shape should get inferred from a function, not by passing separate type params.

IDK what's considered breaking changes and how you deal with them in this project, though, so feel free to ignore me 🙂 I might also very well have misunderstood what this issue is about 😀

**Comment by Jessidhia** [comment] 2019-02-22 07:44
An easy example of this becomes a practical issue (beyond just correctness) is attempting to use `jest.fn(() => null)` as a React element. `() => null` is a perfectly cromulent component that renders nothing, but because the type of `Mock` also adds a construct signature, it becomes an invalid constructor that is still constructible to typescript, somehow (even though you're allowed to return almost arbitrary things from a constructor, primitives such as `null` are ignored).

That, and `() => ({})` is not constructible anyway, even if it returns an object, as it is an arrow function. The same as `jest.fn(class {})` should not be callable, but `jest.fn` creates a call signature for it.

**Comment by sormy** [comment] 2019-04-12 21:48
I would also add that `23.3.14` must be recalled as it is not backward compatible with `23.3.13`.

**Comment by dsebastien** [comment] 2019-08-23 08:04
+1 on improving the typings for Jest mocks.

I've spent quite some time trying to figure out a way to create strongly typed mocks and it was far from straightforward.

I've ended up using the following in my project:

```
export type MockOf<T> = {
  [K in keyof T]: T[K] extends (...args: infer A) => infer B ?
    T[K] & jest.Mock<B, A> : T[K]
};
```

**Comment by antoinebrault** [comment] 2019-08-23 12:46
@dsebastien How about using jest.Mocked<T> ?

**Comment by orta** [comment] 2021-06-07 13:38
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:38 UTC
