### ISSUE TITLE
typescript import material-ui works but import components doesn't

### ISSUE THREAD

**Issue by apoberez** [DefinitelyTyped/DefinitelyTyped#7887] opened 2016-01-30 16:33 UTC
why this works

```
import * as Material from 'material-ui';
...

<Material.Table></Material.Table>
```

but this doesn't: 

```
import * as Table from 'material-ui/lib/table/table'
```

i get error: error TS1192: Module ''material-ui/lib/table/table'' has no default export.
as well as this:

```
import Table from 'material-ui/lib/table/table'
```

tsconfig:

```
{
  "compilerOptions": {
    "target": "es6",
    "sourceMap": true,
    "jsx": "preserve"
  },
  "files": [
    "../typings/tsd.d.ts"
  ]
}
```

webpack:

```
...
            {
                loader: 'babel-loader?presets[]=es2015&presets[]=react!ts-loader',
                test: /\.tsx?$/,
                exclude: /node_modules/
            }
...
```

works only:

```
import Table = require('material-ui/lib/table/table');
```

```
...
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": true,
    "jsx": "React"
  },
  "files": [
    "../typings/tsd.d.ts"
  ]
}
...
```

```
...
{
        loader: 'ts-loader',
        test: /\.tsx?$/,
        exclude: /node_modules/
},
...
```

**Comment by use-strict** [comment] 2016-02-10 14:50
It looks like some time in December material-ui switched from CommonJS to ES6 format. This is a breaking change in material-ui v0.15. The TypeScript definitions were written for v0.13 and haven't been updated yet.

**Comment by ngbrown** [comment] 2016-02-26 00:08
The definitions were updated to export ES6 `default` for material-ui v0.14 in pull-request #7354.  However, I'm not 100% clear on what the most compatible way is for TypeScript definition files going forward is.

Personally I use TypeScript in ES6 mode then Babel and then Webpack.  But I can't assume everyone uses that?

**Comment by dupski** [comment] 2016-03-26 16:03
I've been trying to use just awesome-typescript-loader with webpack and these definitions (I prefer just using a single transpiler + packager), but keep running into

```JSX element type '...' does not have any construct or call signatures```

But the funny thing is it still compiles and runs. Most annoying.

**Comment by CreepGin** [comment] 2016-04-23 19:46
**Solution**: 

`import { Table } from 'material-ui'`

**Comment by use-strict** [comment] 2016-04-25 10:43
@CreepGin , that results in the entire library being included in the bundle, that is assuming you are using webpack.

**Comment by dalexander01** [comment] 2016-08-10 17:23
Anyone get this working? I'm having trouble importing material ui components as well.

**Comment by dalexander01** [comment] 2016-08-12 20:45
@ngbrown how are you importing material-ui components? Is something like

import {Table} from 'material-ui' the only way?

**Comment by ngbrown** [comment] 2016-08-12 20:50
@dalexander01 I think only the ES6 way works.  The way specified in their documentation works:

    import {Table, TableBody, TableHeader, TableHeaderColumn, TableRow, TableRowColumn} from 'material-ui/Table';

or

    import Subheader from 'material-ui/Subheader';

If you are using ES6 and it's not working, what is the error message you are encountering?

Hope that helps.

**Comment by kellenp** [comment] 2016-11-03 20:47
Is this issue resolved? It looks like MUI has been updated to 1.16 in the latest DT package.

**Comment by dupski** [comment] 2016-11-03 23:12
Hey @kellenp, I'm using MUI with TypeScript without any issues now so this can be closed from my side

**Comment by olee** [comment] 2016-12-18 21:43
I am still getting errors like `Cannot find module 'material-ui/RaisedButton'`, however it still runs.
I guess the typings need to be updated?

**Comment by ncknuna** [comment] 2017-06-14 04:31
I'm getting these errors too (e.g. `Could not find a declaration file for module 'material-ui/styles/MuiThemeProvider'`), even though I can find the module declarations inside the @types/material-ui. Is there just something misconfigured about my tsconfig?

**Comment by jef-sure** [comment] 2017-06-19 18:12
I have the same question. I tried to use mobx+react+typescript+material-ui, but I cant make material-ui to work with typescript.

**Comment by a1astair** [comment] 2017-06-26 23:03
Any update on this? I am still getting the `does not have any construct...` error

**Comment by Aristona** [comment] 2017-06-27 07:54
I'm also having the same issue.

**Comment by nickpisacane** [comment] 2017-07-12 20:56
For anyone having the "Cannot Find Module" error with sub-directory imports (e.g `import RaisedButton from 'material-ui/RaisedButton'), it seems adding "material-ui" to "types" in `.tsconfig` fixes the issue, thereby including the declaration file without importing the whole material-ui lib. Probably a noob thing to point out (i'm pretty new to typescript), but hope it helps!

**Comment by ncknuna** [comment] 2017-07-13 19:05
Oh, thanks @nickpisacane! When I first read your comment and then read the docs here (https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) I thought I would have to specify types for all of my installed packages, because of this: "If types is specified, only packages listed will be included." Turns out it seems to work fine though, so I don't know what that documentation actually means, so this is resolved for me at least :)

**Comment by gitsupersmecher** [comment] 2017-10-11 04:27
Could someone post a complete solution? I just looked into Material-UI, and using it with typescript. 

The set-up is tsc -> es6 and webpack -> index.js.

   "compilerOptions": {
        "module": "es6", 
        "target": "es6",
        "moduleResolution": "node",
        "baseUrl": ".",
        "types" : ["material-ui"],

The code is simple: 

`
import * as React from "react";
import * as ReactDOM from "react-dom";
import {AppBar} from 'material-ui';

export class AppLoader extends React.Component < any, any > {

    public constructor(props) {
        super(props);
    }

    public render(): JSX.Element {
        return ( <div> <AppBar  title="Title"    />   </div>);
    }
}

ReactDOM.render(<AppLoader/>, document.getElementById("root"));
`

**Comment by wskidmore** [comment] 2017-10-11 21:55
@gitsupersmecher if you are using the latest mui, mui components are required to be children (at any level) of a theme provider component as the theme provider sets up [context](https://reactjs.org/docs/context.html), which is the root cause of your error message.

http://www.material-ui.com/#/get-started/usage

**Comment by lrn2prgrm** [comment] 2017-12-13 15:22
JSX element type 'Tabs' does not have any construct or call signatures. This is the error I get. I used all combiations i could think of i.e. 
import { Tabs, Tab } from 'material-ui/Tabs';

**Comment by mankityau** [comment] 2020-05-31 00:53
Is there any update on the situation?

I am having a similar situation.
I am trying to use `import { ExpandMore, ExpandLess } from "@material-ui/icons";` for the icons.
My IDE (IntelliJ) is warning with a message `TS2307: Cannot find module '@material-ui/icons' or its corresponding type declarations.`
(Even though, it compiles and work)

However, when I modify my tsconfig.json from using `compilerOptions > module: es6` to `compilerOptions > module: es5` solves the issue.

**Comment by orta** [comment] 2021-06-07 13:31
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:31 UTC
