### ISSUE TITLE
Pouchdb-core constructor options does not include size

### ISSUE THREAD

**Issue by intersides** [DefinitelyTyped/DefinitelyTyped#24446] opened 2018-03-21 16:02 UTC
- [x] I tried using the `@types/pouch-core` package and had problems.
- Authors: @trubit @AGBrown @geppy @fredgalvao

The size option is not present in the new PouchDb() constructor : ex: new PouchDB('mydb', {size: 10});
[https://pouchdb.com/errors.html#not_enough_space](url)
This makes Safari keep popping up  a message asking to increase memory when the local db runs out of space since the default size is 5Mb.

**Comment by intersides** [comment] 2018-03-21 16:04
maybe the solution is in

` namespace Configuration {

        interface CommonDatabaseConfiguration {

           name?: string;

           adapter?: string;

           size?: number;  //<-- HERE

        }

....

`

**Comment by fredgalvao** [comment] 2018-03-21 20:05
I also think the propper solution is to include `size?: number;` on the `CommonDatabaseConfiguration`. Feel free to contribute on a PR ;)

**Comment by intersides** [comment] 2018-03-22 06:57
Frederico, I have made the modifications on a separate branch after cloning the DefinitelyTyped project. When I try to push my branch I get a permission denied error using my current github user "intersides" . Am I missing an intermediate step ?

**Comment by fredgalvao** [comment] 2018-03-22 07:03
I don't remember a permission error being even possible, let alone caused by user mistake.
If anything, I'd suggest following step-by-step what's described at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#how-can-i-contribute, and if the error persists, then I'm as lost as you.

**Comment by orta** [comment] 2021-06-07 13:18
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:18 UTC
