### ISSUE TITLE
[@types/webrtc] Type 'RTCPeerConnection' has no construct signatures

### ISSUE THREAD

**Issue by FeleConvo** [DefinitelyTyped/DefinitelyTyped#43634] opened 2020-04-04 17:53 UTC
- [x] I tried using the `@types/webrtc` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chriskrycho @NullVoxPopuli @manjuks1991 @nakakura

---

Hey guys, 

Using WebRTC types to migrate my project to TypeScript and I found that there is no constructor declared for RTCPeerConnection:

Exact error is: _TS2351: This expression is not constructable.   Type 'RTCPeerConnection' has no construct signatures_

as shown below:

![image](https://user-images.githubusercontent.com/35459194/78457995-b0ab5300-7684-11ea-91f0-aafa2cc84cde.png)

This is in the docs here: [https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection)

Am I missing something trivial here? Is there a fix or way around it?

Thanks for your great work.

Best regards.

**Comment by NullVoxPopuli** [comment] 2020-04-04 18:05
According to: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection

I don't think `null` is a valid `configuration`. 
the parameter is optional, but that'd mean that `undefined` would be allowed, rather than `null`.

**Comment by FeleConvo** [comment] 2020-04-04 18:10
@NullVoxPopuli Actually null works, but the point is that passing `null` or `undefined` or a configuration object generate the same error shown above.

**Comment by NullVoxPopuli** [comment] 2020-04-04 18:10
what if you pass nothing?

**Comment by chriskrycho** [comment] 2020-04-04 18:38
@NullVoxPopuli it’s unrelated to the arguments. The problem is something in how the `new`-able interface definition (instead of a normal `class`) definition is set up, [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/da93d7b13094bacb170ead3f4a289f3b8687e4e5/types/webrtc/RTCPeerConnection.d.ts#L342). I’m not really sure why this was set up the way it is (I don’t actually know why I got pinged here, either, as I’m not an author!), but normally this would just be done with a `class` definition. 🤔

**Comment by orta** [comment] 2021-06-07 13:33
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:33 UTC
