### ISSUE TITLE
[@types/react] fragments in react 16

### ISSUE THREAD

**Issue by hecof** [DefinitelyTyped/DefinitelyTyped#20249] opened 2017-10-03 17:36 UTC
- [ ] I tried using the `@types/react` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I think you should consider to update these lines of code in order to support react 16 fragments

```javascript 
render(): JSX.Element | null | false | string | JSX.Element[]; //class Component<P, S>
interface ElementClass extends React.Component<any> {
    render(): Element | null | false | string | Element[];
}
```

https://reactjs.org/blog/2017/09/26/react-v16.0.html

**Comment by anwarjaved** [comment] 2017-10-03 17:37
I have the same issue, I am getting this error

`ERROR in [at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3470:13
    TS2403: Subsequent variable declarations must have the same type.  Variable 'audio' must be of type 'DetailedHTMLProps<AudioHTMLAttributes<HTMLAudioElement>, HTMLAudioElement
>', but here has type 'DetailedHTMLProps<AudioHTMLAttributes<HTMLAudioElement>, HTMLAudioElement>'.

ERROR in [at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3576:13
    TS2403: Subsequent variable declarations must have the same type.  Variable 'video' must be of type 'DetailedHTMLProps<VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement
>', but here has type 'DetailedHTMLProps<VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>'.
Child html-webpack-plugin for "index.html":`

**Comment by goenning** [comment] 2017-10-03 18:22
There is an open PR for this #19363

Current workaround is to use `public render(): any { }` on the components.

**Comment by hecof** [comment] 2017-10-03 19:02
Yep! you are right I forgot to mention this workaround . Thanks a lot!

**Comment by pabloes** [comment] 2017-11-25 00:34
I'm still having issues with a functional component like this, any idea?
```
function MyComponent() {
    return [<div>1</div>, <div>2</div>];
}
```
https://stackoverflow.com/questions/47481482/react-16-fragment-functional-component-and-typescript-ts2605/47481524#47481524

**Comment by mekwall** [comment] 2017-11-29 17:02
This issue should be extended to also cover the improvements to Fragments in react 16.2.

Now you should be able to return `<></>` and `<React.Fragment></React.Fragment>`, none of which currently works.

**Comment by nicobrinkkemper** [comment] 2017-11-30 12:46
How about this? 

`const Fragment = (React as any).Fragment;`

**Comment by ssalka** [comment] 2017-12-01 02:35
For anyone wanting to avoid an extra `const`, I'm currently doing this:

```
declare module 'react' {
  class Fragment extends React.Component {}
}
```

so `<React.Fragment>` can be used 🙂

**Comment by maciejsikora** [comment] 2018-01-08 11:28
Hi All,
something maybe change in supporting this?

**Comment by chibicode** [comment] 2018-03-23 03:45
Should be fixed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21950

**Comment by nickbreaton** [comment] 2019-08-16 18:38
Just stumbled upon this linked in my codebase. Looks like the issue is fixed now per the comment above and my personal test. 

@hecof Might be good to close this.

**Comment by eps1lon** [comment] 2020-08-13 12:49
This is essentially a duplicate of #18912. Once  Microsoft/TypeScript#21699 is resolved we should be able to use `ReactNode` as a valid return type for function components which includes `string` and `boolean`.

**Comment by orta** [comment] 2021-06-07 14:12
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:12 UTC
