### ISSUE TITLE
[@types/sinon ] Property 'createStubInstance' does not exist on type 'Sinon.Sandbox'.

### ISSUE THREAD

**Issue by ChristophAtAdlos** [DefinitelyTyped/DefinitelyTyped#21954] opened 2017-12-04 19:43 UTC
- [ ] I tried using the `@types/sinon` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @MrBigDog2U @rationull @lumaxis @nicojs @43081j 

Is there a reason why the createStubInstance is not defined? 
Conforming http://sinonjs.org/releases/v4.1.2/sandbox/ it should exist.

**Comment by janis91** [comment] 2017-12-05 06:19
duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21940

**Comment by micksatana** [comment] 2017-12-25 09:29
@ChristophAtAdlos could you help close this issue? It's already fixed in the referred PR above.

Cheers

**Comment by fatso83** [comment] 2020-11-24 14:39
This should be closed.

**Closed** 2021-06-07 13:20 UTC
