### ISSUE TITLE
[@types/twitter] When i tried to import this module in typescript, it prompt me an error that *this is not a module*

### ISSUE THREAD

**Issue by OwaisIbrahim** [DefinitelyTyped/DefinitelyTyped#28002] opened 2018-08-09 16:37 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by chitoku-k** [comment] 2018-12-21 06:46
Due to #30635, `@types/twitter` has been moved to `@types/twitter-for-web`. 

The issue did not reproduce here because as the error message says, this is not a module but a type definition. For instance, the code below compiles without any errors:

```typescript
twttr.ready((t) => {
    t.events.bind('loaded', (ev) => {
    });
});
```

Tested on tsc Version 3.2.2

**Comment by orta** [comment] 2021-06-07 13:17
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:17 UTC
