### ISSUE TITLE
Broken definition for the callback parameter of the then method for @types/selenium-webdriver

### ISSUE THREAD

**Issue by adityagautam** [DefinitelyTyped/DefinitelyTyped#17359] opened 2017-06-21 14:33 UTC
I am converting a Protractor page object library from JavaScript to Typescript. I have a static utility method that refreshes until an element is present (or the timeout limit is reached).
For some reason, I am unable to use a boolean valued promise as a thenable construct and I can't figure out why. The error message is  **Error:(102, 50) TS2345:Argument of type '(isEnabled: boolean) => Promise<CloudletPolicyBean> | undefined' is not assignable to parameter of type '((value: boolean) => CloudletPolicyBean | IThenable<CloudletPolicyBean>) | undefined'.
  Type '(isEnabled: boolean) => Promise<CloudletPolicyBean> | undefined' is not assignable to type '(value: boolean) => CloudletPolicyBean | IThenable<CloudletPolicyBean>'.
    Type 'Promise<CloudletPolicyBean> | undefined' is not assignable to type 'CloudletPolicyBean | IThenable<CloudletPolicyBean>'.
      Type 'undefined' is not assignable to type 'CloudletPolicyBean | IThenable<CloudletPolicyBean>'.**

The source code is below with comment showing where the compile error occurs.
This was asked in SO and people there have commented that this is indeed a error with type definition for webdriver. Can someone here please take a look.
**selenium-webdriver types used: 3.0.4
node:6.9.5
protractor:5.1.2**
```
import {browser, element, ElementFinder, ExpectedConditions} from 'protractor';
import * as wd from 'selenium-webdriver';
import {By} from "selenium-webdriver";

export class ExtendedExpectedConditions {

    public static refreshUntilElementIsPresent(element: ElementFinder,  numberOfSeconds: number = 30000,
        refreshInterval: number = 5000): void {
        this.refreshElement(element, numberOfSeconds, refreshInterval);
    }

    protected static refreshElement(element: ElementFinder, numberOfSeconds: number = 30000, refreshInterval:
        number = 5000) {


        //This line throws the compile error
        element.isPresent().then(value => {
            if (!value) {
                if (numberOfSeconds <= 0) {
                    return new wd.promise.Promise(function (resolve, reject) {
                        reject('Element cannot be found after expected retry numbers');
                    })
                }
                browser.sleep(refreshInterval).then(() => {
                    browser.refresh().then(() => this.refreshUntilElementIsPresent(element, numberOfSeconds -
                    (refreshInterval / 1000)));
                });
            }
       });
    }
}
```

**Comment by andy-ms** [comment] 2017-06-21 15:55
Duplicate of #17358

**Comment by orta** [comment] 2021-06-07 13:41
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:41 UTC
