### ISSUE TITLE
[styled-components] v4 doesn't support React Native

### ISSUE THREAD

**Issue by dawidk92** [DefinitelyTyped/DefinitelyTyped#29795] opened 2018-10-16 20:16 UTC
- [x] I tried using the `@types/styled-components@4.0.1` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster 

Latest version of @types/styled-components doesn't support React Native.

If you're trying to:
```js
import styled from "styled-components/native";
```
TypeScript throws an error:
```Error: TS7016: Could not find a declaration file for module 'styled-components/native'. '[project_path]/node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.```

Also when you're trying to:
```js
import styled from "styled-components";
```
and declare native component like this:
```js
const Test = styled.View`...`
```
it also throws an error:
`Error: TS2551: Property 'View' does not exist on type 'ThemedBaseStyledInterface<any>'. Did you mean 'view'?`

**Comment by dawidk92** [comment] 2018-10-16 20:41
Please also have in mind to support possibility to pass custom Theme interface into `ThemedStyledComponentsModule` connected with Native just like it's shown in [documentation](https://www.styled-components.com/docs/api#typescript) (it isn't updated to v4):
```js
// theme.ts
export default interface ThemeInterface {
  primaryColor: string;
  primaryColorInverted: string;
}
```
```js
// styled-components.ts
import * as styledComponents from "styled-components";
import { ThemedStyledComponentsModule } from "styled-components";

import ThemeInterface from "./theme";

const {
  default: styled,
  css,
  injectGlobal,
  keyframes,
  ThemeProvider
} = styledComponents as ThemedStyledComponentsModule<ThemeInterface>;

export { css, injectGlobal, keyframes, ThemeProvider };
export default styled;
```

**Comment by ReggaePanda** [comment] 2018-10-18 18:00
same issue here
https://github.com/styled-components/styled-components/issues/2099#event-1910748544

**Comment by zhigang1992** [comment] 2018-10-20 01:37
I think current workarounds are:

1. Keep using `styled-components@3`
1. Instead of `styled.View`, do `styled(View)` instead.

A small drawback with 2nd approach is that you need to import `View`, back you get to use the latest version.

Also there was PR https://github.com/styled-components/styled-components/pull/1844

But I doing think it was carried over to this repo.

**Comment by limianwang** [comment] 2018-12-16 05:16
Any updates to this? Any plans in having a type definitions for react-native?

**Comment by glauberfc** [comment] 2018-12-17 22:01
Any updates to this?

**Comment by egorAva** [comment] 2018-12-20 08:51
> I think current workarounds are:
> 
> 1. Keep using `styled-components@3`
> 2. Instead of `styled.View`, do `styled(View)` instead.
> 
> A small drawback with the 2nd approach is that you need to import `View`, but you get to use the latest version.
> 
> Also, there was PR [styled-components/styled-components#1844](https://github.com/styled-components/styled-components/pull/1844)
> 
> But I dont think it was carried over to this repo.

If i try use  2nd approach, i catch exeption :
```
Type '{ children: Element[]; }' has no properties in common with
type 'IntrinsicAttributes & Pick<Pick<ViewProps &
RefAttributes<View>, "style" | "hitSlop" | "onLayout" | "pointerEvents" |
"removeClippedSubviews" | "testID" | "nativeID" 
| ... 38 more ... | "ref"> & Partial<...>, "style" | ... 44 more ... 
| "ref"> & { ...; } & { ...; }'.
```
I have a code:
```
const Wrapper = styled(View)`
  background-color: #fff;
  flex: 1;
`;

class Search extends Component {
  render() {
    retrurn(
      <Wrapper>
        <Text>Search</Text>
      </Wrapper>
    );
  }
}
```

**Comment by zhigang1992** [comment] 2018-12-20 10:45
@egorAva that's due to new changes in React.d.ts

See my comments here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30536#issuecomment-448489437

**Comment by pie6k** [comment] 2019-01-10 12:07
Maybe there could be different types package for different case

eg. if you use plain react use `@types/styled-components` otherwise use `@types/styled-components-native`

**Comment by wrod7** [comment] 2019-01-25 22:23
🧐

**Comment by kallaspriit** [comment] 2019-01-29 08:21
I've read the various issues and tried the suggestions but I'm still lost. Is there currently any reasonable way to use styled-components with react-native in TypeScript?

**Comment by pie6k** [comment] 2019-01-29 17:15
@egorAva I did the same - downgraded to v3.

**Comment by mtford90** [comment] 2019-02-03 12:17
So react native has been dropped?

**Comment by JKillian** [comment] 2019-02-05 19:00
There's nothing blocking anyone from making a PR to add a `native.d.ts` to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/styled-components is there? It shouldn't be too difficult to use most of the existing infrastructure in the already written `index.d.ts` to accomplish this

**Comment by elyalvarado** [comment] 2019-02-05 23:11
@JKillian where is that `native.d.ts`?

**Comment by JKillian** [comment] 2019-02-05 23:20
@elyalvarado Someone has to write it! 😄 It's definitely a non-trivial task to understand the existing types, but it still should be doable to add typings for `styled-components/native`

**Comment by JKillian** [comment] 2019-02-06 20:41
I've made [a PR to add typings for `styled-components/native`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843), please feel free to review!

**Comment by JKillian** [comment] 2019-02-12 23:18
Fixed now that [`@types/styled-components@4.1.9` is published](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843#issuecomment-462943858)! This issue should be closable as the typings provide basic support for `styled-components/native` now. Please let me know if anyone runs into issues!

**Comment by appsolutegeek** [comment] 2019-02-13 11:13
Great news! Testing now, thanks for this. Was really looking forward to using styled-components with react native

**Comment by flavordaaave** [comment] 2019-02-23 14:12
@JKillian according to the [docs](https://www.styled-components.com/docs/api#typescript) you should re-export the styled function with `ThemedStyledComponentsModule` and passing the individual theme interface to it.

Unfortunately I wasn't able to find a `ThemedStyledComponentsModule` interface in your typings. Any chance you could add this as well?

**Comment by Sharcoux** [comment] 2020-03-18 18:30
I'm having the problem again with v5.0.1...

**Comment by Sharcoux** [comment] 2020-03-18 18:32
Fixed by installing `npm i -D @types/styled-components`. Sorry for disturbing.

**Comment by miyacoz** [comment] 2020-12-20 02:31
i just got the same error by running `yarn upgrade styled-components @types/styled-components`.
it didn't change my `package.json` but only `yarn.lock` as `@types/styled-components` from 5.1.5 to 5.1.7, but i found something kinda suspicious...

```diff
@@ -1316,13 +1353,6 @@
   resolved "https://registry.yarnpkg.com/@types/prop-types/-/prop-types-15.7.3.tgz#2ab0d5da2e5815f94b0b9d4b95d1e5f243ab2ca7"
   integrity sha512-KfRL3PuHmqQLOG+2tGpRO26Ctg+Cq1E01D2DMriKEATHgWLfeNDmq9e29Q9WIky0dQ3NPkd1mzYH8Lm936Z9qw==

-"@types/react-native@*":
-  version "0.63.42"
-  resolved "https://registry.yarnpkg.com/@types/react-native/-/react-native-0.63.42.tgz#d0baf405edc646d15d5a7f8e67983b8701c1ea2a"
-  integrity sha512-zb7m2Uwfz6MQh/Nq1DDAmzTRO+EQWV7ZyRl9ZZ2QLd1480xjRjPDQqRkp4vuk3gyRlQtwi0v9I3tOh2IxHFujw==
-  dependencies:
-    "@types/react" "*"
-
 "@types/react-native@^0.63.2":
   version "0.63.37"
   resolved "https://registry.yarnpkg.com/@types/react-native/-/react-native-0.63.37.tgz#c43df90c9d3cc082a97a49a53e989de26cb8ab45"
@@ -1376,13 +1406,12 @@
   integrity sha512-l42BggppR6zLmpfU6fq9HEa2oGPEI8yrSPL3GITjfRInppYFahObbIQOQK3UGxEnyQpltZLaPe75046NOZQikw==

 "@types/styled-components@^5.1.5":
-  version "5.1.5"
-  resolved "https://registry.yarnpkg.com/@types/styled-components/-/styled-components-5.1.5.tgz#a98e2ead1a1c7660b966f3aade4df9c0ec8ed75a"
-  integrity sha512-VWwoKm39W783a75oILtdCjnNn+FSV8Yh3O9naIudtZCAkk+rRfwLWzuPjf5k/OilENgZqAkxJ9sukSOZTAD86g==
+  version "5.1.7"
+  resolved "https://registry.yarnpkg.com/@types/styled-components/-/styled-components-5.1.7.tgz#3cd10b088c1cb1acde2e4b166b3e8275a3083710"
+  integrity sha512-BJzPhFygYspyefAGFZTZ/8lCEY4Tk+Iqktvnko3xmJf9LrLqs3+grxPeU3O0zLl6yjbYBopD0/VikbHgXDbJtA==
   dependencies:
     "@types/hoist-non-react-statics" "*"
     "@types/react" "*"
-    "@types/react-native" "*"
     csstype "^3.0.2"

 "@types/yargs-parser@*":
```

it's a part of the diff of my `yarn.lock` after the upgrade, but i'm wondering why it's removing the dependency for `@types/react-native`.
also i confirmed `native.d.ts` has disappeared from `./node_modules/@types/styled-components/` after the upgrade.

---

anyway i'll just stay on 5.1.5 though, i'm not in hurry for the upgrade 😂

**Comment by orta** [comment] 2021-06-23 08:10
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-23 08:10 UTC

**Comment by Sharcoux** [comment] 2021-06-24 07:56
By the way, there is [rn-css](https://www.npmjs.com/package/rn-css) which is using typescript and probably more fitted for RN projects than styled-components. Maybe it can help some of you.
