### ISSUE TITLE
Checks failing with unrelated notarget No matching version found for typescript@3.7

### ISSUE THREAD

**Issue by sumurthy** [DefinitelyTyped/DefinitelyTyped#40054] opened 2019-10-31 19:42 UTC
I get this error in the / DefinitelyTyped.BenchmarkPR check step. 
Any idea why this is happening? 

```
2019-10-31T19:13:21.8395022Z npm ERR! code ETARGET
2019-10-31T19:13:21.8396141Z npm ERR! notarget No matching version found for typescript@3.7.
2019-10-31T19:13:21.8396606Z npm ERR! notarget In most cases you or one of your dependencies are requesting
2019-10-31T19:13:21.8398474Z npm ERR! notarget a package version that doesn't exist.
2019-10-31T19:13:21.8398945Z 
2019-10-31T19:13:21.8399417Z npm ERR! A complete log of this run can be found in:
2019-10-31T19:13:21.8400166Z npm ERR!     /home/vsts/.npm/_logs/2019-10-31T19_13_17_383Z-debug.log
2019-10-31T19:13:21.8400504Z 
2019-10-31T19:13:21.8442903Z { Error: Command failed: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links
2019-10-31T19:13:21.8443873Z npm ERR! code ETARGET
2019-10-31T19:13:21.8445930Z npm ERR! notarget No matching version found for typescript@3.7.
2019-10-31T19:13:21.8446726Z npm ERR! notarget In most cases you or one of your dependencies are requesting
2019-10-31T19:13:21.8447955Z npm ERR! notarget a package version that doesn't exist.
2019-10-31T19:13:21.8448684Z 
2019-10-31T19:13:21.8449170Z npm ERR! A complete log of this run can be found in:
2019-10-31T19:13:21.8450087Z npm ERR!     /home/vsts/.npm/_logs/2019-10-31T19_13_17_383Z-debug.log
2019-10-31T19:13:21.8452129Z 
2019-10-31T19:13:21.8474562Z     at ChildProcess.exithandler (child_process.js:294:12)
2019-10-31T19:13:21.8475407Z     at ChildProcess.emit (events.js:198:13)
2019-10-31T19:13:21.8475903Z     at maybeClose (internal/child_process.js:982:16)
2019-10-31T19:13:21.8476445Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2019-10-31T19:13:21.8476897Z   killed: false,
2019-10-31T19:13:21.8477502Z   code: 1,
2019-10-31T19:13:21.8478577Z   signal: null,
2019-10-31T19:13:21.8479121Z   cmd:
2019-10-31T19:13:21.8480318Z    'npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links' }
2019-10-31T19:13:21.8624938Z ##[error]Bash exited with code '1'.
2019-10-31T19:13:21.8659955Z ##[section]Finishing: Run comparisons
```

If you do not mention the authors the issue will be ignored.

**Comment by kylechine** [comment] 2019-11-01 00:24
Me too.

It happened because the test script was trying to test with every version of TypeScript from 2.0 to the Next version (nightly built version). Now the nightly built version is 3.8 while 3.7 is just disappeared.

You may try `npm install typescript@3.7' // not working; While `npm install typescript@next` will install 3.8

I guess it happened because some maintainer of TypeScript team delete TypeScript 3.7 by accident.

**Comment by jessetrinity** [comment] 2019-11-01 17:31
We bumped a version too early. This broke the second check you see on PRs `DefinitelyTyped.DefinitelyTyped`, but should be fixed. We were seeing other issues with `BenchmarkPR` so my guess is that the error has propagated to the that pipeline while it is being worked on.

At any rate, BenchmarkPR failing is not being treated as a blocker for PRs at this time so you do not need to report further failures here. Thanks!

**Comment by andrewbranch** [comment] 2019-11-01 19:56
Sorry all, I accidentally pulled in a version of dtslint that was requiring TypeScript 3.7 stable to exist on npm, which doesn’t until next week. I’ve just downgraded and confirmed things are working again.

**Closed by andrewbranch** 2019-11-01 19:56 UTC
