### ISSUE TITLE
[@testing-library/cypress] Missing JQuery typings

### ISSUE THREAD

**Issue by simjes** [DefinitelyTyped/DefinitelyTyped#40099] opened 2019-11-03 10:09 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aaronmcadam, @bastibuck, @NoriSte, @wKovacs64, @existentialism, @airato

After the latest release of typings for `@testing-library/cypress` (`5.0.1`) there is an issue where it won't find required JQuery typings. 

The typings for `@testing-library/cypress` depends upon `Cypress 3.5.0`, where the correct JQuery typings are included, but I assume the reason that this breaks in real projects is because of npm flattening dependencies. 

I tried adding `/// <reference typings="cypress" />` explicitly to `index.d.ts`, but then there is a typings collision with Jest since they also declare typings in the global scope.

I would love to get some input on a solution for this. 

#39394

**Comment by wKovacs64** [comment] 2019-11-03 16:02
Do we have a reproduction repo for this? `@types/testing-library__cypress@5.0.1` and `cypress@3.6.0` are working fine together for me in a couple different real projects.

**Comment by aleccool213** [comment] 2019-11-04 15:43
I am getting the same result. I am using `@types/testing-library__cypress@5.0.1` and `cypress@3.6.0`. The reason it won't work for me is that I am using pnpm and it requires every repo declare transitive dependancies. 

cc: @elliottsj

**Comment by wKovacs64** [comment] 2019-11-05 17:30
Both downshift and your reproduction are missing `"types": ["cypress"]` in `tsconfig.json` ([docs](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json)). That seems to fix both projects on my end.

**Comment by simjes** [comment] 2019-11-06 16:15
doh, I updated the repo 🤦. Could you take another look @wKovacs64 ?

Seems to work fine in the IDE, but running `tsc` still gives me the same error.

**Comment by wKovacs64** [comment] 2019-11-06 16:53
A couple things going on after your changes:

- you have to use `tsc --project cypress` if you have a nested `tsconfig.json` like that
- your Cypress `tsconfig.json` is missing `esnext` from the `lib` array (you'll probably get `IterableIterator` errors without it)
  - could use `extends` in the nested one as an alternative, but it probably doesn't matter

**Comment by AlgusDark** [comment] 2019-11-07 08:11
@wKovacs64 wouldn't be better to explicit JQuery?

```
import {
  configure,
  Matcher,
  MatcherOptions as DTLMatcherOptions,
  SelectorMatcherOptions as DTLSelectorMatcherOptions
} from '@testing-library/dom'
import 'cypress/types/jquery'
```

**Comment by wKovacs64** [comment] 2019-11-07 17:42
@AlgusDark Not sure, but the Cypress docs mention using the `types` option to avoid conflicts:

> The `types` will tell the TypeScript compiler to only include type definitions from Cypress. This will address instances where the project also uses `@types/chai` or `@types/jquery`. Since Chai and jQuery are namespaces (globals), incompatible versions will cause the package manager (`yarn` or `npm`) to nest and include multiple definitions and cause conflicts.

I suspect if your project used `@types/jquery` and the version didn't match the jQuery types bundled with Cypress, you'd run into conflicts by importing like that.

@NicholasBoll might have a more informed opinion here.

**Comment by NicholasBoll** [comment] 2019-11-26 07:18
Global types are tricky. VS Code and the Typescript compiler try to be smart and include them all. On collisions you have to do extra work. A solution for a simple project doesn't work for a project with workspaces. Sometimes the `types` solution works (sometimes VS Code needs the included Typescript service restarted). Sometimes file paths need to be included in the tsconfig just so you can exclude them. Every so often VS Code tries to be smart and downloads `@types/cypress` which are outdated type definitions.

Most of the time the Cypress docs work. Occasionally I've had to fiddle with tsconfig files to get everything working so I don't have to add `/// <reference types="cypress" />` to every test file.

I'm aware of the `@testing-library/testing` project, but unfamiliar with this issue. If the Cypress types are included (note: _not_ `@types/cypress`), then jQuery types come with it. A while ago @bahmutov changed the way Cypress includes types to copy on build to avoid more issues with global type definitions (aka namespaces). If the Cypress folder has a `"types": ["cypress"]`, jQuery should be included and available under `Cypress.$`. I'm not certain if jQuery is available globally.

Even if this types project explicitly imports jQuery types from the Cypress library, isn't there still a problem if a downstream project can't find the Cypress types?

**Comment by NicholasBoll** [comment] 2020-02-03 19:53
@simjes I tried out the reproduction repo you made. @wKovacs64 is correct with the updates that need to be made to reproduction. The following PR fixes the issues. Let me know if you still encounter some.

**Note:** I used `npm install`. There was a `package-lock.json` file, so I figured those were the intended locked dependencies.

**Comment by NicholasBoll** [comment] 2020-02-03 20:15
The PR I forgot to link: https://github.com/simjes/cypress-typings-reproduction/pull/1

**Comment by orta** [comment] 2021-06-07 13:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:09 UTC
