### ISSUE TITLE
Lodash's ObjectIterator have optional 'key' parameter. Should be required.

### ISSUE THREAD

**Issue by torryt** [DefinitelyTyped/DefinitelyTyped#12449] opened 2016-11-02 15:19 UTC
The interface ObjectIterator has an optional `key` parameter. This becomes an issue when trying to use the key in a context with StrictNullChecking enabled. For example, the mapValues() function use ObjectIterator as its callback function:

```typescript
mapValues(dict, (value, key) => {
  // This line throws an error because the key can be undefined
  dict[key];
  if (key) {
    // This line is OK
    dict[key];
  }
});
```
It does not makes sense to check the key for nulls while iterating a dictionary because it cannot exists values in the dictionary that does not have any keys.

I suggest we change the type of the `key` parameter in the interface ObjectIterator from `key?: string` to `key: string`. Maybe this applies for other iterator interfaces as well such as NumericDictionaryIterator and DictionaryIterator. Any comments/objections?

- The authors of that type definition are cc/ @bczengel @chrootsu @stepancar

**Comment by itaysabato** [comment] 2016-11-18 15:20
@torryt is right. I am also struggling with this (also with `forEach`, etc.)

It is wrong to define callback interfaces with optional parameters when the parameters are guaranteed to be supplied to the callback. See for example the standard `Array.forEach` method defined in [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L1225).

Please fix!

Thanks.

**Comment by aj-r** [comment] 2017-04-14 22:53
Duplicate of #11516

**Comment by aj-r** [comment] 2018-04-14 23:07
This is fixed now

**Closed** 2021-06-07 13:27 UTC
