### ISSUE TITLE
Big.js in global scope prone to causing errors when used in Node

### ISSUE THREAD

**Issue by osdiab** [DefinitelyTyped/DefinitelyTyped#29304] opened 2018-10-01 04:09 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nycdotnet @googol 

because this declares the Big.js object in the global scope, when using code modularly in Node/in frontend mobile/browser codebases using webpack, where the library is not present in the global scope, the typings say that it always is; this has caused me to introduce bugs multiple times now thinking that the code is fine, but it's not.

I'm not sure how other libraries like `jquery` or what not handle this issue, or if they just have the same problems.

**Comment by osdiab** [comment] 2018-10-01 06:00
Example of bug in our codebase triggered by this: https://github.com/rahafoundation/raha-api/pull/120

**Comment by googol** [comment] 2018-10-01 09:20
Hi, you should be able to control which global types are imported with the `types` property in the `compilerOptions` of your `tsconfig.json`. When it is not specified, all global types from `node_modules/@types` will be imported. You can specify as an array the names of the packages from which to import global types. So `"types": ["big.js"]` would only import the global typesof big, and no others and an empty array will keep all the global types out of the scope.
This won't affect explicit imports or custom global typings in your source, only the ones from node_modules.

Let me know if this helps!

**Comment by osdiab** [comment] 2018-10-03 06:30
oh wow I didn't know that's how the Typescript `types` property works! That's really counterintuitive from the name of the key in `tsconfig.json`. Good to know, hope other people find this ticket for posterity for other similar problems.

**Comment by osdiab** [comment] 2018-10-03 06:49
Posted a StackOverflow question for visibility here: https://stackoverflow.com/questions/52621222/how-do-you-exclude-global-types-declared-in-typescript-definitions/52621223#52621223

**Comment by googol** [comment] 2018-10-03 08:42
Yeah the types / typeRoots is all very confusing and not so well described in the documentation.

I'm glad this helped!

**Comment by lukescott** [comment] 2019-01-17 18:14
I'm not sure what I'm doing wrong. I have `"types": []` in my compiler options, but `Big` is still showing up as global. I've restarted the TypeScript server and reloaded the project and it still loads it.

**Comment by lukescott** [comment] 2019-01-17 18:33
OK, so it looks like this shows an error:
```
let value: Big // Big is "undefined" without import
```
But this does not show an error:
```
let value = Big(0)
```
The types are not included, but the values are. It thinks `Big` is a global value... How do I fix this?

**Comment by lukescott** [comment] 2019-01-17 18:53
OK, so the advice to use `"types": []` doesn't seem to work. I thought it might be some weird thing with my project, so I created a test project to confirm. I have made two observations thus far:

1. `"types": []` does not seem to do anything with types from `big.js`
2. Typings for `big.js` seem to pollute the global name space if I import it from within my own code:
  ```ts
  // test.ts file
  import {Big} from "big.js"

  // test2.ts
  import "./test"
  Big(0) // no error as long as ./test is included
  ```

I'm at a loss here. I see `"types": []` being recommended with other type libraries, but that advice does not seem to hold with the `big.js` typings.

**Comment by ManuelMolina97** [comment] 2019-04-12 16:06
Why should this issue be closed? It's still a problem.

The `"types": []` workaround isn't working... :cry:

**Comment by googol** [comment] 2019-04-12 17:27
Hi @ManuelMolina97. Could you create a public repo containing a minimal setup that shows the issue so I could take a look?

**Comment by osdiab** [comment] 2019-06-04 19:02
@googol here's the minimal example: https://github.com/osdiab/big-global-types-issue

**Comment by ricardo-mello** [comment] 2019-10-27 00:49
I think that the problem is export the definition globally in the main file. Looking at `decimal.js` code, they moved the global definitions to a specific file to prevent errors and keep the compatibility.

@googol I will open a PR doing the same. Can you take a look, please?

**Comment by orta** [comment] 2021-06-07 16:38
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 16:38 UTC

**Comment by markulrich** [comment] 2022-05-10 01:08
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49852

**Comment by osdiab** [comment] 2022-05-10 06:46
Thanks @markulrich ! 😉
