### ISSUE TITLE
[@types/react] useRef return type clashes with ref prop type

### ISSUE THREAD

**Issue by mateja176** [DefinitelyTyped/DefinitelyTyped#35572] opened 2019-05-19 14:53 UTC
- [x] I tried using the `@types/16.8.17` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

```
Type 'MutableRefObject<HTMLDivElement | undefined>' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
  Type 'MutableRefObject<HTMLDivElement | undefined>' is not assignable to type 'RefObject<HTMLDivElement>'.
    Types of property 'current' are incompatible.
      Type 'HTMLDivElement | undefined' is not assignable to type 'HTMLDivElement | null'.
        Type 'undefined' is not assignable to type 'HTMLDivElement | null'.
```

**Comment by AdrianMrn** [comment] 2019-05-20 11:10
I currently have the same problem, have you found a solution already by any chance?

**Comment by shane935** [comment] 2019-06-03 12:48
A slightly neater solution is to set the initialValue to null in the useRef function call

`const componentRef = useRef<HTMLDivElement>(null);`

this ensures that componentRef = `HTMLDivElement | null` which is what the ref prop is expecting rather than `HTMLDivElement | undefined`.

**Comment by wcandillon** [comment] 2019-06-23 15:21
@shane935 you have made my day sir 🙌🏻

**Comment by staeke** [comment] 2019-07-29 03:25
Seems to me `undefined` should be added to `RefObject<T>.current` like:

```ts
//index.ts, line 80
interface RefObject<T> {
   readonly current: T | null;
}
```

so it reads
```ts
//index.ts, line 80
interface RefObject<T> {
   readonly current: T | null | undefined;
}
```

**Comment by Jessidhia** [comment] 2019-09-10 03:17
It's not a bug, it's catching a legitimate typing error.

For more details, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38228#issuecomment-529749802

**Comment by osf2e** [comment] 2020-04-15 06:30
Just as @Jessidhia say, it's not a bug , maybe you should write like this.
```
import React, {
  forwardRef,
  ForwardRefRenderFunction,
  useImperativeHandle,
  useRef,
  PropsWithChildren,
} from "react";

interface Props {}
interface Ref {
  value: string;
  setValue: (value: string) => void;
}

const InputEmail: ForwardRefRenderFunction<Ref, PropsWithChildren<Props>> = (
  props,
  ref
) => {
  // hooks
  const inputElement = useRef<HTMLInputElement | null>(null);
  useImperativeHandle(ref, () => {
    return {
      value: inputElement.current ? inputElement.current.value : "",
      setValue: (value: string) => {
        inputElement.current && (inputElement.current.value = value);
      },
    };
  });

  // render
  return (
    <div>
      <input
        type="text"
        ref={inputElement}
        defaultValue="admin@demo.com"
        disabled
      />
    </div>
  );
};

const Component = forwardRef(InputEmail);

export default Component;

```

**Comment by konfika** [comment] 2020-05-20 20:17
I'm no expert on this stuff, but after looking at the typings of what I was passing in as a ref and the actual ref type of the component I was passing the ref into, it seemed as though I had the interfaces wrong.

I initially had an interface of props like so for the receiving component:

`type TextboxProps = CustomProps & React.HTMLProps<HTMLInputElement>`

which I changed to:

`type TextboxProps = CustomProps & React.HTMLAttributes<HTMLInputElement>`

I'm not going to pretend I know more than I do, but looking into the typings for the HTMLProps interface and the React.forwardRef() function type you can see that it is using RefAttributes<T>. Just above that, you can see the ClassAttributes<T> type that HTMLProps<T> is extending.

**Comment by ProdigySim** [comment] 2020-08-06 18:59
It looks like this project has 3 overloads for `useRef()`, do we need all 3? It seems like the `useRef<T>(null)` case is the one developers will use most of the time.

```
    function useRef<T>(initialValue: T): MutableRefObject<T>;
    function useRef<T>(initialValue: T|null): RefObject<T>;
    function useRef<T = undefined>(): MutableRefObject<T | undefined>;
```

1. What is the expect use case of the two mutable overloads?
2. Is there some other way this can be supported to that users can more easily find the "correct" overload?

**Comment by joshribakoff** [comment] 2020-08-23 20:10
I have `RefObject`:

![Screen Shot 2020-08-23 at 1 06 16 PM](https://user-images.githubusercontent.com/4021306/90987686-b2958600-e541-11ea-8dbc-68a22a27e11a.png)

I pass it to my `Panel` component as the prop `ref`:

![Screen Shot 2020-08-23 at 1 06 04 PM](https://user-images.githubusercontent.com/4021306/90987680-b1645900-e541-11ea-880a-2646039d61e2.png)

I try to consume w/ `forwardRef`, it becomes `MutableRefObject`:

![Screen Shot 2020-08-23 at 1 06 56 PM](https://user-images.githubusercontent.com/4021306/90987683-b1fcef80-e541-11ea-85a9-834a8527d1a9.png)

I'm now unable to consume the `.current` property:

![Screen Shot 2020-08-23 at 1 10 27 PM](https://user-images.githubusercontent.com/4021306/90987746-0e600f00-e542-11ea-9e21-035469d82698.png)

**Comment by Seanmclem** [comment] 2020-10-21 01:56
Using react-native-web, I had to use. 

```javascript
import {RefObject} from 'react';
// ...
const myRef = useRef() as RefObject<View>
```

**Comment by lior-chervinsky** [comment] 2020-10-21 11:46
I had this problem with an Input so i switched from `useRef<HTMLDivElement>()` -> `useRef<HTMLInputElement>()` and it worked OK

**Comment by Tobbe** [comment] 2020-11-03 08:43
@joshribakoff You can also type the parameters directly

```
export const Panel = React.forwardRef((props: PanelProps, ref: React.RefObject<HTMLDivElement>) => {
```

That way you shouldn't have to typecast when accessing your ref.
But I still don't understand why we have to do this...

**Comment by PRFTCanoaf** [comment] 2020-12-02 22:17
I used this when passing a ref to a form:

```
const formRef = useRef<HTMLFormElement | null>(null);

return <form ref={formRef}></form>
```

**Comment by orta** [comment] 2021-06-07 13:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:11 UTC

**Comment by kenny1983** [comment] 2021-09-09 15:56
> A slightly neater solution is to set the initialValue to null in the useRef function call
> 
> `const componentRef = useRef<HTMLDivElement>(null);`
> 
> this ensures that componentRef = `HTMLDivElement | null` which is what the ref prop is expecting rather than `HTMLDivElement | undefined`.

I feel like I'm losing my @#$%ing mind here, coz @shane935 received **a lot** of love for his comment, but it produces the **exact same** error for me!

Honestly, I feel like the entire move to TypeScript from vanilla JS has been a constant battle against the over-complicated strictness of the compiler.

Now I'm stuck between a rock and a hard place: do I go back to JS and relish in the fact that simple statements like this **just work**, or do I continue on this epic journey of trying to produce "safer" code?

If I was working on a project for my boss, the answer would be obvious: @#$% off TS and go back to **actually getting work done**, instead of wasting (potentially) **weeks** on this constant fight with the TS compiler. But I'm working on my first TS project "just for fun", and although I'm not having much fun ATM, I feel as though this shouldn't be so hard and that the benefits should outweight the effort required. IDK though...what do you guys think??

**Comment by onpaws** [comment] 2021-09-10 14:26
I know what you mean @kenny1983 had similar feelings when I was starting out in TS also :)
Have worked with people who hate it and others who swear by and love it.

One 'pro' argument to static checking I've seen, but can be hard to appreciate as a developer when you're starting out and feeling suffocated by the type checker, is that when typed properly, TS checks should in principle forestall a whole category of exceptions your end users might otherwise encounter, and you might never have known about (not without analytics reporting etc). 

As you know with SPAs, including React, unhandled exceptions can be quite devastating b/c the whole app may unexpectedly just "turn white"/crash, depending. TS should help avoid at least some of the reasons for this.

**Comment by kenny1983** [comment] 2021-09-10 14:47
Thanks @onpaws for both the empathy and the example of how TS **is** worth the effort 👍.

After writing the wild rant above (LOL lets face it, that's what it was 😛) I ended up spending the rest of my night and well into the early hours of the morning reading blogs re: why people love or hate it, then listening to [a podcast from Scott Hanselman](https://www.hanselminutes.com/340/what-is-typescript-and-why-with-anders-hejlsberg) where he talks to Anders Hejlsberg about his intentions behind creating the language. I thoroughly recommend a listen!

Another great resource is [this keynote presentation](https://www.youtube.com/watch?v=3dqZW_DqHIQ) from the GOTO Conference 2012 where Anders demonstrates the power of static typing. I already knew this having come from a C# background, but it never actually dawned on me **why** C# IntelliSense and the equivalent IDE features for JS are so far apart in what they can achieve. Very cool! 😎

**Comment by hazratgs** [comment] 2022-04-06 22:30
There is another way to solve the problem:
`
export const Input = forwardRef<HTMLTextAreaElement, IInputProps>((props, ref) => {
  const inputRef = useRef<HTMLTextAreaElement | null>()

  const createRef = (node: HTMLTextAreaElement | null) => {
    inputRef.current = node
    if (typeof ref === 'function') {
      ref(node)
    } else if (ref) {
      (ref as React.MutableRefObject<HTMLTextAreaElement | null>).current = node
    }
  }

  const clickUploadFileHandler = useCallback(() => {
    if (inputRef) {
      inputRef.current?.focus()
    }
  }, [])

  return (
    <>
      <s.Input ref={createRef} />
      <FileUpload files={files} onClick={clickUploadFileHandler} />
    </>
  )
})

`

**Comment by theronburger** [comment] 2023-04-20 19:00
Had the same issue. 

I was using both  TypeScript _and_ ESLint with the react/require-default-props rule enabled.
This rule enforces that every prop that is not marked as required should have a corresponding defaultProps value. However, with TypeScript, you don't need defaultProps, as optional props and default values can be handled directly in the function signature.

To resolve the issue, you can disable the react/require-default-props rule in your ESLint configuration file (.eslintrc or similar). In your ESLint configuration file, add or update the rules section like this:

```json
{
  "rules": {
    "react/require-default-props": "off"
  }
}
```

This will disable the react/require-default-props rule, and you shouldn't see the error anymore. Since you are using TypeScript to handle optional props and default values, this rule is not necessary for your project.

**Comment by magicdawn** [comment] 2024-06-14 13:59
does anyone know TypeScript support generic Constraints like this ?

```ts
// pseudo code
type LegacyRef<T,U> = string | Ref<T> | Ref<U> where T extends U
```

current

```ts
const ref = useRef<HTMLElement>(null)
<a ref={ref}></a> 

/*
error:
Type 'RefObject<HTMLElement>' is not assignable to type 'LegacyRef<HTMLAnchorElement> | undefined'.
  Type 'RefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLAnchorElement>'.
    Type 'HTMLElement' is missing the following properties from type 'HTMLAnchorElement'
*/
```

Ref is like box/unbox, and should support super type

----

callback ref supported, but not RefObject

```ts
const ref = useRef<HTMLElement | null>(null)
<a ref={(el) => (ref.current = el)}></a>
```

**Comment by nikhila29** [comment] 2024-12-23 06:15
import { Navigate, Route, Routes, useLocation } from "react-router-dom";
import {
	// AautiRetail,
	// MetaRob,
	// RealisticAvatar,
	// ResidentialTownship,
	Services,
	// TechPark,
} from "../components";
// import ComingSoon from "../components/comingsoon";
import { routeNames } from "../routes/routeNames";
import { useEffect, useRef } from "react";


const ServicesContainer = () => {
	const educationRef = useRef(null);
	const virtualMeetingsRef = useRef(null);
	const healthCareRef = useRef(null);
	const bankingRef = useRef(null);

	const location = useLocation();

	const scrollToSection = (section: any) => {
		const strippedSection = section.replace("/services/", "");
		switch (strippedSection) {
			case routeNames.metaverseEducation:
				educationRef.current?.scrollIntoView({ behavior: "smooth" });
				break;
			case routeNames.virtualMeetings:
				virtualMeetingsRef.current?.scrollIntoView({ behavior: "smooth" });
				break;
			case routeNames.metaverseHealthCare:
				healthCareRef.current?.scrollIntoView({ behavior: "smooth" });
				break;
			case routeNames.metaverseBanking:
				bankingRef.current?.scrollIntoView({ behavior: "smooth" });
				break;
			default:
				break;
		}
	};

	useEffect(() => {
		scrollToSection(location.pathname);
	}, [location]);

	return (
		<Routes>
			<Route index element={<Navigate to={routeNames.metaverseEducation} />} />
			<Route
				path={routeNames.metaverseEducation}
				element={
					<Services
						educationRef={educationRef}
						virtualMeetingsRef={virtualMeetingsRef}
						healthCareRef={healthCareRef}
						bankingRef={bankingRef}
					/>
				}
			/>
			<Route
				path={routeNames.virtualMeetings}
				element={
					<Services
						educationRef={educationRef}
						virtualMeetingsRef={virtualMeetingsRef}
						healthCareRef={healthCareRef}
						bankingRef={bankingRef}
					/>
				}
			/>
			<Route
				path={routeNames.metaverseHealthCare}
				element={
					<Services
						educationRef={educationRef}
						virtualMeetingsRef={virtualMeetingsRef}
						healthCareRef={healthCareRef}
						bankingRef={bankingRef}
					/>
				}
			/>
			<Route
				path={routeNames.metaverseBanking}
				element={
					<Services
						educationRef={educationRef}
						virtualMeetingsRef={virtualMeetingsRef}
						healthCareRef={healthCareRef}
						bankingRef={bankingRef}
					/>
				}
			/>
		</Routes>
	);
};

export default ServicesContainer;
Compiled with problems:
×
ERROR in src/containers/servicesContainer.tsx:27:27
TS2339: Property 'scrollIntoView' does not exist on type 'never'.
    25 | 		switch (strippedSection) {
    26 | 			case routeNames.metaverseEducation:
  > 27 | 				educationRef.current?.scrollIntoView({ behavior: "smooth" });
       | 				                      ^^^^^^^^^^^^^^
    28 | 				break;
    29 | 			case routeNames.virtualMeetings:
    30 | 				virtualMeetingsRef.current?.scrollIntoView({ behavior: "smooth" });
ERROR in src/containers/servicesContainer.tsx:30:33
TS2339: Property 'scrollIntoView' does not exist on type 'never'.
    28 | 				break;
    29 | 			case routeNames.virtualMeetings:
  > 30 | 				virtualMeetingsRef.current?.scrollIntoView({ behavior: "smooth" });
       | 				                            ^^^^^^^^^^^^^^
    31 | 				break;
    32 | 			case routeNames.metaverseHealthCare:
    33 | 				healthCareRef.current?.scrollIntoView({ behavior: "smooth" });
ERROR in src/containers/servicesContainer.tsx:33:28
TS2339: Property 'scrollIntoView' does not exist on type 'never'.
    31 | 				break;
    32 | 			case routeNames.metaverseHealthCare:
  > 33 | 				healthCareRef.current?.scrollIntoView({ behavior: "smooth" });
       | 				                       ^^^^^^^^^^^^^^
    34 | 				break;
    35 | 			case routeNames.metaverseBanking:
    36 | 				bankingRef.current?.scrollIntoView({ behavior: "smooth" });
ERROR in src/containers/servicesContainer.tsx:36:25
TS2339: Property 'scrollIntoView' does not exist on type 'never'.
    34 | 				break;
    35 | 			case routeNames.metaverseBanking:
  > 36 | 				bankingRef.current?.scrollIntoView({ behavior: "smooth" });
       | 				                    ^^^^^^^^^^^^^^
    37 | 				break;
    38 | 			default:
    39 | 				break;
ERROR in src/containers/servicesContainer.tsx:54:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
  Type 'null' is not assignable to type 'HTMLDivElement'.
    52 | 				element={
    53 | 					<Services
  > 54 | 						educationRef={educationRef}
       | 						^^^^^^^^^^^^
    55 | 						virtualMeetingsRef={virtualMeetingsRef}
    56 | 						healthCareRef={healthCareRef}
    57 | 						bankingRef={bankingRef}
ERROR in src/containers/servicesContainer.tsx:55:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    53 | 					<Services
    54 | 						educationRef={educationRef}
  > 55 | 						virtualMeetingsRef={virtualMeetingsRef}
       | 						^^^^^^^^^^^^^^^^^^
    56 | 						healthCareRef={healthCareRef}
    57 | 						bankingRef={bankingRef}
    58 | 					/>
ERROR in src/containers/servicesContainer.tsx:56:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    54 | 						educationRef={educationRef}
    55 | 						virtualMeetingsRef={virtualMeetingsRef}
  > 56 | 						healthCareRef={healthCareRef}
       | 						^^^^^^^^^^^^^
    57 | 						bankingRef={bankingRef}
    58 | 					/>
    59 | 				}
ERROR in src/containers/servicesContainer.tsx:57:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    55 | 						virtualMeetingsRef={virtualMeetingsRef}
    56 | 						healthCareRef={healthCareRef}
  > 57 | 						bankingRef={bankingRef}
       | 						^^^^^^^^^^
    58 | 					/>
    59 | 				}
    60 | 			/>
ERROR in src/containers/servicesContainer.tsx:65:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    63 | 				element={
    64 | 					<Services
  > 65 | 						educationRef={educationRef}
       | 						^^^^^^^^^^^^
    66 | 						virtualMeetingsRef={virtualMeetingsRef}
    67 | 						healthCareRef={healthCareRef}
    68 | 						bankingRef={bankingRef}
ERROR in src/containers/servicesContainer.tsx:66:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    64 | 					<Services
    65 | 						educationRef={educationRef}
  > 66 | 						virtualMeetingsRef={virtualMeetingsRef}
       | 						^^^^^^^^^^^^^^^^^^
    67 | 						healthCareRef={healthCareRef}
    68 | 						bankingRef={bankingRef}
    69 | 					/>
ERROR in src/containers/servicesContainer.tsx:67:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    65 | 						educationRef={educationRef}
    66 | 						virtualMeetingsRef={virtualMeetingsRef}
  > 67 | 						healthCareRef={healthCareRef}
       | 						^^^^^^^^^^^^^
    68 | 						bankingRef={bankingRef}
    69 | 					/>
    70 | 				}
ERROR in src/containers/servicesContainer.tsx:68:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    66 | 						virtualMeetingsRef={virtualMeetingsRef}
    67 | 						healthCareRef={healthCareRef}
  > 68 | 						bankingRef={bankingRef}
       | 						^^^^^^^^^^
    69 | 					/>
    70 | 				}
    71 | 			/>
ERROR in src/containers/servicesContainer.tsx:76:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    74 | 				element={
    75 | 					<Services
  > 76 | 						educationRef={educationRef}
       | 						^^^^^^^^^^^^
    77 | 						virtualMeetingsRef={virtualMeetingsRef}
    78 | 						healthCareRef={healthCareRef}
    79 | 						bankingRef={bankingRef}
ERROR in src/containers/servicesContainer.tsx:77:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    75 | 					<Services
    76 | 						educationRef={educationRef}
  > 77 | 						virtualMeetingsRef={virtualMeetingsRef}
       | 						^^^^^^^^^^^^^^^^^^
    78 | 						healthCareRef={healthCareRef}
    79 | 						bankingRef={bankingRef}
    80 | 					/>
ERROR in src/containers/servicesContainer.tsx:78:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    76 | 						educationRef={educationRef}
    77 | 						virtualMeetingsRef={virtualMeetingsRef}
  > 78 | 						healthCareRef={healthCareRef}
       | 						^^^^^^^^^^^^^
    79 | 						bankingRef={bankingRef}
    80 | 					/>
    81 | 				}
ERROR in src/containers/servicesContainer.tsx:79:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    77 | 						virtualMeetingsRef={virtualMeetingsRef}
    78 | 						healthCareRef={healthCareRef}
  > 79 | 						bankingRef={bankingRef}
       | 						^^^^^^^^^^
    80 | 					/>
    81 | 				}
    82 | 			/>
ERROR in src/containers/servicesContainer.tsx:87:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    85 | 				element={
    86 | 					<Services
  > 87 | 						educationRef={educationRef}
       | 						^^^^^^^^^^^^
    88 | 						virtualMeetingsRef={virtualMeetingsRef}
    89 | 						healthCareRef={healthCareRef}
    90 | 						bankingRef={bankingRef}
ERROR in src/containers/servicesContainer.tsx:88:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    86 | 					<Services
    87 | 						educationRef={educationRef}
  > 88 | 						virtualMeetingsRef={virtualMeetingsRef}
       | 						^^^^^^^^^^^^^^^^^^
    89 | 						healthCareRef={healthCareRef}
    90 | 						bankingRef={bankingRef}
    91 | 					/>
ERROR in src/containers/servicesContainer.tsx:89:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    87 | 						educationRef={educationRef}
    88 | 						virtualMeetingsRef={virtualMeetingsRef}
  > 89 | 						healthCareRef={healthCareRef}
       | 						^^^^^^^^^^^^^
    90 | 						bankingRef={bankingRef}
    91 | 					/>
    92 | 				}
ERROR in src/containers/servicesContainer.tsx:90:7
TS2322: Type 'RefObject<null>' is not assignable to type 'RefObject<HTMLDivElement>'.
    88 | 						virtualMeetingsRef={virtualMeetingsRef}
    89 | 						healthCareRef={healthCareRef}
  > 90 | 						bankingRef={bankingRef}
       | 						^^^^^^^^^^
    91 | 					/>
    92 | 				}
    93 | 			/>


Iam also getting same error
unable to fix
