### ISSUE TITLE
@types-2.0/react-css-modules: CSSModules is not a function

### ISSUE THREAD

**Issue by emzero** [DefinitelyTyped/DefinitelyTyped#12844] opened 2016-11-21 22:48 UTC
I'm using the latest version of react-css-modules typings (`@types/react-css-modules@3.7.5`) but it's not working.

I'm using typescript 2.1.1 and my code as following:

```typescript
import * as CSSModules from 'react-css-modules';
const styles = require("./styles.css");

// then whether I use the decorator
@CSSModules(styles)
class MyComponent extends React.Component({}, {}) {
    //...
}
// or the explicit function
export default CSSModules(MyComponent, styles);

// the browser throws an error 'CSSModules' is not a function
// inspecting the variable shows that CSSModules is actually an object with a default property which is actually the function
// but trying to do the following throws a TypeScript error saying CSSModules doesn't have a default property
export default CSSModules.default(MyComponent, styles);
```

I'm not extending the component props from `CSSModules.InjectedCSSModuleProps`. Is that mandatory?

**Comment by emzero** [comment] 2016-11-21 22:54
I've found the problem.

Here's the working definition.
Only thing changed is the export. Changed `export = CSSModules` to `export default CSSModules`.

```typescript
// Type definitions for react-css-modules 3.7.9
// Project: https://github.com/gajus/react-css-modules
// Definitions by: Kostya Esmukov <https://github.com/KostyaEsmukov>, Tadas Dailyda <https://github.com/skirsdeda>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

interface TypeOptions {
    allowMultiple?: boolean;
    errorWhenNotFound?: boolean;
}

type StylesObject = any;

interface CSSModules {
    (defaultStyles: StylesObject, options?: TypeOptions): <C extends Function>(Component: C) => C;
    <C extends Function>(Component: C, defaultStyles: StylesObject, options?: TypeOptions): C;
}

declare module CSSModules {
    // Extend your component's Prop interface with this one to get access to `this.props.styles`
    //
    // interface MyComponentProps extends CSSModules.InjectedCSSModuleProps {}
    interface InjectedCSSModuleProps {
        styles?: StylesObject;
    }
}

declare let CSSModules: CSSModules;

export default CSSModules;

declare module 'react' {
    interface HTMLAttributes<T> {
        styleName?: string;
    }
}
```

Please modify accordingly. Forking everything to submit a PR just for this is overkill. 
Thank you

**Comment by nicolechung** [comment] 2016-12-05 18:35
Just wondering, any update on this? I am having the same issue.

**Comment by nicolechung** [comment] 2016-12-06 19:00
Also: I'd be into making an actual PR for this, but it seems like files have been truncated from this repo? 

I can't seem to find the folder for this one.

**Comment by emzero** [comment] 2016-12-06 19:39
@nicolechung It's on the `types-2.0` branch. Anyway, I'll be submitting a PR later today with this change.

**Comment by nicolechung** [comment] 2016-12-07 15:07
Please do! I am looking forward to this.

**Comment by mcrawshaw** [comment] 2016-12-15 08:06
@emzero did you get a chance to submit?  I can do if your busy...

**Comment by emzero** [comment] 2016-12-15 15:29
@mcrawshaw Sorry, I haven't had the time. Please do if you want.

**Comment by mcrawshaw** [comment] 2016-12-16 02:53
@emzero Actually, I think the issue is on my side.  What's in your tsconfig compiler options?

**Comment by emzero** [comment] 2016-12-16 23:20
Here's the [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13406)

@mcrawshaw What's in my tsconfig of what? What problem are you having?

**Comment by mcrawshaw** [comment] 2016-12-16 23:30
@emzero I believe my the "module" setting was incorrectly set.  It wasn't just this library I was having issue with...  I've had to add "export default *" to many libraries in the past.  My changing my module out to commonjs this was resolved.  I have been able to remove most of my custom typings now.

Original settings (defaults to "es6" modules):
```
"compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "jsx": "preserve",
    "declaration": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "sourceMap": true,
    "noEmit": true
  }
```

New settings:
```
"compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "preserve",
    "declaration": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "sourceMap": true,
    "noEmit": true
  }
```

Note I use babel to prep for browser post-TS.

**Comment by mcrawshaw** [comment] 2017-04-19 21:02
@emzero looks to be resolved, would you mind closing this please?

**Closed** 2017-04-19 22:37 UTC
