### ISSUE TITLE
@types/react-loadable: Export should not be 'default'

### ISSUE THREAD

**Issue by crohlfs** [DefinitelyTyped/DefinitelyTyped#19337] opened 2017-08-25 08:38 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Kovensky @odensc

Based on `node -p "require('react-loadable')"`, it looks like this module does not have a `default` export. The typings have a `default` export causing errors when I try to use it this way.

**Comment by odensc** [comment] 2017-08-25 09:02
Hi @crohlfs,

Putting `"allowSyntheticDefaultImports": true` in your tsconfig should fix this.

**Comment by reintjanhoiting** [comment] 2017-09-06 19:41
Hi @odensc,

I ran in the same issue as @crohlfs described. i do have `"allowSyntheticDefaultImports": true` enabled.

tsconfig.json
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "lib": ["es2015", "es6", "dom"],
        "allowSyntheticDefaultImports": true,
        "jsx": "react"
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "src/**/*"
    ]
}
```

login.async.component.tsx (copy past from the test)
```
import * as React from 'react';

import Loadable, { LoadingComponentProps } from "react-loadable";

class LoadingComponent extends React.Component<LoadingComponentProps> {
  render() {
    return (
      <div>
        {this.props.error}
        {this.props.isLoading}
        {this.props.pastDelay}
        {this.props.timedOut}
      </div>
    );
  }
}

const Loadable100 = Loadable({
  loader: () => import("./login.component"),
  loading: LoadingComponent,
  delay: 100,
  timeout: 10000
});

export default class LoginAsyncComponent extends React.Component {
  render() {
    return <Loadable100 />;
  }
}
```

running: "typescript": "2.5.2",

Everything compiles like a king 👍  , but at run time it ain't working 👎 

> Uncaught TypeError: react_loadable_1.default is not a function

any clue what im missing here ?

**Comment by odensc** [comment] 2017-09-07 06:36
Hmm - can't reproduce. Could you upload a minimal repro to github?

**Comment by reintjanhoiting** [comment] 2017-09-09 08:49
@odensc
sorry for the delayed answer wasn't at home for a few days. 

here is a minimal repro:
https://github.com/reintjanhoiting/react-loadable-allow-synthetic

Thanks for the help!

**Comment by odensc** [comment] 2017-09-13 05:14
Sorry for the delay @reintjanhoiting. Please try setting "module" to "esnext" in your `tsconfig.json`.

**Comment by stevenmusumeche** [comment] 2017-11-26 16:36
same issue here

**Comment by stevenmusumeche** [comment] 2017-11-26 16:37
This is how I am importing it so that it works at runtime

`import { default as Loadable } from 'react-loadable';`

**Comment by rhyek** [comment] 2017-12-27 23:46
> import { default as Loadable } from 'react-loadable';

This doesn't work either. AFAIK that's the same as `import Loadable from 'react-loadable'`.

**Comment by mvestergaard** [comment] 2017-12-28 13:41
I have the same issue. The problem stems from `react-loading` not exposing a default export. It uses `module.exports = Loadable;`.

The correct way to import this via typescript would be `import * as Loadable from 'react-loadable';` but that conflicts with the typings.

**Comment by nilobarp** [comment] 2018-01-05 04:08
For me it only works if do `import * as Loadable from 'react-loadable'`

**Comment by AlexFrazer** [comment] 2018-01-05 16:06
Same problem here. Tried the `allowSyntheticDefaultImports` as well to no avail

**Comment by yss14** [comment] 2018-02-11 18:11
Someone got a working version with typescript and react-loadable?

In my case
```
//App.tsx
import * as Loadable from 'react-loadable';

const AsyncLoadable = Loadable({
	loader: async () => import('./Async')
});

//Async.tsx
import * as React from 'react';

export default class Async extends React.Component<undefined, undefined> {
    render() {
        return <h1>Hello Async</h1>;
    }
}
```
it does not compile.

```
Argument of type '{ loader: () => Promise<typeof "<path>/code-splitting/src/Async">; }' is not assignable to parameter of type 'Options<{ children?: ReactNode; }, typeof "<path>/code-splitting/src...'.
  Type '{ loader: () => Promise<typeof "<path>/code-splitting/src/Async">; }' is not assignable to type 'OptionsWithRender<{ children?: ReactNode; }, typeof "<path>/code-spl...'.
    Property 'render' is missing in type '{ loader: () => Promise<typeof "<path>/code-splitting/src/Async">; }'.
```

**Comment by rhyek** [comment] 2018-02-11 18:14
Try out https://github.com/ctrlplusb/react-async-component. It includes its
own type definitions and found it worked better for me with
react-hot-loader.


Saludos,
Carlos R. Gonzales
+502-30274143

**Comment by mvestergaard** [comment] 2018-02-11 18:16
@yss14 

I found that I had to explicitly grab the `.default` from the imported module, for it to work.
I've wrapped react-loadable like this:

```ts
export function AsyncRoute<T extends React.ComponentType<any>>(
  loader: () => Promise<IModuleWithDefault<T>>,
): React.ComponentType<any> {
  return Loadable({
    loader: () => loader().then(m => m.default),
    delay: 2000,
    timeout: 30000,
    loading: () => <div>loading...</div>,
  });
}
```

**Comment by crohlfs** [comment] 2018-02-11 21:47
I've been using my own type definition for the last few months: https://gist.github.com/crohlfs/f65ea6a03bcf3ca690b913458ee54631

Used like this:
`import * as Loadable from "react-loadable";`

**Comment by Kovensky** [comment] 2018-02-12 01:44
Do **not** use `import * as Loadable`. Repeat it as a mantra.

Either use `import Loadable = require('react-loadable')` if you're not using a bundler, or enable synthetic defaults and use `import Loadable from 'react-loadable'`.

**Comment by lednhatkhanh** [comment] 2018-03-27 14:03
Any updates on this issue?

**Comment by mikemartincode** [comment] 2018-05-07 20:37
Hey, I ran into this issue today while working on a boilerplate. 

Here is a minimal repo that it works on.

I used const Loadable = require("react-loadable").

https://github.com/mikemartincode/react-webpack-typescript-starter

**Comment by lednhatkhanh** [comment] 2018-05-08 08:26
I switched to react-async-component and it's working fine with typescript.

**Comment by Bastardly** [comment] 2018-08-03 20:07
I made a direct import. Worked for me. :)

`import * as Loadable from 'react-loadable/lib/index';`

**Comment by dharmeshtailor** [comment] 2018-09-03 02:55
This worked for me. :-)

const Loadable = require('react-loadable');

**Comment by abhinav2331** [comment] 2018-10-01 13:05
> @odensc
> sorry for the delayed answer wasn't at home for a few days.
> 
> here is a minimal repro:
> https://github.com/reintjanhoiting/react-loadable-allow-synthetic
> 
> Thanks for the help!

Hi I run your code but it not working.

**Comment by Kovensky** [comment] 2018-10-02 01:49
If you're using typescript's module transform without `esModuleInterop`, the only correct way to import `react-loadable` is `import Loadable = require('react-loadable')`.

Otherwise, or when using a bundler, you should import it as `import Loadable from 'react-loadable'`.

Make sure that, if you're using a bundler, that your `modules` setting is either `es2015` or `esnext`, and that both `esModuleInterop` and `allowSyntheticDefaultImports` are enabled.

**Comment by abhinav2331** [comment] 2018-10-02 10:35
> 
> 
> If you're using typescript's module transform without `esModuleInterop`, the only correct way to import `react-loadable` is `import Loadable = require('react-loadable')`.
> 
> Otherwise, or when using a bundler, you should import it as `import Loadable from 'react-loadable'`.
> 
> Make sure that, if you're using a bundler, that your `modules` setting is either `es2015` or `esnext`, and that both `esModuleInterop` and `allowSyntheticDefaultImports` are enabled.

Yes I checked my tsconfig file  both are enabled.
     "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
I am importing Loadable as same
import Loadable = require('react-loadable')
But still loader not rendering only display loading. Please check screenshots.

http://pixeledged.com/image/code.png
http://pixeledged.com/image/loading.png

**Comment by chachaxw** [comment] 2019-03-06 02:35
> Someone got a working version with typescript and react-loadable?
> 
> In my case
> 
> ```
> //App.tsx
> import * as Loadable from 'react-loadable';
> 
> const AsyncLoadable = Loadable({
> 	loader: () => import('./Async')
> });
> 
> //Async.tsx
> import * as React from 'react';
> 
> export default class Async extends React.Component<undefined, undefined> {
>     render() {
>         return <h1>Hello Async</h1>;
>     }
> }
> ```
> this does not compile.
> 
> ```
> Argument of type '{ loader: () => Promise<typeof "<path>/code-splitting/src/Async">; }' is not assignable to parameter of type 'Options<{ children?: ReactNode; }, typeof "<path>/code-splitting/src...'.
>   Type '{ loader: () => Promise<typeof "<path>/code-splitting/src/Async">; }' is not assignable to type 'OptionsWithRender<{ children?: ReactNode; }, typeof "<path>/code-spl...'.
>     Property 'render' is missing in type '{ loader: () => Promise<typeof "<path>/code-splitting/src/Async">; }'.
> ```

I met the same problem with you, but I solved that problem
```Typescript
const Example = Loadable({
    loader: () => import('./components/Example') as Promise<any>,
    loading: Loading,
});
```
And this way can solve typescript problems.

**Comment by lixianbin1** [comment] 2019-03-19 08:42
I met the same problem with you,I think it's useful.
`const Loadable = require('react-loadable')`

**Comment by orta** [comment] 2021-06-07 13:23
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:23 UTC
