### ISSUE TITLE
[@types/styled-components] 4.1.0 breaks themes

### ISSUE THREAD

**Issue by vincentparrett** [DefinitelyTyped/DefinitelyTyped#30536] opened 2018-11-14 23:43 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the author
  - Authors: @Igorbek @Igmat @Lavoaster

Using 
typescript  3.1.6
styled-components 4.1.1
@types/styled-components 4.1.0

Theme definition as shown [in the documentation for styled-components](https://www.styled-components.com/docs/api#define-a-theme-interface) no longer works with the 4.1.0 types.

`
ERROR in [at-loader] ./src/theme/styled.ts:67:5
    TS2352: Conversion of type 'typeof import("I:/vsoftui/node_modules/@types/styled-components/index")' to type 'ThemedStyledComponentsModule<ITheme>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'createGlobalStyle' are incompatible.
    Type '{ (cssObject: Properties<string | number>): GlobalStyleComponent<{}, DefaultTheme>; <P = {}>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P, DefaultTheme>>[]): GlobalStyleComponent<...>; <P = {}>(func: InterpolationFunction<...>): GlobalStyleComponent<...>; }' is not comparable to type '{ (cssObject: Properties<string | number>): GlobalStyleComponent<{}, ITheme>; <P = {}>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P, ITheme>>[]): GlobalStyleComponent<...>; <P = {}>(func: InterpolationFunction<...>): GlobalStyleComponent<...>; }'.
      Type 'GlobalStyleComponent<{}, DefaultTheme>' is not comparable to type 'GlobalStyleComponent<{}, ITheme>'.
        Type 'DefaultTheme' is not comparable to type 'ITheme'.
          Property 'buttons' is missing in type 'DefaultTheme'.`

Reverting to the 4.0.3 types seems to still work, at least it compiles.

**Comment by vincentparrett** [comment] 2018-11-15 00:43
Also, forgot to mention, that npmjs lists a 4.1.1 version, but installing using npm or yarn here just gets 4.1.0 (even with latest tag).

**Comment by prichodko** [comment] 2018-11-15 01:53
Defining own props to styled-component is failing for me as well.

This code: 

```js
import styled from 'styled-components'
export const Button = styled<{}, 'button'>('button')``
```
is failing with:
> `Type error: Expected 1 type arguments, but got 2. `

**Comment by vincentparrett** [comment] 2018-11-15 02:00
Yes, I get that error too, but suspect it is related to the first error?

**Comment by stianbakken** [comment] 2018-11-15 08:11
This workaround seems to be working for me.

```ts
import * as styledComponents from "styled-components";
import { ThemedStyledComponentsModule } from "styled-components";

import { ApplicationTheme } from "./theme";

const styled = {
  default: styledComponents.default,
  css: styledComponents.css,
  createGlobalStyle: styledComponents.createGlobalStyle,
  keyframes: styledComponents.keyframes,
  ThemeProvider: styledComponents.ThemeProvider
} as ThemedStyledComponentsModule<ApplicationTheme>;

const { css, createGlobalStyle, keyframes, ThemeProvider } = styled;

export { css, createGlobalStyle, keyframes, ThemeProvider };
export default styled.default;

```

**Comment by maitriyogin** [comment] 2018-11-15 08:50
me too, will try your workaround

**Comment by YUFENGWANG** [comment] 2018-11-15 12:54
works for me @stianbakken

**Comment by maitriyogin** [comment] 2018-11-15 12:55
for react native?

**Comment by sanqiqi** [comment] 2018-11-15 12:56
works for me too, but why ? @stianbakken

**Comment by vincentparrett** [comment] 2018-11-15 22:58
> This workaround seems to be working for me.

Yes, that works (although I have no idea why), but the problem @prichodko mentioned is still there.

**Comment by Kovensky** [comment] 2018-11-16 07:07
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30511 includes a fix for the themes problem

The place where you add your own props is not in the styled call itself, but between the styled call and the template string. That might have been a breaking change.

As for React Native, I completely forgot about it. The stronger types for DOM elements ended up breaking for native(?).

I am expanding the use of the styled-components API in my code base so I'm adding more fixes as I find them.

**Comment by Kovensky** [comment] 2018-11-16 08:33
Yeah, it got changed to your "option 2" example. I think it got lost when I changed the generic argument not to be a component's props but the component itself (to be able to correctly type the `ref` parameter). It can probably be reimplemented.

As for the second problem... I didn't encounter it at all in my codebase, only in the new PR when I had a bug in the type of `css`. If it was happening before it's possible it's fixed there.

**Comment by prichodko** [comment] 2018-11-16 19:00
@Kovensky then I suppose this section https://www.styled-components.com/docs/api#typescript is out of date?

**Comment by JeroenReumkens** [comment] 2018-11-19 16:04
Same problem here. 
And I can confirm that changing `styled<props>('div')` to `styled('div')<props>` is indeed working. Seem like a fine solution, however I'm curious why this breaking change was introduced, what the reasoning was behind this? 

Besides that, highlighting in Vscode breaks, so there there is probably an updated needed for that too? Because of that I still have the feeling that this is a bug instead of an intended change.

<img width="1288" alt="screenshot 2018-11-19 at 17 02 37" src="https://user-images.githubusercontent.com/2969573/48719180-1e381a00-ec1d-11e8-939a-b1864591d859.png">

**Comment by YUFENGWANG** [comment] 2018-11-20 03:16
@JeroenReumkens same here

**Comment by Kovensky** [comment] 2018-11-20 04:40
This is fixed by https://github.com/styled-components/vscode-styled-components/pull/101

Interestingly, the syntax highlighting _does_ work when `.attrs` is used, which would have the same limitations as the generic argument being before the backticks.

**Comment by JeroenReumkens** [comment] 2018-11-20 07:08
Yes you're right @Kovensky . That forked version of the VSCode plugin does indeed work. Only waiting for that to be released. 
But I'm still wondering if this change was intended, before I start refactoring my complete code base.

**Comment by karolfalkiewicz** [comment] 2018-11-20 11:34
Tried option 1 and option 2 for attaching the type to my styled.component. None of them makes typescript server to show issue with not using required prop when using styled-component.

Screenshot of usage:
![zrzut ekranu 2018-11-20 o 12 31 30](https://user-images.githubusercontent.com/36987335/48770942-3e6ce500-ecc0-11e8-9212-5ab43a2b882d.png)

Screenshot of declaration:
![zrzut ekranu 2018-11-20 o 12 33 32](https://user-images.githubusercontent.com/36987335/48771040-81c75380-ecc0-11e8-912b-c0f019d413b8.png)

**Comment by Kovensky** [comment] 2018-11-20 12:12
That is strange. Works for me...

<img width="585" alt="image" src="https://user-images.githubusercontent.com/73085/48772834-df7f8e00-ed08-11e8-86d9-d66fde445f59.png">

<img width="566" alt="image" src="https://user-images.githubusercontent.com/73085/48772849-ea3a2300-ed08-11e8-9189-9a69a05d4727.png">

**Comment by karolfalkiewicz** [comment] 2018-11-20 12:16
I'm not using babel plugin in our project, only `ts-loader` with `typescript-plugin-styled-components`.
This is how my webpack looks:
![zrzut ekranu 2018-11-20 o 13 14 44](https://user-images.githubusercontent.com/36987335/48772956-4a5ba580-ecc6-11e8-9a2c-0ad37893bfe5.png)
![zrzut ekranu 2018-11-20 o 13 14 53](https://user-images.githubusercontent.com/36987335/48772961-4f205980-ecc6-11e8-8192-157ae1d88177.png)

Versions:
    "ts-loader": "^3.3.1",
    "typescript": "3.1.1",
    "typescript-plugin-styled-components": "^1.0.0",
    "styled-components": "^4.1.1",

**Comment by karolfalkiewicz** [comment] 2018-11-20 12:53
Run checks and got this:
```
../../node_modules/@types/styled-components/index.d.ts:34:16 - error TS2694: Namespace 'React' has no exported member 'ComponentPropsWithRef'.
```

**Comment by Kovensky** [comment] 2018-11-20 12:54
Looks like your `@types/react` is old; make sure it's updated and that you have no duplicates of it (yarn likes to make them unless you delete the old one from the `yarn.lock`)

**Comment by Kovensky** [comment] 2018-11-20 13:17
Yeah, that is incredibly old. You need the 16.7 types and styled-components itself at runtime needs at least 16.6.

**Comment by karolfalkiewicz** [comment] 2018-11-20 13:49
Thanks. That was it 👍

**Comment by JeroenReumkens** [comment] 2018-11-20 13:51
A quick solution for anyone who doesn't want to change a lot right now -> Revert to 4.0.3 and add it as a fixed version in your package.json.

**Comment by tuchk4** [comment] 2018-11-21 15:51
> A quick solution for anyone who doesn't want to change a lot right now -> Revert to 4.0.3 and add it as a fixed version in your package.json.

This works for me thanks. Actually I was surprised that after update @types/styled-components all my application became red :(

**Comment by YUFENGWANG** [comment] 2018-11-24 10:02
any update?

**Comment by JeroenReumkens** [comment] 2018-11-24 10:08
I have the feeling this issue is overlooked by the team, that why I just created an issue in the styled-components repo: https://github.com/styled-components/styled-components/issues/2243 

Hopefully there will be a fix soon.

**Comment by blooddrunk** [comment] 2018-11-28 09:49
Not sure if this is related since I'm new to typescript. `Material-ui` doesn't work with `styled-components` any more after upgrading `@types/styled-components` to @4.1.

A simple styled component which extends a [material-ui component](https://github.com/mui-org/material-ui/tree/master/packages/material-ui/src/Typography) would make the editor complain about missing properties: 

```javascript
const SubTitle = styled(Typography)`
  flex-grow: 1;
  padding-left: 24px;
`;

<SubTitle color="inherit">xxx</SubTitle>
```

Prop definitions for the original material-ui component seems not to be picked up:

```
Type '{ children: string; color: "inherit"; }' is missing the following properties from type 'Pick<Pick<TypographyProps | (TypographyProps & RefAttributes<Component<TypographyProps, any, any>>), "style" | "title" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 252 more ... | "variant"> & Partial<...>, "style" | ... 256 more ... | "variant">': style, className, innerRef, classes, and 2 more.
```

If I change the type of  the material-ui [component](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Typography/Typography.d.ts#L53) manually from `React.ComponentType` to `React.FunctionComponent` , errors are gone. I've got no idea how to make things right.

**Comment by blooddrunk** [comment] 2018-12-19 01:43
Sadly, no. I ended up doing type casting like `Typography as React.FunctionComponent<TypographyProps>
` since I'm not comfortable with the build-in styling solution  of `material-ui`.

**Comment by zhigang1992** [comment] 2018-12-19 06:55
For the issue with `children` not found.

Here is some info from `react.d.ts`

```typescript
// React.Props<T> is now deprecated, which means that the `children`
// property is not available on `P` by default, even though you can
// always pass children as variadic arguments to `createElement`.
// In the future, if we can define its call signature conditionally
// on the existence of `children` in `P`, then we should remove this.
readonly props: Readonly<{ children?: ReactNode }> & Readonly<P>;

**Comment by Kovensky** [comment] 2018-12-19 08:53
I did that in my huge PR that I couldn't figure out how to get merged.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30775

**Comment by rovansteen** [comment] 2018-12-19 14:06
@Kovensky is the original issue supposed to be fixed in #30511? This issue is still open & I'm having the same problem with `@types/styled-components@4.1.4` as the op.

**Comment by rovansteen** [comment] 2018-12-19 18:35
In case someone has the same issue as the OP (broken themes) there's a nice solution with declaration merging mentioned in the `styled-components` repo. https://github.com/styled-components/styled-components-website/issues/392#issuecomment-447067722

**Comment by stevejboyer** [comment] 2018-12-23 01:52
> For the issue with `children` not found.
> 
> Here is some info from `react.d.ts`
> 
> ```ts
> // React.Props<T> is now deprecated, which means that the `children`
> // property is not available on `P` by default, even though you can
> // always pass children as variadic arguments to `createElement`.
> // In the future, if we can define its call signature conditionally
> // on the existence of `children` in `P`, then we should remove this.
> readonly props: Readonly<{ children?: ReactNode }> & Readonly<P>;
> ```
> 
> For example, in order for `View` in `react-native` to work.
> You need to Extending `ViewProps` with a `children` field
> 
> In a `react-native.d.ts`
> 
> ```ts
> export * from "react-native";
> 
> import { ReactNode, ReactText, ReactElement } from "react";
> 
> declare module "react-native" {
>   interface ViewProps {
>     // We don't want to use ReactNode
>     // because we want to exclude String being a child
>     children?:
>       | ReactElement<any>
>       | ReactElement<any>[]
>       | boolean
>       | null
>       | undefined;
>   }
> 
>   interface TextProps {
>     children?: ReactText | ReactElement<TextProps>[];
>   }
> }
> ```
> 
> This is just an example on better type checking on `children` field, for a complete solution. We need to update all the Components in ReactNative that accepts `children`.

Unfortunately this is resulting in not being able to use just a plain old `<View>[stuff]</View>`, resulting in an error: 

`Type '{ children: (Element | null)[]; style: (AbsoluteFillStyle | { alignItems: "center"; justifyContent: "center"; })[]; }' is not assignable to type 'Readonly<ViewProps>'.
  Types of property 'children' are incompatible.
    Type '(Element | null)[]' is not assignable to type 'boolean | ReactElement<any> | ReactElement<any>[] | null | undefined'.
      Type '(Element | null)[]' is not assignable to type 'ReactElement<any>[]'.
        Type 'Element | null' is not assignable to type 'ReactElement<any>'.
          Type 'null' is not assignable to type 'ReactElement<any>'.ts(2322)
(alias) class View
import View`

**Comment by 0x80** [comment] 2019-01-25 14:34
@stevejboyer I don't seem to have that issue? 

This works without errors for me with the latest versions:

```ts
import React from "react";
import { Text, View } from "react-native";
import styled from "styled-components";

const Container = styled(View)`
  flex: 1;
  background-color: hotpink;
  align-items: center;
  justify-content: center;
`;

const App: React.FunctionComponent<{}> = () => {
  return (
    <Container>
      <Text>Open up App.js to start working on your app!</Text>
      <View>
        <Text>Or maybe not</Text>
      </View>
    </Container>
  );
};

export default App;
```

**Comment by kallaspriit** [comment] 2019-01-29 08:00
This break as soon as you add a variable to the mix. Even without using styled components and only the typings change:

*react-native.d.ts*
```typescript
export * from "react-native";

import { ReactNode, ReactText, ReactElement } from "react";

declare module "react-native" {
  interface ViewProps {
    // We don't want to use ReactNode
    // because we want to exclude String being a child
    children?:
      | ReactElement<any>
      | ReactElement<any>[]
      | boolean
      | null
      | undefined;
  }

  interface TextProps {
    children?: ReactText | ReactElement<TextProps>[];
  }
}
```

This works:
```typescript
<View>
  <Text>Test</Text>
</View>
```

This does not:
```typescript,
const foo = "bar";
...
<View>
  <Text>Test {foo}</Text>
</View>
```

with
```
[ts]
Type '{ children: string[]; }' is not assignable to type 'Readonly<TextProps>'.
  Types of property 'children' are incompatible.
    Type 'string[]' is not assignable to type 'string | number | ReactElement<TextProps, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>[]'.
      Type 'string[]' is not assignable to type 'ReactElement<TextProps, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>[]'.
        Type 'string' is not assignable to type 'ReactElement<TextProps, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>'. [2322]
```

But this is because of also messing with the `TextProps` (works when you comment out `interface TextProps {...}`, why is that necessary?

Anyway is there currently any reasonable way to use styled-components with react-native in TypeScript?

**Comment by Jessidhia** [comment] 2019-01-29 08:12
You are missing parens. Should be `ReactText | ReactElement<TextProps> | (ReactText | ReactElement<TextProps>)[]`.

If `ReactElement` validation works someday this would reject fragments, though, even if the things nested inside them are valid.

**Comment by zhigang1992** [comment] 2019-01-30 15:01
@0x80 you can use `ReactNode` which covers all the cases.

**Comment by alteredtastes** [comment] 2019-04-17 16:53
> Tried option 1 and option 2 for attaching the type to my styled.component. None of them makes typescript server to show issue with not using required prop when using styled-component.
> 

I ran into the same issue mentioned by @karolfalkiewicz, in the issue did not resolve for me until I also upgraded node (>v8.15.1) and typescript (v3.4.3), after ensuring I had the latest @types/react and @types/styled-components.

**Comment by jbmusso** [comment] 2019-05-25 11:52
I'm unsure if this is related or not, but type-checking is fully broken on any styled-components (not just for themes) on my setup using `@types/styled-components` v4.1+. Type-checking of any other React components or other non-React code works fine.
It could be a different issue so feel free to let me know if I should open a distinct one from which the discussion should continue.

I've tried most versions ranging from 4.1.0 to 4.1.15, but that didn't seem to type-check. I downgraded to 4.0.3, and type-checking works as expected.

Basically, props seems to be infered as `any`, and the compiler never complains about anything even for the simplest component.

Relevant dependencies (KO):
```json
{
  "dependencies": {
    "typescript": "^3.4.5",
    "styled-components": "^4.2.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6", 
    "@types/node": "^12.0.2",
    "@types/react": "16.8.18",
    "@types/react-dom": "^16.8.4",
    "@types/styled-components": "^4.1.15",
  }
}
```

Fixes with (OK):
```json
    "@types/styled-components": "4.0.3",
```

Running with:
* node@12.3.1
* yarn@1.16.0


The weird thing is that the exact same setup works (= type-checks the simplest styled-components I'd create) on another application using `@types/styled-components@4.1.15`. The major difference between the two apps:
* the OK type-checking application uses `gatsby@2.5.5` (with official, unmodified TypeScript setup)
* the KO non-type-checking setup uses create-react-app with `react-scripts@^3.0.1` - it type-checks with `@types/styled-components@4.0.3` but fails with `@types/styled-components@4.1.15`

tsconfig.json files differ a bit, I'll post if needed.

Things I've tried that didn't help:
* `rm -rf node_modules` multiple times
* using `typescript@3.5-rc` and that didn't change anything for 4.1.15 (does not type-checks), though it type-checks as expected with 4.0.3

I fear a [PEBKAC](https://en.wiktionary.org/wiki/PEBKAC) somewhere, but maybe not since downgrading fixes this. I couldn't isolate the problem more than this.

Thanks for your time.

**Comment by suntearinheart** [comment] 2019-07-11 22:51
The  latest version:  
1.   the error messages:  
Invariant Violation: "barStyle" is not a valid style property.
StyleSheet generated: {
  "barStyle": "'dark-content'"
}
Valid style props: [
  "alignContent",
  "alignItems",
  "alignSelf",
  "aspectRatio",
  "backfaceVisibility",
  "backgroundColor",
  "borderBottomColor",
  "borderBottomEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStartRadius",
  "borderBottomWidth",
  "borderColor",
  "borderEndColor",
  "borderEndWidth",
  "borderLeftColor",
  "borderLeftWidth",
  "borderRadius",
  "borderRightColor",
  "borderRightWidth",
  "borderStartColor",
  "borderStartWidth",
  "borderStyle",
  "borderTopColor",
  "borderTopEndRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "color",
  "decomposedMatrix",
  "direction",
  "display",
  "elevation",
  "end",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "fontFamily",
  "fontSize",
  "fontStyle",
  "fontVariant",
  "fontWeight",
  "height",
  "includeFontPadding",
  "justifyContent",
  "left",
  "letterSpacing",
  "lineHeight",
  "margin",
  "marginBottom",
  "marginEnd",
  "marginHorizontal",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginTop",
  "marginVertical",
  "maxHeight",
  "maxWidth",
  "minHeight",
  "minWidth",
  "opacity",
  "overflow",
  "overlayColor",
  "padding",
  "paddingBottom",
  "paddingEnd",
  "paddingHorizontal",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingTop",
  "paddingVertical",
  "position",
  "resizeMode",
  "right",
  "rotation",
  "scaleX",
  "scaleY",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "start",
  "textAlign",
  "textAlignVertical",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "textShadowColor",
  "textShadowOffset",
  "textShadowRadius",
  "textTransform",
  "tintColor",
  "top",
  "transform",
  "transformMatrix",
  "translateX",
  "translateY",
  "width",
  "writingDirection",
  "zIndex"
]

This error is located at:
    in StyledNativeComponent (created by Styled(StatusBar))
    in Styled(StatusBar) (at App.tsx:96)
    in RCTView (at View.js:45)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at App.tsx:92)
    in ApolloProvider (at App.tsx:91)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
- node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:78:4 in styleError
- node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:35:17 in validateStyleProp
- node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:56:8 in validateStyle
- node_modules/react-native/Libraries/StyleSheet/StyleSheet.js:355:43 in create
- node_modules/styled-components/native/dist/styled-components.native.cjs.js:5941:39 in generateStyleObject
- node_modules/styled-components/native/dist/styled-components.native.cjs.js:6228:61 in <unknown>
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:12671:25 in updateContextConsumer
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17276:21 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17316:41 in workLoop
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17417:15 in renderRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18423:17 in performWorkOnRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18324:24 in performWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18285:14 in performSyncWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18169:19 in requestWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17969:16 in scheduleWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:6934:17 in enqueueSetState
- node_modules/react/cjs/react.development.js:335:31 in setState
* src/App.tsx:75:16 in handleFinishLoading
- node_modules/expo/build/launch/AppLoading.js:31:20 in _callee$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- ... 14 more stack frames from framework internals

2.  the env  : 
  "dependencies": {
    "@expo/vector-icons": "^10.0.3",
    "@types/d3-ease": "^1.0.8",
    "@types/react-native-vector-icons": "^6.4.1",
    "@types/styled-components": "^4.1.18",
    "apollo-boost": "^0.4.3",
    "apollo-cache-inmemory": "^1.6.2",
    "apollo-link-schema": "^1.2.3",
    "eslint-plugin-import": "^2.18.0",
    "expo": "^33.0.7",
    "expo-cli": "^2.20.10",
    "graphql": "^14.4.0",
    "graphql-tools": "^4.0.5",
    "native-base": "^2.12.1",
    "react": "^16.8.6",
    "react-apollo": "^2.5.8",
    "react-dom": "^16.8.6",
    "react-move": "^6.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0",
    "styled-components": "^4.3.2"

3.  my codes:  
const Barstatus = styled(StatusBar)`
	barStyle: 'dark-content';
`

const Container = styled.View`
	flex: 1;
	background-color: white;
	justify-content: center;
	align-items: center;
`

const Title = styled.Text`
	font-size: 20px;
	font-weight: 500;
	color: palevioletred;
`

4.  Problem:   for the Text, View  work fine.  But  Barstatus  comes with error.

**Comment by andrewkfiedler** [comment] 2019-08-01 18:12
Had the same issue where following the docs for v4 didn't work with the current typescript definitions.

I define my theme like so:
```
// import original module declarations
import 'styled-components'
import { ThemeInterface } from '../../src/main/webapp/react-component/styles/styled-components'

// and extend them!
declare module 'styled-components' {
  export interface DefaultTheme extends ThemeInterface {}
}
```

All my components would see the theme prop as any until I downgraded from `4.1.18` to `4.0.3`.

**Comment by michchan** [comment] 2019-09-05 09:43
Same here!

**Comment by plondon** [comment] 2020-01-03 12:30
@andrewkfiedler you just saved my life. <3

**Comment by timbergus** [comment] 2021-01-11 21:42
I have found this error this morning in my project, and I have done the simplest example to reproduce it. The property `component` disappears from `<Typography />` as soon as it is wrapped using __styled-components__. Is this error related to this thread? I'm using version __5.1.7__.

![Screenshot 2021-01-11 223002](https://user-images.githubusercontent.com/1750734/104241182-8ed5cc80-545d-11eb-9d90-61401e3a64b7.png)

**Comment by orta** [comment] 2021-08-03 13:27
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-08-03 13:27 UTC
