### ISSUE TITLE
async cannot infer type(s) from input array

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#24297] opened 2018-03-14 23:00 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.

![screenshot 2018-03-14 15 56 09](https://user-images.githubusercontent.com/11139560/37435415-6dc019c0-27a0-11e8-985c-5910ab85bf91.png)

In the above screenshot - users is typed, but in the callback, it's implicitly typed to 'any'.
I am wondering if async can infer the type somehow.

@rlindgren @sasanj @kerol2r20 @kasuparu @fenying

**Comment by kasuparu** [comment] 2018-03-15 10:31
![async-maplimit-1](https://user-images.githubusercontent.com/4838137/37458089-891f70d8-284c-11e8-8a03-6dc6c5cb1123.png)

I couldn't reproduce this issue. What's the exact type of your `users`?

**Comment by the1mills** [comment] 2018-03-15 16:15
Ughh my fault, I think I was importing async like this

```

const async = require('async');
```

But I of course need to use

```

import async = require('async');
```

Sorry for the false alarm, I am glad async can infer the type.

**Comment by fenying** [comment] 2018-03-16 01:35
For most modules, you could use `import * as xxx from "xxx";` instead of `import xxx = require("xxx");` to avoid this type of mistake. :)

**Comment by the1mills** [comment] 2018-03-16 02:31
I dont understand why the * syntax would help avoid the mistake? Because it's visually more obvious?

**Comment by orta** [comment] 2021-06-07 13:19
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:19 UTC
