### ISSUE TITLE
@types/react-native require conflicts with node

### ISSUE THREAD

**Issue by ddwwcruz** [DefinitelyTyped/DefinitelyTyped#24431] opened 2018-03-21 05:58 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @timwangdev @kamal @nelyousfi 

![selection_027](https://user-images.githubusercontent.com/16479124/37696145-74354ec8-2d0f-11e8-97c1-47649b9a937c.png)

I'm getting duplicate identifier error on react-native. Commenting the one line out seems to fix the problem but that's only a temporary solution.

**Comment by alloy** [comment] 2018-03-21 10:57
Duplicate of #15960.

**Closed by alloy** 2018-03-21 10:57 UTC
