### ISSUE TITLE
@types/react-router: Can't pass Components into react-router Routes with custom type arguments defined

### ISSUE THREAD

**Issue by fultonm** [DefinitelyTyped/DefinitelyTyped#13689] opened 2017-01-02 19:27 UTC
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @.... @RyanCavanaugh 

https://github.com/ReactTraining/react-router/issues/4317

I opened an issue on the `react-router` repo regarding a problem with `react-router` and Typescript. I'm not sure which issue tracker it belongs to, so maybe someone can take a look and see if the bug is more appropriate for this repo?

**Comment by Izhaki** [comment] 2017-03-27 12:07
I'm don't think that there's an issue with @types here.

If you look at the following line (`interface RouteProps`):

    component?: React.SFC<RouteComponentProps<any> | void> | React.ComponentClass<RouteComponentProps<any> | void>;

it basically gives you two options: 

* Don't use typings at all. That's why `React.Component<any, any>` works.
* Strictly adhere to typings.

For the latter case, your `props` interface should extend `RouteComponentProps` like so:

```typescript
export interface EntitiesPageProps extends RouteComponentProps<any> { }
```

and the component as usual:

```typescript
export class EntitiesPage extends React.Component< EntitiesPageProps, undefined >  { }
```

What you provide in https://github.com/ReactTraining/react-router/issues/4317 is neither the first nor the second option - you _do_ provide a type, but not one that adhere with the typings or the router.

**Comment by Izhaki** [comment] 2017-03-28 09:13
Another working solution is to simply use `@types/react-router-redux` instead of `@types/react-router`. See [this project as an example](https://github.com/brunolm/ts-react-redux-startup).

**Comment by mikebridge** [comment] 2017-04-21 16:57
@fultonm The TypeScript looks correct—the problem is that the [Route component injects several variables into the wrapped component](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L101-L119).  Maybe there's a good reason for that design but I can't see why all those props are necessary.  I thought that was the purpose of [withRouter](https://reacttraining.com/react-router/web/api/withRouter).  Anyway, I think it's better to wrap the subcomponents like this so they don't get polluted with unnecessary dependencies:

```typescript
import * as React from "react";
import {RouteComponentProps} from "react-router";

export function withoutRouting<P>(Component: React.ComponentClass<P> | React.SFC<P> ):
    React.ComponentClass<RouteComponentProps<P>> {

    class C extends React.Component<any, any> {

        public render(): JSX.Element {

            const {match, location, history, staticContext, ...rest} = this.props;
            return (
                <Component {...rest} />
            );
        }
    }
    return C;
}

export default withoutRouting;
```
Then:
```typescript
    <Route path="/test" component={withoutRouting(MyComponent)} />
```

**Comment by sbuzonas** [comment] 2017-06-11 01:18
The definition does appear to be correct. The snippet directly above will exclude the props entirely which is the better solution IMO.

Wrapping everything in `withoutRouting` didn't feel right to me, so I took it a step farther and created a wrapper for the Route component.

```typescript
import * as React from 'react';
import { Route as BaseRoute, RouteComponentProps, RouteProps } from 'react-router';

export function withoutRouteProps<P>(
  Component: React.ComponentClass<P> | React.SFC<P>
): React.ComponentClass<RouteComponentProps<P>> {
  class C extends React.Component<any, any> {
    public render(): JSX.Element {
      const {match, location, history, staticContext, ...componentProps} = this.props;
      return <Component {...componentProps} />;
    }
  }
  return C;
}

interface FilteredRouteProps extends RouteProps {
  component?: React.SFC<any> | React.ComponentClass<any>;
}

export function Route(props: FilteredRouteProps) {
  const {
    component,
    ...routeProps
  } = props;

  if (component) {
    return <BaseRoute component={withoutRouteProps(component)} {...routeProps} />;
  }

  return <BaseRoute {...routeProps} />;
}
```

**Comment by sbuzonas** [comment] 2017-06-11 01:33
Although on second glance. Isn't it forcing the props to be only `RouteComponentProps<any>`.

I would think it would be better suited as `ComponentProps & Partial<RouteComponentProps<any>>`?

**Comment by mikebridge** [comment] 2017-06-11 22:53
@sbuzonas That seems like a good idea---I was looking at the `RouteComponentProps<any>` thing and ran into some Liskov issues when overriding `component`, so I added a new property, `plaincomponent`:

```typescript
import * as React from "react";

import {Route, RouteProps} from "react-router";

import {withoutRouteProps} from "./withoutRouteProps";

interface IFilteredRouteComponentProps<P> {
    plaincomponent?: React.SFC<P> | React.ComponentClass<P>;
}

export class FilteredRoute<P> extends React.Component<RouteProps & IFilteredRouteComponentProps<P>, {}> {

    public render(): JSX.Element {
        const {plaincomponent, component, ...rest} = this.props;

        return plaincomponent ? (
            <Route component={withoutRouteProps(plaincomponent)} {...rest} />
        ) : (
            <Route component={component} {...rest} />
        );
    }
}

export default FilteredRoute;
```

I also modified the types on `withoutRouting` / `withoutRouteProps` slightly to get rid of `any`:

```typescript
import * as React from "react";
import {RouteComponentProps} from "react-router";

export function withoutRouteProps<P>(Component: React.ComponentClass<P> | React.SFC<P> ):

React.ComponentClass<RouteComponentProps<P>> {

    class C extends React.Component<RouteComponentProps<P>, {}> {

        public render(): JSX.Element {

            const {match, location, history, staticContext, ...rest} = this.props;
            return (
                <Component {...rest} />
            );
        }
    }
    return C;
}

export default withoutRouteProps;
```

So:

```jsx
<FilteredRoute path="/test" plaincomponent={MyComponentThatDoesNotKnowAboutRouting} />
<FilteredRoute path="/test" component={MyComponentThatImplementsRouting} />
```

**Comment by sbuzonas** [comment] 2017-07-05 16:26
@mikebridge My `RouteComponentProps<any>` statement was IRT https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ea9de8a518b01fa4257d367418e95a4ed2897717/types/react-router/index.d.ts#L67-L69

Shouldn't that be an intersection, rather than only route props or no props, like:

```
type RouteComponentPropsType<P> = RouteContextProps<any> & P;

export interface RouteProps {
  location?: H.Location;
  component?: React.SFC<RouteComponentPropsIntersection<any> | undefined> | React.ComponentClass<RouteComponentPropsIntersection<any> | undefined>;
  render?: ((props: RouteComponentProps<any>) => React.ReactNode);
  children?: ((props: RouteComponentProps<any>) => React.ReactNode) | React.ReactNode;
  path?: string;
  exact?: boolean;
  strict?: boolean;
}
```

**Comment by sbuzonas** [comment] 2017-07-05 17:45
@mikebridge I created a PR the eliminates the need for a workaround in my scenarios.

**Comment by orta** [comment] 2021-06-07 19:07
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 19:07 UTC
