### ISSUE TITLE
lodash typings errors

### ISSUE THREAD

**Issue by connelhooley** [DefinitelyTyped/DefinitelyTyped#7903] opened 2016-01-31 20:59 UTC
I'm getting the following error when I compile my sails project from my lodash typings.

```
error TS2403: Subsequent variable declarations must have the same type.  Variable '_' must be of type 'any', but here has type 'LoDashStatic'.
>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:compile" failed. Use --force to continue.
Aborted due to warnings.
```

I am using TSC 1.7.5. [Here](https://github.com/DefinitelyTyped/DefinitelyTyped/files/111505/files.zip) are my tsconfig, tsd and package files.

I swear this used to work, any help would be much appreciated.

Thanks.

**Comment by RickCarlino** [comment] 2016-02-09 11:44
I have just hit the same issue this morning.

What version are you using? I am on lodash `4.2.1` and running the TSD definitions for what appears to be >`4.0.0`.

**Comment by vvakame** [comment] 2016-02-11 15:26
@chrootsu ?

**Comment by chrootsu** [comment] 2016-02-16 14:50
Sorry for delay.
I can't reproduce the issue even with attached config files. Could you please show example of code that throws the error.

**Comment by connelhooley** [comment] 2016-02-27 14:31
Visual Studio Code underlines the first underscore in the following line inside the lodash.d.ts file (line 239):

`declare var _: _.LoDashStatic;
`

I think this is the line stopping it from compiling.

**Comment by michaelgeorgeattard** [comment] 2016-03-06 19:15
Replicated the issue in an ES6 node project. Intellisense in VSCode is not working because of the following:

`declare var _: _.LoDashStatic;

declare module _ {`

Getting a duplicate identifier error.

I am targeting es6, commonjs in my jsconfig.json.

**Comment by ikhattab** [comment] 2016-04-17 17:04
I have this issue too es5 target, commonjs

any updates on this?

**Comment by petrkoutnysw** [comment] 2016-06-07 12:52
any updates on this?

**Comment by zeeshanjan82** [comment] 2016-06-27 11:37
angy updates on this?

**Comment by JamiesonWarner** [comment] 2016-10-11 02:42
Any updates on this? I'm getting this problem on `registry:dt/lodash#4.14.0+20161004174455`

**Comment by JamiesonWarner** [comment] 2016-10-11 19:58
Update: It appears that the two global typings of lodash are the broken ones: `global~lodash` and `dt~lodash`. The typings off npm worked for me.

**Comment by orta** [comment] 2021-06-07 13:31
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:31 UTC
