### ISSUE TITLE
@types/redux-actions - Add action types for handleActions()

### ISSUE THREAD

**Issue by andrei-cacio** [DefinitelyTyped/DefinitelyTyped#22743] opened 2018-01-08 09:25 UTC
@florian-richter @andy-ms 

This issue was inspired by this [article](https://spin.atomicobject.com/2017/07/24/redux-action-pattern-typescript/).

I think it would be even better if  the `handleActions` function would support Action types generic. This would guarantee that a reducer would only listen to a specific type of actions. Also it would fail for typos and other type of mistakes.

I am thinking of something like this:

```javascript
type INCREMENT = 'INCREMENT';
type DECREMENT = 'DECREMENT';

type CounterActionTypes = INCREMENT | DECREMENT;

handleActions<State, Payload, CounterActionTypes>(...);
```

However, there already is a third generic called `Meta`. I don't know exactly how this can fit in but I think it could be a good addition.

Thoughts?

**Comment by tonyhallett** [comment] 2018-01-15 14:16
With handleActions there is no need for the reducer to receive the action type.  The returned reducer only listens to the actions that are specified and forwards to the corresponding 'reducer' function.

The issue is that when the payload differs in type you have to explicitly provide it.

`const reducerDifferentPayloadTypes = ReduxActions.handleActions<number, any>({
    PAYLOADSTRING: (state, action: ReduxActions.Action<string>) => state + parseInt(action.payload),
    PAYLOADNUMBER: (state, action: ReduxActions.Action<number>) => state + action.payload,
}, 0);`

Here is a solution to that problem :

`type ReducerTypes<State, Payload> = ReduxActions.Reducer<State, Payload> | ReduxActions.ReducerNextThrow<State, Payload> 
type ReducerMetaTypes<State, Payload, Meta> = ReduxActions.ReducerMeta<State, Payload, Meta> | ReduxActions.ReducerNextThrowMeta<State, Payload, Meta>;

interface ActionCreatorHandler<State,Payload > {
    actionCreator: ReduxActions.ActionFunctions < Payload >,
    reducer: ReducerTypes<State,Payload>  
}
interface ActionCreatorMetaHandler<State, Payload,Meta> {
    actionCreator: ReduxActions.ActionFunctionsMeta<Payload,Meta>,
    reducer: ReducerMetaTypes<State, Payload,Meta>
}`

Call the following function if there is no meta ( the function can be generated to include as many type arguments as required ) - note that the ActionCreatorHandler interface takes an action creator as returned from createAction to enable the reducer to be typed without the need to supply the generic type parameters.  The initial state argument is used as normal and ensures that there is no need to supply the state generic parameter to the handleActionsFromCreators function nor in any of the reducers that you supply.

`function handleActionsFromCreators<State, Payload1, Payload2, Payload3, Payload4, Payload5, Payload6, Payload7, Payload8>(initialState: State, ach1: ActionCreatorHandler<State, Payload1>, ach2: ActionCreatorHandler<State, Payload2>, ach3?: ActionCreatorHandler<State, Payload3>, ach4?: ActionCreatorHandler<State, Payload4>, ach5?: ActionCreatorHandler<State, Payload5>, ach6?: ActionCreatorHandler<State, Payload6>, ach7?: ActionCreatorHandler<State, Payload7>, ach8?: ActionCreatorHandler<State, Payload8>) {
    var reducerMap= {};
    for (var i = 1; i < arguments.length; i++) {
        var actionCreatorHandler = arguments[i] as ActionCreatorHandler<State, any>;
        reducerMap[actionCreatorHandler.actionCreator.toString()] = actionCreatorHandler.reducer;
    }
    return ReduxActions.handleActions(reducerMap, initialState) as ReduxActions.Reducer<State,any>;
}`

If all the action creators have meta then use the function below instead ( again this function would be generated to allow for n  ActionCreatorMetaHandler ):

`function handleActionsFromMetaCreators<State, Payload1, Meta1, Payload2, Meta2>(initialState: State, ach1: ActionCreatorMetaHandler<State, Payload1, Meta1>, ach2: ActionCreatorMetaHandler<State, Payload2, Meta2>) {
    var reducerMap = {};
    for (var i = 1; i < arguments.length; i++) {
        var actionCreatorHandler = arguments[i] as ActionCreatorMetaHandler<State, any, any>;
        reducerMap[actionCreatorHandler.actionCreator.toString()] = actionCreatorHandler.reducer;
    }
    return ReduxActions.handleActions(reducerMap, initialState) as ReduxActions.Reducer<State, any>;
}`

With a mixture of action creators with/without meta I had to resort to a different approach :

pass the map from the first in to the second and call the reducerMapHandleActions to get correctly typed reducer ( state being correctly typed ). ( Again these functions need to be generated to allow for n )

`interface Map<State> {}
function createReducerMap<State, Payload1, Payload2>(state: State, ach1: ActionCreatorHandler<State, Payload1>, ach2?: ActionCreatorHandler<State, Payload2>): Map<State> {
    var reducerMap = {};
    for (var i = 1; i < arguments.length; i++) {
        var actionCreatorHandler = arguments[i] as ActionCreatorHandler<State, any>;
        reducerMap[actionCreatorHandler.actionCreator.toString()] = actionCreatorHandler.reducer;
    }
    return reducerMap;
}

function createReducerMapMeta<State, Payload1, Meta1, Payload2, Meta2>(state: State, reducerMap: Map<State>, ach: ActionCreatorMetaHandler<State, Payload1, Meta1>, ach2?: ActionCreatorMetaHandler<State, Payload2, Meta2>): Map<State>{
    for (var i = 1; i < arguments.length; i++) {
        var actionCreatorHandler = arguments[i] as ActionCreatorMetaHandler<State, any, any>;
        reducerMap[actionCreatorHandler.actionCreator.toString()] = actionCreatorHandler.reducer;
    }
    return reducerMap;
}

function reducerMapHandleActions<State>(map: Map<State>, initialState: State) {
    return ReduxActions.handleActions(map as any, initialState) as ReduxActions.Reducer<State, any>;
}
`

**Comment by orta** [comment] 2021-06-07 13:19
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:19 UTC
