### ISSUE TITLE
Property 'propTypes' does not exist on type 'typeof TestComponent'.

### ISSUE THREAD

**Issue by esetnik** [DefinitelyTyped/DefinitelyTyped#32877] opened 2019-02-07 21:36 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @pshrmn @threepointone

If you do not mention the authors the issue will be ignored.

```ts
import React from 'react';

import PropTypes from 'prop-types';

class TestComponent extends React.Component {}
TestComponent.propTypes = {};
```

Error: `Property 'propTypes' does not exist on type 'typeof TestComponent'.`

But no error when using the static keyword.
```ts
import React from 'react';

import PropTypes from 'prop-types';

class TestComponent extends React.Component {
  public static propTypes = {};
}
```

**Comment by ferdaber** [comment] 2019-02-07 21:43
This is a standard TypeScript mechanism. With classes the expectation is that all static properties are initialized in the class definition. Adding it after the fact is only supported for functions.

**Comment by jochienabuurs** [comment] 2019-05-09 15:09
and how would one add it after the fact with a function, because i get an error when doing it like this:
```
import Banner from './Banner';
...
const SubNav: React.FC<Props> = ({ className, items }) => { ... }
...
SubNav.Banner = Banner
```

**Comment by ferdaber** [comment] 2019-05-09 20:25
Once you annotate a value with its type (like you did with `const SubNav: React.FC<Props>` you can't change its type afterwards, so you need to declare it all at once or redeclare it as another constant.

**Comment by briandipalma** [comment] 2019-10-30 12:44
This error only serves to put people who are new to TS off gradually converting their code to TS. I'm having to litter my code with `// @ts-ignore` due to baffling errors like this when changing files from `.js` to `.tsx` and **it catches no bugs**.

**Comment by ericanderson** [comment] 2019-10-30 13:56
In this case it catches no bugs. It catches a ton of bugs elsewhere. Type everything as “any” if you want this behavior. Also this is not an issue for DT as it is about the behavior of TS, not the types. 

Please close.

**Comment by t-ricci-enhancers** [comment] 2020-11-30 11:40
The issue is the `PureComponent` and `Component` class and interface definitions do not inherit from `ComponentClass` which is the only place where `propTypes?: WeakValidationMap<P>` is defined

**Comment by t-ricci-enhancers** [comment] 2020-11-30 11:44
Also PureComponent and Component class cannot implement ComponentClass which defines the properties of the class function/object and would declare propTypes on the class instance instead. We need a PR to copy these declarations inside the class as static properties

**Comment by orta** [comment] 2021-06-07 13:38
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:38 UTC
