### ISSUE TITLE
Compatibility with Socket.io 2.0.1

### ISSUE THREAD

**Issue by darrenbrett** [DefinitelyTyped/DefinitelyTyped#16619] opened 2017-05-18 16:23 UTC
My dev environment:
OS X El Capitan 10.11.6
MacBook Air
VSC Version 1.12.2 (1.12.2)
Node: v7.4.0

We are trying to update our socket.io versions in our Angular app so that they match those we're using on the server. Currently, when I hover over our dependencies in our package.json file, this is what I see:

> TypeScript definitions for socket.io
> Latest version: 1.4.29

The server socket.io version we're using is 2.0.1. 

Is there a timeline on having this updated to be compatible with 2.0.1?

**Comment by crutchcorn** [comment] 2018-02-18 03:16
I'm gonna be trying my best to tackle this this weekend. I've already made definition files for lusca, and will now be attempting to make them for socket.io.

**Comment by crutchcorn** [comment] 2018-02-20 02:42
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23776

This pull request needs assistance for minor linting things, but should otherwise be good to go

**Comment by SArnab** [comment] 2018-04-16 18:44
Any update on this? #23776 was closed.

**Comment by BorntraegerMarc** [comment] 2018-04-18 15:40
@SArnab It wasn't closed because it's resolved 😄

**Comment by crutchcorn** [comment] 2018-04-18 15:43
@SArnab @BorntraegerMarc the typings in that PR are good for the most part, but CI is failing. If anyone wants to fix the issues, they can fork my fork and keep work off of that. I will likely loop back around to this, however it may take some time as a lot has come up for me recently

**Comment by BorntraegerMarc** [comment] 2018-04-19 07:53
@crutchcorn I could take a look at this. But what parts are missing for the typings?

**Comment by MickL** [comment] 2020-03-24 18:37
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18127

**Comment by orta** [comment] 2021-06-07 13:24
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:24 UTC
