### ISSUE TITLE
@types/react-redux The 'connect' function seems to be returning 'any'

### ISSUE THREAD

**Issue by josecarlosns** [DefinitelyTyped/DefinitelyTyped#37414] opened 2019-08-06 20:46 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - File: `react-redux/index.d.ts`.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf @MrWolfZ 

If you do not mention the authors the issue will be ignored.

## TL:DR

The `connect` function of `react-redux` is not returning a properly typed component, instead seems to be returning a `any` value, which breaks all the type-safety and intellisense of my Typescript code. Tested on `@types/react-redux@^7.1.0`.

## Environmnent

**`react-native info`:**

```
System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 271.08 MB / 7.71 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.4.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**`package.json`:** _(I've ommited some unrelated dependencies for the sake of simplicity)_ 

```json
"dependencies": {
    "react": "16.8.6",
    "react-native": "^0.60.4",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
  },
  "devDependencies": {
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.60.1",
    "@types/react-redux": "^7.1.0",
    "@types/redux-thunk": "^2.1.0",
    "typescript": "^3.5.3"
  }
```

## Context

So I'm working on a React-native project on my job and I decided to use Typescript for type-safety and autocomplete/intellisense features on my IDE of choice (Visual Studio Code). Also keep in mind that I'm relatively new to Typescript, so I may be doing something wrong, if thats the case please correct me. 

So to use typescript with react-native I would define a component like this: 

```tsx
interface Props {
  label: string;
}

class CustomComponent extends Component<Props> {
  render(): ReactElement {
    return (
      <View>
        <Text>{this.props.label}</Text>
      </View>
    );
  }
}

export default CustomComponent;
```

And I would get the expected behavior, that is proper type-checking and autocompletion features on VS Code:

![image](https://user-images.githubusercontent.com/28950443/62570072-a91d7b00-b865-11e9-8776-443b7090f484.png)

That error on the component its because its lacking the `label` prop, that I defined in the component's `Props` interface, and since I didn't define any `defaultProps` or marked it with the optional flag (`?`) it makes it a required prop.

But lets say I want to connect that component to my Redux Store, then I would use the `connect` function of `react-redux` and map props and/or action creators to it, like this:

```tsx
// Properties passed from the parent component
interface OwnProps {
  label: string;
}

// Properties passed from the store
interface StoreProps {
  theme: 'light' | 'dark';
}

// Props of the component
type Props = OwnProps & StoreProps;

class CustomComponent extends Component<Props> {
  render(): ReactElement {
    return (
      <View>
        <Text
          style={{ color: this.props.theme === 'light' ? 'white' : 'black' }}
        >
          {this.props.label}
        </Text>
      </View>
    );
  }
}

// The store structure, defined here for the sake of simplicity
interface Store {
  theme: 'light' | 'dark';
}

const mapStateToProps = (state: Store): StoreProps => {
  const { theme } = state;

  return {
    theme
  };
};

export default connect(mapStateToProps)(
  CustomComponent
);
```

But when I do this the component loses all type-safety and autocompletion, where it basically accepts any prop with any value, and the IDE doesn't detect its possible props:

![image](https://user-images.githubusercontent.com/28950443/62571327-75dbeb80-b867-11e9-9cbc-78e027aba546.png)

The code works as expected, but it loses all features that made me use typescript in the first place, so thats a no no.

After searching basically everywhere on the interwebs and asking on 2 slack channels and a discord server, I couldn't find an answer for this riddle. But I found something: **it seems that the `connect` function, even with proper generic type arguments, is returning a `any` value and, obviously, thats not a properly typed React component!**

![image](https://user-images.githubusercontent.com/28950443/62572096-56de5900-b869-11e9-82ff-4cf081f8bbf9.png)

So what am I doing wrong? I've been through basically dozens of articles and guidelines about how to properly type redux-connected components, and it just doesn't work, and I kinda need this to work, because deadlines. Please help, send the eagles.

## Workaround

Just manually type the default export, like this:

```tsx
const connectedComponent: typeof CustomComponent = connect<
  StoreProps,
  DispatchProps,
  OwnProps,
  Store
>(mapStateToProps)(CustomComponent);

export default connectedComponent;
```
With that typescript works as expected with type-checking and intellisense, but still thats just a workaround and may cause unexpected behavior down the line.

**Comment by brendanmc6** [comment] 2019-08-12 13:25
I am facing this issue as well-- any ideas?

**Comment by noahm** [comment] 2019-08-12 21:08
I just started upgrading react-redux in my app from 5.0 to 7.1 and am dealing with this issue now too. :( Haven't yet found any good answers to why, but it's definitely related to the complex `Matching` type used as part of defining `InferableComponentEnhancerWithProps`.

**Comment by brendanmc6** [comment] 2019-08-19 15:40
@noahm @JoseCarlosNS I found a temporary fix:

install `@types/hoist-non-react-statics`

I was able to see that this dependency is imported in the react-redux types, and this is where the `any` was being introduced.

I don't fully understand why these types are not installed in the first place. Perhaps a caching issue in our projects? I would appreciate if someone can help investigate.

It definitely is related to this previous PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34406

**Comment by brendanmc6** [comment] 2019-08-19 16:21
Continuing my investigation, I can see that an older version (2.5.0) of `hoist-non-react-statics` gets placed in my root `node_modules` folder, and this old definition file is the one being picked up by typescript. Still no clue how to fix this...

**Comment by noahm** [comment] 2019-08-20 23:05
@brendanmc6 You are my hero for the day! It would have taken me ages to trace it back to that package considering the size of the project this issue is part of. Unfortunately, I think the only real fix is removing the two coexisting versions of `hoist-non-react-statics` as you had feared. Fortunately, I don't think there's any real breaking changes from 2.x to 3.x and there's definitely some fixes that you'll want in regards to handling more modern react features like `memo` so for now I'm solving the issue on my end by adding the following to my `package.json`.
```
"resolutions": {
  "hoist-non-react-statics": "3.3.0"
}
```

I can worry about getting the rest of my dependencies upgraded later. :)

**Comment by hmafzal** [comment] 2019-09-30 16:02
Yep, that seemed to be the issue for me as well. Adding the resolutions to 3.3.0 worked as a workaround!

**Comment by hampustagerud** [comment] 2019-11-14 17:42
Also facing problems after upgrading to v7 from an older version and adding `hoist-non-react-statics` as a direct dependency seemed to solve all of them... Thanks @brendanmc6!

**Comment by brendanmc6** [comment] 2020-01-30 17:22
Update: I am not sure what has changed or where, but I have removed this dependency from my package.json and it seems to be working as intended. Connect no longer returns `any`.

@noahm @hmafzal @hampustagerud can any of you confirm the types are fixed in your repo as well? Then we can close this issue.

**Comment by noahm** [comment] 2020-01-30 18:08
I never added `hoist-non-react-statics` as a direct dependency in my project, and instead opted for using the `resolutions` field to force the use of version 3.3.0 across the project. In the time since last August I've been able to upgrade the rest of my direct dependencies that were making me indirectly dependent on older versions of `hoist-non-react-statics` so I'm sure I could remove the forced resolution and the problem would remain solved. However, I don't plan to do that because I like that leaving that field in place will prevent an older version of the package from being installed by accident as a sub-dependency of some other package I might add in the future.

**Comment by kg-currenxie** [comment] 2020-03-05 01:42
Adding `resolutions` solved it! <3 Spent 3 hours debugging :P

**Comment by orta** [comment] 2021-06-07 14:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:09 UTC
