### ISSUE TITLE
[@types/matter-js] outdated 

### ISSUE THREAD

**Issue by nukadelic** [DefinitelyTyped/DefinitelyTyped#24665] opened 2018-04-01 05:47 UTC
Please update to version [0.14.1](https://raw.githubusercontent.com/liabru/matter-js/master/build/matter.js)

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/matter-js

@piranha771, @hasparus, https://twitter.com/ivanegegia

**Comment by kcolton** [comment] 2018-06-29 02:47
Duplicate of: #24257

The types are some of the most accessible docs and its a bummer to have to remove entirely to use (or I don't know which commands to override to relax tsc being used through `ts-loader` to warn on issues)

I'm gonna take a stab at it for 14.x

**Comment by kcolton** [comment] 2018-07-05 18:20
I have started working on adding some of the missing definition's. It's been more work than anticipated, but I'll eventually get through it: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...kcolton:master

If someone is in a pinch - you can try using my branch at your own risk. 

It will likely still be a few weeks before it is ready to be published. I have a lot of tests to write.

It's hard to know how many more changes I need to make. The tests will help figure that out and give a degree of confidence that i've covered more than just the use cases i'm running into.

One thing that would be helpful is knowing how the definitions were generated for the current version @piranha771  @hasparus.

Seems like maybe dts-gen or similar because of all the extra comments that came along for the ride.

@andy-ms Appreciate any advise you would have; good example definition packages, if you recognized the output format of the current type definitions, or anything else that comes to mind. My goal is to also leave this in a state where it is:
A) easy to maintain and does not fall so far behind again 
B) can be used as an example to the matter-js team in how it could improve their docs, save dev time, and ultimately take ownership of the definition file.

Much thanks! 😃

**Comment by andy-ms** [comment] 2018-07-09 20:08
I don't have much advice, other than to consider enabling more lint rules, particularly `export-just-namespace` and `no-unnecessary-class`. To fix `export-just-namespace`, remove `export = Matter;` and the `declare namespace Matter` wrapper and just export everything directly. To fix `no-unnecessary-class`, replace classes with only static methods with namespaces.

**Comment by orta** [comment] 2021-06-07 13:40
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:40 UTC
