### ISSUE TITLE
@types/chrome-apps errors in index.d.ts

### ISSUE THREAD

**Issue by mburakkalkan** [DefinitelyTyped/DefinitelyTyped#28387] opened 2018-08-25 17:07 UTC
- [x] I tried using the `@types/chrome-apps` package and had problems.
- [x] I tried using the latest stable version of tsc `(3.0.1)`. (Also tried 2.8.4 and 2.9.2)
- [x] Authors: @niikoo @AdamLay @pine613 @mzsm @RReverser @pyle @matthewkimber @otiai10 @couven92 @rreverser @sreimer15 

I am developing a nwjs app with angular 6 which I will use chrome.* api somewhere. I added the `/// <reference types="chrome-apps" />` line on top of my component ts file. But I am getting these errors when `ng build`:

> ERROR in node_modules/@types/chrome-apps/index.d.ts(4859,31): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4859,51): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4861,31): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4861,51): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4861,79): error TS1128: Declaration or statement expected.
> node_modules/@types/chrome-apps/index.d.ts(4861,102): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(4863,22): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4865,37): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4865,41): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4867,22): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4867,26): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4869,39): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4869,43): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4871,26): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4871,30): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4873,22): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4875,21): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4875,26): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4875,60): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4875,82): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(4877,22): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4877,27): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4877,89): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(4879,23): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(4879,28): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(4879,97): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(4993,19): error TS1005: '>' expected.
> node_modules/@types/chrome-apps/index.d.ts(4993,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4993,54): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4994,15): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4994,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4994,56): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4995,16): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4995,38): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4995,61): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4996,15): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4996,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4996,51): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4996,60): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(4998,24): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5000,26): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5002,29): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5004,30): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5006,22): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5006,30): error TS1005: ':' expected.
> node_modules/@types/chrome-apps/index.d.ts(5006,75): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(5006,96): error TS1005: ')' expected.
> node_modules/@types/chrome-apps/index.d.ts(5008,41): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5037,19): error TS1005: '>' expected.
> node_modules/@types/chrome-apps/index.d.ts(5037,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5037,60): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5037,75): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5039,26): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5041,32): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5043,25): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5045,22): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5048,19): error TS1005: '>' expected.
> node_modules/@types/chrome-apps/index.d.ts(5048,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5048,56): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5049,16): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5049,38): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5049,61): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5049,71): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5051,21): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5051,29): error TS1005: ':' expected.
> node_modules/@types/chrome-apps/index.d.ts(5051,72): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(5051,91): error TS1005: ')' expected.
> node_modules/@types/chrome-apps/index.d.ts(5053,44): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(5055,32): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5057,20): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5093,29): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5093,49): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5099,25): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5099,45): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5135,29): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5135,49): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5137,32): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5137,52): error TS1005: ';' expected.
> node_modules/@types/chrome-apps/index.d.ts(5137,92): error TS1005: '(' expected.
> node_modules/@types/chrome-apps/index.d.ts(5142,19): error TS1005: '>' expected.
> node_modules/@types/chrome-apps/index.d.ts(5142,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5142,54): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5143,15): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5143,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5143,56): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5143,64): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5145,28): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5147,21): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5154,21): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5157,19): error TS1005: '>' expected.
> node_modules/@types/chrome-apps/index.d.ts(5157,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5157,56): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5157,64): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5159,27): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5165,32): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5167,24): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5169,25): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5171,21): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5173,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5177,19): error TS1005: '>' expected.
> node_modules/@types/chrome-apps/index.d.ts(5177,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5177,54): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5178,15): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5178,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5178,56): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5179,15): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5179,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5179,51): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5179,60): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5180,13): error TS1109: Expression expected.
> node_modules/@types/chrome-apps/index.d.ts(5185,39): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5187,28): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5189,32): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5191,38): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5193,27): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5195,29): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5201,29): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5201,37): error TS1005: ':' expected.
> node_modules/@types/chrome-apps/index.d.ts(5201,62): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5204,19): error TS1005: '>' expected.
> node_modules/@types/chrome-apps/index.d.ts(5204,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5204,54): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5204,63): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5206,28): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5208,32): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(5210,37): error TS1005: ',' expected.
> node_modules/@types/chrome-apps/index.d.ts(9422,1): error TS1128: Declaration or statement expected.

**Comment by pyle** [comment] 2018-08-26 04:29
I also encountered this issue on Friday whilst building from version 0.0.2 of @types/chrome-apps (also angular 6).
It doesn't appear to be related to a specific version of Typescript. 

What i think is happening is that instead of just using the @types/chrome-apps as a reference for the editor the compiler is attempting to build the files.

I was able to reproduce in a new @angular/cli project (both @types/chrome-apps@{0.0.1,0.0.2}, but unable to reproduce in a plain typescript build environment, which leads me to believe that the angular cli compiler/webpack config is attempting to bundle this in with it's build.

Surprisingly if I add some other random typing such as 'chrome' or 'moment' to the reference comment it doesn't throw these kinds of errors. 

@mburakkalkan As a workaround for the moment just remove the comment at the top of your file, the editor should still know about it provided the "node_modules/@types" folder is referenced in tsconfig.json under "typeRoots".

@niikoo Has this been failing for your use cases/build tools?

**Comment by mburakkalkan** [comment] 2018-08-26 09:12
I commented out the whole `networking.onc` namespace typings from index.d.ts and now it compiles without errors. I think there is something wrong in that.

**Comment by niikoo** [comment] 2018-08-26 09:53
It did not fall the tests, but I have fixed and rebuilt all the typings. Waiting for PR to be merged.

**Comment by pyle** [comment] 2018-09-03 06:08
Angular CLI: 6.1.5
Node: 9.10.1
OS: linux x64
Angular: 6.1.6

Steps to reproduce:
1. install latest `@angular/cli`
2. create new app `ng new test-app`
3. install latest typing `npm i --save-dev @types/chrome-apps`
4. `ng build` -> Build success
5. `ng build --aot` -> Build success
6. Add the following line to `test-app/src/app/app.component.ts`
`/// <reference types="chrome-apps" />`
Build fails with below error

Appears to be failing at the vendor chunk step: chunk {vendor}

Also fails in the following project i work on if I add `@types/chrome-apps`:
https://github.com/google/loaner/blob/master/loaner/package.json


Build Error:
```
ERROR in node_modules/@types/chrome-apps/index.d.ts(40,28): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(40,36): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(40,42): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(40,60): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(44,15): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(44,23): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(44,29): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(44,50): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(44,59): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(44,72): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(3343,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(3343,27): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(3344,15): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(3345,15): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(3346,24): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(3346,54): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5656,31): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5656,51): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5658,31): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5658,51): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5658,79): error TS1128: Declaration or statement expected.
node_modules/@types/chrome-apps/index.d.ts(5658,102): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5660,22): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5662,37): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5662,41): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5664,22): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5664,26): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5666,39): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5666,43): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5668,26): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5668,30): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5670,22): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5672,21): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5672,26): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5672,60): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5672,82): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5674,22): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5674,27): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5674,89): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5676,23): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5676,28): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5676,97): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5790,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(5790,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5790,54): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5791,15): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5791,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5791,56): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5792,16): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5792,38): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5792,61): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5793,15): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5793,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5793,51): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5793,60): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5795,24): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5797,26): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5799,29): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5801,30): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5803,22): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5803,30): error TS1005: ':' expected.
node_modules/@types/chrome-apps/index.d.ts(5803,75): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5803,96): error TS1005: ')' expected.
node_modules/@types/chrome-apps/index.d.ts(5805,41): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5834,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(5834,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5834,60): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5834,75): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5836,26): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5838,32): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5840,25): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5842,22): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5845,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(5845,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5845,56): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5846,16): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5846,38): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5846,61): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5846,71): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5848,21): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5848,29): error TS1005: ':' expected.
node_modules/@types/chrome-apps/index.d.ts(5848,72): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5848,91): error TS1005: ')' expected.
node_modules/@types/chrome-apps/index.d.ts(5850,44): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5852,32): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5854,20): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5890,29): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5890,49): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5896,25): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5896,45): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5932,29): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5932,49): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5934,32): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5934,52): error TS1005: ';' expected.
node_modules/@types/chrome-apps/index.d.ts(5934,92): error TS1005: '(' expected.
node_modules/@types/chrome-apps/index.d.ts(5939,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(5939,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5939,54): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5940,15): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5940,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5940,56): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5940,64): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5942,28): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5944,21): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5951,21): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5954,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(5954,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5954,56): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5954,64): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5956,27): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5962,32): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5964,24): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5966,25): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5968,21): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5970,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5974,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(5974,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5974,54): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5975,15): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5975,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5975,56): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5976,15): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5976,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5976,51): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5976,60): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5977,13): error TS1109: Expression expected.
node_modules/@types/chrome-apps/index.d.ts(5982,39): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5984,28): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5986,32): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5988,38): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5990,27): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5992,29): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5998,29): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(5998,37): error TS1005: ':' expected.
node_modules/@types/chrome-apps/index.d.ts(5998,62): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(6001,19): error TS1005: '>' expected.
node_modules/@types/chrome-apps/index.d.ts(6001,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(6001,54): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(6001,63): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(6003,28): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(6005,32): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(6007,37): error TS1005: ',' expected.
node_modules/@types/chrome-apps/index.d.ts(11504,1): error TS1128: Declaration or statement expected.

```

**Comment by niikoo** [comment] 2018-09-04 08:38
The default typescript version is:
`"typescript": "~2.7.2"` (package.json)

`chrome-apps` requires 2.8, see:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome-apps/index.d.ts#L5

**Comment by pyle** [comment] 2018-09-05 21:39
Yep, that did it, cheers. Was too used to the old chrome typings with version 2.4; 

Default `@angular/cli` client creates a project with typescript 2.7.2 @mburakkalkan , nrwl uses ng cli so this is probably the case for yourself.

**Comment by mburakkalkan** [comment] 2018-09-16 19:17
@niikoo I tried using the latest stable version of tsc (3.0.1). (Also tried 2.8.4 and 2.9.2)

**Comment by mburakkalkan** [comment] 2018-09-16 19:28
Oh @niikoo, excuse me, the global tyscript installation is a different thing from being a dependency. I missed this important difference. The versions that I mentioned above was the global ts versions. Sorry, I am now trying to upgrade angular's ts version as you told. I will be back soon with the result 👍

**Comment by mburakkalkan** [comment] 2018-09-16 19:58
Yes, builded without errors with local ts 2.9.2, great!

And 3.0.3 builds without errors too, but only shows a warning like angular-cli recommending ts version should be between 2.7.2 and 2.10.

I think this could be my fault on global vs local dependency confusion 🙄 Sorry for that and thank you for your interest!

**Comment by niikoo** [comment] 2018-09-20 16:47
No problem @mburakkalkan.
Could you close this issue?

**Closed** 2018-09-21 03:36 UTC
