### ISSUE TITLE
[@types/react] ComponentType should allow props subtype

### ISSUE THREAD

**Issue by JalilArfaoui** [DefinitelyTyped/DefinitelyTyped#35923] opened 2019-06-03 14:07 UTC
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @pshrmn @saranshkataria @lukyth @eps1lon 

IMHO `ComponentType` should authorize a  function to use a subtype of props of a specific component type : 

I can't see why this shouldn't work : 

```tsx
interface AB {
  a: "A" | "B";
}
interface ABC {
  a: "A" | "B" | "C";
}
const someFunc = (Comp: ComponentType<AB>) => <Comp a="B" />;

const list: ComponentType<ABC>[] = [];

const specificallyRenderedList = list.map(someFunc);
```

I get : 
```
Error:(53, 43) TS2345: Argument of type '(Comp: ComponentType<AB>) => Element' is not assignable to parameter of type '(value: ComponentType<ABC>, index: number, array: ComponentType<ABC>[]) => Element'.
  Types of parameters 'Comp' and 'value' are incompatible.
    Type 'ComponentType<ABC>' is not assignable to type 'ComponentType<AB>'.
      Type 'ComponentClass<ABC, any>' is not assignable to type 'ComponentType<AB>'.
        Type 'ComponentClass<ABC, any>' is not assignable to type 'ComponentClass<AB, any>'.
          Types of property 'propTypes' are incompatible.
            Type 'WeakValidationMap<ABC> | undefined' is not assignable to type 'WeakValidationMap<AB> | undefined'.
              Type 'WeakValidationMap<ABC>' is not assignable to type 'WeakValidationMap<AB>'.
                Types of property 'a' are incompatible.
                  Type 'Validator<"A" | "B" | "C"> | undefined' is not assignable to type 'Validator<"A" | "B"> | undefined'.
                    Type 'Validator<"A" | "B" | "C">' is not assignable to type 'Validator<"A" | "B">'.
                      Type '"A" | "B" | "C"' is not assignable to type '"A" | "B"'.
                        Type '"C"' is not assignable to type '"A" | "B"'.
```

I can't see why, if `someFunc` is able to work with a component that can take `'A'` or `'B'`, it wouln't garantee that it can work with a component able to handle `'A'` or `'B'` or `'C'` ? 

Shouldn't we consider that `ComponentType<SomeSubType>` is a subtype of `ComponentType<SomeType>` ? And then apply Liskov substitution principle ?

**Comment by JalilArfaoui** [comment] 2019-06-27 08:49
Has any of you @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @pshrmn @saranshkataria @lukyth @eps1lon had a change to read this ?

**Comment by eps1lon** [comment] 2019-06-27 12:31
So your function expects a component that has `'A' | 'B'` but you're giving it a list of components that have `'A' | 'B' | 'C'`. Your function can't deal with the literal `'C'` which is what error tells you.

For more information about the topic see covariant vs contravariant types.

**Comment by JalilArfaoui** [comment] 2019-06-27 19:53
Thanks for you answer @eps1lon 

My understanding is that : 

- `someFunc` can take as an input any component that has a prop `a` that can be either litteral `"A"` or litteral `"B"`. This is what I understand from `ComponentType<AB>`. 
- I feed `map` with components that can have props `a` that can be either litteral `"A"` or litteral `"B"` or litteral `"C"`. 
 - That means that we're trying to feed `someFunc`  with a component that can have `"A"`, `"B"` or `"C"` in `a`. 

I would believe that we could always give a component that can take `"A"`, `"B"` or `"C"` to a function that would only use `"A"` or `"B"` values ...

To help me understand where I'm mistaken, could you give me an example that wouldn't work here ?

**Comment by JalilArfaoui** [comment] 2019-06-27 20:05
> Your function can't deal with the literal 'C' which is what error tells you.

My function doesn't want to, and doesn't know about possible `"C"` value.  

The other way around works fine : 

```ts
const otherFunc = (props: ABC) => props.a;
const obj: AB = { a: 'B' };
otherFunc(obj);
```

Except in this one it's about what value is given to the function (it has to be a subset of what the function can handle), whereas with the component it seems to me it's the other way around : we pass to the function a component that must be to handle values (props) : we have to pass a component that can handle a superset of what will be passed to it....

I'm sure I'm mistaken somewhere, but I'd like to understand where ...

**Comment by ferdaber** [comment] 2019-07-11 15:33
Your issue can be simplified to the following issue:
```ts
declare const ABC: (arg: 'A' | 'B' | 'C') => unknown
declare const AB: (arg: 'A' | 'B') => unknown
declare function higherOrderFunction(func: typeof ABC): unknown
higherOrderFunction(AB); // error
```

The issue is that in the implementation of `higherOrderFunction`, it expects to be able to call its `func` argument that's passed in with an arg that is of type `'C'`, but since you passed in `AB`, that won't work and therefore is type-unsound. This is why when dealing with functions as parameters, the types are compared contravariantly (goes the other way around).

Of course, your specific example uses the built-in `Array.prototype.map` function and we know as humans that the `map` function doesn't actually invoke its arguments (it doesn't care that the arguments are functions), but TypeScript has no knowledge of that and therefore will err on the careful side.

If you want this to not error for you, you can disable the `--strictFunctionTypes` compiler option in your `tsconfig.json` file, and it will perform bivariant parameter checking for function types.

**Comment by orta** [comment] 2021-06-07 13:13
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:13 UTC
