### ISSUE TITLE
Lodash 4.14.52 Typescript Compile Errors

### ISSUE THREAD

**Issue by abbeyciolek** [DefinitelyTyped/DefinitelyTyped#14384] opened 2017-02-01 18:29 UTC
I tried using the `@types/lodash` package and had problems.
Compiled with tsc v2.1.1
@bczengel , @Sheeo 

received the following errors: 

```
node_modules/@types/lodash/index.d.ts(11444,21): error TS1005: ']' expected.
node_modules/@types/lodash/index.d.ts(11444,22): error TS1005: ';' expected.
node_modules/@types/lodash/index.d.ts(11444,23): error TS1128: Declaration or statement expected.
node_modules/@types/lodash/index.d.ts(11444,33): error TS1005: ']' expected.
node_modules/@types/lodash/index.d.ts(11444,34): error TS1005: ')' expected.
node_modules/@types/lodash/index.d.ts(11444,35): error TS1128: Declaration or statement expected.
node_modules/@types/lodash/index.d.ts(11444,37): error TS1128: Declaration or statement expected.
node_modules/@types/lodash/index.d.ts(19441,1): error TS1128: Declaration or statement expected.
~$ tsc -v
Version 2.1.1
```

**Comment by Sheeo** [comment] 2017-02-01 18:39
Cannot reproduce using TypeScript 2.1.5

**Comment by ihadeed** [comment] 2017-02-02 07:26
I can confirm this. Tried using TypeScript `2.0.10` and `2.1.5`.

**Comment by ihadeed** [comment] 2017-02-02 08:52
Upgrading to `2.1.5` solved this issue for me.

**Comment by votiakov** [comment] 2017-02-02 11:14
TypeScript 2.1.5+ resolves this issue.
Thanks.

**Comment by stepanzarubin** [comment] 2017-02-02 16:52
According to semantic versioning, there was a significant change which is breaking actually, so the version name has to be something like `4.15.0` or even `5.0.0` but not `4.14.52`.

Where can I see the full list of releases for @types/lodash?

**Comment by Sheeo** [comment] 2017-02-02 17:08
@stepanzarubin no, the semantic version of the type declarations follows the semantic version of the lodash version they target, currently 4.14. See [the issue](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14288#issuecomment-276667860) for discussion of it.

There currently seems to be no way to indicate from the typings that you'll need a newer TypeScript version to compile them -- all of this orthogonal to the version of the lodash package itself.

**Comment by mhegazy** [comment] 2017-02-02 17:42
This is a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14338. 

All `@types` packages have compiler version tags on them. e.g. `@ts2.0` or `@ts2.1`. so fixing the version of your dependency to `@types/lodash@ts2.0`  should avoid getting an incompatible version.

**Comment by Delagen** [comment] 2017-04-25 05:08
12394

**Comment by orta** [comment] 2021-06-07 19:05
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 19:05 UTC
