### ISSUE TITLE
[types/react-tracking] missing prop `tracking`

### ISSUE THREAD

**Issue by dutzi** [DefinitelyTyped/DefinitelyTyped#34738] opened 2019-04-15 11:34 UTC
- [ ] I tried using the `@types/react-tracking` package and had problems.

I'm getting the following error:
```
[0] src/index.tsx(240,16): error TS2741: Property 'tracking' is missing in type '{ brandColor: string; onConnect: (socialNetwork: Network) => Promise<void>; publisherName: string; onSignin: () => void; initialEmail: string | undefined; availableNetworks: Network[]; isMobile: boolean; }' but required in type '{ onSignin: () => void; onConnect: (socialNetwork: Network) => Promise<void>; publisherName: string; brandColor: string; initialEmail?: string | undefined; availableNetworks: Network[]; tracking: TrackingProp; isMobile: boolean; }'.
```

For the following code:
```js
const MyComponent = ({
  tracking,
}: {
  tracking: TrackingProp;
}) => {
  ...
});
export default track()(MyComponent);
```

@ferdaber

**Comment by ferdaber** [comment] 2019-04-15 15:40
This example isn't very helpful for me to be able to investigate. Can you post a minimal repo to reproduce the issue? Or expand on your example?

**Comment by dutzi** [comment] 2019-04-15 15:47
Sorry, here's something you can just place in VSCode and see the error:

```js
import React from 'react';
import track, { TrackingProp } from 'react-tracking';

const MyComponent = ({ tracking }: { tracking: TrackingProp }) => {
  tracking.trackEvent({});
  return <div>Hey!</div>;
};

let TrackedComponent = track()(MyComponent);

const MyComponent2 = () => {
  return <TrackedComponent />;
};

export default MyComponent2;
```

![image](https://user-images.githubusercontent.com/927310/56146487-f4f29e80-5fae-11e9-9ce8-a6395b6e0113.png)

**Comment by ferdaber** [comment] 2019-04-15 16:06
I don't maintain the types for `react-tracking` but from a cursory glance at their documentation it seems that its types are not appropriately injecting the `tracking` prop into the inner component, so I would ping the maintainer of this specific package. This issue doesn't seem to be related to the core react types package.

**Comment by Chnapy** [comment] 2020-04-21 14:11
I just started to use this lib, I found multiple issues on the typing.

Some types should not be exported:
- `ReactTrackingContext`, internal use only

Some types are not exported, but should be:
- `withTracking`, function
- `trackEvent`, function

Following [index.js](https://github.com/nytimes/react-tracking/blob/master/src/index.js). I may miss others issues.
I can do the changes, when I'll have time. But since I just started to use this lib it may be better that someone else does them.

@alloy @damassi @drbalm just in case you want/have time to work on this issue thanks 🙏

**Comment by damassi** [comment] 2020-04-21 15:29
Please see [the tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-tracking/test/react-tracking-with-types-tests.tsx) for example use-cases. If that's not sufficient, feel free to submit a PR with your suggestions.

**Comment by orta** [comment] 2021-06-07 13:12
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:12 UTC
