### ISSUE TITLE
bluebird-global then is typed incorrectly

### ISSUE THREAD

**Issue by aaronjensen** [DefinitelyTyped/DefinitelyTyped#28083] opened 2018-08-13 16:16 UTC
- [x] I tried using the `@types/bluebird-global` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @d-ph 

This should typecheck, but does not:

```ts
const bar: Bluebird<string> = Promise.resolve<string|undefined>('hi').then(() => 'hi');
```

Switching to the TS lib definition of the below works:

```ts
then<TResult1 = T, TResult2 = never>(
  onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, 
  onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
): Bluebird<TResult1 | TResult2>;
```

It does break the tests though as `Bluebird<T>` is not assignable to `Promise<T>` because of:

```
Type 'Bluebird<string>' is not assignable to type 'Promise<string>'.
  Property '[Symbol.toStringTag]' is missing in type 'Bluebird<string>'.
```

That seems like a separate problem, so perhaps the tests should be changed.

**Comment by d-ph** [comment] 2018-08-14 23:05
Just a complete side note (without giving a proper thought to what the ticket says): 

I'm aware that Bluebird isn't compatible (type-wise) with standard Promise. This has improved massively over time -- as you said, the only problem now is the missing `Symbol` property. This doesn't change a fact that the use case you mentioned is quite unlikely in my book. The whole reason to use `bluebird-global` (or at least a secondary reason) is to avoid using the `Bluebird` symbol, and instead just use the Promise symbol. In other words, casting a Promise to a Bluebird (e.g. via assigning a Promise to a Bluebird variable) is a low priority use case in `bluebird-global`. If one still needs to do that, they can wrap a Promise in a Bluebird constructor, which will satisfy both TypeScript and the runtime (in runtime it would probably be a noop).

It'd be easier if Bluebird cleanly extended the standard Promise in TypeScript world, for sure. It's just a question of whether we want to touch the status quo.

**Comment by aaronjensen** [comment] 2018-08-14 23:13
FWIW, that was only a contrived example that demonstrated the issue. With the `then` types as they were I had breaks in several places in my codebase and I don't have anything that casts to `Bluebird`.

**Comment by d-ph** [comment] 2018-08-26 14:25
Hi again,

I created a PR for bringing the `then` and `catch` methods back to sync with what the std ts lib says. As you can probably tell, they were in sync once. In the future, when we drop TS 2.x support (actually, when `@types/bluebird` drop TS 2.x support), I will make use of the new TS 3 feature that will allow me to remove the copy&paste from std lib. This should hopefully fix the breaks in your codebase.

About casting to Bluebird promises. I added an information in `@types/bluebird-global` that casting to Bluebird is expected to cause problems. I also mentioned a walkaround if casting is still needed. The bottom line is this: due to how `bluebird-global` exposes Bluebird's methods, the global Promise will never be a Bluebird promise type-wise. It might be sometimes, but it's not something devs should rely on. It's obviously not a ideal, since at runtime you can mix global Promises and Bluebird promises. I can't, however, think of any way of achieving full type compatibility with current TS feature set. But again, this shouldn't be a massive issue, if devs settle on using either the global Promise or the Bluebird promise in their projects (as opposed to using both). You said that nowhere in you codebase do you cast to `Bluebird` -- that means that it _should_
work and if it still doesn't after my current PR gets merged, then I'd appreciate if you could come up with the minimal steps-to-reproduce of the remaining problems without trying to cast to a `Bluebird`-typed variable (as you did in the ticket's original message).

About the last comment you made in the original ticket message:
```
Property '[Symbol.toStringTag]' is missing in type 'Bluebird<string>'.
```
In runtime, Bluebird promises don't implement the `[Symbol.toStringTag]` property. Therefore, the d.ts for Bluebird doesn't mention it and therefore the assignment fails.

Bluebird devs do great job at being as compatible with std lib Promise as possible. However, as you can see, these 2 "projects" are run by two different "bodies" and therefore there will be discrepancies (which are hopefully addressed as they appear). I wouldn't like `bluebird-global` to be "the person" who points out the discrepancies. And therefore I really don't see `bluebird-global` ever trying to fully say that the global Promise _is_ the Bluebird promise -- just for the sake of being a good "team player" in the ecosystem. I would however see and use a TS feature, which would allow me and other people to definitely say that "in my codebase, please ignore all typings that define and/or augment a certain global symbol (e.g. Promise) and use this specific polyfill for it (e.g. Bluebird)" . This, however, is not the situation we are in, so we need to adapt to what we've got and see how it goes. I'd say `bluebird-global` is doing a quite decent job at being both a good "team player" and being useful to the end devs.

Let me know what you think about it.

@d-ph

**Comment by aaronjensen** [comment] 2018-08-26 17:13
@d-ph Thank, I'll take a look soon. 
What is the TS 3 feature you're referring to?

**Comment by d-ph** [comment] 2018-08-26 17:41
The TS 3 feature I refer to is the triple-slash `<reference lib="..." />`. Nothing major, but allows me to drop the copy&paste job in `bluebird-global` typings, which is needed if someone compiles to es5.

http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#-reference-lib--reference-directives
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3cf39396301026e5e063080cc36253052db914c5/types/bluebird-global/index.d.ts#L89

But again, I updated the copy&paste job in the current typings, so we don't need to wait for dropping the TS 2.x support.

**Comment by aaronjensen** [comment] 2018-08-27 14:51
No problem. What if bluebird-global.d.ts was generated from bluebird.d.ts. It could be a babel transform that resulted in a `bluebird-global.d.ts` that didn't reference `Bluebird` at all, and instead typed `Promise` to be just like a `Bluebird`. The idea would be that `Promise` was `Bluebird` and you'd never actually import a `Bluebird` in your codebase. If you did, you'd have to `Promise.resolve` it to get it to be a `Promise`.

As long as everything is dealing with `Promise`, it should work fine. The problem is when mixing `Promise` and `Bluebird` and I don't see a way around that other than to eliminate `Bluebird`.

**Comment by d-ph** [comment] 2018-08-28 22:58
Generating `bluebird-global` from `bluebird` typings would be too elaborate, although I admit it would solve the problem.

I came up the following type alias that changes the return type of a function from `Bluebird<T>` to `Promise<T>`
```typescript
type ChangeReturnTypeToPromise<T extends Function> = T extends (...args: infer ArgsT) => Bluebird<infer PromiseT> ? (...args: ArgsT) => Promise<PromiseT> : never;

// ...
  delay: ChangeReturnTypeToPromise<typeof Bluebird.delay>;
// ...
```
Unfortunately, it works only on functions that don't use generic types. Which is the minority of the functions in `Bluebird`.

At this point, the situation looks pretty grim to me.

**Comment by aaronjensen** [comment] 2018-08-28 23:06
I hit the same problem when I tried, it makes all generic types `{}`.

For now, I think I'll continue importing bluebird in and using it. Perhaps future versions of TS will offer other options. In the meantime, your PR is an improvement, so may as well get that in and perhaps add an additional caveat.

Thanks!

**Comment by d-ph** [comment] 2018-08-29 20:53
I added a docblock information about the problem with the return type of bluebird-specific methods.

Thanks for bringing these problems into light. And apologies for these limitations.

@d-ph

**Comment by aaronjensen** [comment] 2018-08-30 01:11
No problem. Thank you for your help.

**Comment by Shahaed** [comment] 2018-09-28 17:01
Nice!

**Comment by orta** [comment] 2021-06-07 13:17
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:17 UTC
