### ISSUE TITLE
[Lodash] Excessive stack depth comparing types

### ISSUE THREAD

**Issue by rhys-vdw** [DefinitelyTyped/DefinitelyTyped#25632] opened 2018-05-09 05:37 UTC
```ts
function safeFindIndex<T extends object>(
  array: ReadonlyArray<T>,
  matcher: Partial<T>,
  recordName: string,
  assertMatcher: Partial<T> | undefined
): number {
  const index = findIndex(array, matcher)  // ERROR HERE: immutable-array.ts:21
  if (index === -1) {
    reportError(new TypeError(`Couldn't find ${recordName}`), { extra: { matcher } })
  } else {
    const found = array[index]
    if (assertMatcher !== undefined && !isMatch(found, assertMatcher)) {
      reportError(
        new TypeError(`${recordName} was in unexpected state`),
        { extra: { record: found, assertMatcher } }
      )
    }
  }
  return index
}
```

This code causes this error:

```
ERROR in [at-loader] TS2321: Excessive stack depth comparing types 'Partial<T>' and 'string | [string, any] | ListIterator<T, boolean> | PartialDeep<T> | undefined'.

ERROR in [at-loader] ./app/assets/javascripts/utilities/immutable-array.ts:21:34
    TS2321: Excessive stack depth comparing types 'Partial<T>' and 'string | [string, any] | ListIterator<T, boolean> | PartialDeep<T> | undefined'.
```

**package versions**
- `@types/lodash@4.14.108`
- `typescript@2.8.1`

This is not an issue with `@types/lodash@4.14.106`

**cc:** @aj-r @andy-ms

**Comment by andy-ms** [comment] 2018-05-09 14:44
@rhys-vdw This looks like a duplicate of Microsoft/TypeScript#21592.

It looks like it's fixed in your case if you write `matcher: _.PartialDeep<T>,` instead of `matcher: Partial<T>`.

**Closed** 2018-05-09 14:44 UTC
