### ISSUE TITLE
testing-library-react: incorrect typescript error thrown for render result

### ISSUE THREAD

**Issue by Ardeshir81** [DefinitelyTyped/DefinitelyTyped#41130] opened 2019-12-18 17:34 UTC
- [x] I tried using the `@types/testing-library__react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.7.3)
- [?] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there). (**this is not a question, its a bug report**)
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@alexkrolick
@kentcdodds
@eps1lon
@weyert
@ifiokjr
@danieljcafonso

```tsx
const { queryByTestId } = render(
    <MyComponent />
  );
```
throws me a typescript error in my IDE:

> Property 'queryByTestId' does not exist on type 'RenderResult<typeof import("./node_modules/@types/testing-library__dom/queries")>'.ts(2339)

but the function actually exists and is usable and everything in console is fine!

I have no typescript problems with other queries (`queryByRole`, etc...)

**Comment by danieljcafonso** [comment] 2019-12-18 18:14
Hello @Ardeshir81 😄 
What IDE are you using? I'm unable to reproduce that issue on VSCode 😕

**Comment by Ardeshir81** [comment] 2019-12-19 10:51
HI!
I'm using VSCode 1.41.0

This is my exact code:
```tsx
import { render, fireEvent, wait } from '@testing-library/react';
// ...
test('renders with no problem', () => {
  // ...
  const { queryByTestId } = render(
    <InterfaceIPConfig
      formState={Test.getFakeFormInputs()}
      setFormState={Test.SetFakeFormState}
    />
  );
  // ...
})
```

and this is my error:

![Screenshot_2019-12-19_11-00-02](https://user-images.githubusercontent.com/5755214/71154042-e5b7a500-224f-11ea-9dac-2c57b6453849.png)



this is my `package.json`:
```json
{
  "devDependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@types/jest": "^24.0.23",
    "@types/node": "^12.12.14",
    "@types/react": "^16.9.15",
    "@types/react-dom": "^16.9.4",
    "@types/react-router-dom": "^5.1.3",
    "concurrently": "^5.0.0",
    "eslint-plugin-prettier": "^3.1.1",
    "husky": "^3.1.0",
    "prettier": "1.19.1",
    "pretty-quick": "^2.0.1",
    "react-app-rewired": "^2.1.5",
    "scp": "0.0.3",
    "typescript": "^3.7.3"
  },
}
```

and this is parts of my `package-lock.json`:
```json
{
  "@types/testing-library__dom": {
      "version": "6.10.0",
      "resolved": "https://registry.npmjs.org/@types/testing-library__dom/-/testing-library__dom-6.10.0.tgz",
      "integrity": "sha512-mL/GMlyQxiZplbUuFNwA0vAI3k3uJNSf6slr5AVve9TXmfLfyefNT0uHHnxwdYuPMxYD5gI/+dgAvc/5opW9JQ==",
      "dev": true,
      "requires": {
        "pretty-format": "^24.3.0"
      }
    },
    "@types/testing-library__react": {
      "version": "9.1.2",
      "resolved": "https://registry.npmjs.org/@types/testing-library__react/-/testing-library__react-9.1.2.tgz",
      "integrity": "sha512-CYaMqrswQ+cJACy268jsLAw355DZtPZGt3Jwmmotlcu8O/tkoXBI6AeZ84oZBJsIsesozPKzWzmv/0TIU+1E9Q==",
      "dev": true,
      "requires": {
        "@types/react-dom": "*",
        "@types/testing-library__dom": "*"
      }
    },
}
```

Thanks @danieljcafonso for devoting time on this

**Comment by danieljcafonso** [comment] 2019-12-20 15:59
Hi again @Ardeshir81
Once again, I've tried to reproduce the issue with the same conditions you have and failed to reproduce it.
Not sure this may help, but there is a minor update on the `@types/testing-library__dom`. Try to update your dependencies and check if the issue persists.

**Comment by Ardeshir81** [comment] 2019-12-21 11:38
YEP!

That solved the issue 

THANKS!

**Comment by Ardeshir81** [comment] 2019-12-21 11:42
btw, I had to explicitly install `@types/testing-library__dom`, it wasn't already in my `package.json`, but now it is! I'm not sure if that is a problem with me being unable to use npm to update it , or with other packages that depend on it that they forgot to update the dependency.

**Comment by eps1lon** [comment] 2019-12-27 06:28
> That solved the issue

@Ardeshir81 Would you be so kind and close the issue if this is solved for yoU?

**Closed** 2019-12-29 05:08 UTC
