### ISSUE TITLE
Cannot install @types/react-router-dom

### ISSUE THREAD

**Issue by md-shahnawaz08** [DefinitelyTyped/DefinitelyTyped#36104] opened 2019-06-11 07:30 UTC
```
npm install @types/react-router-dom
```
```
npm ERR! Unexpected end of JSON input while parsing near '...ue9VlHwQSChuoAqmIDkEG'

npm ERR! A complete log of this run can be found in:
npm ERR!     \npm-cache\_logs\2019-06-11T07_28_08_137Z-debug.log
```

**Comment by AnderssonPeter** [comment] 2019-06-16 09:23
I just installed it with no errors.
I'm using node v12.4.0 and npm v9.6.0.

**Comment by joealden** [comment] 2019-06-20 11:18
@md-shahnawaz08  please only open one issue for a problem you are having (this is a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35943).

**Closed** 2019-06-21 07:23 UTC
