### ISSUE TITLE
Definition Request: math.js

### ISSUE THREAD

**Issue by dbeckwith** [DefinitelyTyped/DefinitelyTyped#4269] opened 2015-05-05 15:13 UTC
http://mathjs.org/index.html

**Comment by usernaem** [comment] 2015-10-17 19:15
+1

**Comment by DanCorder** [comment] 2015-12-07 12:17
Duplicate of #3275 ?

**Comment by vagaroso** [comment] 2015-12-07 12:20
@DanCorder yep

**Closed** 2015-12-10 13:21 UTC
Labels: Definition:Request
