### ISSUE TITLE
React components with multiple root elements are not supported

### ISSUE THREAD

**Issue by xMihai** [DefinitelyTyped/DefinitelyTyped#20356] opened 2017-10-06 12:37 UTC
- [X] I tried using the `@types/react` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @richseviora

React 16 components can have multiple root elements.

`const Items = ({ items }: MyProps) => items.map(item => <div key={item.id}>{item.name}</div>)`

However, TypeScript will break with:
`error TS2605: JSX element type 'Element[]' is not a constructor function for JSX elements.
  Property 'render' is missing in type 'Element[]'.`

**Comment by tkrotoff** [comment] 2017-10-06 14:53
See PR #19363

**Comment by danedavid** [comment] 2017-10-12 17:49
That PR has been merged, so now does this work ?

**Comment by xMihai** [comment] 2017-10-13 08:19
It throws the same error with `@types/react@16.0.10`

Returning array of elements works in React 16. The SO answer is incorrect.
I can suppress the Typescript error and have my code working if I cast my component as `any`:
`const Items: any = ({ items }: MyProps) => items.map(item => <div key={item.id}>{item.name}</div>)`

**Comment by edorivai** [comment] 2017-10-13 13:09
Just leaving my reproduction repo of my SO question here for reference:
https://github.com/edorivai/ts-sfc-array

**Comment by kiliancs** [comment] 2017-10-27 17:14
Experiencing the same problem using @types/react version 16.0.18.

As simple as `({ name }) => [ <span>Hello</span>, <span>{name}</span> ]`;

**Comment by ericlam51** [comment] 2017-11-13 19:49
The problem is still present for `16.0.22`

**Comment by TheFullResolution** [comment] 2017-11-17 08:04
The problem is still present for 16.0.24

**Comment by madou** [comment] 2017-11-17 21:59
Trying to keep as much type safety as I could, I'm typing my SFC that return arrays like this atm:

```
const MapPage: React.StatelessComponent<Props> = (props): any => [
  <div key={1}>hi</div>
];
```

**Comment by Profeten** [comment] 2018-02-07 12:55
Is this resolved yet?

**Comment by donaldpipowitch** [comment] 2018-02-07 12:58
No. We'll probably need to wait for https://github.com/Microsoft/TypeScript/issues/21699 which is aimed to be included in TypeScript 2.8. There are several steps which need to be implemented first: https://github.com/Microsoft/TypeScript/pull/20239#issuecomment-363372640.

**Comment by pke** [comment] 2018-09-06 13:06
Since https://github.com/Microsoft/TypeScript/pull/20239#issuecomment-363372640 has been closed now, do we still have to wait for Microsoft/TypeScript#21699 to get this fixed?

**Comment by lipemat** [comment] 2019-05-15 21:31
To workaround the issue in the meantime I was able to suppress the error by casting the component to `any`. 
In the provided example it would look like this.
```js
const Items: any = ({ items }: MyProps) => items.map(item => <div key={item.id}>{item.name}</div>)
```
Like other provided workarounds, it's not 100% ideal but it does resolve the issue.

**Comment by Spektr** [comment] 2019-12-02 13:46
as a workaround without :any
```
function getSingleElement(): JSX.Element {
    return <>{itemsInArray}</>;
}
```

**Comment by eps1lon** [comment] 2020-08-13 12:49
This is essentially a duplicate of #18912. Once  Microsoft/TypeScript#21699 is resolved we should be able to use `ReactNode` as a valid return type for function components which includes `string` and `boolean`.

**Comment by orta** [comment] 2021-06-07 14:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:11 UTC
