### ISSUE TITLE
Express typings require superfluous declaration

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#24265] opened 2018-03-13 16:02 UTC
@andy-ms @tkrotoff @zaggino @micksatana @alex3165

I have this issue on SO:

https://stackoverflow.com/questions/49260387/express-router-file-has-a-typescript-error/49260575

I have a case where this doesn't compile:

```js
import * as express from 'express';
let router = express.Router();
export = router;
```

but this does:

```js
import * as express from 'express';
let router = express.Router() as express.Router;
export = router;
```

seems superfluous and I am trying to figure out if it can be fixed.

**Comment by andy-ms** [comment] 2018-03-13 16:13
Duplicate of Microsoft/TypeScript#22504

**Closed by andy-ms** 2018-03-13 16:13 UTC
