### ISSUE TITLE
How to correctly define a reference (React.RefObject<StyledComponentClass>) for styled-components (for TypeScript)?

### ISSUE THREAD

**Issue by khusamov** [DefinitelyTyped/DefinitelyTyped#30225] opened 2018-11-02 06:37 UTC
I tried using the `@types/styled-components` package and had problems.

How to correctly define a reference for styled-components?

I wrote the following test code:

    import React, {Component, RefObject, ReactNode} from 'react';
    import styled, {StyledComponentClass} from 'styled-components';
    
    type TModalShadowContainer = StyledComponentClass<{}, any>;
    
    const ModalShadowContainer: TModalShadowContainer = styled.div` 
    	background-color: black;
    `;
    
    export default class Modal extends Component {
    
    	private readonly modalRef: RefObject<TModalShadowContainer>;
    
    	constructor(props: {}) {
    		super(props);
    		this.modalRef = React.createRef<TModalShadowContainer>();
    	}
    
    	public render(): ReactNode {
    		return (
    			<ModalShadowContainer ref={this.modalRef}>
    				{this.props.children}
    			</ModalShadowContainer>
    		);
    	}
    
    }

The error appears on the line:

    <ModalShadowContainer ref={this.modalRef}>

Error text:

    Type 'RefObject<StyledComponentClass<{}, {}, {}>>' is not assignable to type 'string | ((instance: Component<{ as?: string | ComponentClass<any, any> | StatelessComponent<any> | undefined; theme?: {} | undefined; }, any, any> | null) => any) | RefObject<Component<{ ...; }, any, any>> | undefined'.
      Type 'RefObject<StyledComponentClass<{}, {}, {}>>' is not assignable to type 'RefObject<Component<{ as?: string | ComponentClass<any, any> | StatelessComponent<any> | undefined; theme?: {} | undefined; }, any, any>>'.
        Type 'StyledComponentClass<{}, {}, {}>' is not assignable to type 'Component<{ as?: string | ComponentClass<any, any> | StatelessComponent<any> | undefined; theme?: {} | undefined; }, any, any>'.
          Property 'setState' is missing in type 'StyledComponentClass<{}, {}, {}>'.

How to describe (define) a ref in TypeScript lang?

Since everyone is trying to convince me not to do it, I have to refer to the original sources, namely:

https://www.styled-components.com/docs/advanced#refs  
https://reactjs.org/docs/refs-and-the-dom.html#creating-refs

**Comment by lukyth** [comment] 2018-11-02 06:49
Probably a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28884

**Comment by dawidk92** [comment] 2018-11-14 20:39
```js
interface StyledComponentClass
```
had been removed in `@types/styled-components@4.1.0`. What should we have been using instead of it?

Beside of that question is there any option to follow changes in typings? Some kind of changelog?

**Comment by tp** [comment] 2018-11-15 08:15
@dawidk92 Does the `AnyStyledComponent` type fulfill your needs?

**Comment by dawidk92** [comment] 2018-11-15 08:50
@tp yes, thank you :)

**Comment by orta** [comment] 2021-06-07 13:15
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:15 UTC
