### ISSUE TITLE
Chart.js - Object literal may only specify known properties, and 'stepSize' does not exist in type 'TickOptions'.

### ISSUE THREAD

**Issue by sandrocsimas** [DefinitelyTyped/DefinitelyTyped#27476] opened 2018-07-22 18:33 UTC
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti, @FabienLavocat, @KentarouTakeda, @larrybahr, @mernen, @josefpaij, @danmana, @guillaume-ro-fr, @chicoxyzzy, @archy-bold, @braincore, @gebeto, @frabnt, @alexdor.

I'm trying to use the library Chart.js in my Angular application with Typescript, but I'm getting the following error:
````
Error: Object literal may only specify known properties, and 'stepSize' does not exist in type 'TickOptions'.
````
Looking at the TickOptions interface, the property is really not present there, but it's on another interface that extends TickOptions, the interface LinearTickOptions:
````
interface LinearTickOptions extends TickOptions {
    maxTicksLimit?: number;
    stepSize?: number;
    suggestedMin?: number;
    suggestedMax?: number;
}
````
How to make Typescript look for the interface LinearTickOptions instead of TickOptions? This is the code that shows the error:
````
import {Chart} from 'chart.js';

new Chart(this.clientsPerMonthElement.nativeElement, {
  type: 'line',
  data: {
    labels,
    datasets: [{
      data,
      label: 'Clientes no mês',
      backgroundColor: 'transparent',
      borderColor: lineColor,
      borderWidth: 2,
      pointBackgroundColor: lineColor,
      pointRadius: 4,
    }],
  },
  options: {
    legend: {
      display: false,
    },
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true,
          stepSize: 1, // I'm getting an error here
        },
      }],
    },
  },
});
````
These are my chart.js dependencies:
````
"@types/chart.js": "2.7.28",
"chart.js": "2.7.2",
````

**Comment by praveenpuglia** [comment] 2019-03-28 18:45
And it's gonna be literally almost a year and still nothing :( Same issue today.

**Comment by fmozaffari** [comment] 2019-10-15 22:23
same issue today

**Comment by gebeto** [comment] 2019-10-17 06:25
need to add types to Charts.js package 😄

**Comment by mariah123** [comment] 2020-02-21 12:14
still today ....

Also,

 ```
Type '{ gridLines: { display: false; }; barPercentage: number; barThickness: number; }' is not assignable to type 'ChartXAxe'.
  Object literal may only specify known properties, and 'barPercentage' does not exist in type 'ChartXAxe'.
```

**Comment by rafaelbiten** [comment] 2020-04-01 21:32
I had the same issue today with the `maxBarThickness` prop and the solution was to refactor it from `scales.xAxes[{ maxBarThickness }]` to be a `barThickness` prop inside datasets.

**Comment by danmana** [comment] 2020-04-07 08:13
I think we can close this issue.

The original issue is no longer reproducible.
`TickOptions` now extends `NestedTickOptions` which has `stepSize?: number;`

@mariah123 
It looks like you are trying to add `barPercentage` on an `ChartXAxe`, but that is not supported.
`barPercentage`  should be placed on a dataset - see https://www.chartjs.org/docs/latest/charts/bar.html?h=barpercentage

Similar with what @rafaelbiten already figured out with `maxBarThickness` https://www.chartjs.org/docs/latest/charts/bar.html?h=maxbarthickness

**Comment by ashish-nodejs** [comment] 2020-07-27 16:16
> still today ....
> 
> Also,
> 
> ```
> Type '{ gridLines: { display: false; }; barPercentage: number; barThickness: number; }' is not assignable to type 'ChartXAxe'.
>  Object literal may only specify known properties, and 'barPercentage' does not exist in type 'ChartXAxe'.
> ```

any luck for this issue ... I also getting same ...

**Comment by joshbhavesh12** [comment] 2020-07-27 22:37
'{ barPercentage: number; ticks: { fontColor: string; fontSize: number; stepSize: number; beginAtZero: boolean; padding: number; }; }' is not assignable to type 'ChartXAxe'.

[ng]   Object literal may only specify known properties, and 'barPercentage' does not exist in type 'ChartXAxe'

**Comment by danmana** [comment] 2020-07-28 14:19
@ashish-nodejs @joshbhavesh12 `barPercentage` does not go on the `ChartXAxe`, you have to set it **on the dataset**!

Here is the documentation: https://www.chartjs.org/docs/latest/charts/bar.html#dataset-configuration

```js
const chart = new Chart(canvas, {
  type: "bar",
  data: {
    labels: ["January", "February", "March"],
    datasets: [
      {
        label: "My Dataset",
        data: [65, 59, 80],
        fill: false,
        barPercentage: 0.5, // < --- here, on the dataset
        barThickness: 'flex',
        maxBarThickness: 10,
        minBarLength: 2
      }
    ]
  },
  options: {
    scales: {
      yAxes: [
        {
          ticks: {
            beginAtZero: true
          }
        }
      ]
    }
  }
});
```

Here is a working example: https://codepen.io/danmana/pen/XWXwVZB?editors=0010

**Comment by orta** [comment] 2021-06-07 13:18
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:18 UTC

**Comment by berkaygurbuz** [comment] 2022-03-30 11:00
I migrate v2 to v3 in my old project. I think LinearTickOptions are deprecated. It gives me error like ```Module '"chart.js"' has no exported member 'LinearTickOptions'.``` I am using **suggestedMax** and **suggestedMin** properties what I should use instead of them?

**Comment by danmana** [comment] 2022-03-31 10:19
@berkaygurbuz Starting with Chart.js v3 the types have moved to https://github.com/chartjs/Chart.js/tree/master/types

The `@types/chart.js` definitions should only be used with chart.js 2.*.
When switching to v3 simply uninstall `@types/chart.js` and the default types should work
