### ISSUE TITLE
Aphrodite: incompatible with @types/react 15.6.0?

### ISSUE THREAD

**Issue by estaub** [DefinitelyTyped/DefinitelyTyped#18484] opened 2017-07-28 23:58 UTC
`@types/aphrodite` 0.5.6 appears to be incompatible with `@types/react 15.6.0` and a few versions before that.  For all HTML element types, I see a message of the form:

`Error:(2989, 13) TS2403:Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'HTMLProps<HTMLAnchorElement>'.
`

complaining about `<my project>/node_modules/@types/aphrodite/node_modules/@types/react/index.d.ts`

The element definitions have changed, e.g.

Aphrodite's embedded react/index.d.ts:
`            a: React.HTMLProps<HTMLAnchorElement>;
`
__15.6.0__
`            a: React.DetailedHTMLProps<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>;
`

When fixing this, consider changing the @types/aphrodite/package.json dependency:
```
"dependencies": {
        "@types/react": "*"
    },

```
to require 15.6 or better.  

`@types/aphrodite` 0.5.6 is compatible with `@types/react 15.0.35`, which I've fallen back to.

I'm a noob at dealing with these kinds of version-dependency issues on libs, especially on `@types`.  Otherwise, I'd PR it.  I have no idea how the `@types/aphrodite/package.json` is generated, or how `@types/aphrodite/node_modules` is filled, or where the `@types/react` version '15.0.83' is specified.

@tkrotoff fyi

**Comment by GamesMaxed** [comment] 2017-08-01 19:16
Since this is merged shouldn't the issue be closed?

**Comment by ajaska** [comment] 2017-08-01 19:56
Not sure what's going on, but I'm getting similar issues with `@types/react-redux` and `@types/react-dom`. Bizarrely, `npm install` produces a working `node_modules` but `yarn` results in a `node_modules` that's broken:
https://gist.github.com/ajaska/e3ae7420946ece1e91e73cf614f6d2a3 

I took a look at this; `yarn` creates those sub-`node_modules` directories (so getting different versions? unsure) but `npm install` doesn't?

```
  "dependencies": {
    "@types/react": "^15.0.38",
    "@types/react-dom": "^15.5.1",
    "@types/react-redux": "^4.4.46",
    "react": "^0.14.9",
    "react-dom": "^0.14.9",
    "react-redux": "^5.0.5",
}
```

**Comment by estaub** [comment] 2017-08-01 23:35
@ajaska Thanks!  https://github.com/yarnpkg/yarn/issues/1334#issuecomment-319522102 may be relevant enough to be worth subscribing to.

**Comment by ajaska** [comment] 2017-08-02 20:27
I can reproduce this using the official [TypeScript React Starter](
https://github.com/Microsoft/TypeScript-React-Starter) package. This is a broken `package.json`:

```
{
  "name": "my-app2",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/jest": "^20.0.5",
    "@types/node": "^8.0.19",
    "@types/react": "^15.0.38",
    "@types/react-dom": "^15.5.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-scripts-ts": "2.5.0"
  },
  "devDependencies": {},
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  }
}
```

It broke when I changed `"@types/react": "^16.0.0",` to `"@types/react": "^15.0.38",`.

I'm seeing this elsewhere in the wild:

- https://stackoverflow.com/questions/45304086/ts2403-error-at-every-typescript-react-project 
- https://stackoverflow.com/questions/45468683/error-at-node-modules-types-react-dom-subsequent-variable-declarations-mus

No idea who to ask for support here, @onigoetz ? @RyanCavanaugh ? Could you take a look or direct me towards someone more qualified? Thank you!

**Comment by ajaska** [comment] 2017-08-02 20:37
And again, `yarn` will produce a broken `node_modules` whereas `npm install` will produce one that functions just fine.

**Comment by goldins** [comment] 2017-08-02 20:53
I experienced the same problem and did some digging. I'm not absolutely sure what the problem is or the fix, but here's what I think is happening:

The `@types/react-*` `package.json` files have `"@types/react": "*"` as dependencies, which means `@types/react` 16.0.0 (as of now) is being placed into the `@types/react-*/node_modules` directories. yarn's TypeScript transpilation step is picking up one of these files instead of the top-level `@types/react/index.d.ts` file. (I'm not sure why `npm` doesn't have the same problem)

My temporary development-only solution is to delete the lower-level `@types/react-*/node_modules` directories.

**Comment by fabianishere** [comment] 2017-08-03 13:25
Adding React to the `paths` object in my `tsconfig.json` file solved the issue for me for now:

```json
{
    "compilerOptions": {
        "typeRoots": [
            "node_modules/@types"
        ],
        "paths": {
            "react": ["node_modules/@types/react"] <---
        }
}
```

**Comment by goldins** [comment] 2017-08-03 15:08
@fabianishere I like that solution, but it adds a maintenance cost (i.e. this isn't specific to `@types/react`. Do you know what the default tslint behavior is? Do lower-level definitions overwrite higher-level of the same name? That seems backwards.

**Comment by estaub** [comment] 2017-08-03 16:38
@goldins Did you mean `tslint`?  I don't understand why you're asking about it.  Maybe you meant `tsc`?

**Comment by goldins** [comment] 2017-08-03 20:35
Yes, I must have meant `tsc`. Apologies, I'm just getting started with TypeScript.

**Comment by fabianishere** [comment] 2017-08-03 21:51
@goldins The issue is that Yarn resolves packages that use the dependency `@types/react: *` to version 16.0.0, while I have `@types/react 15.6.1` installed. This means that two versions will be installed which causes conflicts.

If you for example try to import `react-dom`, TypeScript will load its type definitions at `node_modules/@types/react-dom`. This package also loads React's type definitions and TypeScript will first look for these in the `node_modules` of that directory (thus `node_modules/@types/react-dom/node_modules/@types/react`). This directory is linked to version 16.0.0 of the React type definitions

If you then import `react`, TypeScript will load the type definitions at `node_modules/@types/react`, which is still at version 15.6.1.

By adding `react` to your paths, you tell the TypeScript compiler that it should always resolve to a certain path.

**Comment by jbmilgrom** [comment] 2017-08-03 22:15
Had this same issue. `Yarn upgrade` resulted in this error. `npm install` did not.

It turns out Yarn was installing _dependent_ node_modules directories inside of `@types` packages. For instance, I received `node_modules/@types/enzyme/node_modules` and `node_modules/@types/react-dom/node_modules` directories. These directories of course themselves depended on type declarations that were also installed inside of the `@types` directory as top-level type declarations as expected. Looks like its a bug in the `Yarn` and definitelyTyped interaction...

**Comment by delight-by** [comment] 2017-08-13 19:52
As a side note Yarn is not the only offender here. If a package lists specific version of @types/react as a non-dev dependency (e.g. botframework-webchat does that) you'll get the same problem with NPM - it'll create node_modules/{package}/node_modules/@types/react which will then be picked up by tsc and fail the compilation due to React definitions incompatibility.
@goldins If I'm not mistaken TypeScript definitions never overwrite each other, they are always merged. Behavior we see is probably described here https://www.typescriptlang.org/docs/handbook/tsconfig-json.html :
> By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.

So @fabianishere 's use of "paths" seems like the only proper way to fix the problem (I'm not sure about typeRoots though, it should be the default value so no need to overwrite it, at least it works for me).
Also skipLibCheck: true will work yet it's really a shotgun approach and should be used only if you're OK with the consequences.

**Comment by estaub** [comment] 2017-08-13 20:18
@delight-by I can't be specific, but yarn is a lot worse in this regard than npm.  In my case, I dropped back from yarn to npm because of this behavior, and all these problems went away.  I'm not disagreeing you about npm's behavior with pinned versions - just saying yarn appears to make these package-specific `node_modules` in many more cases.

**Comment by delight-by** [comment] 2017-08-13 20:29
@estaub Yarn definitely has a bug with * (any) version in package.json triggering the latest version install. That's exactly why I temporarily switched to NPM like you and most of the people here. But only until I faced the same problem with NPM couple of days later)

**Comment by glentakahashi** [comment] 2017-08-14 21:15
I've logged the yarn bug here https://github.com/yarnpkg/yarn/issues/4136

**Comment by davidctj** [comment] 2017-09-21 11:43
I remove @types/react in my package.json, and let yarn install the latest version of @types/react (16.0.5), seems fix the problem

**Comment by joevo2** [comment] 2017-09-25 03:23
I removed the package.json entry of @types/react-dom and re install using `yarn add @types/react-dom` and it seems to be ok now for me

**Comment by myangsc** [comment] 2017-10-05 00:52
@joevo2 solution work's for me, but is there any better way to do it?

**Comment by myangsc** [comment] 2017-10-05 22:37
@joevo2 use yarn add solve it, then use npm view @types/react-dom and reinstall it to package.json

**Comment by markwangen** [comment] 2017-11-14 13:17
Just remove all react & type@react from dependency, then re-npm install them, fix my issue~

**Comment by rosskevin** [comment] 2017-12-08 14:45
For yarn users: `rm -rf node_modules yarn.lock && yarn` worked around this for me.  Note that you must remove the `yarn.lock`, otherwise it won't work around the issue.

**Comment by zubivan** [comment] 2017-12-09 11:07
@rosskevin was running in circles around this issue for the past few hours. Thanks for posting this solution,  that was the one that actually helped!

**Comment by dleavitt** [comment] 2018-03-07 03:29
in case it's helpful to anyone - for me this was due to mismatched versions in my react and react-ui definitions

**Comment by pie6k** [comment] 2018-03-07 14:07
Add 

```
"resolutions": {
   "@types/react": "^16.0.40"
 }
```

to `package.json`

Reinstall `node_modules` with `yarn install`

Note it's a bit hacky to force package version for every package in `node_modules`, but in case of `@types` it's rather safe.

**Comment by orta** [comment] 2021-06-07 13:21
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:21 UTC
