### ISSUE TITLE
ERROR: ../node_modules/@types/readable-stream/index.d.ts:13:15 - error TS2417: Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.

### ISSUE THREAD

**Issue by jalle007** [DefinitelyTyped/DefinitelyTyped#45371] opened 2020-06-09 00:52 UTC
I have Ionic app that worked JUST fine, till few days ago. Now I cant login.

     Ionic INFO:
           Ionic CLI                     : 5.4.13 (C:\Users\Me\AppData\Roaming\nvm\v10.15.3\node_modules\ionic)
           Ionic Framework               : @ionic/angular 5.1.1
           @angular-devkit/build-angular : 0.901.7
           @angular-devkit/schematics    : 9.1.7
           @angular/cli                  : 9.1.7
           @ionic/angular-toolkit        : 2.2.0
        
        Capacitor:
        
           Capacitor CLI   : 2.0.2
           @capacitor/core : 2.0.2
        
        Cordova:
        
           Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
           Cordova Platforms : android 8.1.0
           Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)
        
        Utility:
        
           cordova-res (update available: 0.14.0) : 0.6.0
           native-run (update available: 1.0.0)   : 0.2.8
        
        System:
        
           Android SDK Tools : 26.1.1 (e:\Android\SDK)
           NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
           npm               : 6.4.1
           OS                : Windows 10

/functions/package.json

    {
      "name": "functions",
      "scripts": {
        "build": "tsc",
      
      },
      "engines": {
        "node": "8"
      },
      "main": "lib/index.js",
      "dependencies": {
        "firebase-admin": "^8.10.0",
        "firebase-functions": "^3.6.1",
        "nexmo": "^2.6.0"
      },
      "devDependencies": {
        "@types/node": "^12.12.7",
        "firebase-functions-test": "^0.2.0",
        "tslint": "^5.12.0",
        "typescript": "^3.8.3"
      },
      "private": true
    }

command: **npm run build** give error:  

    ../node_modules/@types/readable-stream/index.d.ts:13:15 - error TS2417: Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.
      The types of '(new Stream.Readable.PassThrough(...))._transform' are incompatible between     these types.

 
So its complaining about package that is in base Ionic project. <br> For better readability I paste my PROJECT package.json on pastebin 
https://pastebin.com/raw/yp323qmW

Problem is , not that only firebase functions doesnt compile but ALSO
I cannot login to Firebase ;(

    ERROR TypeError: app.auth is not a function
        at MapSubscriber.project (**angular-fire-auth**.js:39)
     
   
**Dont tell me its about Ionic , its clearly not.
There is something WRONG with this Type def readable-stream**

any help is appreciated

**Comment by markdreyer** [comment] 2020-06-12 17:45
Looks to be a result of [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d20b4ca4e23651ee21cd98f37d725317d9575d01)

@andreubotella do you have any background on this change and why it would be failing to compile?

**Comment by andreubotella** [comment] 2020-06-12 18:09
My changes to node/stream in that commit should not affect node v10, but I did add those fields to readable-stream because the tests were failing. It might be related to that, but I'm going to look more in depth.

**Comment by markdreyer** [comment] 2020-06-12 20:27
The [nodesj/readable-stream](https://github.com/nodejs/readable-stream) project states they are compatible with Node 6, 8, and 10

I am not too familiar with this code, but perhaps these new fields only belong in the `types/node/v12/stream.d.ts` and `types/node/v12/stream.d.ts` types and not in `types/node/stream.d.ts ` to maintain compatability with older versions?

**Comment by andreubotella** [comment] 2020-06-12 21:29
`types/node` seems to always track the latest version: #44097 added definitions for node v14 by updating `types/node` in place and adding a `types/node/v13` folder.

I suppose I shouldn't have added those properties to `readable-stream`, since it's supposed to track the streams in node v10 – that was a last-minute fix to get the tests succeeding. But I don't think `types/readable-stream/readable-stream-tests.ts` can be made to depend on the `streams` module from a specific node version.

**Comment by REPTILEHAUS** [comment] 2020-06-15 20:32
Just did npm i and getting this errors now too along with

` Property '_transform' in type 'PassThrough' is not assignable to the same property in base type 'PassThrough'.`

along with `Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.` 

Also in an Ionic app, I keep getting issues with this type definitions.

**Comment by jalle007** [comment] 2020-06-16 03:44
I had to recreate whole app from scratch.
simply couldnt get rid of this error

So annoying. and what I noticed is this. whenever I run **npm i**, this folder `node_modules\@types\readable-stream\ `stays empty, thus no modules are installed.

**Comment by REPTILEHAUS** [comment] 2020-06-16 09:55
Whaaaat ? I dont even have these types in my package.json and it keeps blocking my projects, previously ive had to hack my own type definitions using `any` just to get past this dependency.

**Comment by andreubotella** [comment] 2020-06-16 11:52
So, here's the problem. Back in #45175, I added the [`readableEncoding`](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_readable_readableencoding) and [`readableEnded`](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_readable_readableended) properties to the type definitions for Node.js's native readable streams, on versions v12 and above. That seemed to work fine.

But when I submitted the PR, I noticed that the automated tests were failing on the `readable-stream` crate, because some classes were implementing `stream.Readable` (or classes extended from it) and didn't have those properties. So it made sense to add them, right? I was in a bit of a rush to get the PR ready for merging because it was blocking a work project, and since the tests were passing, I forgot to check that `readable-stream` did not in fact implement those properties. That was dumb, yeah.

So, the way things are right now, the type definitions work fine on node ≥ v12, as long as you don't try to use those two properties on readable, duplex or transform (including pass-through) streams. But on node < v12, it seems like there are conflicts when you try to use the streams from `readable-stream` as Node streams.

Removing those two properties brings back the conflicts on node ≥ v12, so the fix must be more involved. @TeamworkGuy2, as the maintainer of `readable-stream`, do you have any ideas?

**Comment by TeamworkGuy2** [comment] 2020-06-18 01:31
I didn't realize I was considered the active maintainer of `readable-stream`, I think I've committed to it once or twice. I never did fully wrap my head around the whole node.js streams vs userland `readable-stream` package maintenance.

I think your first paragraph @andreubotella is the correct approach, only add the `readableEncoding` and `readableEnded` properties to node.js's native streams for version ≥12. And then figure out how to fix the failing `readable-stream` tests.

Maybe the DefinitelyTyped [readable-stream](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/readable-stream) definition needs a patch first. Just a hunch, but [readable-stream](https://www.npmjs.com/package/readable-stream) major versions are cut from Node.js stable release version.
`readable-stream` v2.x is based on node.js 8 and v3.x is based on Node.js v10 so maybe the readable-stream [package.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/readable-stream/package.json) needs to have the node.js version defined in it.

I'm not sure of the best approach without seeing the error and digging into it. I haven't been doing much with DefinitelyTyped lately and probably won't have time in the near future so anyone who can please give it a try.

**Comment by markdreyer** [comment] 2020-06-18 02:35
I can take a look at patching readable-stream type definition. Think the issue may be that the type file is referencing `/// <reference types="node" />` which assumes the latest node, but it really should reference the v10 node types.

**Comment by andreubotella** [comment] 2020-07-10 15:37
I suppose this issue can now be closed, since #45563 is merged.

@jalle007, please check if the issue is solved, and close if so.

**Comment by orta** [comment] 2021-06-07 13:05
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:05 UTC
