### ISSUE TITLE
Regression in `connect` from @types/react-redux@7.0.2 allows any props

### ISSUE THREAD

**Issue by mikew** [DefinitelyTyped/DefinitelyTyped#36873] opened 2019-07-13 19:08 UTC
- [x] I tried using the `@types/react-redux@6.0.14 -> 7.1.1` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @nicholasboll @mdibyo @kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @mrwolfz

If you do not mention the authors the issue will be ignored.

---

I can't pinpoint the commit / change that introduced the regression, just the version. Versions after 7.0.1 will seemingly allow any props, even ones with the wrong type.

Repro:

```ts
import React from 'react'
import { connect } from 'react-redux'

interface Props {
  title: string
}

const Example = (props: Props) => <div>{props.title}</div>
const ExampleConnected = connect()(Example)

const ThisShouldNotCompile = () => (
  <div>
    {/* This errors, as it should. */}
    <Example />
    {/* Yet this happily compiles. */}
    <ExampleConnected />
  </div>
)
```

Versions before 7.0.2 will show an error for both elements in `ThisShouldNotCompile`.

**Comment by dusan-dragon** [comment] 2019-07-16 15:07
@mikew try to install 7.1.1 again and if it is still not working try to `rm -rf node_modules` We had same issue with 7.1.0 I updated the version and now it is working again.
But maybe it would be nice to add a regression test here...

**Comment by rmarganti** [comment] 2019-07-30 15:12
In my own experience, I found this to be caused by version clashes in the sub-dependencies. Specifically, there was two versions of `@types/hoist-non-react-statics` installed, due to different requirement between this package and an outdated version of `styled-components`. Upgrading to the most recent version of Styled Components solved this for me, so you may want to start there.

**Comment by orta** [comment] 2021-06-07 13:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:11 UTC
