### ISSUE TITLE
[@types/styled-components]

### ISSUE THREAD

**Issue by alleycat-at-git** [DefinitelyTyped/DefinitelyTyped#34650] opened 2019-04-11 07:00 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] 
  - Authors: @eps1lon @Igorbek @Jessidhia

The problem is that styled components types makes my typescript intellisense work real slow. It takes sometimes up to 100% CPU. I found out that this particular line
```
export type ThemedStyledProps<P, T> = P & ThemeProps<T>;
```
is causing troubles.  Once you remove `P &` it works again as normal.

**Comment by eps1lon** [comment] 2019-04-11 09:21
Please include the exact version of `@types/styled-components`, `typescript` and `vscode`. Likely a duplicate of #34391.

**Comment by kolengri** [comment] 2019-04-13 08:06
Hi, I have the same issue. Typescript version and @types/styled-components version give a big impact on performance.

Typescript 3.4.3, @types/styled-components 4.1.14, Vscode 1.33.1
yarn tsc  66.81s user 0.95s system 106% cpu 1:03.74 total
VS
Typescript 3.4.3, @types/styled-components 4.1.5, Vscode 1.33.1
yarn tsc  56.45s user 0.79s system 108% cpu 52.669 total

Typescript 3.3.4000, @types/styled-components 4.1.5, Vscode 1.33.1
yarn tsc  41.79s user 0.62s system 106% cpu 39.667 total

**Comment by orta** [comment] 2021-06-07 13:12
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:12 UTC
