### ISSUE TITLE
[@types/react-select] Anything can be passed to Select

### ISSUE THREAD

**Issue by szymkab** [DefinitelyTyped/DefinitelyTyped#34959] opened 2019-04-24 09:31 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl @jonfreedman

Hi,

Because of line 54 at `Select.d.ts` anything can be passed to select and typescript will not show any errors.

`export type SelectComponentsProps = { [key in string]: any };`

What is the purpose of that `{ [key in string]: any };` in Select types?

**Comment by artgladun** [comment] 2019-04-24 09:55
Together with my team, we are trying to move from react-select v1 to v2; but with such `any` props it is very hard to work with and check everything manually instead to just trust linter... especially there are small differences like disabled -> isDisabled

**Comment by szymkab** [comment] 2019-04-26 14:20
The thing is that if interface extends `{ [key in string]: any };` you can pass literally everything to that component. It somehow solves an issue with having custom props in select components but it has a lot of disadvantages, e.g. you can pass everywhere  (even if you make typo typescript will not inform you) and intelisense is not working.

So, I've prepared a solution with a generic argument that can be used for custom props of select components (and is by default set to `{ [key in string]: any };`).

If you don't pass second generic argument you can have `any` props in custom component just like now:

![Zrzut ekranu 2019-04-26 o 16 17 39](https://user-images.githubusercontent.com/13819284/56814244-09505a00-683f-11e9-9e8d-b5c361e99f2f.png)

If you pass an interface as second argument you can have type on that custom prop:

![Zrzut ekranu 2019-04-26 o 16 18 27](https://user-images.githubusercontent.com/13819284/56814270-1705df80-683f-11e9-9356-34e31460f6f0.png)

**Comment by agwells** [comment] 2019-06-23 23:04
This one caused problems for me too, because I've made some wrapper components around React-Select, that override some props, and pass other props through. So I have a props definition that did that by using some helper types based on `Pick` and `Extract`. It looks something like this:

```typescript
import { Props as ReactSelectProps } from 'react-select/lib/Select';

// Omit: Create a type that has all the keys of T except those named in K
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
// Merge: Create a type that combines types M and N, but where N has a field
// with the same name as M, use only N's definition of that field.
type Merge<M, N> = Omit<M, Extract<keyof M, keyof N>> & N;

// My wrapper component's props can't just `extend` ReactSelectProps, because
// the types for `value` and `onChange` are incompatible.
type WrappedSelectProps = Merge<ReactSeletProps, {
  name: string;
  value?: number;
  options: Array<{value: number, label: React.ReactNode}>,
  onChange: (selection?: number) => void;
}>;
```

This worked great before, but now it fails to provide any validation or Intellisense of the props to pass through to React-Select. That's because `Pick` and `Extract` (and most utility types) use `keyof` as their base. And now that the React-Select  props extend `{ [key in string]: any}`, doing `keyof` on it just returns `string`.

Fortunately I found a workaround for it. You can extract the "known keys" from a mapped type without using `keyof` via a somewhat confusing mix of mapped types, conditional types, and type inference: https://stackoverflow.com/questions/51954558/how-can-i-remove-a-wider-type-from-a-union-type-without-removing-its-subtypes-in/51955852#51955852

```typescript
type KnownKeys<T> = {
  [K in keyof T]: string extends K ? never : number extends K ? never : K;
} extends { [_ in keyof T]: infer U }
  ? U
  : never;
```

... still, it would be more convenient to just be able to use normal utility types like `Pick` and `Extract`. For my purposes (writing types that are based on the React-Select props) it would be enough if the defined props of the `Select` component were just defined as a separate exported type (sort of like `SelectComponentsProps` is):

```typescript
export type SelectComponentsProps = { [key in string]: any };

export interface NamedProps<OptionType> {
    /* Aria label (for assistive tech) */
  'aria-label'?: string;
  /* Focus the control when it is mounted */
  autoFocus?: boolean;
  // ... etc
}

export type Props<OptionType = { label: string; value: string }> = NamedProps<
  OptionType
> &
  SelectComponentsProps;
```

**Comment by schnerd** [comment] 2019-09-25 04:44
Similar problem to @agwells – extending `{ [key in string]: any }` seems to break helpers like Omit/Pick/Extract that are necessary for creating wrapper components. Here's a [minimal reproduction of the issue in TS playground](https://www.typescriptlang.org/play/index.html?jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnAEJpYAKxY6AXjgBvOAG0A1liZxgAOzioYUeQHMAugC4UcmQF96dLAA9IsWXJhYoBPG14R+cE1bkATdJ1Q8+6YXTg4ECw5AFcASVQAeVY5AH5tACMICAAbHDl6QIA3ZFTQrAS4ZLSM+j0GeSsbOzgAFSwlAEZnY1cPOAcnYQrcCDklOBgm7QbmuCFhXPysbQByAhS5g0rLa1tcNjGYACZW9vQokGAYAB4u1AAaODngsMiYkLmAPhFe-sHd0cbdiZFpgrzRYQZb0IA).

Agree with the above recommendations to export the props separately (assuming extending `{ [key in string]: any }` cannot be removed). Will use the workaround for now, thanks!

**Comment by orta** [comment] 2021-06-07 13:12
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:12 UTC
