### ISSUE TITLE
Passing array to async methods causes missing index signature problems - it should not.

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#24469] opened 2018-03-23 00:33 UTC
@jeremyhon @rlindgren @fenying @kasuparu @kerol2r20 @sasanj 

- [x] I tried using the `@types/async` package and had problems.

<kbd>
<img src="https://user-images.githubusercontent.com/11139560/37805330-b3564f7a-2df6-11e8-85c3-960e0b07c9a4.png">
</kbd>

_____________

**I don't know how to solve it**. An array *should have* an index signature, by definition. The user should not have to define it manually, tmk.

Here is the code, if you need it:

```js
   import R = require('ramda');
   import async = require('async');
   const diff = R.difference(['ab'], ['c','x']);
   async.map(diff, function (id, cb) {});
```

How do we solve this error? I have like 3 questions on SO regarding this error and cannot find an answer. Thanks.

**Comment by ORESoftware** [comment] 2018-03-23 00:45
This seems to solve it:
https://stackoverflow.com/a/44788314/7898461

but goddamn there has to be a better error message or something...I also don't know why that works.

**Comment by fenying** [comment] 2018-03-23 02:00
Can you share the version of TypeScript and `@types/async` you are using.

I cannot reproduce this problem with your code, using TS v2.7.2 and `@types/async` v2.0.48.

**Comment by ORESoftware** [comment] 2018-03-23 02:20
Yeah sure:

`"@types/async": "^2.0.47",
tsc => version 2.7.2

**Comment by orta** [comment] 2021-06-07 13:41
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:41 UTC
