### ISSUE TITLE
Incorrect exports in react-icons

### ISSUE THREAD

**Issue by LKay** [DefinitelyTyped/DefinitelyTyped#20345] opened 2017-10-06 07:50 UTC
- [x] I tried using the `@types/react-icons` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts` and `lib` files) so they can respond.
  - Authors: @johnnyreilly 

Current, recently merged definitions are wrong for all components located in `lib` directory. Transpiled code does not contain default export but it's transpiled to commonjs code with single `module.export` statement. because of that importing default in typescript code resolves `undefined` and breaks the compiled code at runtime.

For example file [lib/fa/500px.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7d9561b8f2923ec71c0a50ee009b75f8ca057ff6/types/react-icons/lib/fa/500px.d.ts) has export defined as:

```typescript
export default class Fa500px extends React.Component<IconBaseProps> { }
```
but in fact this should look like:
```typescript
declare class Fa500px extends React.Component<IconBaseProps> { }
export = Fa500px;
```

Then imports in the actual consuming code should be defined as:
```
import Fa500px = require('react-icons/lib/fa/500px');
```

@johnnyreilly if you still have the script for auto generation all these files, could you change your template and regenerate fixed typings?

**Comment by johnnyreilly** [comment] 2017-10-06 07:56
Hi @lkay,

It's working fine for me and usage is covered in the tests. Do you want to try using es6 import syntax (as in test) and see if that resolves your issue? Script generation is in the scripts folder of the type definition

**Comment by johnnyreilly** [comment] 2017-10-06 08:02
FWIW my change essentially took the output generated for the `fa` `md` folders and reproduced them underneath the `lib` folder.

**Comment by LKay** [comment] 2017-10-06 09:08
The test will pass because they test he definitions and not what library actually exports. This would only work if typescript compiler receives the `--allowSyntheticDefaultImports` flag and be forced to create virtual default imports at the compilation step. 

Files in the `lib` have commonjs exports:
```js
exports.default = Fa500px;
module.exports = exports['default'];
```

The `react-icons` library uses `babel-plugin-add-module-exports` which add the second line of the above and that breaks Typescript default import as its overridden by commonjs pattern.

**Comment by johnnyreilly** [comment] 2017-10-06 09:42
Actually I'm not using `--allowSyntheticDefaultImports` or babel and it's working fine on my machine. I have a feeling this could be fixed in your build.

That said if you want to make that change then I'd be happy to test it on my machine and review.

**Comment by LKay** [comment] 2017-10-06 10:03
Can you share your compiler options fro `tsconfig.json`? Mine are as follow:
```json
    "compilerOptions": {
        "jsx": "react",
        "removeComments": true,
        "sourceMap": true,
        "target": "es5",
        "lib": ["dom", "es2015.iterable", "es7", "scripthost"],
        "module": "commonjs",
        "moduleResolution": "node",
        "noUnusedLocals": false,
        "noUnusedParameters": false,
        "allowSyntheticDefaultImports" : true,
        "baseUrl": ".",
        "paths": {
            "*": ["types/*"]
        }
    }
```
I use similar config for most of my projects and when I import some icon like:
```typescript
import FaClose from "react-icons/lib/fa/close";
```
Then `FaClose` is `undefined`.

**Comment by johnnyreilly** [comment] 2017-10-06 10:32
Sure: 

```
{
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "compilerOptions": {
    "allowSyntheticDefaultImports": false,
    "target": "es5",
    "downlevelIteration": true,
    "importHelpers": true,
    "sourceMap": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "allowJs": false,
    "checkJs": false,
    "lib": [
      "dom",
      "es2015",
      "es2016",
      "es2017",
      "esnext"
    ],
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true
  }
}
```

Usage looks like this:

```
import FaSearch from 'react-icons/lib/fa/search';

// and in render:

                                            <FaSearch aria-hidden="true" />

```

**Comment by dyst5422** [comment] 2018-03-27 21:35
Can this be fixed by adding a default export to the  .d.ts files?

ie 
```ts
declare class Fa500px extends React.Component<IconBaseProps> { }
export default Fa500px;
export = Fa500px;
```

**Comment by dyst5422** [comment] 2018-03-27 21:43
#20448 addresses this.

short form - the typings have been updated, use `"allowSyntheticDefaultImports": true`

**Comment by orta** [comment] 2021-06-07 14:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:11 UTC
