### ISSUE TITLE
Can not add @types/express-sessions

### ISSUE THREAD

**Issue by pavel-butkevich-98** [DefinitelyTyped/DefinitelyTyped#44810] opened 2020-05-17 16:18 UTC
- [x] I tried using the `@types/express-sessions` package and had problems.
- [x] I tried using the next stable version of tsc "typescript": "3.8.3"
I am tryng to use express-sessions in my app, but have next error after **yarn add @types/express-sessions**
![image](https://user-images.githubusercontent.com/45014413/82153909-10e00800-9873-11ea-80ae-d27137e655a0.png)
Can anybodt help me? ts version: 3.8.3, express version: 4.17.1
  - Authors: @TheHandsomeCoder, @donnut, @mdekrey, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @samsonkeung, @angeloocana, @raynerd, @moshensky, @ethanresnick, @deftomat, @blimusiek, @biern, @rayhaneh, @rgm, @drewwyatt, @jottenlips, @minitesh, @Krantisinh, @pirix-gh, @brekk, @Nemo108, @jituanlin, @Philippe-mills, @Saul-Mirone

If you do not mention the authors the issue will be ignored.

**Comment by peterblazejewicz** [comment] 2020-05-17 22:00
seems to be duplicate of #44808

**Comment by orta** [comment] 2021-06-07 13:06
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:06 UTC
