### ISSUE TITLE
React 16.6 types

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#29989] opened 2018-10-24 01:27 UTC
React 16.6 was released today: https://reactjs.org/blog/2018/10/23/react-v-16-6.html

I would have made this as a PR, but there is a problem with the new `static contextType` feature that I don't know how to solve. This is probably a TypeScript core problem.

First, the type of `context` is defined in `class Component` and marked as `@deprecated` (which triggers the `deprecation` tslint rule), but `context` is only deprecated if `static contextType` is not defined.

Second, the type of `this.context` depends on the type of `static contextType`, and there is no way I can think of, within TypeScript's generic system, declaring that in the types. While I can hack that into `ComponentClass`'s definition, it wouldn't help actually subclassing `Component` correctly.

Probably the only solution that would work short term is removing the `context: any` declaration entirely, but it'd be a breaking change.

---

This is not the first time we hit limitations of the generic system in React; see `getDerivedStateFromProps` which had to be left out of `Component`'s definition entirely because it'd just have to have `any` inputs and outputs anyway.

**Comment by Kovensky** [comment] 2018-10-30 16:28
The problem is that that `P` is just a hidden `any`. It is _shadowing_ the `P` parameter of the class by creating its own local `P` parameter.

**Comment by artem-malko** [comment] 2018-10-30 16:49
Wow, bad news for me( Thank you for explanation.

**Comment by CodeRevver** [comment] 2018-11-15 20:04
For anyone looking for types, I think this is resolved as of 14th Nov - https://www.npmjs.com/package/@types/react

**Comment by pluma** [comment] 2018-11-15 20:13
Am 15.11.2018 9:04 nachm. schrieb Michael Clark:For anyone looking for types, I think this is resolved as of 14th Nov - https://www.npmjs.com/package/@types/reactLooks like React DOM is still on 16.0 though.

**Comment by Finesse** [comment] 2018-11-22 03:55
What version of `@types/react` does contain 16.6 features but doesn't contain 16.7 features? There is no 16.6 version of `@types/react` in NPM.

**Comment by a7madgamal** [comment] 2019-01-23 19:54
I'm looking at our company package.json and it's unexpectedly hard to install/update @types packages that matches the actual packages. I hope this change some day!

for now, any help on this issue would be great :)

**Comment by orta** [comment] 2021-06-07 13:15
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:15 UTC
