### ISSUE TITLE
[@types/node] assert.strictEqual(false, ...) triggers unreachable code error

### ISSUE THREAD

**Issue by alexander-fenster** [DefinitelyTyped/DefinitelyTyped#44944] opened 2020-05-21 01:39 UTC
`assert.strictEqual(false, anyArgument)` triggers unreachable code error for any code below **after the recent @types/node update**. This **only** reproduces with `@types/node` 10.17.24, 12.12.41, 13.13.8 (published recently).

Note that it only reproduces with `false` as a value being checked. Replace it with anything else and it will compile.

This looks to me like a `tsc` problem rather than types problem (I reported it in https://github.com/microsoft/TypeScript/issues/38699) but the fastest fix would be rolling back the `@types/node` changes, so I'm duplicating the issue here as well.

**TypeScript Version:**  3.9.3, also reproduces on 3.8.x

**Code**

```ts
import * as assert from 'assert';

const b = false;
assert.strictEqual(false, b);
console.log('really unreachable?');
```

**Expected behavior:** should compile with `--allowUnreachableCode false`.

**Actual behavior:**

```
$ npx tsc --allowUnreachableCode false src/index.ts 
src/index.ts:5:1 - error TS7027: Unreachable code detected.

5 console.log('really unreachable?');
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```
This looks to be directly caused by recent releases of `@types/node` with this commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e9103792668257b6cc86cd21d6c455ecb5fae1ea included.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @G-Rath as a commit author

**Comment by G-Rath** [comment] 2020-05-21 01:53
This does look like a semi-bug in tsc, related to how boolean literals work.

You can resolve this by casting `false` to `boolean`:

```
import * as assert from 'assert';

const b = false;

assert.strictEqual(false as boolean, b);
console.log('really unreachable?');
```

**Comment by G-Rath** [comment] 2020-05-21 01:57
Here's an example of similar behaviour where I've had to [cast to `boolean` in the past](https://github.com/G-Rath/terra/blob/master/src/formatter/ensurers/ensureIndentation.ts#L94).

This one is caused by the control flow analysis being unable to safely look into the `forEach` to figure that the variable is reassigned, and so it becomes type `false`, making the condition in the `if` afterwards an error since the value will always be `false`.

**Comment by alexander-fenster** [comment] 2020-05-21 02:06
Thank you for the suggestion @G-Rath, this seems enough to put out the fire in our codebase.

**Comment by G-Rath** [comment] 2020-05-21 02:16
ugh I just realised this is because you're passing `false` into the *actual* parameter, not the expected.
The `expected` argument has type `T`, and so what the type is inferred from.

You can resolve this better by swapping the order.

**Comment by alexander-fenster** [comment] 2020-05-21 02:25
That's true - I don't know why it's written this way, it's some really old code that suddenly got broken. Yes, it makes sense to change the order to a correct one (and explains why there are not a lot of folks who are affected by this).

**Closed** 2021-06-07 13:06 UTC
