### ISSUE TITLE
I suggest breaking up the types directory into a folder for each letter of the alphabet.

### ISSUE THREAD

**Issue by Shmungtzklklastr** [DefinitelyTyped/DefinitelyTyped#38664] opened 2019-09-27 14:32 UTC
This would be easier to manage and browse, and it would combat github's lack of sharding.

I don't think any letter individually will reach 1000 entries anytime soon

@renanmav  @alloy

**Comment by alloy** [comment] 2019-09-27 15:39
This isn’t really something for me to speak to. Paging @orta

**Comment by yoursunny** [comment] 2019-10-01 18:17
The problem is, `baseUri` and `typeRoots` would no longer work, affecting packages that reference another package's types.

```jsonc
        "baseUrl": "../",
        "typeRoots": [
            "../"
        ],
```

**Comment by orta** [comment] 2021-06-07 14:07
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:07 UTC
