### ISSUE TITLE
TS2403: Subsequent variable declarations must have the same type. After NPM install

### ISSUE THREAD

**Issue by AcousticGuitar** [DefinitelyTyped/DefinitelyTyped#17000] opened 2017-06-06 16:17 UTC
- [x] I tried using the `@types/Node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I wanted Node Typings in my Typescript project so I entered this command:

npm install @types/node --save
Which resulted in:

```c:/xyz/node_modules/@types/node/index.d.ts(89,13)
error TS2403: Subsequent variable declarations must have the same type.
Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.
```

My machine had node version 7.0.3 The installed types was for version + @types/node@7.0.28
If I uninstall the typings my project compiles with no problems.

It appears as if the typings content is not correct per the error message! 
The failing line of code in index.d.ts
![noderequire](https://user-images.githubusercontent.com/10676026/26839642-43413762-4aa9-11e7-9542-78819504c9df.GIF)

This is the TSConfig content:

```{
    "compilerOptions": {
        "module": "amd",
        "moduleResolution": "node",
        "target": "es5",
        "noImplicitAny": false,
        "jsx": "react",
        "sourceMap": false,
        "baseUrl": ".",
        "paths": {
            "OfficeFabric/*": [
                "node_modules/office-ui-fabric-react/lib-amd/*"
            ]
        }
    } 
}
```

Typescript version is 2.2.2

**Comment by andy-ms** [comment] 2017-06-06 17:04
Duplicate of Microsoft/TypeScript#16298.

**Closed by andy-ms** 2017-06-06 17:04 UTC
