### ISSUE TITLE
[@types/react-native] XMLHttpRequest typings broken since 0.57.51

### ISSUE THREAD

**Issue by vovkasm** [DefinitelyTyped/DefinitelyTyped#35124] opened 2019-04-30 20:07 UTC
- [x] I tried using the `@types/react-native` package version 0.57.51 and had problems.
- [x] I tried using the latest stable version of tsc (3.4.5).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @avin-kavish (as author of the PR that broke things), @weswigham (as commiter), @alloy, @newyankeecodeshop 

Version 0.57.51 of @types/react-native was published after merge of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34902 (Added progress event to XHR as per spec). This PR attempted to fix https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34882. I don't know if this fix styled components or anything for web, but this commit definitely broken.

First immediate problem is compatibility of types for EventTarget and XMLHttpRequest. I got this error:
```
node_modules/@types/react-native/globals.d.ts:231:11 - error TS2430: Interface 'XMLHttpRequestUpload' incorrectly extends interface 'EventTarget'.
  Types of property 'addEventListener' are incompatible.
    Type '<K extends "timeout" | "error" | "progress" | "abort" | "load" | "loadend" | "loadstart">(type: K, listener: (this: XMLHttpRequestUpload, ev: XMLHttpRequestEventTargetEventMap[K]) => any) => void' is not assignable to type '(type: string, listener: EventListener | EventListenerObject | null, options?: boolean | AddEventListenerOptions | undefined) => void'.
      Types of parameters 'listener' and 'listener' are incompatible.
        Type 'EventListener | EventListenerObject | null' is not assignable to type '(this: XMLHttpRequestUpload, ev: ProgressEvent) => any'.
          Type 'null' is not assignable to type '(this: XMLHttpRequestUpload, ev: ProgressEvent) => any'.

231 interface XMLHttpRequestUpload extends EventTarget, XMLHttpRequestEventTarget {
              ~~~~~~~~~~~~~~~~~~~~
```

Second, this commit simply incorrect. It defines all events as `ProgressEvent` type (see my comment to diff: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/671e555f444bb9be0ab14b1d05d73b7e6d9622de#r33356858)

**Comment by newyankeecodeshop** [comment] 2019-04-30 20:22
@vovkasm Are you including `dom` in the `lib: []` TS config? That won't work with React Native because it does not implement the full DOM API set. The type definitions in `react-native/global.d.ts` define the subset of types that React Native does implement. They are not fully compatible with the types from `dom` because RN does not implement all the APIs exactly the same.

**Comment by vovkasm** [comment] 2019-04-30 20:25
@newyankeecodeshop No, I simply copy part of dom and adapt it to RN environment (I need Websocket API). But my definition of EventTarget was almost identical to that one from lib.dom.d.ts.

**Comment by vovkasm** [comment] 2019-04-30 20:29
For reference I share my globals.d.ts here: https://gist.github.com/vovkasm/dd19b27f7b56d6290754ff953d86c2b9

**Comment by avin-kavish** [comment] 2019-04-30 21:10
I'm comparing to lib dom file and it seems to match up perfectly.

**Comment by avin-kavish** [comment] 2019-04-30 21:46
Get someone to revert it for now, I have  no time to fix it.

**Comment by vovkasm** [comment] 2019-05-01 07:06
I'm also was not right about event types... they really all ProgressEvent according to [XMLHttpRequest Standard](https://xhr.spec.whatwg.org/#events) and RN implementation different (It should be fixed on RN side probably, but it will take time).

I will try to investigate it deeply...

But has to bring up one general question about typings. We currently don't touch Websocket types and define XMLHttpRequest and fetch types, but probably should treat both same way - either define Websocket and XMLHttpRequest, or not to define both Websocket and XMLHttpRequest. What way we should select?

**Comment by newyankeecodeshop** [comment] 2019-05-01 13:01
@vovkasm We need to define all the missing types (ideally), but it requires someone to validate that the types are correct. Not everyone uses the low-level networking APIs like `XMLHttpRequest`. Many folks use `fetch` or a library like `axios`, which has its own types. I suspect the lack of `WebSocket` so far is because not that many apps directly use WebSockets.
When defining the polyfill types, it's important to base them off the Flow types in React Native, since the types defined in the TypeScript DOM library are the browser's types.
It looks like you could fix the issue by removing the `null` from the signature of `addEventListener`? I don't even know if React Native supports `null` for that method on WebSocket.

**Comment by vovkasm** [comment] 2019-05-01 17:00
@newyankeecodeshop Thank you! Mostly Agree!

> I suspect the lack of WebSocket so far is because not that many apps directly use WebSockets

So I can make PR to support Websocket API. Good!

> When defining the polyfill types, it's important to base them off the Flow types in React Native, since the types defined in the TypeScript DOM library are the browser's types.

Yes and no. Yes because RN polyfills really different from web. No because flow typings (at least couple of month ago when I looked at it) was in poor state, they were full of errors, contains untyped parts and less mature (compared to typescript). I prefer to use two sources of trust: docs and implementation.

> It looks like you could fix the issue by removing the null from the signature of addEventListener? I don't even know if React Native supports null for that method on WebSocket.

It was my first attempt. But then other errors exposed (about compatibility ProgressEvent and Event) so I postponed this until communication with community. So now I plan to make more serious attempt to fix this.

**Comment by vovkasm** [comment] 2019-06-15 17:39
I can workaround this by tuning my own `globals.d.ts` which contains EventTarget definition. It was copied from `dom.d.ts` and affected part look like:
```ts
interface EventListener {
  (evt: Event): void
}

interface EventListenerObject {
  handleEvent(evt: Event): void
}

interface EventTarget {
  addEventListener(type: string, listener: EventListenerOrEventListenerObject | null, options?: boolean | AddEventListenerOptions): void
  dispatchEvent(evt: Event): boolean
  removeEventListener(type: string, listener?: EventListenerOrEventListenerObject | null, options?: EventListenerOptions | boolean): void
}
```

I'm not really using `EventListenerObject`, so I simplify this part:
```ts
interface EventListener {
  (evt: Event): void
}

interface EventTarget {
  addEventListener(type: string, listener: EventListener, options?: boolean | AddEventListenerOptions): void
  dispatchEvent(evt: Event): boolean
  removeEventListener(type: string, listener: EventListener, options?: EventListenerOptions | boolean): void
}
```

There was two points that cause errors:

1. nullability of `listener` argument
```
node_modules/@types/react-native/globals.d.ts:231:11 - error TS2430: Interface 'XMLHttpRequestUpload' incorrectly extends interface 'EventTarget'.
  Types of property 'addEventListener' are incompatible.
    Type '<K extends "timeout" | "error" | "progress" | "abort" | "load" | "loadend" | "loadstart">(type: K, listener: (this: XMLHttpRequestUpload, ev: XMLHttpRequestEventTargetEventMap[K]) => any) => void' is not assignable to type '(type: string, listener: EventListener | EventListenerObject | null, options?: boolean | AddEventListenerOptions | undefined) => void'.
      Types of parameters 'listener' and 'listener' are incompatible.
        Type 'EventListener | EventListenerObject | null' is not assignable to type '(this: XMLHttpRequestUpload, ev: ProgressEvent) => any'.
          Type 'null' is not assignable to type '(this: XMLHttpRequestUpload, ev: ProgressEvent) => any'.

231 interface XMLHttpRequestUpload extends EventTarget, XMLHttpRequestEventTarget {
```
2. After making listener argument required, second error:
```
node_modules/@types/react-native/globals.d.ts:231:11 - error TS2430: Interface 'XMLHttpRequestUpload' incorrectly extends interface 'EventTarget'.
  Types of property 'addEventListener' are incompatible.
    Type '<K extends "timeout" | "error" | "progress" | "abort" | "load" | "loadend" | "loadstart">(type: K, listener: (this: XMLHttpRequestUpload, ev: XMLHttpRequestEventTargetEventMap[K]) => any) => void' is not assignable to type '(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined) => void'.
      Types of parameters 'listener' and 'listener' are incompatible.
        Type 'EventListenerOrEventListenerObject' is not assignable to type '(this: XMLHttpRequestUpload, ev: ProgressEvent) => any'.
          Type 'EventListenerObject' is not assignable to type '(this: XMLHttpRequestUpload, ev: ProgressEvent) => any'.
            Type 'EventListenerObject' provides no match for the signature '(this: XMLHttpRequestUpload, ev: ProgressEvent): any'.

231 interface XMLHttpRequestUpload extends EventTarget, XMLHttpRequestEventTarget {
```

**Comment by vovkasm** [comment] 2019-06-15 17:42
I'm still plan to add WebSocket definitions to globals.d.ts, but it needs more work. Until that I'm not sure what to do with this issue. Thought if I'm the only one who experienced this issue then it can be safely closed...

**Comment by swansontec** [comment] 2019-09-06 19:53
This issue is easy to reproduce - just do `tsc --init` & `yarn add @types/react-native` in a new project, and you will have pages of errors as soon as you try to use the React Native types.

The quick-fix is to disable the `DOM` default library in tsconfig.json:

```json
"compilerOptions": {
  "lib": ["es6"]
}
```

But this has several problems, such as missing `WebSockets`, as discussed above. Since the out-of-box experience is broken with `@types/react-native`, I think this bug should stay open. Is there some other way to message the user, so they know these types require configuration changes?

**Comment by newyankeecodeshop** [comment] 2019-09-09 13:23
@swansontec I believe it's really important that the DOM library not be included in React Native projects. RN does not implement the DOM APIs, and where there is some overlap, such as with Geolocation or the `FormData` type, the RN runtime does not implement the exact same API as the browser. Geolocation has functions not in the browser, and the `FormData` type has fewer methods than the browser's. We need code to fail to compile when it tries to use these types incorrectly. I wouldn't want developers on my team to see code auto-complete showing Web APIs that don't exist in a RN environment.

I think we need someone from the TypeScript team at Microsoft to help us figure out how to deal with the inconsistency. For projects that try to support both environments, we need a way to define the React Native runtime globals in a way that at least doesn't collide with the browser's implementation. Maybe a way for the TypeScript compiler to be able to "pick" the right system types.

**Comment by weswigham** [comment] 2019-09-09 18:14
You could probably define a `@types/react-native-env` similar to how [`@types/webpack-env`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-env/index.d.ts) declares the global library methods available in the webpack module environment. It's possible that you'd want two versions - one that's _just_ for use with `react-native`, and one written to be the least common subset of APIs between `react-native`'s environment and the dom.

**Comment by newyankeecodeshop** [comment] 2019-09-09 20:10
@vovkasm Did you have any luck with the WebSocket type definitions? It would be nice to include those into the globals. Is that the only major subsystem still missing type declarations?

**Comment by phatmann** [comment] 2020-12-22 23:40
Any workaround for WebSocket not being defined? For now I am using @ts-ignore, but that is a hack.

**Comment by orta** [comment] 2021-06-23 08:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-23 08:09 UTC
