### ISSUE TITLE
Property 'transition' does not exist on type 'Selection<BaseType, {}, null, undefined>' in angular2

### ISSUE THREAD

**Issue by justforuse** [DefinitelyTyped/DefinitelyTyped#16176] opened 2017-04-27 15:06 UTC
- [x] I tried using the `@types/d3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek

I use angular-cli to generate a new project
then I install d3
```
npm install d3 --savedev
npm install @types/d3 --save-dev
```
the version of angular is 4.0.0 and d3 is 4.8.0.
and I add these to typings.d.ts
```
declare module 'd3' {
    export * from 'd3-array';
    export * from 'd3-axis';
    export * from 'd3-brush';
    export * from 'd3-chord';
    export * from 'd3-collection';
    export * from 'd3-color';
    export * from 'd3-dispatch';
    export * from 'd3-drag';
    export * from 'd3-dsv';
    export * from 'd3-ease';
    export * from 'd3-force';
    export * from 'd3-format';
    export * from 'd3-geo';
    export * from 'd3-hierarchy';
    export * from 'd3-interpolate';
    export * from 'd3-path';
    export * from 'd3-polygon';
    export * from 'd3-quadtree';
    export * from 'd3-queue';
    export * from 'd3-random';
    export * from 'd3-request';
    export * from 'd3-scale';
    export * from 'd3-selection';
    export * from 'd3-shape';
    export * from 'd3-time';
    export * from 'd3-time-format';
    export * from 'd3-timer';
    export * from 'd3-transition';
    export * from 'd3-voronoi';
    export * from 'd3-zoom';
}
```

and here is my app.component.ts:
```
import * as d3 from 'd3';
...
d3.select(this).select("path").transition().attr("d", function (d) {
    return arc2(<any>d);
})
...
```
but it occur an error:
`Property 'transition' does not exist on type 'Selection<BaseType, {}, null, undefined>' in angular2`
If I remove `.transition()`, everything performs well.
Is there any method to solve it? thanks for your advice.

**Comment by tomwanzek** [comment] 2017-04-27 15:37
As per my earlier response, to the original issue you posted on **d3-v4-definitelytyped**:

> For an example on how to use **D3** within an Angular 2 project please see [d3-ng2-demo](https://github.com/tomwanzek/d3-ng2-demo). While it draws on the D3 Service provided by the [d3-ng2-service](https://github.com/tomwanzek/d3-ng2-service), you can simply directly define a comparable service with the D3 modules your project requires in your angular-cli project.

> 
> If you look at the source code for the [Brush Zoom 2 Component](https://github.com/tomwanzek/d3-ng2-demo/blob/master/src/app/d3-demos/brush-zoom-2/brush-zoom-2.component.ts#L94), you will see that `transition` compiles/works without issue.
> 
> In short, this should not be a definitions issue, but is likely a consequence of the unnecessary addition you indicated to the `typings.d.ts` file of your Angular project.
> 
> If, _after_ reviewing the example code I referenced above and possibly using StackOverflow for how-to questions, you still experience what appears to be a bug, please open an issue on DefinitelyTyped and ping me there. Preferably with a link to a repo that reproduces the issue.

Have you explored the example code, I referred you to? As the code works with `transition()`, there does not appear to be an issue with the definitions.

As indicated above, there is **no need** to add anything to `typings.d.ts` to work with the `d3` bundle or individual D3 modules in angular 2.

If **after** reviewing your code in comparison to the reference example, you still experience a compile time error on `transitition()`. Please, provide a link to a **minimally viable repo** that reproduces the issue.

I could then clone the repo and investigate deeper.

**Comment by justforuse** [comment] 2017-04-28 02:13
@tomwanzek 
Thanks for your advice, and I remove the unneeded code in typings.d.ts. 
here is my repo for this issue:
https://github.com/justforuse/angular2-d3-transition-issue

I tried again and the error still occured.

you can just run `npm install` and `ng serve` to run this project
By the way, here is info of my angular-cli:
```
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0

```

Thanks a lot.

**Comment by justforuse** [comment] 2017-04-28 06:16
@tomwanzek  I tried `npm uninstall --save-dev @types/node`, and restart project, everything works well and no error occured, So is that says `@types/d3` has bug?
What if I use d3 without `@types/d3`? Is it necessary for angular2?
Hopes for your opinion

**Comment by tomwanzek** [comment] 2017-04-28 14:37
@justforuse I cloned the repo and ran `ng serve`/`ng build`. The compile error you referenced on `transition` does _not_ reproduce for me.

Due to constrained cycles, I am limiting my review to this particular question.

I will, however, just briefly note the following:

```
var svg = this.chartContainer.nativeElement.attr("width", width + 100).attr("height", height + 100);
```
will throw a runtime exception of:
```
this.chartContainer.nativeElement.attr is not a function
```

In your mouse over callbacks, the argument `d` is shadowed and one of them should be renamed for clarity.

As a general note, I would encourage you to use the generics provided for in the methods and interfaces of the D3 definitions to clarify your code's intent rather than flowing through `any` implicitly. While I know, that this is just a minimally viable reproduction repo, it's a great help when reviewing code for questions like the one raised here.

**Comment by justforuse** [comment] 2017-04-28 16:09
@tomwanzek  Oh..it's my fault, and I update my repo if you have time to review it. just change that code to `var svg = d3.select(".chart").attr("width", width + 100).attr("height", height + 100);`.
https://github.com/justforuse/angular2-d3-transition-issue

I really appreciate your effort,  I'm not an expert on typescript, and I don't know how to solve the error if I remove `any`. I just want to add a d3 chart on my component. I never thought things will be so weird.
For now, I will just remove `@types/d3` to make my project work.
Hopes for your solution. Thanks

**Comment by tomwanzek** [comment] 2017-04-28 16:41
No worries. Here is the thing, why would you remove `@types/d3`, it works fine. Like I said before, I do not have an issue with your repo, it compiles fine. With your latest change, the app component renders and responds to the mouseovers:

![Screenshot of you pie chart](https://cloud.githubusercontent.com/assets/16323903/25537771/ebd0c470-2c0d-11e7-9180-acf2df7ea46e.PNG)

As for the suggested clean-up and use of the generics to control type-safety of selected elements and types of the "data" passed into them or `pie` for that matter. The JSDoc comments in the typings from `d3-selection`, `d3-shape` have information regarding the meaning of the different generics used by interfaces/methods. A code editor like VSCode would also show them as hovers.

Beyond the general getting more acquainted with TypeScript, you can also check out the **d3-ng2-demo** I mentioned before. The components replicate some standard D3 examples, while also show-casing possible ways to use the generics i.p. of the selection API in TypeScript.

If you are a bit more adventurous, you can check out the shape tests of the D3 module definitions in **DefinitelyTyped**, e.g. [d3-selection tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-selection/d3-selection-tests.ts). If you bear in mind that they are a bit artificial, as they only test the consistency of the definitions, you can get a feel for how the generics of selections work.

Beyond that, StackOverflow is probably the better place to carry on with "how to" questions.

The definitions for `transition()` seem to work, however. So if you no longer experience the compile time issue, I think we can close this issue here. Thx, T

**Comment by tomwanzek** [comment] 2017-05-01 18:37
@justforuse Can this be closed?

**Comment by justforuse** [comment] 2017-05-02 02:03
@tomwanzek ok, Thanks a lot

**Closed** 2017-05-02 02:04 UTC

**Comment by SaadAhmedSiddiqui** [comment] 2017-11-30 06:34
I have fixed my code by:
import { select as d3Select } from 'd3-selection';
import { transition as d3Transition } from 'd3-transition';
d3Select.prototype.transition = d3Transition;

**Comment by azzimuth** [comment] 2018-05-04 09:43
@SaadAhmedSiddiqui `[ts] Property 'prototype' does not exist on type 'typeof "c:/Git/myrepo/myproj/node_modules/@types/d3-selection/index"'.`

**Comment by justforuse** [comment] 2018-05-05 05:25
Forget to reply, this is because I use [`cnpm`](https://www.npmjs.com/package/cnpm) to install the packages, and I turn back to `npm`, no errors happened

**Comment by ms-tng** [comment] 2023-01-09 12:53
Just in case somebody comes here through a search for the issue: In our case, the root cause was that `d3-transition` used a different version of `d3-selection` than the one we used directly. Deduplicating both packages in our package manager lockfile solved it.
(In our case: using https://www.npmjs.com/package/yarn-deduplicate for Yarn 1. Afterwards, we had to delete and reinstall `node_modules` due to https://github.com/yarnpkg/yarn/issues/8146.)
