### ISSUE TITLE
bluebird-global instance methods lose promise type information

### ISSUE THREAD

**Issue by aaronjensen** [DefinitelyTyped/DefinitelyTyped#28081] opened 2018-08-13 15:48 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/bluebird-global` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @d-ph

The following does not, but should typecheck:

```ts
Promise.resolve([3]).map((n: number) => true);
```

See: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10801#issuecomment-412355785

This is a related, but slightly different reproduction:

https://www.typescriptlang.org/play/index.html#src=declare%20class%20Foo%3CU%3E%20%7B%0A%20%20map%3CU%3E(mapper%3A%20(u%3A%20U)%20%3D%3E%20boolean)%3A%20void%3B%0A%7D%0A%0Ainterface%20Bar%3CT%3E%20%7B%0A%20%20map%3A%20typeof%20Foo.prototype.map%3B%0A%7D%0A%0Adeclare%20var%20bar%3A%20Bar%3Cstring%3E%3B%0A%0Abar.map((n%3A%20number)%20%3D%3E%20false)

My suggestion of `map: typeof Bluebird<T>.prototype.map` isn't valid--I'm not sure how to do that in TS.

Changing bluebird-global's definition to the below does work, but that implies we have to copy/paste all of the definitions out of `bluebird`...

```ts
        map<U>(mapper: IterateFunction<IterableItem<T>, U>, options?: Bluebird.ConcurrencyOption): Bluebird<T extends Iterable<any> ? U[] : never>;
```

**Comment by d-ph** [comment] 2018-08-14 22:48
Status: 

I created a TypeScript Feature Request, that suggests allowing devs to write `typeof Bluebird<T>.prototype.map` (i.e. provide the generic type of the class in the `typeof` expression). See the linked issue above.

To walk-around this problem, the `strictFunctionTypes` option can be set to `false` in `tsconfig.json`. This is obviously a *bad* idea, since the issue is still there (it just allows the compilation to pass). The issue being: the type of the Promise is lost, when `.map` (and possibly other instance methods) is used.

**Comment by aaronjensen** [comment] 2018-08-14 22:53
@d-ph Awesome, thanks for filing that. I wonder if they'd be open to a feature that would allow completely replacing/subverting the `Promise` and `PromiseConstructor` definitions instead since ultimately, that is more or less what we want, yeah? I'm sure that's a bad idea for reasons I haven't thought of...

**Comment by aaronjensen** [comment] 2018-08-14 23:03
Oh, and in the meantime, would it make sense to copy-paste the definitions for now so that they work properly?

**Comment by aaronjensen** [comment] 2018-08-14 23:14
@d-ph there's something to this, I think:

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

interface Promise<T> extends Omit<Bluebird<T>, 'call' | 'then' | 'catch' | 'finally'> {
```

It fixes the issue above. I'm still working through some problems with `call` that make `Bluebird` incompatible with `Promise`, but it's showing some potential. 

[Here's a minimal example](https://www.typescriptlang.org/play/index.html#src=declare%20class%20Foo%3CT%3E%20%7B%0A%20%20map(t%3A%20T)%3A%20boolean%20%0A%7D%0A%0Ainterface%20Promise%3CT%3E%20extends%20Foo%3CT%3E%20%7B%20%7D%0A%0Adeclare%20var%20p%3A%20Promise%3Cnumber%3E%0A%0Ap.map(4)%0Ap.map('hi'))

**Comment by d-ph** [comment] 2018-08-15 22:49
I see how your `extend Omit<>` works, however I'd rather go with what Ryan suggested in the other ticket. Both ways achieve the same goal, but I find the verbose method of specifically listing all methods on the `Promise` global interface more controllable (white-listing) than saying "take all methods from Bluebird but the following few" (black-listing). Though, I admit it requires significantly more typing.

I'll create a PR that does what Ryan recommended (to all Promise's instance methods) and this will resolve this ticket's immediate issue with getting an error just for using one of the methods.

---

In regards to the inability to assign `Bluebird<any>` to `Promise<string>` -- for now I'm interested only in why it's possible to assign `Bluebird<any>` to `Bluebird<string>`, but not `Bluebird<any>` to `Promise<string>` (i.e. the example you gave in the linked TypeScript issue).

Let's leave this and the linked ticket open until it's found out what the reason is and then see what to do next.

**Comment by orta** [comment] 2021-06-07 13:17
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:17 UTC
