### ISSUE TITLE
tripleslash references => moment.d.ts

### ISSUE THREAD

**Issue by FreakAzoidIssued** [DefinitelyTyped/DefinitelyTyped#8568] opened 2016-03-15 13:19 UTC
I tried using the latest `moment.d.ts` file in this repo and had problems at compile time while using typescript 1.8.7.

TS2654 Build: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.

**Comment by vvakame** [comment] 2016-03-15 16:57
I can't reproduce your issue.

```
$  git rev-parse master
867c558058e051e30e2d02ad3c9987f3fd110844
$ tsc -v
Version 1.8.7
$ tsc --target es6 --noImplicitAny --module commonjs moment/moment.d.ts
$ echo $?
0
```

**Comment by FreakAzoidIssued** [comment] 2016-03-15 17:10
If you reference the moment.d.ts, which is on disk and not in the solution directly, the tripleslash error occurs at server side typescript compile time.

**Comment by orta** [comment] 2021-06-07 13:30
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:30 UTC
