### ISSUE TITLE
@types/gun incompatible with React CRA / Babel

### ISSUE THREAD

**Issue by rm-rf-etc** [DefinitelyTyped/DefinitelyTyped#37344] opened 2019-08-04 04:59 UTC
- [x] I tried using the `@types/gun` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Jack-Works 

I'm forced to find a workaround to use `@types/gun` in a create-react-app project because [babel doesn't support namespaces, and likely never will](https://github.com/babel/babel/pull/9785#pullrequestreview-236668097). The types for GunDB are all namespaced, so this library won't work for any CRA / Babel users. Since namespaces are now considered legacy and it seems that the push is to use ES6 modules everywhere, I think it makes sense to remove namespaces from `@types/gun`.

To add some extra context, modifying CRA without ejecting requires some jumping thru hoops:
https://github.com/timarney/react-app-rewired/
https://github.com/arackaf/customize-cra/

FWIW, I'm trying to author a `react-gun` library.

Would very much appreciate some workaround suggestions.

**Comment by Jack-Works** [comment] 2019-08-04 10:05
Yes although ESModule is good to use, sadly the `gun` itself is providing a complex API. Without namespace, I can't type gun in the correct way

**Comment by rm-rf-etc** [comment] 2019-08-05 01:40
Actually, it seems namespace support was merged into babel. Maybe I just need a bleeding edge version.

**Comment by rm-rf-etc** [comment] 2019-08-05 08:04
@Jack-Works, Looks like namespace support is in the latest version of `@babel/plugin-transform-typescript`, but I'm still not able to get this error resolved. Could you provide an example of how to import the `Gun` namespace, and/or something like `ChainReference`? `import Gun from 'gun'` seems to reference `Gun.Constructor`, and that's all I can access.

**Comment by Jack-Works** [comment] 2019-08-05 08:24
I'm sorry when writing typing for gun, I didn't consider it clearly. There is no way to import ChainReference and type is very unfriendly with untyped code.

When I'm free, I'll try to resolve this problem.

**Comment by rm-rf-etc** [comment] 2019-08-05 08:46
@Jack-Works okay, thank you for you help with this. I think I found a good temporary solution:
```
import Gun from 'gun';
const gun = Gun();
type ChainReference = typeof gun;
```
This seems to be working, but now I'm seeing other problems I don't understand.

If I try to use `.put()`, I can't pass in my data because the type for the first argument is `never`:
```
(method) Gun.ChainReference<any, any, "pre_root">.put(data: never, ...
```
Is this just a mistake? I see the same issue with `.get()`:
```
(method) Gun.ChainReference<any, any, "pre_root">.get<string | number | symbol>(key: never, ...
```

**Comment by rm-rf-etc** [comment] 2019-08-05 09:15
@Jack-Works have a look at this code, this compiles and runs as expected.
https://github.com/rm-rf-etc/react-gun-test/blob/master/src/App.tsx

I've cast `as any` on the `.once()`, `.get()`, and `.put()` methods, to verify that these methods are being used how GUN expects.

I can start submitting PR's as I find these issues.

**Comment by rm-rf-etc** [comment] 2019-08-05 10:15
```diff
diff --git a/types/gun/index.d.ts b/types/gun/index.d.ts
index 0cba9d6620..1d1813fcbe 100644
--- a/types/gun/index.d.ts
+++ b/types/gun/index.d.ts
@@ -86,7 +86,7 @@ declare namespace Gun {
          * @param callback invoked on each acknowledgment
          */
         put(
-            data: Partial<AlwaysDisallowedType<DisallowPrimitives<IsTop, DisallowArray<DataType>>>>,
+            data: string | number | boolean | { [p: string]: string | number | boolean },
             callback?: AckCallback
         ): ChainReference<DataType, ReferenceKey, IsTop>;
         /**
@@ -102,7 +102,7 @@ declare namespace Gun {
          * **Here the type of callback respect to the actual behavior**
          */
         get<K extends keyof DataType>(
-            key: ArrayOf<DataType> extends never ? K : never,
+            key: string | ChainReference,
             callback?: (
                 /** the raw data. Internal node of gun. Will not typed here. */
                 paramA: Record<
@@ -156,7 +156,7 @@ declare namespace Gun {
          */
         once(
             callback?: (
-                data: (DisallowPrimitives<IsTop, AlwaysDisallowedType<ArrayAsRecord<DataType>>>) | undefined,
+                data: string | number | boolean | (DisallowPrimitives<IsTop, AlwaysDisallowedType<ArrayAsRecord<DataType>>>) | undefined,
                 key: ReferenceKey
             ) => void,
             option?: { wait: number }

```

@Jack-Works, here's some changes I made in the type definitions. I cloned this to my local and used `npm link` to use these definitions in my project. I was able to remove the cast `as any` and compile:
https://github.com/rm-rf-etc/react-gun-test/blob/npm-linked-types-gun/src/App.tsx

**Comment by Jack-Works** [comment] 2019-08-05 13:48
> @Jack-Works okay, thank you for you help with this. I think I found a good temporary solution:
> 
> ```
> import Gun from 'gun';
> const gun = Gun();
> type ChainReference = typeof gun;
> ```
> 
> This seems to be working, but now I'm seeing other problems I don't understand.
> 
> If I try to use `.put()`, I can't pass in my data because the type for the first argument is `never`:
> 
> ```
> (method) Gun.ChainReference<any, any, "pre_root">.put(data: never, ...
> ```
> 
> Is this just a mistake? I see the same issue with `.get()`:
> 
> ```
> (method) Gun.ChainReference<any, any, "pre_root">.get<string | number | symbol>(key: never, ...
> ```

It's by design. With typed interface, methods like `get` and `put` will act normal.

**Comment by rm-rf-etc** [comment] 2019-08-06 02:12
> > @Jack-Works okay, thank you for you help with this. I think I found a good temporary solution:
> It's by design. With typed interface, methods like `get` and `put` will act normal.

Could you elaborate? Maybe include an example? Shouldn't `get` and `put` accept – be default – a type which includes all valid gun data types?

**Comment by Jack-Works** [comment] 2019-08-06 02:16
> > > @Jack-Works okay, thank you for you help with this. I think I found a good temporary solution:
> > > It's by design. With typed interface, methods like `get` and `put` will act normal.
> 
> Could you elaborate? Maybe include an example? Shouldn't `get` and `put` accept – be default – a type which includes all valid gun data types?

You can see the test example in the @types/gun

**Comment by rm-rf-etc** [comment] 2019-08-07 04:27
I understand now. In the next version, will `ChainReference` be exported? It might help me write the types for `react-gun`.

**Comment by Jack-Works** [comment] 2019-08-07 10:17
Yes, I'll find time to do that when I'm free.

**Comment by Jack-Works** [comment] 2019-08-10 05:07
Got no idea how to do this well, maybe I need to contribute to gun and let them to use esmodule first

**Comment by Jack-Works** [comment] 2019-08-10 06:29
https://github.com/amark/gun/issues/789

**Comment by rm-rf-etc** [comment] 2019-08-14 18:46
@Jack-Works, cross-posting this question from gitter.

Is a reason we can't export the Gun namespace? I'm having trouble typing the following function for [react-gun](https://github.com/rm-rf-etc/react-gun):

```typescript
export const init = <AppState>(RootName: Gun.ArrayOf<AppState>, ...args: any[]) => {
    const gun = Gun<AppState>(...args);
    const app = gun.get(RootName);
    return { gun, app };
};
```

**Comment by Jack-Works** [comment] 2019-08-15 01:24
Actually I can, I know there is a change in the gun that make gun provides
esmodule export. After the export shipped, I'll use a more graceful way to
export the types.

**Comment by Jack-Works** [comment] 2019-08-24 08:02
I have seen the experimental es module export gun, I'll rewrite the types later, make it more friendly to TypeScript and non-typescript users.

**Comment by orta** [comment] 2021-06-07 14:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:09 UTC
