### ISSUE TITLE
Rethinkdb 2.0.x

### ISSUE THREAD

**Issue by sma** [DefinitelyTyped/DefinitelyTyped#4551] opened 2015-06-04 16:30 UTC
Is anybody working on an update for RethinkDB 2.0.x (http://www.rethinkdb.com/api/javascript/)? The provided type definition are for RethinkDB 1.10 and are lacking the promise based API. If nobody is, I'd volunteer.

**Comment by ronzeidman** [comment] 2015-09-10 11:02
I've built something:
https://www.dropbox.com/s/d1k1eir9o6n6y0l/rethinkdb.d.ts?dl=0
but it causes my TypeScript compiler to get out-of-memmory exceptions,
if you can fix it it will be much appreciated

**Comment by niieani** [comment] 2015-12-01 13:43
I have them ready, I'll file a pull request today, once I finish adding a few more small fixes. It's feature complete, since I've first built a crawler for the RethinkDB documentation and then tuned it by hand.
https://github.com/niieani/rethinkdb-typescript-definition
It's a shame I haven't seen @ronzeidman's work first, it has some good elements to it. If you'd like to contribute your parts to my definitions, feel free to do so.

**Comment by ronzeidman** [comment] 2015-12-07 15:03
Hi,
I'm not working on this full-time but I've tried using your definitions and I found some things missing:
in RInterface:
```typescript
minval: any;
maxval: any;
```
https://rethinkdb.com/api/javascript/between/
> You may also use the special constants r.minval and r.maxval for boundaries, which represent “less than any index key” and “more than any index key” respectively.

a key can be a string a number or compund array, also the special interface can have options so getAll should be something like this:
```typescript
export type RKeyType = string|number|Array<string|number|RStringInterface|RNumberInterface>|RStringInterface|RNumberInterface|RArrayInterface;

getAll(key:RKeyType, ...keys_and_then_options:Array<RKeyType|{ index? }>):RSelectionInterface<any>;
getAll(args:RSpecialInterface, options?:{ index? }); 
```

you can also map an array/sequence of objects, not only values:
```typescript
map(a_function:ExpressionFunction<RValueInterface<any>|RObjectInterface<any>, RAnyInterface|Object>):RArrayInterface;
```

under RSequenceStream you can choose an index of the sequence (if it contains several elements) and not only attribute
```typescript
(index:number|RNumberInterface):RSingleSelectionInterface<any>;
```
You can also choose an attribute of an object interface:
```typescript
(attr:string|RStringInterface):RValueInterface<any>;
```

run in rethinkdbdash doesn't require the connection:
```typescript
run(connection?:RConnectionInterface, options?:RConnectionOptionsInterface):Promise<T>;
```

you can't ungroup if you do things like something.group('a').map(...).ungroup(), you need to use the new typescript 1.7's 'this' type. Instead of returning "RStreamInterface<RemoteT>" you should be returning "this".

I will try to fix all issues I encounter and try to upload here a fixed version.
Regards,
Ron Zeidman

**Comment by niieani** [comment] 2015-12-07 16:38
@ronzeidman Awesome, thanks Ron. I've noticed the ungroup problem myself, and also found that the new TypeScript 1.7 `:this` is the solution. I'd be glad if you could fork this one:
https://github.com/niieani/rethinkdb-typescript-definition
and send a pull request with the modifications there, since I've fixed a few bugs since filing the DefinitelyTyped pull request too. I'll submit them in here when we have more fixes in ready.

**Comment by ronzeidman** [comment] 2015-12-10 10:46
I've fixed it to make it workable (now all my code compiles with the new
definitions!).
For the groupped interface I had to make a new one with duplication of the
functions, but now it works fine.
I only fixed things that impacted my work directly so there are many things
I did not update, therefore the quality is not good enough for a pull
request but you can look at it and try to brush it up.

Best Regards,
Ron Zeidman

**Comment by ronzeidman** [comment] 2015-12-10 10:50
Apperantly GitHub does not support uploading d.ts files even when zipped
[rethinkdb_d_ts.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/57968/rethinkdb_d_ts.txt)

**Comment by niieani** [comment] 2015-12-10 12:18
@ronzeidman Just taking a look, but I've noticed something strange - were you correcting the latest version from my repository? It seems some methods are missing, like `skip(n:number|RNumberInterface):RArrayInterface;` in `RInterface`.
As for the `RGroupedStreamInterface` duplication of definitions, I think we can do something better than a workaround, like a second generic in the type for the output.
Also, I've noticed your comment: `'&' is a workaround so I can use both cursor or array interfaces after run (in rethinkdbdash it returns arrays by default)` - such overrides belong to the `rethinkdbdash.d.ts` project, not `rethinkdb.d.ts`. Also, `rethinkdbdash` might be changing the default behavior to match that of `rethinkdb`.
Anyway, Ron, I'll try to merge what I can when I have some free time.

**Comment by niieani** [comment] 2015-12-10 12:24
@ronzeidman I've merged most of your changes without testing into a separate branch here: https://github.com/niieani/rethinkdb-typescript-definition/tree/ronzeidman/rethinkdb 
I've also added you as a collaborator to the project so if you make changes you can push them to that branch. As we solve the remaining issues, we can merge it to master, and then finally to DefinitelyTyped.

**Comment by ronzeidman** [comment] 2015-12-10 13:49
Great, thanks.
I've put the "skip" (and "limit", "slice" and "without") in the RSequenceInterface making them return "this". that all of the derived interfaces get them for free: RArrayInterface, RSequenceArrayInterface and RSequenceStream<RemoteT>.
About the grouped interface, I needed a new interface and I needed for making the some of the group functions that reduce the value return a grouped value interface that can't be reduced further, also "this" type cannot change the Generics inside the interface which cause problems making the group interface inherit from some of the RSequenceInterface. maybe we should move the functions I've made return "this" to a new interface which both RSequenceInterface and RGroupedStreamInterface inherit from.
As for the Array/Cursor, you are right, I "fixed" it by making RCursorInterface extend Array in rethinkdbdash. It's not an optimal solution but I can't think of anything better.

**Comment by ronzeidman** [comment] 2015-12-10 14:50
Sorry, first commit to github... 
I accidentally pushed it to the master instead of my branch, reverted it and committed to the right one, you can review if you'd like.

**Comment by niieani** [comment] 2015-12-27 21:03
@ronzeidman Thanks for your help. Today I've completely refactored the d.ts so that it's more extensible (most methods that appear in multiple interfaces have their own generic `interface`), plus I've made `RArray` generic, but unfortunately I didn't reimplement your addition of `RGroupedStream` yet. 
If you'd like to take a look at the new structure and possibly add an implementation of RGroupedValue and RGroupedStream in a similar way to what I've done (separating methods into their own, generic interfaces) that would be most helpful. 
If you decide to do so, I would ask you to configure your editor so that it does not change the whitespace like the last time (indentation should be 2 spaces, as in the `.editorconfig` file) or modify the charset, which should be `UTF-8` (last time your editor deleted the little arrows in the comments). I can personally recommend either Atom or the free Visual Studio Code which has great TypeScript support, or finally IntelliJ WebStorm, cause it supports folding.
https://github.com/niieani/rethinkdb-typescript-definition/blob/master/rethinkdb/rethinkdb.d.ts

**Comment by ronzeidman** [comment] 2015-12-27 22:36
@niieani Hi, 
sorry for the spaces, will be fixed next time
this looks like a lot of work but I'm sorry to inform that at least for me it didn't work.
After I've fixed some minor bugs like:
```typescript
        concatMap<ArrOfT, U extends RValue<ArrOfT>>(concatFunction:ConcatFunction<T, U>): RStream<ArrOfT>;
--->
        concatMap<U>(concatFunction:ConcatFunction<T, U|Array<U>|RObject<U>|RArray<U>|RValue<U>>): RArray<U>;

    type Bounds = 'closed'|'open';
--->
    type Bounds = string; //'closed'|'open';

-    row<T extends Array<ArrOfT>, ArrOfT>(name:r.stringLike): RArray<ArrOfT>;

    getAll(key:KeyType, ...keys_and_then_options:Array<KeyType | { index?:string }>): RSelection<RemoteT>;
-    getAll(key:KeyType, options?:{ index:string }): RSelection<RemoteT>;
-    getAll(key:KeyType, ...keys:Array<KeyType>): RSelection<RemoteT>;
-    getAll(range:Array<KeyType>, options?:{ index:string  }): RSelection<RemoteT>;
+    getAll(key:KeyType): RSelection<RemoteT>;
    getAll(args:RSpecial): RSelection<RemoteT>;

    left_bound?: string; // 'closed'
    right_bound?: string; // 'open'
---->
    leftBound?: string; // 'closed'
    rightBound?: string; // 'open'

    r.bracketsGetByIndex<RStream<RemoteT>>,
--->
    r.bracketsGetByIndex<RObject<RemoteT>>,
```

I tried to compile my code, and it just never finished compiling. It was caught in an endless loop (like my original typescript attempt...)
try running tsc on something that uses this typing file and see for yourself, I'll try making an example of something small that doesn't compile and issue an issue to the typescript people but in the meantime the previous typings worked like a charm, so I'll be using them...

**Comment by niieani** [comment] 2015-12-27 23:28
@ronzeidman Well, actually I forgot to say that I was using the `typescript@next` when working on these. I had the never ending loop at one point, but I think I've fixed it, or at least, it does compile the test file for me now, using today's version of TypeScript. 
If you want to try installing the latest TypeScript build, you can do it by typing: `npm install -g typescript@next`. Thanks for the feedback.

**Comment by ronzeidman** [comment] 2015-12-28 06:14
Wow, typescript is growing fast.
I won't be available in the next couple of days but I'll look into it when I have time.

**Comment by niieani** [comment] 2015-12-28 10:03
Sure, no problem. Enjoy the New Years eve ;)

**Comment by ronzeidman** [comment] 2015-12-29 22:50
Hi, Thanks!
I had a few hours, I tried to use the new type definitions and they mostly work but after all this work and the very complex definitions, I think we maybe took a "Do everything perfect" approach instead of "Make it give the best benefit and annoy the user the least" approach.
I'm saying that maybe the whole type definition might need to be much less fragmented. I mean, sometimes my fields are arrays and sometimes objects, sometimes strings or numbers... I don't want to always need to explicitly cast everything all the time. it's especially hard when I try to map an array:
```typescript
r.expr([{
innerArray: [{},{},{name: 'test1'}]
},{
innerArray: [{},{},{name: 'test2'}]
}])('innerArray').map((array) => array(2))('name');

//returns ['test1', 'test2']
```
when I just want to get an item from a different table:
```typescript
r.table('table1').get(999).do((row) => r.table('table2').get(row('connectedId')));
```
With grouping and reduction it's even more complex and almost everything goes:
```typescript
r.expr([{ a: 3 }, { a: 4 }, { a: 5 }, { b: 3 }, { b: 4 }, { b: 5 }])
  .group(function(row) { return row.hasFields('a') })
  .concatMap(function(row) { return row.values() })
  .reduce(function(left, right) { return left.add(right) })
  .add(9)
  .ungroup()
  ('reduction')
  .sum();
//the result is 42 BTW
```
everything will need an explicit cast in almost every function on the way.
Maybe the first thing we should provide is just an "RExpr<T>" interface that has the entire API, but that API will return the right objects, and will be able to check for the right parameters and will always return RExpr (except when calling "run" and also "r" and "r.db" will have a different interfaces).
I think the code that uses these types of type definition will provide more value and will annoy the user less (he wont need to always explicitly cast r.row<string[]>('someArray')) and will provide the best value in terms of code completion return values and valid values at the cost enabling a user to "join" or to run a "getAll" on something that is not a table and receive an error. or trying to "add" to an array or stream.
Maybe it's giving up when we are close to a good solution but still... seems like typescripting that requires type casts all the time is more annoying than helpful.

Maybe it's just the time...
Enjoy New Years eve :)
Good night

**Comment by niieani** [comment] 2015-12-29 23:27
@ronzeidman I had similar doubts when looking at the actual usage of the typings, however I believe that we're possibly missing just a few features of TypeScript that could remove the need of casting everything. Mainly, the problem is caused by the inability to recover/access properties of a type from parameters of a method. 
After all, once we declare the type of a table, say:
```ts
r.table<{ id: string, name: string, prop: Array<{ test: string }> }>('test').get('123') // and then do more with it
```
We already have all the information we need to conduct any transformations on this data. We know what's a row, we know that's a prop. If we could only declare types like: 

```ts
// access property of T
method(property:string): T.property
```
We could solve at least 50% of the need for casting. Other things that could help here would be:

* extracting generics from generics (e.g. so we can use the `T` when the type is `Array<T>`)
* an opposite of union of types, a "difference" type (T1 - T2)
* an "all-optional" type, basically converting a class or interface declaration into one where all of their properties are optional - this could be useful for doing stuff like `.update({ oneProp: ... })`

TypeScript is moving forward really quickly in the recent times, so I think it might be worth writing proposals for the above use cases, so that in the future we could have true type safety without the burden of manually re-casting all the time.

On the other hand, the sheer ambiguity and the number of overloads required to code the methods for a RethinkDB driver to me kind of smells of not very well thought-out design process. In the last few days I've tried to write my own RethinkDB driver in TypeScript, but the complexity of overloads in methods and things like using rest parameters in the middle of a method's signature made me not want to do it.
So maybe it could also make sense to open a RethinkDB issue regarding the driver's API, perhaps drivers for the future RethinkDB, say 3.0, could implement a less ambiguous syntax. The good thing is that the protocol is separate from the client API, which means it's already technically possible to make a client with a different syntax. In TypeScript, Java or C#, passing in objects with params { }, instead of worrying about argument positioning and overloads could be one thing, but it would be best to think about this more.

You too, Enjoy the New Years Eve :) :balloon:

**Comment by jakebailey** [comment] 2024-02-11 06:20
rethinkdb v2 is on DT.

**Closed by jakebailey** 2024-02-11 06:20 UTC
Labels: Definition:Request
