### ISSUE TITLE
[@types/react-redux] 'hoist-non-react-statics' has no exported member 'NonReactStatics'

### ISSUE THREAD

**Issue by stewartrule** [DefinitelyTyped/DefinitelyTyped#33690] opened 2019-03-07 13:05 UTC
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

@jamesreggio @JounQin

updating from `@types/react-redux 7.0.1` to `@types/react-redux 7.0.2` gives the following error:

```
'/node_modules/hoist-non-react-statics' has no exported member 'NonReactStatics'.

47 import { NonReactStatics } from 'hoist-non-react-statics';
```
seems like it was introduced here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/8b1beff944f6c7bf913b6fcee31fb5f7129064a7

**Comment by jamesreggio** [comment] 2019-03-07 18:26
Yikes. I introduced a dependency upon `@types/hoist-non-react-statics` in that change, but I didn't add it as a dependency. This problem is, I'm not sure where to declare it as a dependency, since the types only depend upon the types.

@JounQin, can you help me to understand how to fix this. Do we need to add an `///<reference` or add something to the `package.json`?

As a temporary workaround, you can `npm install --dev @types/hoist-non-react-statics` to your project.

**Comment by darrencrossley** [comment] 2019-03-07 19:49
I could be wrong but I think the problem is maybe more simple,

    import { NonReactStatics } from 'hoist-non-react-statics';

should be

    import NonReactStatics from 'hoist-non-react-statics';

downgrading to @types/react-redux 7.0.1 is a quick fix until this is fixed.

**Comment by JustFly1984** [comment] 2019-03-08 20:15
I got this issue today too. Downgrading to 7.0.1 helped

**Comment by bordi** [comment] 2019-03-10 15:04
Same here.

**Comment by surgeboris** [comment] 2019-03-10 21:13
> Yikes. I introduced a dependency upon `@types/hoist-non-react-statics` in that change, but I didn't add it as a dependency

DefinitelyTyped automatically added ` @types/hoist-non-react-statics` as a dependency to `@types/react-redux`, but (apparently) that wasn't enough for your typings to work.

> As a temporary workaround, you can `npm install --dev @types/hoist-non-react-statics` to your project.

No, that will not work as this dependency is already automatically added  by DefinitelyTyped, but it's not enough for TS to treat your typings correctly.

I guess the problem that TS is not aware of the existence of `hoist-non-react-statics` module, as `hoist-react-statics` package itself is not present in node_modules (it's a shame that TS cannot derive module existince from `@types/hoist-non-react-statics` package, although there may be a valid reason for such behaviour e.g. compatibility). This hypothesis is confirmed by the fact that [manual installation of `hoist-non-react-statics` does make your typings work correctly](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33446#issuecomment-471338263).

So, @jamesreggio I guess you have to add `hoist-non-react-statics` package as a dependency [to the `package.json` of `@types/react-redux`](https://github.com/jamesreggio/DefinitelyTyped/blob/8b1beff944f6c7bf913b6fcee31fb5f7129064a7/types/react-redux/package.json#L4) in order to fix this issue.

**Comment by JustFly1984** [comment] 2019-03-11 20:09
@surgeboris updated to 7.0.3 and added `hoist-non-react-statics` and `@types/hoist-non-react-statics`, fixed an issue

**Comment by amertak** [comment] 2019-03-15 15:44
The fix not really working for me. Maybe I am doing something wrong. Using yarn 1.13

**Comment by jamesreggio** [comment] 2019-03-15 19:27
Okay everybody, thanks for your patience.

I figured out a fix and opened a PR: #33919.

Apparently, if you use the Node-style type definition export (with `export =`), the proper way to import is with `import [name] = require([package name])`. I'm rather unfamiliar with the nuances of these import/export patterns, and I'm only vaguely more confident that I understand it now 😆 

Hopefully the maintainers of DefinitielyTyped can get this merged and released ASAP. Sorry again for the regression.

**Comment by wolfy1339** [comment] 2019-03-18 17:39
Unfortunately, even with `7.0.4` that was recently released, this hasn't fixed the problem for me

**Comment by weswigham** [comment] 2019-03-18 18:10
It looks like the explicit dependency on `@types/hoist-non-react-statics` is still missing.

**Comment by weswigham** [comment] 2019-03-18 18:10
IIRC it needs a `paths` mapping in [the tsconfig](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/tsconfig.json) to make the dependency on another `@types` definition explicit.

**Comment by weswigham** [comment] 2019-03-18 18:18
actually, no - a fresh `npm i @types/react-redux` installed `@types/hoist-non-react-statics`. I don't see any problem?

**Comment by weswigham** [comment] 2019-03-18 18:19
Yup, the dependency is definitely listed in its `package.json`:
```ts
  "dependencies": {
    "@types/hoist-non-react-statics": "*",
    "@types/react": "*",
    "redux": "^4.0.0"
  },
```
if y'all still having issues, you should double check the right versions of everything have been installed.

**Comment by weswigham** [comment] 2019-03-18 18:21
(Specifically, the dependency is listed as `*`, so you may have an older version of `@types/hoist-non-react-statics` that is maybe missing the type which `npm` counts as satisfying the dependency?)

**Comment by jamesreggio** [comment] 2019-03-18 18:26
So, the problem is somewhat nuanced.

The `hoist-non-react-statics` package included its own hyper-basic typings from `v2.2.0` until `v3.0.0`, and if the version of `hoist-non-react-statics` that resolves in your project root in in that range, you'll encounter this error since the package-local typings take precedence over `@types/hoist-non-react-statics`.

There are two immediate workarounds:

1. Add `hoist-non-react-statics@^3.3.0` to your project as a dependency.
2. If using yarn, add a resolution override to your `package.json` as such:
    ```
      "resolutions": {
        "hoist-non-react-statics": "^3.3.0"
      }
    ```

Neither of these are optimal, because most devs are (rightfully) not aware of the existence of `hoist-non-react-statics` in the first place.

I'm not really sure what the optimal approach would be here, but I suspect that if we could list a specific versionspec for `@types/hoist-non-react-statics` inside of the `package.json` for `@types/react-redux`, we could mitigate the impact.

@weswigham — do you know if its possible to replace the autogenerated dependency with `*` with a dependency upon `@types/hoist-non-react-statics` with `>=3.3.0`?

**Comment by weswigham** [comment] 2019-03-18 18:28
> @weswigham — do you know if its possible to replace the autogenerated dependency with * with a dependency upon @types/hoist-non-react-statics with >=3.3.0?

If you explicitly add it in the `package.json` it might work? AFAIK you can't hardcode versions for implied or path-mapping based dependencies, but i could be wrong.

@sandersn know anything more?

**Comment by jamesreggio** [comment] 2019-03-18 18:50
I just opened a PR that includes a specific version of `@types/hoist-non-react-statics` in the `package.json`. Hopefully that works? Certainly couldn't hurt.

@weswigham, do you mind reviewing and giving approval?

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33979

**Comment by wolfy1339** [comment] 2019-03-18 18:53
I don’t know if that is the correct fix. I added a direct dependency on `hoist-non-react-statics@latest` and it fixed all problems.

**Comment by jamesreggio** [comment] 2019-03-18 20:36
Ugh, @weswigham + @sandersn — I'm not sure what to do. The Travis build failed because I added a specific versionspec for `@types/hoist-non-react-statics`. See the error [here](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/508027399?utm_source=github_status&utm_medium=notification).

It's true that my change to `@types/react-redux` _requires_ a minimum of 3.3.0 of `@types/hoist-non-react-statics`, so I feel like I should be able to express that constraint. Can you help me understand how to do that? (Should I do as the error message says and add it to `dependenciesWhitelist.txt` in `types-publisher`? That seems like too big a hammer.)

**Comment by weswigham** [comment] 2019-03-18 20:38
It's not too big a hammer - your issue is pretty much exactly what the log message describes.

**Comment by jamesreggio** [comment] 2019-03-18 21:45
Cool, I have a PR ready to merge over on `types-publisher`: https://github.com/Microsoft/types-publisher/pull/595

@weswigham — can you land it?

**Comment by sandersn** [comment] 2019-03-18 22:42
It's published as of 3:06 PDT (40 minutes before this comment or so).

**Comment by jamesreggio** [comment] 2019-03-18 23:28
Okay folks, give `@types/react-redux@7.0.5` a try and let me know if you're still broken.

**Comment by wolfy1339** [comment] 2019-03-19 04:53
Still the same problem with `@types/react-redux@7.0.5`. The only fix that has worked for me is to manually require `hoist-non-react-statics` in my project

**Comment by jmussman** [comment] 2019-03-22 00:42
Seconded, still broken in @types/react-redux@7.0.5.

**Comment by wolfy1339** [comment] 2019-03-22 01:31
@jamesreggio @weswigham I'm not sure if you have seen the comments but pinging you so we're sure you have seen it

**Comment by jmussman** [comment] 2019-03-22 03:03
Yes, thanks, I had. I was teaching React this afternoon at Cisco when this bit the class. After a quick check and I found this thread I had them back down to 7.0.1 and it worked OK. But, I have some slight weirdness. If I add hoist-non-react-statics it works, as described above. If I uninstall hoist-non-react-statics it continues to work. So maybe there is a real dependency that gets picked up there, but sticks around even if you remove that package. If I clear out node_modules and package-lock.json and reinstall without hoist, it's broken again. I have to get out of here now, so I can't spend anymore time on it right now trying to dig deeper. Somebody else might find it faster anyways being more in tune with the package.

**Comment by jamesreggio** [comment] 2019-03-22 04:00
I’m going to dig into this again tomorrow, but honestly, I need some help
from an expert. The intricacies of the TS module system baffle me. I feel
like I’ve done everything correctly here...

Can those of you who are having the problem please paste a gist of your
package-lock.json or yarn.lock? I feel like this may be a problem related
to the unusual fact that hoist-non-react-statics included its own typings
for a short period in the past.

**Comment by wolfy1339** [comment] 2019-03-22 04:05
Here's my `package-lock.json`: https://github.com/hellomouse/GNS/blob/greenkeeper/default/%40types/react-redux-7.0.5/package-lock.json

**Comment by jmussman** [comment] 2019-03-22 13:32
Hi James,

OK I understand what is wrong in my class project. I don't know how to fix it, yet. But, I'm going to put out what I know, and maybe somebody at Definitely Typed might be able to help you.

react-router is installed before react-redux by the previous lab. The current version of react-router (up until 4 days ago) was 4.3.1, and has a dependency on hoist-non-react-statics@2.2.5. So, under the rules since nobody else had any dependency on hoist-non-react-statics the package was installed at the top level of node_modules. Now react-redux@6.0.1 is installed. It depends on hoist-non-react-statics@3.3.0. But, since 2.2.5 is already at the top level, it puts 3.3.0 in the node_modules folder UNDER react-redux. So it appears that the dependency in @types/react-redux of @types/hoist-non-react-statics@3.3.0 doesn't find it because it's not at the top level. Those rules I haven't dug into yet, but someone else may be able to pin that down right away.

Other folks issues described earlier may be very similar to this scenario.

Related question: how are we supposed to know which version of @types/react-redux maps to which version of react-redux? Since the numbers don't line up, I'm lost there.

**Comment by wolfy1339** [comment] 2019-03-22 16:42
I've made a PR to fix this issue #34090

**Comment by maracuja-juice** [comment] 2019-03-29 16:38
Shouldn't this issue be reopened as the underlying problem isn't fixed yet with version 7.0.5?

**Comment by ee0pdt** [comment] 2019-04-02 09:45
100% agree this should not be closed, still broken unless you manually add to devDependancies

**Comment by wolfy1339** [comment] 2019-04-02 17:27
I have filed the proper fix that the people here have seemed to ignore since the beggining: #34406

**Comment by maracuja-juice** [comment] 2019-04-04 19:53
So now that the PR is merged the react-redux types has to update the dependency on hoist-non-react-statics?

**Comment by wolfy1339** [comment] 2019-04-04 20:01
I think so. But i think you can get away with removing the dependency (uninstall it), and re-adding it
________________________________

**Comment by maracuja-juice** [comment] 2019-04-04 20:20
You mean the react-redux typings? I'll try that.

**Comment by OliverJAsh** [comment] 2019-04-05 09:25
@wolfy1339 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34406 didn't seem to fix the issue for me. I think this is because `hoist-non-react-statics` will be installed inside of `@types/hoist-non-react-statics` (`node_modules/@types/hoist-non-react-statics/node_modules/hoist-non-react-statics`), so TS still uses the types from my root version (`node_modules/hoist-non-react-statics`).

**Comment by wolfy1339** [comment] 2019-04-05 13:02
At this point it was worth the try. Anyone else have an idea?

**Comment by maracuja-juice** [comment] 2019-04-05 13:45
@weswigham Can you reopen this issue?

**Comment by alan-mroczek** [comment] 2019-04-12 09:16
Had similar issue - using yarn instead of npm to install dependencies resolved my issue. Posting as a side note because maybe you guys can give it a try as a workaround.

**Comment by maracuja-juice** [comment] 2019-04-12 09:28
@alan-mroczek We use yarn so no this doesn't help. There must be something else at play here. (lock file?)

**Comment by timmywil** [comment] 2019-04-13 19:31
I don't know if I understand the exact issue, but the solution that worked for me with yarn was to add a resolutions field to package.json.

```
"resolutions": {
  "hoist-non-react-statics": ">=3.3.0"
}
```

**Comment by gitowiec** [comment] 2019-04-29 15:56
This problem is still active for `"@types/react-redux": "7.0.8",` and setting "resolutions" is not an universal solutions because "resolutions" don't work in monorepo (yarns workspaces)

**Comment by maracuja-juice** [comment] 2019-04-29 16:29
And I don't expect it to be the solution anyway. In my opinion the @types package after it is installed should "just work"

**Comment by wolfy1339** [comment] 2019-04-29 16:44
Could the solution to this whole ordeal be to add it as a peer dependency? Sure it's not foolproof, but it's the only way to guarantee that typescript finds the required dependency

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by krazyjakee** [comment] 2019-05-02 08:52
Tried many things, downgrading to @types/react-redux 7.0.1 is still the only fix that works at the moment.

**Comment by jfbrazeau** [comment] 2019-05-02 11:31
The same for me ! But I hope a real fix will come one day (keeping this outdated dependency is odd !).

**Comment by schmod** [comment] 2019-05-06 14:47
I think we need to do the same thing as #34406 in the react-redux typings, as NPM & Yarn aren't necessarily going to put the "correct" version of `hoist-non-react-statics` in the directory above `@types/react-redux`.  

This is a really gnarly solution (and could theoretically be mitigated if TypeScript would allow us to import `@types/hoist-non-react-statics/index.d.ts` directly, but I'm not seeing any reasonable alternatives.

**Comment by alessioprestileo** [comment] 2019-05-10 11:10
> I think we need to do the same thing as #34406 in the react-redux typings, and just add a direct dependency on `hoist-non-react-statics`, as NPM & Yarn aren't necessarily going to put the "correct" version of `hoist-non-react-statics` in the directory above `@types/react-redux` (which will cause TS to grab v2.5's built-in `index.d.ts` if it's there)
> 
> This is a really gnarly solution (and could theoretically be mitigated if TypeScript would allow us to import `@types/hoist-non-react-statics/index.d.ts` directly, but I'm not seeing any reasonable alternatives (and basically anybody else who depends on `@types/hoist-non-react-statics` is going to need to do the same)

What about importing from '../hoist-non-react-statics'?
As far as I see the package '@types/hoist-non-react-statics' is automatically installed when '@types/react-redux' is installed, so there should be no risk of it missing.
I attached 2 files to show a solution that works for me.

[hoist-non-react-statics_index.d.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/3166179/hoist-non-react-statics_index.d.txt)
[react-redux_index.d.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/3166180/react-redux_index.d.txt)

**Comment by schmod** [comment] 2019-05-10 14:57
Given the way that npm works, we can't guarantee that the `hoist-non-react-statics` typings will be in a sibling directory of `react-redux`.  Depending on what other dependencies the user has installed, it it could be a grandparent, or it could be a child.

**Closed** 2019-05-13 22:17 UTC

**Comment by jefflewis** [comment] 2019-06-05 21:33
This is still broken for me. My `export default connect()(MyComponent)` is given an `any` type. Going back to `7.0.1` fixes this part... This appears to be a change in `7.0.2`.

**Comment by Intregrisist** [comment] 2019-06-12 18:12
As of 7.1.0 I am still experiencing this issue:
```
Type error: Namespace '"/.../node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.  TS2694
```

**Comment by s-h-a-d-o-w** [comment] 2019-06-14 09:29
Still happens with `7.1.0` and downgrading to `7.0.1` isn't an option for us because we need TS `3.5.2` (with TS `3.4.5`, `7.0.1` does work) and with that, we get:
```
node_modules/@types/react-redux/index.d.ts:109:84 - error TS2344: Type 'GetProps<C>' does not satisfy the constraint 'Shared<TInjectedProps, GetProps<C>>'.
  Type 'unknown' is not assignable to type 'Shared<TInjectedProps, GetProps<C>>'.
```

**Comment by tsakalidiskostas** [comment] 2019-06-27 08:08
So, any.. workarounds? I am not an expert on the subject, so I can't understand what I need to do with this.

**Comment by s-h-a-d-o-w** [comment] 2019-06-27 08:42
@tsakalidiskostas 

Well, we decided that we will commit a modified version of the `react-redux` types to our repo. (After deciding against using [patch-package](https://github.com/ds300/patch-package). Which can be an alright temporary solution if you don't mind the necessary yarn workaround.)

Where we simply change the following line:
```js
> = ComponentClass<JSX.LibraryManagedAttributes<C, P>> & hoistNonReactStatics.NonReactStatics<C> & {
```
to:
```js
> = ComponentClass<JSX.LibraryManagedAttributes<C, P>> & {
```

Since we don't use statics, it doesn't hurt us but that may of course not be an acceptable solution for everyone.

**Comment by tsakalidiskostas** [comment] 2019-06-27 09:57
Cool! I went with @alessioprestileo 's suggestion of changing 
`import hoistNonReactStatics = require('hoist-non-react-statics');` 
for 
`import { NonReactStatics } from '../hoist-non-react-statics';` 
and changing the call to 
`> = ComponentClass<JSX.LibraryManagedAttributes<C, P>> & NonReactStatics<C> & {`
and it worked for me as well, was actually just heading to update when I saw your answer :D

**Comment by deser** [comment] 2019-06-27 10:23
So would you publish new version in npm with fixes?:)

**Comment by schmod** [comment] 2019-06-27 11:41
Can we just get the maintainers of hoist-non-react-statics to check the typings back into their repo?

**Comment by tsakalidiskostas** [comment] 2019-07-01 06:52
So.. is this happening or should I go forward with a fork change on that?

**Comment by cornr** [comment] 2019-07-05 09:55
Hi there. We also updated to the latest `7.1.1` of `@types/react-redux` version with `react-redux`: `7.1.0` and we are seeing this error with npm. I'm confused since all tickets referring to this are closed.
A downgrade to `7.0.1` does fix this problem but causes a new problem if we use the latest Typescript Version `3.5.x`:

```
/.../node_modules/@types/react-redux/index.d.ts(109,84): error TS2344: Type 'GetProps<C>' does not satisfy the constraint 'Shared<TInjectedProps, GetProps<C>>'.
  Type 'unknown' is not assignable to type 'Shared<TInjectedProps, GetProps<C>>'.
    Type 'Matching<TInjectedProps, GetProps<C>>' is not assignable to type 'Shared<TInjectedProps, GetProps<C>>'.
      Type 'P extends keyof TInjectedProps ? TInjectedProps[P] extends GetProps<C>[P] ? GetProps<C>[P] : TInjectedProps[P] : GetProps<C>[P]' is not assignable to type 'TInjectedProps[P] extends GetProps<C>[P] ? GetProps<C>[P] : never'.
```
making it a kinda sad workaround.

**Comment by weswigham** [comment] 2019-07-05 18:57
There's a latest version (ie, `7.1.1`) of `@types/react-redux` [do not use `Shared<TInjectedProps, GetProps<C>>` as a constraint](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts#L98) (precisely because of that fix in TS that pointed out that the constraint was incorrect) - you have another library which is forcing a nested include of an older version of the `react-redux` types, I think.

**Comment by tsakalidiskostas** [comment] 2019-07-05 22:23
So, I have the workaround. It is called "patch package". 

If you haven't used patch package before it is actually quite easy! You simply add it to your config, npm install it, then you just hit a patch package command on the changed module you have fixed and is working and voila. Now you have a few module that resides under patch package that has only the changed files of the module you was fixing, nothing too fancy or too big etc.. The error is fixed, the dependency is not lost, so when / if they fix it you can easily just delete one or two files and it is all fine

**Comment by bocong** [comment] 2019-07-12 17:10
Wondering why this issue was closed, since it seems like this is a problem for many (if not all) of us.

**Comment by jalMogo** [comment] 2019-07-17 04:49
I can confirm that installing `hoist-non-react-statics` resolves this error for `react-redux` 7.1.0 and `@types/react-redux` 7.1.1 I'm using Typescript 3.4.3 as well.

I don't know why this issue is closed, however. Is there a more reasonable solution, without having to patch the package or override the module resolutions tree?

**Comment by ericmasiello** [comment] 2019-08-05 00:35
I'm having the same issue as @jalMogo

**Comment by CommerceOwl** [comment] 2019-08-12 12:35
Still seeing this issue.

**Comment by local-minimum** [comment] 2019-08-12 13:02
@jalMogo as far as I understand it, this is not an issue with redux, but with hoist-non-react-statics and that's why the issue is closed here. There are multiple workarounds in the thread, but better would be if someone skilled enough gave the hoist-people a fix.

**Comment by jmussman** [comment] 2019-08-12 18:13
I disagree that it is an issue with hoist-non-react-statics. It is an issue with the description of redux, in that it ends up looking at the older and wrong version of hoist-non-react-statics if it exists in the node_modules tree, which it does when some other stuff like the router is installed. The dependency needs to be described properly and the new version properly installed closer in the node_modules tree.

**Comment by TheFragen** [comment] 2019-09-16 10:49
This is still an issue.

**Comment by ericmasiello** [comment] 2019-09-16 12:37
+1

**Comment by SweRavn** [comment] 2019-10-20 05:43
I'm still getting this issue and the lint says there is an error in the code. Is anyone still working on this or is it considered closed? I have all the latest versions installed and still get:

Namespace '"/home/myhome/Projects/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.ts(2694)

**Comment by wolfy1339** [comment] 2019-10-20 05:46
This is definitely an issue on their part. Workaround: `@types/hoist-non-react-statics` should be listed as a dependency in YOUR project for it to work

**Comment by SweRavn** [comment] 2019-10-20 05:50
But i have that, and still get the issue:
"dependencies": {
...
  "@types/hoist-non-react-statics": "^3.3.1",

is in my package.json

**Comment by wolfy1339** [comment] 2019-10-20 06:34
My bad. You need `hoist-non-react-statics`
________________________________

**Comment by arendjr** [comment] 2019-11-08 09:46
I have `"hoist-non-react-statics": "^3.3.0"` in my dependencies and `"@types/hoist-non-react-statics": "^3.3.1"` in my devDependencies and I still have the problem myself as well. I have confirmed no other libraries are pulling in older versions of these either.

**Comment by JounQin** [comment] 2019-11-08 10:48
Anyone facing this problem should provide a runnable reproduction, otherwise we can now offer any help.

**Comment by arendjr** [comment] 2019-11-08 11:36
I'm sorry, the project I'm experiencing this is not open-source and I do not have the time to create a separate project to showcase it. What I did notice however is the project had no issues until I enabled `allowJs: true` in the `tsconfig.json`. Without this setting, everything worked fine still. Hope it helps.

**Comment by ericblade** [comment] 2019-12-21 02:41
adding the 'hoist-non-react-statics' seems to have fixed it here.

repro is just installing @types/react-redux and then importing anything in react-redux in a tsx file.

**Comment by MihailShev** [comment] 2019-12-28 14:44
One way to fix this issue is to add "skipLibCheck": true in tsconfig.json. It isn`t the best solution, but as a workaround, it may be used.

**Comment by hedgepigdaniel** [comment] 2020-01-14 08:41
I think this happens because typescript resolves things in this order:
 1. `package/package.json[types]`
 1. `@types/package`
 1. `package` (everything except the `types` field)

Why it does that is a mystery to me, but its documented here: https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules

So for example, if you have the following directory structure: 
```
node_modules/
  @types/
    hoist-non-react-statics/ (3.3.0)
    react-redux/
      node_modules/
        hoist-non-react-statics/ (3.3.0)

  hoist-non-react-statics/
    package.json (2.0, which has a types field!!!)
    index.d.ts
```

Then typescript will do the following:
 1. fail to get types from `node_modules/@types/react-redux/node_modules/hoist-non-react-statics` because the current version does not include types
 1. succeed in finding types from  `node_modules/hoist-non-react-statics` (the old version) because its `package.json` has a `types` field

hence as others have mentioned you can fix the problem by adding a dependency in your project on the latest `hoist-non-react-statics`, because that doesn't have a `types` field in `package.json` so it makes step 2 fail.

Ironically, you can also fix it by adding a dependency in your project on an older `hoist-non-react-statics`, e.g. 3.0.0. This works because it forces the correct version (3.3.0) to be installed in  `node_modules/@types/react-redux/node_modules/types/hoist-non-react-statics`, where it is resolved earlier :confounded: 

So I have two questions:
1. Why does typescript treat the `types` field specially in this way, and it comes before or after `@types` packages depending on whether t the `types` field is used or not?
1. If `hoist-non-react-statics` once had built in types, why did they get renegaded to here? This wouldn't be a problem if the types were built into package. I can't see how yarn/NPM can properly deal with separate packages for code and types seeing as they don't know how the two are connected.

**Comment by DannyDelott** [comment] 2020-02-03 19:51
This issue seems to have resurfaced with the latest package versions, ie:

`react-redux@7.1.3`
`@types/react-redux@7.1.7`


I was able to resolve this by manually including the following packages in my `package.json`:

```
hoist-non-react-statics@3.3.2
@types/hoist-non-react-statics@3.3.1
```

Because the `hoist-non-react-statics` packages after my initial `npm install` there were duplicates of these packages in my `node_modules` folder. Running `npm dedupe` cleared that up.

Hope that helps anyone else who comes along!

**Comment by GamesOfSummer** [comment] 2020-05-19 19:00
I got it as well - praise be to @DannyDelott 's solution!

**Comment by johanazhu** [comment] 2020-05-22 05:42
I had this issue as well - praise be to @DannyDelott 's solution!

**Comment by yousifalraheem** [comment] 2020-06-01 10:12
Quickest solution for now without polluting your `package.json` with dependencies you don't directly need is to remove `@types/react-redux`
```terminal
npm remove @types/react-redux
```

**Comment by enrique-ramirez** [comment] 2020-08-14 12:13
Issue is still happening and the only way to fix this is to add the mentioned dependencies to your project. This is not ideal, though, so hopefully we'll get a fix soon!

**Comment by OctoD** [comment] 2020-10-19 13:27
Still noticing this issue. 

For anyone willing to keep developing while a stable fix will be live, you can use the typedef below:

```ts
// [your-src-folder]/types/hoist-non-react-statics.d.ts

declare module 'hoist-non-react-statics' {
  type NonReactStatics<T> = any;
  export { NonReactStatics }
}
```

**This it's not the ideal solution, but at least is useful for avoiding build errors with TS**

**Comment by matthieugicquel** [comment] 2020-11-24 09:34
Just adding a message here so that other people can find it: a similar issue happened to us with styled-components (in a React Native app).

All the styled-components were typed as any with the error indicated here not visible anywhere.

Adding @types/hoist-non-react-statics and hoist-non-react-statics (^3.3.0) explicitly to package.json fixed it.
