### ISSUE TITLE
Generic type 'JQuery<TElement, HTMLEle ment>' requires 2 type argument(s).

### ISSUE THREAD

**Issue by AbinayaSubbiah** [DefinitelyTyped/DefinitelyTyped#19052] opened 2017-08-17 06:36 UTC
I tried using the `@types/jquery` [version 3.2]package and facing below issues from jquery file.

`ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (69,18): Generic type 'JQuery<TElement, HTMLEleme
nt>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (119,89): Generic type 'JQuery<TElement, HTMLElem
ent>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (128,63): Generic type 'JQuery<TElement, HTMLElem
ent>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (128,84): Generic type 'JQuery<TElement, HTMLElem
ent>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (147,101): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (149,65): Generic type 'JQuery<TElement, HTMLElem
ent>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (704,45): Generic type 'JQuery<TElement, HTMLElem
ent>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (2955,11): All declarations of 'JQuery' must have
 identical type parameters.
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (2991,87): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3020,84): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3032,118): Generic type 'JQuery<TElement, HTMLEl
ement>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3136,85): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3147,119): Generic type 'JQuery<TElement, HTMLEl
ement>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3156,90): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3194,85): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3206,119): Generic type 'JQuery<TElement, HTMLEl
ement>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3349,51): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3356,17): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3716,70): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3727,48): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3920,49): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3969,93): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3978,94): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (3993,66): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4241,54): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4254,67): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4582,57): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4598,86): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4609,120): Generic type 'JQuery<TElement, HTMLEl
ement>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4618,91): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4647,54): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4817,42): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (4828,49): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (5336,75): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (5336,129): Generic type 'JQuery<TElement, HTMLEl
ement>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (5349,78): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (5349,117): Generic type 'JQuery<TElement, HTMLEl
ement>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (5362,80): Generic type 'JQuery<TElement, HTMLEle
ment>' requires 2 type argument(s).
ERROR in E:/Incident sample/185508/ejproject/node_modules/@types/jquery/index.d.ts (5362,134): Generic type 'JQuery<TElement, HTMLEl
ement>' requires 2 type argument(s).`

**Comment by leonard-thieu** [comment] 2017-08-17 12:51
Update TypeScript to the most recent version.

**Comment by lweberk** [comment] 2017-08-17 20:16
Same here with typescript 2.4.2. Is that version not supposed to be the latest stable to date?

**Comment by leonard-thieu** [comment] 2017-08-17 21:05
Are you getting this message in Visual Studio or by running `tsc` directly?

**Comment by lweberk** [comment] 2017-08-17 21:44
With the official sublime text typescript plugin. I checked directly with tsc and it does not throw any errors. Makes me wonder whether i'm digging at the wrong place.

**Comment by lweberk** [comment] 2017-08-17 21:53
Found the issue. It was plugin-related. The plugin did not get the default system path to the typescript sdk, thus reverting to 1.* feature set and consequently not correctly running as it would have from the CLI.

**Comment by leonard-thieu** [comment] 2017-08-17 21:56
Glad you figured it out. Thanks for reporting back on your solution.

**Comment by AbinayaSubbiah** [comment] 2017-08-18 05:56
@leonard-thieu  installed jQuery in my angular cli sample and getting this error message in Visual Studio code

**Comment by leonard-thieu** [comment] 2017-08-18 17:52
@AbinayaSubbiah could you post a minimum repro?

**Comment by lweberk** [comment] 2017-08-21 12:00
@AbinayaSubbiah My case was for sublime text 3 running in a Debian (stretch) OS setup. Possibly quite different from your setup. In any case, the st3 plugin has an option to specify the path to the typescript libraries; `typescript_tsdk`, which in my case had to explicitly point to `/usr/lib/nodejs/typescript/lib`, since I'm using the Debian packaged versions of typescript (not npm install). The interesting thing to note is that instead of outright failing, typescript reverts to its 1.x feature set when unable to figure out where its library is... for whatever reason. That caused the errors to pop up. Maybe there is something similar in the VisualStudio-Typescript integration setup?

**Comment by LukeTOBrien** [comment] 2019-07-01 19:39
This is still an open issue.  
I have found the only workarround is to downgrade your `@types/jquery`.

> It seems to be an issue with @types/datatables.net. I think the current version of datatables.net typings (1.10.5) is still not compatible withe the latest version of jquery typings (3.2.10).  
> For now, you can force the version of @types/jquery to 2.0.46.  
[Source](https://www.bountysource.com/issues/47309144-error-with-generic-type-jquery-telement-htmlelement-requires-2-type-arguments)

However this also causes errors in other parts of my code.  
Could someone take a look at resolving this please. ;-)

**Comment by leonard-thieu** [comment] 2019-07-02 14:53
> This is still an open issue.
> I have found the only workarround is to downgrade your `@types/jquery`.
> 
> > It seems to be an issue with @types/datatables.net. I think the current version of datatables.net typings (1.10.5) is still not compatible withe the latest version of jquery typings (3.2.10).
> > For now, you can force the version of @types/jquery to 2.0.46.
> > [Source](https://www.bountysource.com/issues/47309144-error-with-generic-type-jquery-telement-htmlelement-requires-2-type-arguments)
> 
> However this also causes errors in other parts of my code.
> Could someone take a look at resolving this please. ;-)

I'm unable to reproduce the error (https://github.com/leonard-thieu/DefinitelyTyped-issue-19052).

Could you post a minimal repro?

**Comment by orta** [comment] 2021-06-07 13:23
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:23 UTC
