### ISSUE TITLE
react-redux: mapDispatchToProps cannot be undefined

### ISSUE THREAD

**Issue by jens-duttke** [DefinitelyTyped/DefinitelyTyped#16192] opened 2017-04-28 07:23 UTC
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @thasner, @tkqubo

With version 4.4.40 a change of the type definition has been introduced, which breaks the functionality of connect().

Regarding the react-redux documentation:
> If you don't want to subscribe to store updates, pass null or undefined in place of mapStateToProps.
see https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

But this doesn't work in version 4.4.40 of the type definition, `undefined` results in the error:
```
TS2345: Argument of type 'MapStateToProps<TStateProps, TOwnProps> | (() => MapStateToProps<TStateProps, TOwnProps>) | undef...' is not assignable to parameter of type 'MapStateToPropsParam<TStateProps, TOwnProps>'.
      Type 'undefined' is not assignable to type 'MapStateToPropsParam<TStateProps, TOwnProps>'.
```

**Comment by thasner** [comment] 2017-04-28 12:37
can you share your code or an example?

**Comment by jens-duttke** [comment] 2017-05-02 08:16
This is an example which works in 4.4.39, but not in 4.4.40:
```
const mapStateToProps = (state) => ({
	foo: state.foo
});

const mapDispatchToProps = undefined;

export default connect<{ foo: string }, {}, {}>(mapStateToProps, mapDispatchToProps);
```

**Comment by thasner** [comment] 2017-05-02 13:27
@jens-duttke this compiles for me.
(With `no-implicit-any`, it complains about `const mapDispatchToProps = undefined;` implicitly being `any`.)

Why are you specifying a second `undefined` argument to `connect`? You can omit it.

Also, you should define unused generic types as `void` instead of `{}`. `{}` accepts objects with arbitrary properties.

**Comment by jens-duttke** [comment] 2017-05-10 10:17
@thasner: The example code from my comment is just a minimalistic version to show the problem.
Since, regarding the Redux documentation, the value can be undefined, the type definition should consider that too, no matter if my minified example follows all best practices.
The real code has a bit more logic and functionality, where it may make sense to use a variable/constant which can have undefined as value.

**Comment by mikew** [comment] 2017-05-10 23:52
@thasner TypeScript still complains if you omit the second argument, which is valid in react-redux. This is with and without `no-implicit-any`.

**Comment by mikew** [comment] 2017-05-11 01:19
I'm not sure if I'm missing something huge, but this covers my bases:

```typescript
export declare function connect<TOwnProps, TStoreShape>(
    mapStateToProps: MapStateToPropsWithoutDispatch<TOwnProps, TStoreShape>
): InferableComponentDecorator<TOwnProps>;

export interface DispatchProps {
    dispatch: Dispatch<any>;
}

interface MapStateToPropsWithoutDispatch<TOwnProps, TStoreShape> {
    (state: TStoreShape, ownProps?: TOwnProps): TOwnProps;
}
```

Then it can be used like:

```tsx
import { DispatchProps } from 'react-redux'

// This would be defined elsewhere in your application.
interface StoreShape {
  myReducer: {
    foo: string;
  }
}

// Define your component's props.
interface MyComponentProps {
  foo: string;
  someOptionalProp?: string;
}

// A basic example.
@connect<MyComponentProps, StoreShape>(state => ({
  foo: state.myReducer.foo
}))
export class MyComponent extends React.Component<MyComponentProps & DispatchProps, {}> {
  render () {
    this.props.dispatch(actions.myAction())
    return <div>{this.props.foo}</div>
  }
}

// This is a bit of a smell, having to re-hint the type of ownProps.
// This is because in order to make ownProps optional, its type is:
//     TOwnProps | undefined
@connect<MyComponentProps, StoreShape>((state, ownProps: MyComponentProps) => ({
  foo: state.myReducer.foo,
  someOptionalProp: ownProps.someOptionalProp
}))
export class MyComponent extends React.Component<MyComponentProps & DispatchProps, {}> {
  render () {
    this.props.dispatch(actions.myAction())
    return <div>{this.props.foo} {this.props.someOptionalProp}</div>
  }
}
```

**Comment by thasner** [comment] 2017-05-16 15:21
> The example code from my comment is just a minimalistic version to show the problem.

@jens-duttke as I said, this compiles for me, so I can't reproduce the problem.

What version of Typescript are you using? Do you have `strictNullChecks` enabled? Perhaps the problem is that you've specified the `mapDispatchToProps` type parameter as `{}` and are trying to pass it `undefined`?

**Comment by orta** [comment] 2021-06-07 13:25
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:25 UTC
