### ISSUE TITLE
express() function and express namespace ambiguity

### ISSUE THREAD

**Issue by ziyaddin** [DefinitelyTyped/DefinitelyTyped#37920] opened 2019-08-26 09:22 UTC
- [x] I tried using the `@types/express` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov 

Problem: When I try the following code sample:

```ts
import express from 'express';

const app = express();

app.get('/', (request, response) => {
  response.send('Hello world!');
});

app.listen(5000);
```
and after that run `tsc`:

```sh
npx tsc file.ts
```
I get the following error:

> Module '...' can only be default-imported using the 'esModuleInterop' flag

> This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

If I try to import `express` via non-default import method, I get TS errors:

![image](https://user-images.githubusercontent.com/1016523/63680279-556ad580-c804-11e9-85ca-0b1ff7603877.png)

> Cannot invoke an expression whose type lacks a call signature. Type 'typeof e' has no compatible call signatures.ts(2349)

> file.ts(1, 1): Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

I think there is an ambiguity between namespace `express` and function `express()`.

What about isolating them in export part?

**Comment by 1478773579** [comment] 2019-08-30 09:42
you shuold try  'require' express not import

**Comment by smichel17** [comment] 2020-09-09 16:46
I'm pretty sure this issue is present in plain js, and this change would result in compiled js that crashes at runtime; so, it's a good thing that the compiler warns you about it. The issue is that CommonJS (node)'s `require()` has different semantics than ES2015 modules' `import *`

- `require()` can return a function (which may also have other properties)
- `import` will always return just a plain object
    - `import * as` lets you give that object a name, or you can destructure it with `import { }`
    - Default exports/imports are actually just syntactic sugar
        - `export default foo` is shorthand for `export foo as default`
        - `import x from "foo"` is shorthand for `import { default as x } from "foo"`

Express uses CommonJS semantics, and does not make the `createApplication` function available as a property, so you *can't* access it directly using `import`.

Typescript can handle this in two ways. Documentation and details are in [the handbook](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) and https://github.com/Microsoft/TypeScript/issues/7185#issuecomment-354566288. I recommend the first, since it's more explicit:

1. Change your first line to `import express = require('express');`
2. Add  `"esModuleInterop": true,` to your `tsconfig.json`'s `compilerOptions` and use `import express from 'express';`

**Comment by ziyaddin** [comment] 2020-09-09 17:27
@smichel17 thanks for explanation!

**Comment by jcagz96** [comment] 2020-09-14 15:21
I resolved that runninh the next commands:

1º 
`yarn tsc --init`

2º
`yarn tsc`

**Comment by orta** [comment] 2021-06-07 14:08
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:08 UTC
