### ISSUE TITLE
[@types/react-native] Error when using valid StyleSheet style on `<Image />`

### ISSUE THREAD

**Issue by IljaDaderko** [DefinitelyTyped/DefinitelyTyped#29651] opened 2018-10-11 12:51 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @skn0tt @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk @mvdam @esemesek

---

Using valid style created by StyleSheet.create on imaghe results in following typescript error

> [ts]
> Type 'RegisteredStyle<ViewStyle | TextStyle | ImageStyle>' is not assignable to type 'StyleProp<ImageStyle>'.
>   Type 'RegisteredStyle<ViewStyle | TextStyle | ImageStyle>' is not assignable to type 'RecursiveArray<false | ImageStyle | RegisteredStyle<ImageStyle> | null | undefined>'.
>     Property 'length' is missing in type 'Number & { __registeredStyleBrand: ViewStyle | TextStyle | ImageStyle; }'.
> index.d.ts(3750, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<{ children?: ReactNode; }> & Readonly<ImageProps>'
> (JSX attribute) style?: StyleProp<ImageStyle>
> Style

Can be reproduced via

```js
import * as React from 'react';
import { Image, StyleSheet } from 'react-native';

/**
 * Component
 */
class GameHeaderBar extends React.Component<{}> {
  render() {
    return <Image style={styles.barImg} source={{ uri: 'game_header_bar' }} />;
  }
}

export default GameHeaderBar;

/**
 * Styles
 */
const styles = StyleSheet.create({
  barImg: {
    position: 'relative',
    zIndex: 2
  }
});
```

I started getting this issue after upgrading `@types/react-native@0.56.24` to `@types/react-native@0.57.4`

**Comment by IljaDaderko** [comment] 2018-10-12 06:33
@zhigang1992 Your workaround does the trick 👍 but as you are experiencing similar behaviour I'm more confident that there is an issue now.

**Comment by Esemesek** [comment] 2018-10-12 15:55
Duplicate of #29265

**Closed** 2018-10-12 16:14 UTC
