### ISSUE TITLE
[React] React.FC doesn't allow bare return of children

### ISSUE THREAD

**Issue by dontsave** [DefinitelyTyped/DefinitelyTyped#33006] opened 2019-02-12 18:34 UTC
in "@types/react": "^16.8.2"

this works:
```
export class Test extends React.PureComponent<void, void> {
	render() { 
		return this.props.children;
	}
}
```

but this doesn't work:

```
export const Test:React.FC<void> = p => {
	return p.children;
};
```

seems like the functional component should allow bare return of children just as the class component does. Perhaps a mismatch between the `ReactNode` and `ReactElement` types?

**Comment by richsilv** [comment] 2019-02-13 15:16
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544

As a workaround, you can wrap the children in a Fragment.

**Comment by mgmolisani** [comment] 2019-02-13 23:13
Just got into Typescript and this was what happened to me in the _first_ component I wrote. Render in Component type is of return type ReactNode. This should be identical in my mind but instead it forces an ReactElement return or null. Very odd behavior.

**Comment by jochienabuurs** [comment] 2019-04-12 14:02
I would expect the definition below:
```
type PropsWithChildren<P> = P & { children?: ReactNode };
...
interface FunctionComponent<P = {}> {
        (props: PropsWithChildren<P>, context?: any): ReactElement | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```
to be:
```
type PropsWithChildren<P> = P & { children?: ReactNode };
...
interface FunctionComponent<P = {}> {
        (props: PropsWithChildren<P>, context?: any): ReactNode | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```

**Comment by chancegraff** [comment] 2019-09-29 17:57
Another option is to cast your child as a `ReactElement`.

```

const Example: React.FC = (props) => {
  const {
    children,
  } = props;

  return children as React.ReactElement;
};
```

**Comment by ValentinH** [comment] 2019-10-06 20:40
as @mgmolisani mentioned, this is very confusing for newcomers: 
![image](https://user-images.githubusercontent.com/2678610/66275569-27a89000-e88a-11e9-8fb3-ac79b45b9f69.png)

When you are just starting to integrate TS to a React app, this hurts you pretty fast and at first, you are just lost. 😢

**Comment by mgmolisani** [comment] 2019-10-06 20:46
> as @mgmolisani mentioned, this is very confusing for newcomers:
> ![image](https://user-images.githubusercontent.com/2678610/66275569-27a89000-e88a-11e9-8fb3-ac79b45b9f69.png)
> 
> When you are just starting to integrate TS to a React app, this hurts you pretty fast and at first, you are just lost. 😢

Had this not been an open source project I was contributing to, I would have dropped TS immediately for being inaccurate on such a simple case and forcing me to wrap in a fragment. Casting is an option but leads to questions and ignoring the error wasn't an option because of the linter settings and CI. Been a while since I looked at this but definitely affected TS adoption for me.

**Comment by FredyC** [comment] 2020-04-10 06:17
I just want to share my two cents with the approach I chose for my project instead of relying on built-in types. It's definitely not a full-fledged solution, but sufficient for all my use cases. I especially like it requires me to be explicit about specifying a type of `children`, even if it is `never`.

Furthermore, this also works great with returning `children` because they use the correct type. Note the use of the built-in `Required` type.

https://gist.github.com/FredyC/3aba908bb0894b83dc25cf1a02d1928d

**Comment by eps1lon** [comment] 2020-08-13 12:49
This is essentially a duplicate of #18912. Once  Microsoft/TypeScript#21699 is resolved we should be able to use `ReactNode` as a valid return type for function components which includes `string` and `boolean`.

**Comment by orta** [comment] 2021-06-07 13:38
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:38 UTC
