### ISSUE TITLE
@types/winston - unable to log Error

### ISSUE THREAD

**Issue by lebesnec** [DefinitelyTyped/DefinitelyTyped#18220] opened 2017-07-19 15:36 UTC
- I tried using the `@types/winston` package and had problems.
- Authors: @bonnici @codeanimal @DABH

If you add the types for Winston, you can't no longer log Error.

```
let err:Error= new Error('ttdt');
logger.error(err);
```
=> does not compile

```
let err:any = new Error('ttdt');
logger.error(err);
```
=> actually log the error

It's not just Error by the way, the winston modules allow to log any type of object, for example:

```
let err:any = {a:1};
logger.error(err);
```

**Comment by DABH** [comment] 2017-08-20 20:54
Can you please provide a complete minimum example that doesn't compile?  I have a file test.ts with the contents
```typescript
import winston = require('winston');

let logger:any = winston;
let err:Error = new Error('ttdt');
logger.error(err);
```
and when I run `tsc test.ts && node test.js` I get the output
```
error:  Error: ttdt
    at Object.<anonymous> (/home/dabh/winston_test/test.js:4:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```
which I believe is the correct output (it's the exact same output I get if I declare `err` as `any` rather than `Error`).  It definitely compiles at least.  My `package.json` looks like
```json
{
  "engines": {
    "node": ">=7.8.0"
  },
  "dependencies": {
    "@types/es6-promise": "0.0.32",
    "@types/winston": "*",
    "winston": "*"
  },
  "devDependencies": {}
}
```
and I have no tsconfig.json.  If you can provide a more complete example, hopefully we can track down what's going on!  Or, if it seems to be working for you, we can close the issue.

**Comment by lebesnec** [comment] 2017-08-23 09:57
import * as logger from "winston";

    logger.configure({
        level: 'debug',
    	transports: [
    		new logger.transports.Console({
    			colorize: true
    		})
    	]
    });

    let e:Error= new Error('test');
    logger.error(e);

result : `[ts] Argument of type 'Error' is not assignable to parameter of type 'string'.`

My `package.json` file :

    {
        "dependencies": {
            "winston": "^2.3.1"
        },
        "devDependencies": {
            "@types/node": "6.x.x",
            "@types/winston": "^2.3.3",
            "typescript": "^2.4.1"
        }
    }

my `tsconfig.json` file :

    {
        "compilerOptions": {
            "module": "commonjs",
            "target": "es6",
            "noImplicitAny": true,
            "moduleResolution": "node",
            "sourceMap": true,
            "mapRoot": "dist",
            "outDir": "dist",
            "baseUrl": ".",
            "paths": {
                "*": [
                    "node_modules/*"
                ]
            }
        },
        "include": [
            "src/**/*"
        ]
    }

**Comment by XeniaSiskaki** [comment] 2018-02-09 14:56
What's the progress here? I'm having the exact same issue

**Comment by DABH** [comment] 2018-02-25 23:45
So as far as I can tell this is actually by design.  Following the winston 2.x docs, the first parameter is a message, which is always expected to be a string.  There are 3+ ways around this that might be good enough for you:

1. Winston supports template strings:
    logger.info(`${1}`, e);
2. You can just print the error message, without the stack trace:
    logger.info(e.message);
3. Winston takes a metadata parameter to log an object along with the message (intended to be JSON metadata):
    logger.info('Found the following error: ', e);

Hopefully one of those solutions is good for you.  However, I don't think this is actually an issue with the TS definitions, because even if winston (being a non-typed JS library) allows other things to be logged (I guess anything that can be .toString()'d), I believe the intent of the library is to only allow strings for the message parameter.  Feel free to correct me if you can find anything to the contrary.  Thanks!

**Comment by DABH** [comment] 2018-02-25 23:47
(The same applies for any of the log level methods, like `info`, `error`, etc.)

**Comment by orta** [comment] 2021-06-07 13:22
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:22 UTC
