### ISSUE TITLE
react-router : error TS2339: Property 'exact' does not exist on type 'IntrinsicAttributes 

### ISSUE THREAD

**Issue by pierre-H** [DefinitelyTyped/DefinitelyTyped#15416] opened 2017-03-27 13:32 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkrotoff 

Thank you for your work !

I've got this error when I use the option exact={true} on BrowserRouter with React-Router v4: 
`error TS2339: Property 'exact' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RouteProps, ComponentState>> & { childre...'.`

**Comment by pierre-H** [comment] 2017-03-27 13:52
I had to add `exact?: boolean;` on RouteProps in Route.d.ts in @types/react-router

@sergey-buturlakin
@mrk21
@vasek17
@ngbrown
@awendland
@KostyaEsmukov

**Comment by tkrotoff** [comment] 2017-03-27 14:49
@pierre-H a code snippet would be nice

Also react-router v4 does not have `Route.d.ts`, you are confusing with react-router v3 or v2, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/v3/lib/Route.d.ts
vs
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-router

**Comment by pierre-H** [comment] 2017-03-30 08:01
So we have to create a specific version of types/react-router for v4 ?

**Comment by jish** [comment] 2019-02-27 18:10
I am still seeing this error. Has this issue been resolved, or is there a workaround? 🤔

**Comment by jkoudys** [comment] 2019-07-04 02:24
I experienced this issue myself, and found it was caused by a mismatch between the type version of the @types it was picking up, and the react-router I had installed. I moved to TS recently and it was trying to use the types for v4 Route, but the installed react-router was v3.

**Comment by orta** [comment] 2021-06-07 13:24
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:24 UTC

**Comment by orta** [comment] 2021-06-07 13:26
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
