### ISSUE TITLE
Issue with types in @types/node

### ISSUE THREAD

**Issue by jasonleehodges** [DefinitelyTyped/DefinitelyTyped#44058] opened 2020-04-20 20:59 UTC
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/node` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jkomyno  @a-tarasyuk @r3nya @BrentDouglas 

If you do not mention the authors the issue will be ignored.

I'm seeing the below issue pop up now that a new package (13.13.1) was released 4 hours ago. These types seem to be a dependency for a lot of the packages that I'm using in my project. Itw as working before, but then I just did a clean build of my project and it upgraded the package.

There are many many more authors on this module - please feel free to tag the appropriate party.

```
ERROR in .../node_modules/@types/node/globals.d.ts(1075,15):
TS2430: Interface 'Require' incorrectly extends interface 'RequireFunction'.
  Types of property 'cache' are incompatible.
    Type 'Dict<NodeModule>' is not assignable to type '{ [id: string]: NodeModule; }'.
      Index signatures are incompatible.
        Type 'NodeModule | undefined' is not assignable to type 'NodeModule'.
          Type 'undefined' is not assignable to type 'NodeModule'.
```

**Comment by SimonSchick** [comment] 2020-04-20 21:31
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44019

**Comment by orta** [comment] 2021-06-07 13:08
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:08 UTC
