### ISSUE TITLE
Including Highstock

### ISSUE THREAD

**Issue by tedcurrent** [DefinitelyTyped/DefinitelyTyped#12437] opened 2016-11-02 09:37 UTC
I have a webpack+TS+react project and I'm trying to upgrade from Highcharts to Highstock.

`import * as Highcharts from "highcharts";`

works just fine for Highcharts, but the following doesn't for Highstock

`import * as Highcharts from "highcharts/highstock";`

So, there is no module declaration for Highstock in the types? How is it supposed to be used?

Thanks!

**Comment by cyrilgandon** [comment] 2016-11-02 10:36
@tedcurrent : have you try to install highcharts with typings from 2.0 (`npm install @types/highcharts`)?

I don't see any export modules into the highstock.d.ts file on 2.0. 

Their should be something like

```
declare module "highcharts/highstock" {
    export = __Highstock;
}
```

**Comment by tedcurrent** [comment] 2016-11-02 10:44
@cyrilgandon: yeah I got the latest typings. By manually adding the following into highstock.d.ts file it works:
```
declare module "highcharts/highstock" {
    export = __Highstock;
}
```
However, this is not too feasible, as we reload the typings every time we run the project. I am kind of wondering, what is the intended way of use? Without any module declaration, it seems to me that the highstocks typings cannot be used. Right?

Thanks for the reply!

**Comment by cyrilgandon** [comment] 2016-11-02 10:46
Yes, I think this is an issue that need to be solved.
Personnaly, I fixed it by not using the typings from npm, but copy and paste it into a custom folder in my project.
That allows you to still work while waiting for this to be fixed. Are you going to create a PR to fix this?

**Comment by tedcurrent** [comment] 2016-11-02 10:52
Yeah I can check this out later. You can do it of course if you have time. There are also other issues that should be solved as can be seen in #11385 . Kind of wondering if those should be fixed on the same go?

**Comment by penghuili** [comment] 2016-11-08 16:18
@tedcurrent saved my life!

**Comment by Skuriles** [comment] 2016-12-09 10:43
Are there any updates to this issue..
Finally I got my angular 2 app with systemjs and Highcharts to work. 
But only with declaring Highcharts as a global:

`declare var Highcharts;`

If i try to import * as Highcharts from "highcharts" and use the current Typings the compiler will complain because:

`Property 'Stockchart' does not exist on type 'Static'.` 

Code looks like this:
`new Highcharts.StockChart(this.options);`

If I try do add manually the stuff from @tedcurrent the compiler throws error as well:

`: Exports and export assignments are not permitted in module augmentations.`

So..long answer short questions:
Does anybody got a highstock application to work with the highcharts typings without compiler errors?
At least it works but the compiler errors are annoying

**Comment by cyrilgandon** [comment] 2016-12-09 10:58
There was a big update on the typings some times ago after my post, everything is working fine now.

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1907cc359bba46fb875f3c19226bdf30d49d37a3

**Comment by Skuriles** [comment] 2016-12-09 11:44
I'm using the latest types version (4.2.23). Could it be that it is a problem with highcharts 5?

**Comment by Skuriles** [comment] 2016-12-09 12:19
For me it looks like, that typescript is using the default index.d.ts from node_modules/@types/highcharts and not the highstock.d.ts.
 so if I import like this:

`import * as Highcharts from "highcharts`

the problem is that in @types/highcharts/index.d.ts is no StockChart defined

if I 

`import * as Highcharts from "highstock"` (with declaration in systemjs)

"module highstock is not found"....

So how can I make the compiler to use the highstock.d.ts file instead of index.d.ts to prevent compile errors?

**Comment by cyrilgandon** [comment] 2016-12-09 12:58
From what I remembered the correct syntax is 

`import * as highstock from "highcharts\highstock" `

**Comment by Skuriles** [comment] 2016-12-09 13:18
Systemjs is working with your definition
but the types are still not working:

`Property 'StockChart' does not exist on type 'typeof "foo/node_modules/@types/highcharts/highstock"'.`

**Comment by cyrilgandon** [comment] 2016-12-09 13:57
StockChart is a property of highcharts not highstock.
So if your line is `highstock.StockChart `, it should be `highcharts.StockChart` instead.

```
import * as Highcharts from 'highcharts';

var foo = Highcharts.StockChart;

```

**Comment by cyrilgandon** [comment] 2016-12-09 14:13
You are right, I don't know what is wrong with highstock, I am not able to do anything with it neither.
HighchartsMore is working fine, not Highstock..

**Comment by orta** [comment] 2021-06-07 13:28
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:28 UTC
