### ISSUE TITLE
[@types/react] Returning props.children is a type error

### ISSUE THREAD

**Issue by MoritzKn** [DefinitelyTyped/DefinitelyTyped#44572] opened 2020-05-08 14:40 UTC
- [x] I tried using the `@types/react` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag (sorry for mentioning so many people but that's what it said, was this right?)

The following code will give a type error:

```tsx
import React from "react";

export const Wrapper: React.FC<{}> = ({children}) => {
  return children;
};
```

Type error ([see playground](https://www.typescriptlang.org/play/?jsx=2&ssl=6&ssc=1&pln=1&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4BYAKCqQA9JY40IA7AZ3gHUoUwwkoALkTEYAOgBiAYQA8AbwC+APjgBeOAAo5aABbAANgBMiLBQEo1KuVThwiMAK5QWTPUZMVKCz1SA)):
```
Type '({ children }: { children?: ReactNode; }) => ReactNode' is not assignable to type 'FC<{}>'.
  Type 'ReactNode' is not assignable to type 'ReactElement<any, any> | null'.
    Type 'undefined' is not assignable to type 'ReactElement<any, any> | null'.(2322)
```

But in JavaScript, it works just fine (see [code sandbox](https://codesandbox.io/s/wizardly-sammet-jfl4t?file=/src/App.js)).

**Comment by ferdaber** [comment] 2020-05-08 15:43
This is a limitation of TypeScript's checking against JSX constructors. Unfortunately there's not a workaround without a type assertion.

You can do something like 
```ts
export const Wrapper = ({ children }: { children?: ReactNode }) => {
  return children as unknown as JSX.Element;
}
```

**Comment by MoritzKn** [comment] 2020-05-08 16:07
@ferdaber  I don't have an in-depth understanding of the types of React so this might be a silly question, but doesn't `ReactNode` extend `JSX:Element`?

**Comment by ferdaber** [comment] 2020-05-08 16:10
`ReactNode` is a supertype of `JSX.Element`, so it's actually the other way around.

**Comment by MoritzKn** [comment] 2020-05-08 16:50
Shouldn't that mean that `ReactNode` fulfills the requirements of `JSX.Element`?

**Comment by ferdaber** [comment] 2020-05-08 19:05
A supertype is a more broad type than its subtypes, so imagine:
```ts
declare const myVar: string | number

// this would not be good, it should error
const myOtherVar: string = myVar
```

So think of it in the context of `ReactNode`:
```ts
declare const someNode: string | number | boolean | null | undefined | JSX.Element | JSX.Element[] // plus others

// this should not work
const myJsxElement: JSX.Element = someNode
```

In terms of runtime, React *does* allow nearly all subtypes of `ReactNode` to be returned in a component as of v16 (with the exception of `undefined`), but the TypeScript compiler hasn't been updated to allow for that, it *only* allows anything that produces `JSX` to have a return type that is assignable to `JSX.Element`.

**Comment by MoritzKn** [comment] 2020-05-08 23:54
Judging by the error I also assumed that `undefined` would be the issue so I tried `children || null` but it did work either. Shouldn't this work then?

If this just isn't possible using the current version of TypeScript and you already thought about it in-depth, I can also accept that. I am just trying to understand.

**Comment by ferdaber** [comment] 2020-05-11 14:06
The acceptable types that TypeScript itself can accept for JSX expressions do not match with what React accepts, TypeScript, when JSX integration was first developed, expects that component that can be used for creating JSX expressions *must* return the "plain-object" React element (the one with `$$key` and `props` and `$$owner`)

Over time, React added new abilities to return arrays and booleans and etc. but the TypeScript compiler was never updated to accommodate for that. Unfortunately, the fix is not as simple as adding more typings to the library, it has to be updated on the compiler itself.

So right now, the issue is presented as forcing any component to *always* return either the "plain-object" element or null, but if you try to return anything else (like booleans and arrays), it will yell at you.

If you return `children || null`, you would still be leaving in any "non-valid" truthy values like `true`, non-zero numbers, non-empty strings, and arrays, so the error is still present.

**Comment by MoritzKn** [comment] 2020-05-11 22:52
Thank you for the detailed write-up! 

I also found this section in the [documentation](https://www.typescriptlang.org/docs/handbook/jsx.html#function-component):

> As the name suggests, the component is defined as a JavaScript function where its first argument is a props object. TS enforces that its return type must be assignable to JSX.Element.

I was under the assumption that TS would tread JSX expressions just like calls to `React.createElement` and not hardcode any types. Apparently this is not the case but that would be a TypeScript issue, I assume.

I've got one more thought though:
What if `JS.Element` would be defined as something along the lines of `ReactNode | ReactNode[] | string | number | boolean | null`? Wouldn't that make it possible and also simply the definition of `children` as also simply being a `JS.Element`?

Just an idea though. I am sure there is an issue with that too. You can close the issue if you like.

**Comment by ferdaber** [comment] 2020-05-12 00:03
I can't close issues since I'm not a maintainer of the entire repo unfortunately, but anyways to the question of changing `JSX.Element`, that unfortunately also won't work because the `JSX.Element` type is assigned to every JSX expression, which *must* be the object that is returned from a `React.createElement` call 😕

**Comment by MoritzKn** [comment] 2020-05-12 08:06
Meh :/
I might open an issue on TypeScript itself sometime but I don't feel it would have particularly good chances. So not very motivated. Anyway, closing the issue here.

**Closed** 2020-05-12 08:06 UTC

**Comment by MoritzKn** [comment] 2020-05-12 08:14
Seems like this is the appropriate Issue for TypeScript itself: microsoft/TypeScript#14729
It's also mainly about deriving the types from `React.createElement` as I thought it would already be the case.

**Comment by deerawan** [comment] 2024-06-12 19:05
> This is a limitation of TypeScript's checking against JSX constructors. Unfortunately there's not a workaround without a type assertion.
> 
> You can do something like
> 
> ```ts
> export const Wrapper = ({ children }: { children?: ReactNode }) => {
>   return children as unknown as JSX.Element;
> }
> ```

Other workaround is using fragment

```tsx
return <>{children}</>;
```
