### ISSUE TITLE
@types/jsdom 11.0.5 causes an error

### ISSUE THREAD

**Issue by c-yan** [DefinitelyTyped/DefinitelyTyped#26338] opened 2018-06-07 05:41 UTC
- [x] I tried using the `@types/jsdom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (2.9.1)
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu

`@types/jsdom` 11.0.5 causes an following error, 11.0.4 is OK:

```
node_modules/@types/jsdom/index.d.ts:10:10 - error TS2305: Module '"C:/Users/xxxx/Documents/yyyy/node_modules/@types/jsdom/node_modules/parse5/lib/index"' has no exported member 'ElementLocation'.

10 import { ElementLocation } from 'parse5';
            ~~~~~~~~~~~~~~~
```

**Comment by moreJs** [comment] 2018-06-07 06:58
+1， rollback to 11.0.4

**Comment by antonyoneill** [comment] 2018-06-07 10:42
Not sure how we missed this issue this morning.. We fell into this trap with last night, breaking our build systems.

I had a look into this and it seems the issue is with the update to 11.0.5 by @inikulin here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f33a9352395f79e968e1c5a1b27640fa6ed73b58#diff-fafb97eb9756a7977e59e4ad8a54b849 

I think part of the problem is that the `index.d.ts` within `parse5` v3 and v4 is not valid?

In any case I think the solution to this issue is to rollback the commit, as `jsdom@11.11.0` (latest) uses v4.0.0 which contains the `MarkupData.ElementLocation` definition.

@inikulin any ideas? 😬

**Comment by inikulin** [comment] 2018-06-07 10:48
I have no idea how breaking changes should be managed in TS typings. Note that this will break typings for those who use latest jsdom, since they've updated to last parse5.

**Comment by antonyoneill** [comment] 2018-06-07 11:11
I might be missing something but latest jsdom uses parse5 v4.0.0 which still contains the MarkupData.ElementLocation?
https://github.com/inikulin/parse5/blob/v4.0.0/lib/index.d.ts#L9-L10

So actually the change that was made in f33a935 isn't valid for any current versions of jsdom? Unless perhaps `@types/parser5` is installed..

**Comment by inikulin** [comment] 2018-06-07 20:33
@antonyoneill My bad, it hasn't be merged yet: https://github.com/jsdom/jsdom/pull/2242.

**Comment by antonyoneill** [comment] 2018-06-08 08:22
🙌 Ah! OK perfect. I'm happy to keep my types version locked until jsdom is upgraded to the parse5@5 

Will keep an eye on that issue

**Comment by suszczykdaniel** [comment] 2018-06-10 17:02
Ok guys, so wchich version should I use now becouse I tried a lot of combinations of jsdom, @types/jsdom etc and none is working...

**Comment by leonard-thieu** [comment] 2018-06-10 17:05
Submitted a PR to try to fix this (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26421).

I'm not sure if it's a proper fix. The alternative would be to introduce parse5 v3 type declarations and follow https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version.

**Comment by dhruv2204** [comment] 2018-06-17 17:31
I am still facing this issue. I have rolled back to "jsdom": "^11.5.1" and "@types/jsdom": "^11.0.4" ?

**Comment by leonard-thieu** [comment] 2018-06-17 19:48
@dhruv2204 #26439 hasn't been merged yet.

**Closed** 2018-06-19 22:35 UTC

**Comment by c-yan** [comment] 2018-06-20 00:34
11.0.6 works!!
I thank everyone involved in the fix.

**Comment by rolandjitsu** [comment] 2018-06-21 09:49
@c-yan I'm still having the same problem with `11.0.6`. It only works with `11.0.4` or below.

**Comment by c-yan** [comment] 2018-06-21 09:59
@rolandjitsu If you do not use jsdom directly, I think that it is not necessary to install @type/jsdom.

**Comment by rolandjitsu** [comment] 2018-06-21 11:12
@
I needed the typings. Even though I don't directly install jsdom, I still can access the jsdom object exposed by jest-environment-jsdom-global package.

Not sure how this could be fixed.

**Comment by rolandjitsu** [comment] 2018-06-21 13:36
@c-yan I figured, that's why I use `11.0.4` at the moment. Thanks.

**Comment by AliRam81** [comment] 2020-02-21 06:52
i am using the jsdom 16.2 and have the same type import compile error 

![image](https://user-images.githubusercontent.com/35732186/75011021-dedf2580-547e-11ea-9c60-82d56322038a.png)

![image](https://user-images.githubusercontent.com/35732186/75011084-07ffb600-547f-11ea-8e86-1dfc7452bbd7.png)

any suggestion? 

thank you

**Comment by eugeneshemonaev** [comment] 2020-02-24 11:49
same issue

**Comment by mikevoets** [comment] 2020-02-25 22:15
@AliRam81 @eugeneshemonaev Downgrading to "@types/jsdom": "^12.2.4" is a workaround for me.

**Comment by alecf** [comment] 2020-05-15 16:11
I have been hitting this as well and the problem turns out to be that `enzyme` is installing `cheerio` which itself installs `parse5@3`:
```
$ npm list parse5
XXX@1.0.0 /home/alecf/XXX
├─┬ enzyme@3.11.0
│ └─┬ cheerio@1.0.0-rc.3
│   └── parse5@3.0.3 
├─┬ jsdom@16.2.1
│ └── parse5@5.1.1 
└─┬ mapbox-gl-js-mock@1.0.2
  └─┬ jsdom@11.11.0
    └── parse5@4.0.0 
```

and when I look at where stuff actually gets installed (using relative paths just to match the error output)
```
$ jq .version node_modules/@types/jsdom/../../parse5/package.json
"3.0.3"
```

I think the problem is that `@types/jsdom` only depends on `@types/parse5`, allowing `parse5` itself to be out of date:

```
$ grep parse5 node_modules/@types/jsdom/package.json 
    "@types/parse5": "*",
```

so one workaround here is to require parse5 directly in your project, which forces the resolution to be parse5, instead of the outdated one from enzyme/cheerio:
```
$ npm install --save-dev parse5@5
```
