### ISSUE TITLE
react-router 1.0 definitions

### ISSUE THREAD

**Issue by emanuelbsilva** [DefinitelyTyped/DefinitelyTyped#6246] opened 2015-10-11 12:23 UTC
Hi all,

First of all let me say that i am just now exploring react and typescript. So as i was reading all about both ecosystems i found out about this great project, thank you all for making all these great definitions.

I'm starting a project where i also want to use react-router, but immediately found out while i was coding that the definitions for the react-router were wrong. I forked this repository to update the react-router.d.ts and as i was editing i realise that the react-router.d.ts relates to the 0.13 version of react-router. I want to contribute to this repository by updating react-router.d.ts definitions as i need them, but i find it wrong to overwrite the 0.13 version with 1.0 definitions. So, what to do? Should i create another file for the 1.0 version or overwrite the 0.13?

Thank you all!

**Comment by subjectix** [comment] 2015-10-11 12:49
If you take a look at the [version](http://definitelytyped.org/guides/contributing.html#version) section of the contributing guide you'll see that it's best to rename the old one as `react-router-0.13.d.ts` and continue upgrading the main `react-router.d.ts` file.

**Comment by robyoder** [comment] 2015-11-15 05:24
Duplicate of #5939? 

Plus, PR #6073 is open, so I hope you're not still writing the definitions from scratch, @emanuelbsilva.

**Comment by robyoder** [comment] 2016-05-03 05:33
Suggest this to be closed. Definitions are much past 1.0 now.

**Comment by vvakame** [comment] 2016-05-05 17:16
thanks!

**Closed by vvakame** 2016-05-05 17:16 UTC

**Comment by emanuelbsilva** [comment] 2016-05-31 16:02
Hi @robyoder sorry for not responding earlier. Thanks for the answer!
