### ISSUE TITLE
[@types/node] child_process StdioOptions does not allow "inherit" in array form anymore.

### ISSUE THREAD

**Issue by mgroenhoff** [DefinitelyTyped/DefinitelyTyped#28069] opened 2018-08-13 08:34 UTC
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @thw0rted @andy-ms 

The perfectly valid value `["inherit", "pipe", "pipe", "ipc"]` for option `stdio` is no longer accepted and fails to compile.

Cause: #28025

Can we please stop making backwards-incompatible changes in patch versions please?

**Comment by thw0rted** [comment] 2018-08-13 10:17
@mgroenhoff Sorry, this is a(nother) oversight in the Node docs.  As you point out, "inherit" is a valid string to pass in the array-syntax but the docs [say it is not](https://nodejs.org/api/child_process.html#child_process_options_stdio), even though it's used in an example [further down the same page](https://nodejs.org/api/child_process.html#child_process_subprocess_kill_signal).  I'll get together a PR for both here and the Node docs (again!).

As for not making breaking changes in patch versions, I'm honestly not sure what else to do.  Last time I submitted a similar change (specifying the actual type of a parameter that was previously `any`), people's code broke and they complained, but as far as I can tell DT really doesn't have a way to schedule or wall off changes to prevent that -- DT can't follow semver, by design.   If you know of a process we could follow to prevent patch-version breakage, I'd be happy to follow it.

**Comment by mgroenhoff** [comment] 2018-08-14 07:27
Well you need to untie the two versions and start using semver for types the way normal packages do. But I guess that would just cause more confusion than it does now. Please don't take it personal. It was more of a rant against DT because this happens way to often. Thank you for the PR's!

**Comment by thw0rted** [comment] 2018-08-14 07:43
Don't sweat it at all, I understood what you meant.  There's some discussion about semver etc [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25500) and [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25677), if you have ideas how to make DT less brittle I'm sure they'd be welcome.

**Comment by mgroenhoff** [comment] 2018-08-14 08:13
Those are some interesting discussions. I think the best course of action for me would be to start using exact versions for types as suggested in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26847#issuecomment-400384518

**Comment by orta** [comment] 2021-06-07 13:17
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:17 UTC
