### ISSUE TITLE
React.SFC components not usable in JSX with TSC 2.4.1

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#17601] opened 2017-06-29 07:52 UTC
Happens with latest `@types/react` in combination with tsc 2.4.1.

```tsx
const AComponent: React.SFC<{}> = () => <div/>

const element = <AComponent/>
//               ^^^^^^^^^^
// JSX element type 'ReactElement<any> | null' is not a constructor function for JSX elements.
// Type 'null' is not assignable to type 'ElementClass'.
```

The problem seems to be that the compiler no longer accepts a function that is allowed to return `null` as a valid component. It does accept classes whose `render` method returns null, though.

**Comment by dontsave** [comment] 2017-06-30 16:34
This is happening for me with @types/react@15.0.33. Reverting to 15.0.27 solves it

**Comment by pselden** [comment] 2017-07-13 06:14
Is this a similar issue here? 

```
JSX element type 'ReactElement<any>' is not a constructor function for JSX elements. Property 'render' is missing in type 'ReactElement<any>'.
```

I have a .d.ts file that exports this:
```
export declare const PrimaryButton: React.StatelessComponent<ButtonProps>;
export declare const SecondaryButton: React.StatelessComponent<ButtonProps>;
export declare const TertiaryButton: React.StatelessComponent<ButtonProps>;

```

When simply trying to do:
```
import {SecondaryButton} from 'my-component-lib';

//...

render() {
   return <SecondaryButton></SecondaryButton>;
}
```

**Comment by Kovensky** [comment] 2017-07-13 08:23
I can't seem to reproduce this anymore after doing updates; I wonder if this was caused by nested dependencies not correctly updating.

**Comment by orta** [comment] 2021-06-07 13:41
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:41 UTC
