### ISSUE TITLE
react-router: `withRouter` narrows components with `any` prop type to `{}`

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#24070] opened 2018-03-04 15:18 UTC
Given a component that has a props type of `any`, when wrapping the component in the `withRouter` HOC, the returned component has a prop type of `{}`. I would expect the return component to have a prop type of `any`.

`any` should not be narrowed to `{}`.

Components with `any` type are common when gradually migrating a codebase to TypeScript, where many components may have their prop types undefined whilst the codebase is gradually migrated.

Example:

``` tsx
import React, { SFC } from 'react';
import { withRouter } from 'react-router-dom';

const MyComponent: SFC<any> = () => null;

const MyComponentWithRouter = withRouter(MyComponent);

<MyComponentWithRouter
  // Unexpected error: Property 'foo' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<any, never>, ComponentState>> & Rea...'.
  foo={1}
/>
```

Related https://github.com/gcanti/typelevel-ts/issues/19

This issue was introduced by the change in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21329 /cc @Grmiade (PR author)

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-router` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @tkrotoff @huy-nguyen @grmiade @DaIgeb @egorshulga @neuoy 

If you do not mention the authors the issue will be ignored.

**Comment by Grmiade** [comment] 2018-03-04 16:14
The problem is the `Omit` definition, indeed :/ Maybe with Conditional Types we could fix that.

**Comment by Grmiade** [comment] 2018-03-04 16:29
If the old definition worked for you (explicit way). You can directly add it to your project, in a `types` folder. To overwrite the new definition provided by `@types/react-router`.

**Comment by OliverJAsh** [comment] 2018-03-04 16:31
Your change actually improves things for us because it fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17181, so we'd like to keep using it if possible.

**Comment by Grmiade** [comment] 2018-03-04 16:59
The only simple workaround I see by waiting conditional types is:
```typescript
const MyComponent: React.StatelessComponent<any> = () => null;
const MyComponentWithRouter = withRouter(MyComponent) as React.ComponentType<any>;
const Test = () => <MyComponentWithRouter foo={1} />
```

**Comment by Pajn** [comment] 2018-03-10 18:20
This is probably an issue with TypeScript. any works in general very bad with inference.

Maybe you can work around it by explicitly setting the generic parameter `withRouter<any>(MyComponent)`

**Comment by OliverJAsh** [comment] 2018-03-12 13:24
> Maybe you can work around it by explicitly setting the generic parameter withRouter<any>(MyComponent)

Unfortunately not because the problem is in `Omit` when given a type of `any`:

``` ts
type Test = Omit<any, never>
// Test is type `{}`, not `any`
```

My workaround:

``` ts
const MyComponentWithRouter = withRouter(MyComponent) as ComponentType<any>;
```

**Comment by Grmiade** [comment] 2018-03-12 14:27
https://github.com/Microsoft/TypeScript/pull/21847
`type Omit<T, K> = Pick<T, Exclude<keyof T, K>>;`
The `Omit`definition should be fixed soon 💪

**Comment by OliverJAsh** [comment] 2018-03-12 14:30
@Grmiade This would still be an issue, no?

``` ts
type Foo = Pick<any, never>;
// Foo type is `{}`, not `any`
```

`Pick` will always return an object.

I guess we'll need to use conditional types to only use `Pick` when the type is not `any`?

**Comment by Grmiade** [comment] 2018-03-12 14:34
Yes, if the `Pick`'s behavior doesn't change, we should use conditional types too ;)

**Comment by Grmiade** [comment] 2018-03-28 08:53
👋 @OliverJAsh Conditionals Types are released 🎉 

If you create a `types/react-router.d.ts` file with this code in your project. Do it works for ur case?
```typescript
import { RouteComponentProps } from 'react-router'

declare module 'react-router' {
  type ReturnedType<T> = T extends RouteComponentProps<any>
    ? Pick<T, Exclude<keyof T, keyof RouteComponentProps<any>>>
    : T

  export function withRouter<P>(
    component: React.ComponentType<P>,
  ): React.ComponentClass<ReturnedType<P>>
}
```

I will propose a PR in the day ;)

**Comment by Grmiade** [comment] 2018-06-01 07:07
After consideration, I don’t think withRouter should accept `any` as generic type. `any` can be ANYthing as string or boolean, it’s not assignable to a props type. 
We can close this issue I think.

**Comment by Kizmar** [comment] 2018-11-14 16:45
Where did this end up landing? I'm running into this issue on current versions.

Currently using @OliverJAsh 's workaround.

**Comment by orta** [comment] 2021-06-07 13:19
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:19 UTC
