### ISSUE TITLE
[@types/jest] - Mocks args seem wrong

### ISSUE THREAD

**Issue by fthouraud** [DefinitelyTyped/DefinitelyTyped#49985] opened 2020-12-07 08:48 UTC
Hello 👋 

After having to upgrade **@types/jest** to **26.0.16**, I'm having issues with the `toHaveBeenNthCalledWith` (and similar) methods to check the arguments of my mocks.

I now have a type's error like this one:
`TS2345: Argument of type 'SendTemplatedEmailRequest' is not assignable to parameter of type '(err: AWSError, data: SendTemplatedEmailResponse) => void'.   Type 'SendTemplatedEmailRequest' provides no match for the signature '(err: AWSError, data: SendTemplatedEmailResponse): void'.`

Looking at the AWS types definitions, there's is such a definition: `sendTemplatedEmail(callback?: (err: AWSError, data: SES.Types.SendTemplatedEmailResponse) => void): Request<SES.Types.SendTemplatedEmailResponse, AWSError>`.

But there's also the one that I'm actually using: `sendTemplatedEmail(params: SES.Types.SendTemplatedEmailRequest, callback?: (err: AWSError, data: SES.Types.SendTemplatedEmailResponse) => void): Request<SES.Types.SendTemplatedEmailResponse, AWSError>`.

If I get back to the **26.0.15** version then everything is fine.

I saw some modifications on the latest commit that could have led to that (unless I'm missing the point 😬). I'll also try to allocate time to look into it more closely.

Mention: @stilettk @devanshj 

Anyway, thanks for your work and time ❤️

Edit 1: the [related PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47020) with ongoing discussions about the issue described here.

**Comment by pleunv** [comment] 2020-12-07 09:35
`toHaveBeenLastCalledWith()` now also appears to only take 0 parameters.

**Comment by nico-w** [comment] 2020-12-08 09:14
I experienced the same issue with `toHaveBeenCalledWith()` in several tests after upgrading to `@types/jest@26.0.17`.
Error Message: `Expected 0 arguments, but got 2.`

Interesting fact:
This issue **only** appeared for 2 of 6 instances in one test file. The failing ones had a warning about `max-len` from eslint as well. The others not and they also had no type issues. Maybe there is a conflict somehow?

Downgrading to `@types/jest@26.0.15` solved my problem so far.

**Comment by luiz290788** [comment] 2020-12-08 14:16
I've had the same issue. The issue is related to overloading methods. As we are now trying to infer the arguments of the method to check while calling `.toHaveBeenCalledWith` and typescript has a [limitation](https://github.com/Microsoft/TypeScript/issues/24275#issuecomment-390701982) while inferring arguments and return type from overloaded functions we are checking only for the last overload defined because typescript assumes that it is the most generic overload when sometimes that is not the case. So if you are not using the last overload, you are going to get an error now. I think this is an issue in jest type definition.

There is a [workaround](https://stackoverflow.com/questions/52760509/typescript-returntype-of-overloaded-function) for the overload inferring problem. We can try to use that.

**Comment by marikaner** [comment] 2020-12-09 08:55
Same issue, I also have overloaded methods.

**Comment by orta** [comment] 2021-06-23 08:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-23 08:09 UTC
