### ISSUE TITLE
[@types/react-native] Property 'ref' does not exist on type AnimatedProps

### ISSUE THREAD

**Issue by ovy9086** [DefinitelyTyped/DefinitelyTyped#43478] opened 2020-03-30 10:10 UTC
- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors 
  - Authors: @alloy @zusinShinpei @Esemesek @jeremybarbet @akrger 

Since migrating to react-native 0.62 I get the following error for `Animated.View` and all the `Animated.Components` or components created using `createAnimatedComponent()`:

`Property 'ref' does not exist on type 'IntrinsicAttributes & AnimatedProps<ViewProps> & { children?: ReactNode; }'`

Example :

```
<>
    {/*Working*/}}
    <View ref={(ref) => console.log('Ref', ref)} />

    {/*Throwing error */}
    <Animated.View ref={(ref) => console.log('RefAnimated', ref)} />
</>
```

This happens with a bare project using : https://github.com/react-native-community/react-native-template-typescript 

My relevant dependencies :
```
"react": "16.11.0",
"react-native": "0.62.0"
"@types/react-native": "^0.62.0",
"typescript": "^3.8.3"
```

Probably relevant React-Native commit : https://github.com/facebook/react-native/commit/66e72bb4e00aafbcb9f450ed5db261d98f99f82a

**Comment by alloy** [comment] 2020-03-30 12:32
Duplicate of #42806

**Closed by alloy** 2020-03-30 12:32 UTC
