### ISSUE TITLE
[react-router] `ExtractRouteParams` breaks with custom matchers

### ISSUE THREAD

**Issue by maraisr** [DefinitelyTyped/DefinitelyTyped#52914] opened 2021-05-13 06:41 UTC
React-rotuer's `generatePath` method just proxies `path-to-regexp`, which supports [custom matchers](https://github.com/pillarjs/path-to-regexp/tree/v1.7.0#custom-match-parameters).

Currently the typescript fails when asking for `generatePath('/abc/:xyz([a-z])?', { xyz: 'a'})` <- should be valid. But fails.

cc @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @nguyen @grmiade @DaIgeb @egorshulga @rraina @t49tran @8enSmith @wezleytsai @eps1lon @HipsterBrown @pawfa

**Comment by beaucollins** [comment] 2021-05-27 19:47
Some patterns now may be possible with #52712 however it doesn't cover all cases. An example:

```
generatePath('/abc/:xyz(-[^/]{1,})', {xyz: '-foo' });
```

This fails because the initial split uses `/` which is also a character you can put in your pattern.

```
T extends `${infer _Start}:${infer ParamWithOptionalRegExp}/${infer Rest}`
```

Unfortunately this seems to be going down the hole of implementing RegExp pattern maching in TypeScript string literals. 😱

**Comment by maraisr** [comment] 2021-05-29 21:37
Perhaps we remove these type restrictions then? 

The problem with the forward slash seems mute, can't it just infer like `${infer a}(${string}${infer b}` and then recurve that, and then handle if `b` starts with a ?

That'll solve this no?

**Comment by beaucollins** [comment] 2021-06-01 16:34
> That'll solve this no?

Possibly. Start with the most specific pattern for `extends ${infer ...}` and handle each less specific one.

The key names may also need to be cleaned up. There's also the technical possibility of having a `)` in you pattern, however that probably isn't a problem because the `)` will be URL escaped in practice.

**Comment by maraisr** [comment] 2021-06-01 21:29
@beaucollins thanks for jumping in this! 🥰

**Comment by beaucollins** [comment] 2021-06-01 21:31
It's @lmichelin who landed #52712 so thanks to them!

**Comment by justingrant** [comment] 2021-07-30 19:02
I just upgraded my project to post-#52712 types (@types/react-router@5.1.16) and I'm now getting TS errors that may be related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52914#issuecomment-849894856 above.  The first segment in the path seems to be extracted correctly, but the second segment is extracted with the prop name being extracted as the whole regex (e.g. `'d(\\\\d{8})('` instead of just `d`).

I assume that the problem is that the final forward-slash in my URL pattern is optional (`(/)?`) and it's being interpreted as a separator.

Any ideas for how to work around this?  cc @lmichelin @beaucollins 

Here's the relevant lines of my JSX:

```ts
<Route
  path="/times/:v(day|list)/:d(\\d{8})(/)?"
  render={(routeProps: RouteComponentProps<{ d: string; v: string }>) => {
``` 

The `render` prop gives me this error:

```
No overload matches this call.
  Overload 1 of 2, '(props: (RouteProps<"/times/:v(day|list)/:d(\\\\d{8})(/)?", { v: string; } & { "d(\\\\d{8})(": string; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>) | Readonly<...>): Route<...>', gave the following error.
    Type '(routeProps: RouteComponentProps<{    d: string;    v: string;}>) => JSX.Element' is not assignable to type '(props: RouteComponentProps<{ v: string; } & { "d(\\\\d{8})(": string; }, StaticContext, unknown>) => ReactNode'.
      Types of parameters 'routeProps' and 'props' are incompatible.
        Type 'RouteComponentProps<{ v: string; } & { "d(\\\\d{8})(": string; }, StaticContext, unknown>' is not assignable to type 'RouteComponentProps<{ d: string; v: string; }, StaticContext, unknown>'.
          Property 'd' is missing in type '{ v: string; } & { "d(\\\\d{8})(": string; }' but required in type '{ d: string; v: string; }'.
  Overload 2 of 2, '(props: RouteProps<"/times/:v(day|list)/:d(\\\\d{8})(/)?", { v: string; } & { "d(\\\\d{8})(": string; }> & OmitNative<{}, keyof RouteProps<string, { [x: string]: string | undefined; }>>, context: any): Route<...>', gave the following error.
    Type '(routeProps: RouteComponentProps<{    d: string;    v: string;}>) => JSX.Element' is not assignable to type '(props: RouteComponentProps<{ v: string; } & { "d(\\\\d{8})(": string; }, StaticContext, unknown>) => ReactNode'.ts(2769)
Pages.tsx(124, 50): 'd' is declared here.
index.d.ts(92, 5): The expected type comes from property 'render' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Route<{}, "/times/:v(day|list)/:d(\\\\d{8})(/)?">> & Readonly<RouteProps<"/times/:v(day|list)/:d(\\\\d{8})(/)?", { ...; } & { ...; }> & OmitNative<...>> & Readonly<...>'
index.d.ts(92, 5): The expected type comes from property 'render' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Route<{}, "/times/:v(day|list)/:d(\\\\d{8})(/)?">> & Readonly<RouteProps<"/times/:v(day|list)/:d(\\\\d{8})(/)?", { ...; } & { ...; }> & OmitNative<...>> & Readonly<...>'
(JSX attribute) render?: ((props: RouteComponentProps<{
    v: string;
} & {
    "d(\\\\d{8})(": string;
}, StaticContext, unknown>) => ReactNode) | undefined
```

**Comment by beaucollins** [comment] 2021-07-30 19:15
> Any ideas for how to work around this?

@justingrant You can cast it to something that `ExtractRouteParams` can handle as a bit of a hack to unblock yourself.

```ts
<Route
  path={"/times/:v(day|list)/:d(\\d{8})(/)?" as "/times/:v/:d"}
  render={(routeProps: RouteComponentProps<{ d: string; v: string }>) => {
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKFEljgG9EIBXGJAGidaQGFdIAdkgEwACjjABnOAF842XASLoYAWhzcoZKjsoAeBCzZU4cMChgALALz0ARAHoYoJJIcAuAG4AKACYoATwAfABtgSRgASg9fbwAdON96AA4ZSO8HSIB+OzgUaUdnEFcPTxi7GRM4IgFfJChbbw02cQgpdy42PnAIIRFWqT1GXw6IqGABAHNSOE9RmHGp2QA+SLhrZYYq01MiGGYoATg9ZYAJJBCQiD0HZaqZOVuqIA

**Comment by justingrant** [comment] 2021-07-30 19:26
> You can cast it to something that `ExtractRouteParams` can handle as a bit of a hack to unblock yourself.

Great hack! Works well and is reasonably self-describing. Thx.

**Closed** 2022-05-04 22:16 UTC
