### ISSUE TITLE
@types/tween.js index.d.ts is not a module

### ISSUE THREAD

**Issue by chris-dk** [DefinitelyTyped/DefinitelyTyped#20480] opened 2017-10-11 03:05 UTC
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Amos47 , @sunetos , @jzarnikov , @alexburner 

Hi everybody,
I tried to use tween.js in my angular 4 app, to tween some three.js 3D objects, but so far it didn't work.
In my package.json in "dependencies" I put
`"@tweenjs/tween.js": "16.9.0"`
and in "devDependencies" I put
`"@types/tween.js": "16.9.0"`

Then in the component I wrote
`import * as TWEEN from "@tweenjs/tween.js";`

But when I try to start/compile it I get the error:
**`...node_modules/@types/tween.js/index.d.ts' is not a module`**

My tsconfig.json looks like the following:
`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./wwwroot/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strict": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
`
I searched some hours, but couldn't find anything helpful. Can somebody help me please?

**Comment by alexburner** [comment] 2017-10-11 17:51
> I searched some hours, but couldn't find anything helpful. Can somebody help me please?

This sounds an awful lot like a StackOverflow question. Do you believe this to be a bug with the tween.js typings? Are other @types dependencies working correctly for you?

**Comment by Amos47** [comment] 2017-10-11 18:37
I can't reproduce the error. If you can provide a plunker or some minimal example that'd be helpful. As such it works for me with `"@tweenjs/tween.js": "^17.1.1"` and `"@types/tween.js": "^16.9.0"`.

I don't see anything in your code.. You have definitely installed the dev dependencies?

I think I agree that this is more of a SO question for now. We should close this issue.

**Comment by chris-dk** [comment] 2017-10-13 13:21
After deleting node_modules and installing all of them again, the error message "index.d.ts is not a module" no longer appeared, but then I got the error that for "@tweenjs/tween.js" the declaration file could not be found.
Finally the problem was solved by removing
`"types": [ ]`
from /ClientApp/tsconfig.app.json, because tsconfig.app.json is extending the tsconfig.json and can overwrite the options in the latter.

**Closed** 2017-10-13 13:23 UTC
