### ISSUE TITLE
Express 4.17.3 is breaking express.Response properties

### ISSUE THREAD

**Issue by manuelbieh** [DefinitelyTyped/DefinitelyTyped#42812] opened 2020-03-04 02:08 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @puneetar

The recent update of the Express types break all my apps because `express.Response` obviously no longer has any accessible properties. Example: https://circleci.com/gh/manuelbieh/react-ssr-setup/104

Not sure if I might be using it incorrectly but since I also only see one tiny test with a very specific testcase (sending `json()` as response) I think there's a chance that this is a bug.

**Comment by guyellis** [comment] 2020-03-04 04:05
Same here:

```
ERROR in [at-loader] ./lib/routes/api-note.ts:330:18 
    TS2339: Property 'status' does not exist on type 'Response<any>'.
ERROR in [at-loader] ./lib/routes/api-note.ts:354:18 
    TS2339: Property 'send' does not exist on type 'Response<any>'.
```

https://travis-ci.org/guyellis/plant/builds/658020632

**Comment by Rauttis** [comment] 2020-03-04 08:22
Looks like it's [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138) repeating once again.

Basically one of the dependencies of `@types/express` is locked to an old, incompatible version in `package-lock.json`.

In my case running `npm i @types/express-serve-static-core` and then `npm uninstall @types/express-serve-static-core` fixed it as this caused the version in `package-lock.json` to be updated. Maybe there is a better way to do this (without re-building the entire package-lock file).

**Comment by tamarzil** [comment] 2020-03-05 09:19
Looks like @types/express, version 4.17.3  requires the dependency on @types/express-serve-static-core to be with min. version 4.17.1, and right now it's "*"

**Comment by gkalpak** [comment] 2020-04-25 10:07
This looks like a duplicate of #40138.
You can fix the outdated `@types/express-serve-static-core` version as described in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138#issuecomment-589867440.

**Comment by orta** [comment] 2021-06-07 13:34
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:34 UTC
