### ISSUE TITLE
[react-router] Type 'Location' is not generic.

### ISSUE THREAD

**Issue by rhys-vdw** [DefinitelyTyped/DefinitelyTyped#28484] opened 2018-08-29 05:13 UTC
I tried using the `@types/react-router@4.0.30` package and had problems.

```
ERROR in [at-loader] ./node_modules/@types/react-router/index.d.ts:69:13
    TS2315: Type 'Location' is not generic.
```

This is correct, the version of `@types/history` that this package depends on does *not* have a generic `Location` type. However the current version in `master` [does](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3be76f6b28823e1f712d32ff3f7bc720922e6cf3/types/history/index.d.ts#L27-L33).

cc @sergey-buturlakin, @ngbrown, @rokoroku

**Comment by rhys-vdw** [comment] 2018-08-29 05:15
Perhaps related to #27012.

Seems the package is being distributed without the correct dependency on `@types/history`:

From package.json
```
    "dependencies": {
        "@types/react": "*",
        "@types/history": "*"
    },
```

**Comment by vipseixas** [comment] 2018-08-31 15:33
The problem is at line 69 at index.d.ts:

```
export interface RouteComponentProps<P, C extends StaticContext = StaticContext, S = H.LocationState> {
  history: H.History;
  location: H.Location<S>;
  match: match<P>;
  staticContext?: C;
}

```

It should be `location: H.Location`, since it is really not generic:

```
export interface History {
    length: number;
    action: Action;
    location: Location;
...
}

```

**Comment by rhys-vdw** [comment] 2018-09-12 09:13
Ah, I fixed this by removing and re-adding `@types/react-router` and `@types/react` who both depend on the package. My package does not depend on `@types/history` so I could not update it directly, and the subdependency is not updated with `yarn upgrade --latest @types/react-router`. However, when it's added for the first time it will be locked to latest.

**Comment by flushentitypacket** [comment] 2019-02-06 18:33
@rhys-vdw Thanks for the hint. Doing what you described didn't work for me for some reason, but it pointed me in the right direction: I just went in and modified the yarn.lock to get myself unstuck from that state.

**Comment by youngmushroom** [comment] 2019-05-14 02:59
update your react-router or add  {"skipLibCheck": true} to your tsconfig.json

**Comment by orta** [comment] 2021-06-07 13:16
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:16 UTC
