### ISSUE TITLE
(192,16): Generic type 'Dispatch<S>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by sunilkhuttan** [DefinitelyTyped/DefinitelyTyped#28346] opened 2018-08-24 06:54 UTC
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the the latest "npm install --save @types/react-redux" having this issue when run the npm start

**Comment by mattmccutchen** [comment] 2018-08-28 02:32
Duplicate of #9611

**Comment by orta** [comment] 2021-06-07 13:16
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:16 UTC
