### ISSUE TITLE
[node] Missing global URL and URLSearchParams typings

### ISSUE THREAD

**Issue by ulrichb** [DefinitelyTyped/DefinitelyTyped#34960] opened 2019-04-24 10:40 UTC
This is a follow-up issue of #25342 and #19799.

In #25269 the `URL` and `URLSearchParams` classes have been added as globals because since Node.js 10.0 they are [exposed as globals](https://nodejs.org/api/url.html#url_class_url).

Because `lib.dom.d.ts` also exposes them as globals, projects _which referenced both_, `node` and `lib.dom`, got "Duplicate identifier 'URL'" errors (see #25342). Therefore the global `URL` and `URLSearchParams` has been removed again.

This fix (actually a workaround  for a missing declaration merging feature of TypeScript) now has the drawback that we cannot use the global `URL` class in Node.js-code (instead we need to import it from the `url` module). This is especially bad for universal modules which are supposed to work in the browser + node by just using the global `URL` (which works since Node.js 10).

So I want to discuss solutions for this atm. unsupported scenario here. (Without having local declarations in consuming projects.)

----

One solution would be to support this scenario in TypeScript (allow - exactly same? - global class definitions in multiple declaration files). @weswigham Would this be possible?

A more straight-foward solution would be to create a new DT package (e.g. `node-global-url` or maybe better `whatwg-global-url`) which can be installed additionally and selected by using e.g. `"types": ["node", "node-global-url"]` in a `tsconfig.json` for projects which face the mentioned scenario above.

Any other ideas?

**Comment by weswigham** [comment] 2019-04-24 16:48
Rewrite the global URL and the node URL such that they can declaration merge? IIRC if you write it as interface+namespace+value it should merge without dupe errors provided the types line up.

**Comment by ulrichb** [comment] 2019-04-24 19:05
@weswigham 

The problem is that we need a _class_ in the global namespace. And here the declaration merging doesn't seem to work (which is the underlying problem behind #25342).

See [this small repro](https://www.typescriptlang.org/play/#src=declare%20global%20%7B%0D%0A%0D%0A%20%20%20%20class%20URL%20%7B%20%2F%2F%20ISSUE%3A%20%22Duplicate%20identifier%20'URL'%22%20%0D%0A%0D%0A%20%20%20%20%20%20%20%20constructor(url%3A%20string%2C%20base%3F%3A%20URL2%20%7C%20string)%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20class%20URL2%20%7B%20%2F%2F%20No%20error%0D%0A%0D%0A%20%20%20%20%20%20%20%20constructor(url%3A%20string%2C%20base%3F%3A%20URL2%20%7C%20string)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconsole.log(new%20URL(%22%2Fpath%22%2C%20new%20URL(%22http%3A%2F%2Fexample.com%22)))%3B%0D%0A%0D%0Aconsole.log(new%20URL2(%22%2Fpath%22%2C%20new%20URL2(%22http%3A%2F%2Fexample.com%22)))%3B%0D%0A%0D%0Aexport%20default%20%22make%20this%20a%20module%22%0D%0A).

**Comment by ulrichb** [comment] 2019-07-05 23:11
@weswigham Any news on this? Has the "class merging in the global namespace" any chance to be supported by TS? If no, should we go for a new "node-global-url" package as mentioned in the issue description above?

**Comment by thw0rted** [comment] 2019-08-02 11:26
Just got bit by this, came here to report and found that it's been open for a few months with no apparent movement.

Isn't The Real Problem that projects shouldn't be including both `lib.dom` and `node`?  I mean, you're either in the browser or you're not, at least at any one time, right?  Surely these two can't be the only global namespace conflicts between the two environments?

**Comment by simonbuchan** [comment] 2019-08-07 07:19
@thw0rted - as mentioned, isomorphic code (libraries that can run in both the browser and node without changes) often uses both, even though that gives you the intersection and not the union of the environment, which would be more correct.

**Comment by thw0rted** [comment] 2019-08-07 07:55
Surely there's got to be a better way to do it than just polluting the global namespace of your X environment with the stuff that only Y provides, though, right?  I have different sets of config files (npm / webpack / tsc / etc) for different environments, and can conditionally ignore certain files if they're only used in one or the other.  If we don't already have a documented standard practice for writing isomorphic libraries *without* including conflicting baseline libraries, we certainly should.

**Comment by simonbuchan** [comment] 2019-08-07 23:04
MyCoolLib needs access to browser APIs if it's running in a browser, and node APIs if it's running in node. Using both `lib: dom` and `types: node` is a simple, development friendly option, and you can check with (something like) `tsc --noEmit --lib dom` and `tsc ---noEmit --types node` separately.

Unrleated, but ideally the published declaration files would not reference or declare a dependency on either, so users of the lib don't get polluted, but that's hard to do at the moment due to the lack of "internal" declaration files / declaration bundling.

**Comment by thw0rted** [comment] 2019-08-08 07:00
So if using both is "development friendly" then how should this issue be resolved?  I feel like there was a similar conflict between some kind of Buffer (or ArrayBuffer, or similar?) a few years back, but I can't recall the specifics.  Is there some way we could rename one of the offending types to e.g. NodeURL, such that it transpiles to the right name in the emitted code?

**Comment by simonbuchan** [comment] 2019-08-08 08:03
Typescript for it's non-DOM included libs uses a pattern like:

```ts
interface Foo { 
  // instance stuff
}
interface FooConstructor {
  readonly prototype: Foo;
 new (...): Foo;
 // static stuff
}
declare var: FooConstructor;
```

This pattern means you can merge the separate declarations, as interfaces merge, and the var will be referring the the same (merged) type in both declarations, even if they are different.
This seems to be an accident of how the library files are designed such that, e.g. `lib.es2017.d.ts` can extend types introduced in `lib.es5.d.ts`.
That wouldn't fix this issue until both typescript and @types/node both switch to that style though, and that would have pretty high chance of breaking everything.
I'm really not sure what the right answer is here, without changes to typescript.

**Comment by sindresorhus** [comment] 2019-11-29 04:55
[Node.js 8 will soon be out of LTS](https://github.com/nodejs/Release). That means Node.js modules will start targeting Node.js 10 and use the `URL` and `URLSearchParams` globals, so this is about to become a much more widespread problem.

**Comment by forivall** [comment] 2020-01-21 22:05
An alternative that I just created is as follows:
```
declare global {
  var URL: typeof globalThis extends { URL: infer U }
    ? U
    : typeof import('url').URL;
}
```

**Comment by forivall** [comment] 2020-01-21 22:48
Addendum: The circular type definition error can be overcome by adding some additional requirement to the type inference where only the DOM lib would suffice. For example, I found that this works, but is ugly, and for current uses, i'll be using the above in my universal libs that use `URL`.

```ts
declare global {
  var URL: typeof globalThis extends {
    Document: new () => { querySelectorAll: any };
    URL: infer URLCtor;
  }
    ? URLCtor
    : typeof import('url').URL;
}
```

**Comment by sdegutis** [comment] 2021-04-03 16:09
Is there any news or progress on this? I keep having to import {URL} from 'url' just to satisfy TypeScript even though it's already in the global scope in my Node.JavaScript app.

**Comment by demurgos** [comment] 2022-01-15 18:57
The `dom` lib now uses an interfaces and variable declaration. It should be possible to do the same on the Node side and fix issue I think.

The issue is that global classes are not merged, but interfaces should work fine.

By testing locally, I was able to use the global URL, with all the configurations: `node`, `dom`, and both.

**Closed** 2022-02-01 08:08 UTC

**Comment by thw0rted** [comment] 2022-02-01 09:04
Just to confirm, this new fix means that we no longer need to `import {URL} from "url"` in Node?  That's good, but as I understand it that also means that if the DOM and Node implementations ever diverge in the future, authors of universal libraries will start getting merge errors, right?  I guess that's a bridge to cross when we come to it.

**Comment by antongolub** [comment] 2022-02-01 09:38
It's hard to say what will happen in the future. But here is what we have now: we can compose '@types/node' with `lib: ['dom']` or without (`lib: ['es2020']'`) and remove mentioned `import {URL} from "url"` workaround from our code.

**Comment by aaronatbissell** [comment] 2022-02-01 19:17
A combination of @types/node and typescript: 3.7.3 yields:

```
../../node_modules/.registry.npmjs.org/@types/node/12.20.43/node_modules/@types/node/url.d.ts:137:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'URLSearchParams' must be of type '{ new (init?: string | string[][] | URLSearchParams | Record<string, string>): URLSearchParams; prototype: URLSearchParams; }', but here has type '{ new (init?: string | string[][] | URLSearchParams | Record<string, string>): URLSearchParams; prototype: URLSearchParams; toString(): string; }'.

137         var URLSearchParams: {
                ~~~~~~~~~~~~~~~

  ../../node_modules/.registry.npmjs.org/typescript/3.7.3/node_modules/typescript/lib/lib.dom.d.ts:16107:13
    16107 declare var URLSearchParams: {
                      ~~~~~~~~~~~~~~~
    'URLSearchParams' was also declared here.
```

Is there a good workaround for this now?

**Comment by antongolub** [comment] 2022-02-01 19:41
@aaronatbissell,

I'm afraid that only TS 3.8.2+ seems to be working. This is due to `URLSearchParams` var declarations mismatch:

[v3.7.3 lib/dom.generated.d.ts#L16087](https://github.com/microsoft/TypeScript/blob/v3.7.3/src/lib/dom.generated.d.ts#L16087)
```ts
declare var URLSearchParams: {
    prototype: URLSearchParams;
    new(init?: string[][] | Record<string, string> | string | URLSearchParams): URLSearchParams;
};
```

[v3.8.2 lib/dom.generated.d.ts#L16136](https://github.com/microsoft/TypeScript/blob/v3.8.2/src/lib/dom.generated.d.ts#L16136)
```ts
declare var URLSearchParams: {
    prototype: URLSearchParams;
    new(init?: string[][] | Record<string, string> | string | URLSearchParams): URLSearchParams;
    toString(): string;
};
```

**Comment by thw0rted** [comment] 2022-02-02 10:24
Check out https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25677 -- DT versioning is a pain and a half, and I don't think there's a great answer yet.  That issue does link to some changes in the README, which gave us [this section](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).

For the version-specific fixes you're looking at, [the typesVersions feature](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-very-new-typescript-versions), which lets you specify different typings for different TS versions.  I said in the thread I linked above, I'm not sure how that interacts with different directories for different major library versions (Node already has /v12, /v14, etc), but it "should" be possible to provide different types to different TS versions.  (It's just likely to result in a *lot* of duplication...)

**Comment by antongolub** [comment] 2022-02-02 12:09
I see three ways:
1) Add '// Minimum TypeScript Version: 3.8.3' annotation to the libdef
2) Separate typings for TS <=3.8
3) Use the mentioned above janky workaround.

I really can't decide which is the less evil.

CC @peterblazejewicz, @weswigham, @gabritto
