### ISSUE TITLE
@types/react

### ISSUE THREAD

**Issue by adostal** [DefinitelyTyped/DefinitelyTyped#20812] opened 2017-10-22 10:03 UTC
In type definition @types/react is bug in interface LinkHTMLAttributes.

<img width="1680" alt="snimek obrazovky 2017-10-22 v 12 02 25" src="https://user-images.githubusercontent.com/13852854/31860812-07c3f30c-b721-11e7-9986-a3a7b46e3a63.png">

**Comment by Yanivox** [comment] 2017-10-22 11:30
same here
`[at-loader] ./node_modules/@types/react/index.d.ts:2785:9    
TS2300: Duplicate identifier 'as'.`

<img width="517" alt="screen shot 2017-10-22 at 14 30 11" src="https://user-images.githubusercontent.com/1440203/31861415-95ee95a6-b735-11e7-9e6a-3aedac386b05.png">

**Comment by jas0ncn** [comment] 2017-10-22 12:11
same issue.
u can just remove line 2793 and then it works as before.

**Comment by dawnmist** [comment] 2017-10-22 12:13
There's now *4* pull requests to fix this, but due to the change a day ago to the JSDoc rules all the packages that *use* react now fail to lint, resulting in a spurious (as far as react itself is concerned) Travis CI failure.

It is essential that *one* of the pull requests get merged (not all 4 - or we'll risk ending up in the reverse of the current situation, which was caused by merging duplicated pull requests).

Current list of pull requests to fix this:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20808
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20809
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20811
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20815

**Comment by pocesar** [comment] 2017-10-22 12:20
I wonder how did this even got merged

**Comment by kyaroru** [comment] 2017-10-22 12:49
having same error while trying to integrate React Native with TypeScript :)

**Comment by adostal** [comment] 2017-10-22 12:52
Now we must set older version in package.json:

from:
`"@types/react": "^16.0.17",`

to:
`"@types/react": "16.0.16",`

**Comment by dawnmist** [comment] 2017-10-22 13:20
@pocesar From what I could see, there were 2 pull requests merged about 12-24 hours apart that were both adding the new "as" field - one to the beginning of the interface and one to the end. They were both tested against the types as they existed prior to either of them being merged, and the individual lines between the two didn't conflict...

The issue was that when one pull request was merged it did not trigger retesting the second pull request by the Travis CI tests, so the fact that the second pull request was invalidated by the merge of the first wasn't detected. This then meant that the second was subsequently also merged some hours later.

That's why I am a little concerned about there being several pull requests new to fix the issue - if all 4 were to be processed we will likely lose the "as" parameter entirely in essentially a repetition of the original error of double merging of its addition caused by duplicate pull requests.

**Comment by dawnmist** [comment] 2017-10-22 13:28
Make that 5 pull requests now - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20816/files

And another issue report - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20818

**Comment by pocesar** [comment] 2017-10-22 15:34
@dawnmist makes sense, since the CI was erroring out, it went unnoticed

**Comment by leonardfactory** [comment] 2017-10-22 16:15
As a temporary fix for anyone who stumbled upon this, if you're using Yarn, just add previous version in [`resolutions`] package.json section:

```json
  ...,
  "resolutions": {
    "@types/react": "16.0.16"
  },
```

**Comment by orta** [comment] 2021-06-07 14:10
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:10 UTC
