### ISSUE TITLE
[react-native] support Animated.Value in properties

### ISSUE THREAD

**Issue by hktonylee** [DefinitelyTyped/DefinitelyTyped#12202] opened 2016-10-24 10:36 UTC
- [x] I tried using the latest `react-native/react-native.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

All the properties in `ViewStyle` do not support `Animated.value`. Is it a good idea to add animation support to the type definition?

For example, `tsc` will report error on this code snippet:

```
someStyle: {
    opacity: new Animated.Value(0),
}
```

**Comment by vvakame** [comment] 2016-10-25 14:24
please send a pull request. I'll review it.

**Comment by alloy** [comment] 2017-03-23 10:59
There should probably be a `Animated.ViewStyle` for `Animated.View` indeed. Please do submit a PR.

**Comment by vonweb** [comment] 2017-07-06 07:13
@hktonylee Did you have any solution now

**Comment by hktonylee** [comment] 2017-07-07 11:18
@vonweb Sorry I don't have solution right now. Thanks for reminding me about this problem and I will revisit it later.

**Comment by chrismcleod** [comment] 2017-11-08 18:41
@vonweb a temp solution to get rid of typescript errors is to cast twice like this, though you lose type safety:

```typescript
const style = {
  opacity: new Animated.Value(0)
} as any as ViewStyle
```

**Comment by rodrigoelp** [comment] 2018-01-05 00:37
I notice this issue has been for more than a year and I tried to change the definition myself, trying to understand what the problem is. I got a lot of red and I am not sure why.

( below was my stupid attempt to "fix" it)
```ts
export interface ViewStyle extends FlexStyle, TransformsStyle {
  ...
  opacity?:  number | Animated.Value; // no?... nop.. :(
}
```

I guess not many try to do animations in react native with typescript :(

**Comment by stantoncbradley** [comment] 2018-08-15 22:58
also, these types don't seem to be correct either:
```
export interface TransformsStyle {
    transform?: (
        | PerpectiveTransform
        | RotateTransform
        | RotateXTransform
        | RotateYTransform
        | RotateZTransform
        | ScaleTransform
        | ScaleXTransform
        | ScaleYTransform
        | TranslateXTransform
        | TranslateYTransform
        | SkewXTransform
        | SkewYTransform)[];
    transformMatrix?: Array<number>;
    rotation?: number;
    scaleX?: number;
    scaleY?: number;
    translateX?: number;
    translateY?: number;
}
```
I can open a pr for that one

**Comment by rodrigoelp** [comment] 2018-08-15 23:12
Hi @stantoncbradley, I end up applying the style directly to the object as part of my declaration.

You can find some of my sample code [here](https://github.com/rodrigoelp/reactnative-typescript-exercise-19/blob/2082e3019638e51a8799f97959a0d4f76bbb6593/src/index.tsx#L137). Unfortunately, I tried to understand with proper examples in typescript but I couldn't find that many online (which is a true shame).

**Comment by stantoncbradley** [comment] 2018-08-15 23:28
@rodrigoelp thanks for sharing! These values still look like they are of type Animated.Value. how does does that get validated against Animated.View's style type, which doesn't support Animated.Value?

**Comment by rodrigoelp** [comment] 2018-08-16 07:35
If you check the type definition, they extend some objects in the `Animated` namespace, in which the definition redeclares `View` as any... (effectively allowing any definition).

I imagine once you start including new stuff there typescript has no way of validating it anymore.

**Comment by rodrigoelp** [comment] 2018-08-16 07:37
The definition of Animated starts [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L8173)

And the redefinition of `View` is [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L8490)

**Comment by stantoncbradley** [comment] 2018-08-17 21:40
workaround to include both AnimatedValues on properties like 'opacity', and on nested transforms properties (transform: [{ translateY: animatedValue }]):

```
export type ExtendedTextStyles = StyleProp<{
  [key in keyof TextStyle] : (
    Animated.Value | TextStyle[key] |
    [{ [key in keyof TransformsStyle] : Animated.Value | TransformsStyle[key] }]
  );
}>
```
credit to @danielwong2268

**Comment by stantoncbradley** [comment] 2018-08-21 17:57
@rodrigoelp ok I finally figured it out, thanks your comments were very helpful!
For anyone else who ends up here, the Animated types are correct, if a little confusing.
As it stands, all the `View`, `Text`, and `Image` styles only apply to those components, not to their animated counterparts (ie `Animated.View`). That's because, as @rodrigoelp pointed out, `Animated` redefines `Animated.View`, `Animated.Text`, and `Animated.Image` as type `any`. So, for example, the `TransformsStyles` that are listed as type `number` when I would expect type `Animated.Value`, ie `translateX?: number;`, is correct, because this is the only valid type for `translateX` on the non-animated components, and the animated components use type `any`, so they don't even use the `TransformsStyles` type at all.  I closed my PR above, and think this issue can be closed as well.

**Comment by pie6k** [comment] 2019-03-21 11:25
I've made 'kind of' type that converts any view styles into animatable styles.

```ts
type MaybeAnimated<T> = T | Animated.Value;
type AnimatedScalar = string | number;

type AnimatedStyles<T> = {
  [Key in keyof T]: T[Key] extends AnimatedScalar
    ? MaybeAnimated<T[Key]>
    : T[Key] extends Array<infer U>
    ? Array<AnimatedStyles<U>>
    : AnimatedStyles<T[Key]>
};

type ViewAnimatedStyles = AnimatedStyles<ViewStyle>;

const test: ViewAnimatedStyles = {
  transform: [
    {
      rotateY: new Animated.Value(2),
    }
  ]
}
```

You get auto-suggestions and animated values work.

Limitation:
`Animated.Value` definition under the hood is just empty class so technically, everything will match it. So you'll be able to assign an incorrect value to it (eg plain string instead of number)

**Comment by reactnative098** [comment] 2019-05-15 14:19
Hello My friend
why Animated.Value and Animated.timing are ((Unresolved type Value))
and my code not run









/** @format */
import { AppRegistry} from 'react-native';
import React from 'react';
import {View,Image , Animated} from 'react-native';

class App extends React.Component{
    constructor(props){
        super(props);

        this.spinValue = new Animated.Value(0)
    }
    componentWillMount(){
        Animated.timing(this.spinValue,{
            toValue: 1,
            duration: 3000,
        }).start();
    }

    render(){
        const spin = this.spinValue.interpolate({
            inputRange: [0,1],
            outputRange: ['0deg', '360deg']
        });
       return(
           <View style={{flex:1,justifyContent:'center', alignItems:'center'}}>
               <Image source={require('./src/images/a.png')} style={{width:100,height:100, transform:[{ rotate: spin }]}}/>
           </View>
       )
    }
}


AppRegistry.registerComponent('ReactApp', () => App);

**Comment by hsource** [comment] 2020-06-16 20:50
This seems to be supported in the latest types:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aa4ea25/types/react-native/index.d.ts#L8770

They're still a bit buggy, but better than nothing!

**Comment by alloy** [comment] 2020-06-17 09:24
@hsource Thanks for the bump, in the interest of repo hygiene I’ll close this 🙏

**Comment by alloy** [comment] 2020-06-17 09:25
@hsource Oh and if you have specific cases that are buggy but don’t know of a fix; a PR that adds test cases illustrating the issue(s) is a great first step towards solving this together.

**Closed by alloy** 2020-06-17 09:24 UTC
