### ISSUE TITLE
@types/angular throwing IScope errors

### ISSUE THREAD

**Issue by rissicay** [DefinitelyTyped/DefinitelyTyped#18196] opened 2017-07-19 01:41 UTC
I tried using the `@types/angular` package and had problems.
I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

The new version of @types/angular throws errors when adding properties to $scope variable.

error TS2339: Property 'changeTab' does not exist on type 'IScope'.

Is there a way to fix this? I'm assuming this is a bug??

**Comment by TomSeldon** [comment] 2017-07-19 09:54
Hi @rissicay,

I've just run into the same issue. It's related to a breaking change published in the latest patch version (!) of types/angular, that was released about 14hrs ago.

The change is that you can no longer specify arbitrary keys on ng.IScope (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2cde2fb1edb6952211f4b555583810c106dadb94).

Good news is that it's an easy fix.

Where you're currently using `ng.IScope`, instead create a new interface that extends scope to use in your component/directive/whatever.

e.g.

```typescript
// before
function (scope: ng.IScope) {
  scope.changeTab(); // type error
}
```

```typescript
interface MyDirectiveScope extends ng.IScope {
  changeTab: any; // replace any with actual type
}

function (scope: MyDirectiveScope) {
  scope.changeTab(); // all is right with the world again
}
```

**Comment by rissicay** [comment] 2017-07-19 10:14
Was this released as a patch or a minor in the version bump?

This is a pretty big change for legacy angular apps.

**Comment by TomSeldon** [comment] 2017-07-19 10:33
`npm view @types/angular` shows this was a patch release from `1.6.26` to `1.6.27`.

```json
     '1.6.25': '2017-06-29T14:49:08.248Z',
     '1.6.26': '2017-07-12T21:17:02.859Z',
     '1.6.27': '2017-07-18T19:27:00.407Z'
```

I've never actually checked `@types` follows semantic versioning, I just assumed that was the case. Realistically this seems like it should have been a major release (as it's a breaking change).

**Comment by rissicay** [comment] 2017-07-19 11:43
I also assumed it was following semantic versioning.

I hope the core contributors consider following semantic versioning eventually. It is a major pain having your CI/CD environments all fail while making test/production builds because of a patch bump, but then it can be argued the versions in the package.json should of been fixed versions.

As for the scope change, I personally am against it, for the simple fact that a lot of people on angular 1 are there because of large legacy code bases. I realize that modern angular js, everything is a component now, but the road to code base completely updated is long... oh so very long.

**Comment by TomSeldon** [comment] 2017-07-19 12:17
Same. It's hard to be angry when at least 50% of the problem is due to not locking down dependencies properly. Though, upgrading to a patch release obviously shouldn't cause breaking changes.

**Comment by pablorsk** [comment] 2017-07-22 16:39
## Solution

### Step one: quick solution
```
npm install @types/angular@1.6.26 --save-dev
```
Now, your `package.json` show this:
```
"@types/angular": "1.6.26",
```
### Step two: plan to fix the error

See [oficial documentation about angularjs scope](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/angular#a-word-on-scope-and-assigning-new-members). If you like see the discussion about this change, check [this issue](https://github.com/Microsoft/TypeScript/issues/12596#issuecomment-299976171).

**Comment by jesuslpm** [comment] 2017-11-17 11:30
Another solution is [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). 
Add a new `d.ts` file to your project with the following content:
```typescript
import { IRootScopeService } from 'angular';

declare module 'angular' {
    interface IRootScopeService {
        [key: string]: any;
    }
}
```

**Comment by orta** [comment] 2021-06-07 13:22
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:22 UTC
