### ISSUE TITLE
@types/redux-form: I can't get it passing type check

### ISSUE THREAD

**Issue by testerez** [DefinitelyTyped/DefinitelyTyped#19727] opened 2017-09-13 19:03 UTC
I tried using the `@types/redux-form@7.0.5` package and had problems (am I doing something wrong):

```ts
import * as React from 'react';
import { reduxForm, FormProps } from 'redux-form';

@reduxForm({ form: 'test-form' })
// [ts]
// Argument of type 'typeof ShareModalForm' is not assignable to parameter of type 'ComponentType<InjectedFormProps<{}, {}>>'.
//   Type 'typeof ShareModalForm' is not assignable to type 'StatelessComponent<InjectedFormProps<{}, {}>>'.
//     Type 'typeof ShareModalForm' provides no match for the signature '(props: InjectedFormProps<{}, {}> & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
export class MyForm extends React.Component<FormProps> {
  render() {
    return <form onSubmit={this.props.onSubmit}>test</form>;
    // [ts]
    // Type '{ onSubmit: FormSubmitHandler<{}, {}> | undefined; children: string; }' is not assignable to type 'DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>'.
    //   Type '{ onSubmit: FormSubmitHandler<{}, {}> | undefined; children: string; }' is not assignable to type 'FormHTMLAttributes<HTMLFormElement>'.
    //     Types of property 'onSubmit' are incompatible.
    //       Type 'FormSubmitHandler<{}, {}> | undefined' is not assignable to type 'EventHandler<FormEvent<HTMLFormElement>> | undefined'.
    //         Type 'FormSubmitHandler<{}, {}>' is not assignable to type 'EventHandler<FormEvent<HTMLFormElement>> | undefined'.
    //           Type 'FormSubmitHandler<{}, {}>' is not assignable to type 'EventHandler<FormEvent<HTMLFormElement>>'.
  }
}
```

Authors: @carsonf @aikoven @LKay @bancek @alsiola

**Comment by LKay** [comment] 2017-09-14 01:47
Like the error message says, you have incorrect types provided as submit handler. Can't tell more without seeing actual code.

**Comment by testerez** [comment] 2017-09-14 01:58
This is all the code... I think that this example should compile. But maybe I'm not using the types as intended... `onSubmit` is coming from `FormProps` interface imported from `@types/redux-form@7.0.5`

**Comment by LKay** [comment] 2017-09-14 02:05
This is incorrect: `React.Component<FormProps>`, `FormProps` are reserved to use with `Form` component. You should be using `InjectedFormProps` here.

**Comment by testerez** [comment] 2017-09-14 02:47
Thanks! this is in fact fixing the second error but not the first one:
```tsx
import * as React from 'react';
import { reduxForm, InjectedFormProps } from 'redux-form';

@reduxForm({ form: 'test-form' })
// [ts]
// Argument of type 'typeof ShareModalForm' is not assignable to parameter of type 'ComponentType<InjectedFormProps<{}, {}>>'.
//   Type 'typeof ShareModalForm' is not assignable to type 'StatelessComponent<InjectedFormProps<{}, {}>>'.
//     Type 'typeof ShareModalForm' provides no match for the signature '(props: InjectedFormProps<{}, {}> & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
export class MyForm extends React.Component<InjectedFormProps> {
  render() {
    return <form onSubmit={this.props.onSubmit}>test</form>;
  }
}

```

**Comment by testerez** [comment] 2017-09-15 02:43
I gave up on the decorator syntax and use compose. Fixes my typing issue.

**Comment by LKay** [comment] 2017-09-15 05:20
Oh, I just noticed you're using decorator `@reduxForm` syntax. This is still not fully specified and experimental feature in Typescript. Use HOC way of decorating your component.

**Comment by testerez** [comment] 2017-09-15 05:34
It's what I did (with `compose`) 👍 
Thanks for the answer!

**Comment by npeham** [comment] 2018-04-18 22:53
@testerez I'm getting the same errors as you. Could you please post your working code where you get no compile errors? Especially the decorate/compose part of your component with reduxForm. Thank you!

**Comment by npeham** [comment] 2018-04-19 18:13
@testerez thank you very much I solved my issues! For me, it was a little bit tricky because I use es6 classes for my react components and I am not familiar with the redux compose function. In addition to that I use the JSS feature from material-ui-next and there I have to wrap my component with the withStyles HOC for getting my style classes working. This compose function is a really nice and clean thing.

The only thing that I changed is that I wrote an default export. So I don't have to create a extra constant and name it (in your example MyForm) for exporting the component:
```
export default compose(
    reduxForm({form: 'employeeDateSelect'}),
    withStyles(styles)
)(EmployeeDateSelect); // ES6 class
```

**Comment by iwgx** [comment] 2019-04-27 19:07
Here how I'm solved this issue for anyone that still wondering, basically same with solution above. Using `InjectedFormProps`
```tsx
import React, { Component } from "react";
import { Field, reduxForm, InjectedFormProps } from "redux-form";
import { Input } from "reactstrap";
import { connect } from "react-redux";

class ComponentsNavbar extends Component<InjectedFormProps, {}> {
  renderField = ({ input }: any) => {
    return <Input type="text" {...input} />
  };

  render() {
    return (
      <Field name="search" component={this.renderField} />
    );
  }
}

const formWrapper = reduxForm({ form: "search" })(Navbar);

export default connect(null)(formWrapper);
```

**Comment by mateja176** [comment] 2019-06-04 14:55
Reproduced on [stackblitz](https://stackblitz.com/edit/redux-form-demo?file=ContactForm.tsx) with `reduxForm` HOC

**Comment by orta** [comment] 2021-06-07 13:22
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:22 UTC
