### ISSUE TITLE
../node_modules/@types/knockout/index.d.ts:1060:13 - error TS2403

### ISSUE THREAD

**Issue by sheryf** [DefinitelyTyped/DefinitelyTyped#37490] opened 2019-08-09 03:20 UTC
../node_modules/@types/knockout/index.d.ts:1060:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'ko' must be of type 'typeof import(".../node_modules/knockout/build/types/knockout")', but
here has type 'KnockoutStatic'.

1060 declare var ko: KnockoutStatic;

knockout.d.ts(5, 1): 'ko' was also declared here.

**The above fails to compile the index.d.ts type definition file.** 
As read in a stackoverflow comment, this is a **Typescript augmentation issue.** Is there a fix or patch available for this? 

I'm new to Typescript and this is a frustrating compile headache. 

My work around was to rename var ko to something else e.g. kot and the corresponding export value in the index.d.ts file @1060. Every fiber in my body knows this cant be right but compilation works for my js application.

kindly advice/ fix

**Comment by Tabueeee** [comment] 2019-10-06 18:48
So i just ran into this problem myself and found this issue. The problem is not fixable in this repo because this issue is caused by using @types/knockout. 
You can fix this issue by just deleting @types/knockout because knockout provides it's own typings. You may need to re-import some types tough because they have different names in @types/knockout.

**Comment by ViceIce** [comment] 2019-10-15 07:55
I'll send a pr to remove knockout and fix depending packages

**Comment by Paule97** [comment] 2020-04-06 10:05
Help me too. I have the same problem but can't fix it

**Comment by viceice** [comment] 2020-04-06 10:27
@Paule97 My current workaround is a `.yarnclean` file

```
@types/knockout/
```

So yarn will wipe the types after install

**Comment by orta** [comment] 2021-06-07 14:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:09 UTC
