### ISSUE TITLE
[redux-form] Incorrect typings for FieldArray

### ISSUE THREAD

**Issue by BEGEMOT9I** [DefinitelyTyped/DefinitelyTyped#36903] opened 2019-07-15 16:05 UTC
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @m-b-davis @aikoven @LKay @bancek @Aleksion @weswigham

Using a `<FieldArray>` to create custom class-based component in TypeScript 3.5+ fails. Something wrong with props interfaces (`WrappedFieldArrayProps`, `BaseFieldArrayProps`). Here is an example: https://codesandbox.io/s/kind-shadow-us55u

Installed dependencies:
- redux-form@8.2.4
- @types/redux-form@8.1.4

If you are trying to use `BaseFieldArrayProps` with `WrappedFieldArrayProps`, the following error appears:
```
Type 'typeof CustomComponent' is not assignable to type 'ComponentClass<WrappedFieldArrayProps<any> & { name: "any_string"; component: typeof CustomComponent; customProp: string; }, any> | FunctionComponent<WrappedFieldArrayProps<any> & { name: "any_string"; component: typeof CustomComponent; customProp: string; }> | (typeof CustomComponent & ComponentClass<...>) | (typeo...'.
  Type 'typeof CustomComponent' is not assignable to type 'ComponentClass<WrappedFieldArrayProps<any> & { name: "any_string"; component: typeof CustomComponent; customProp: string; }, any>'.
    Type 'CustomComponent' is not assignable to type 'Component<WrappedFieldArrayProps<any> & { name: "any_string"; component: typeof CustomComponent; customProp: string; }, any, any>'.
      Types of property 'props' are incompatible.
        Type 'Readonly<CustomComponentProps> & Readonly<{ children?: ReactNode; }>' is not assignable to type 'Readonly<WrappedFieldArrayProps<any> & { name: "any_string"; component: typeof CustomComponent; customProp: string; }> & Readonly<{ children?: ReactNode; }>'.
          Type 'Readonly<CustomComponentProps> & Readonly<{ children?: ReactNode; }>' is not assignable to type 'Readonly<WrappedFieldArrayProps<any> & { name: "any_string"; component: typeof CustomComponent; customProp: string; }>'.
            Types of property 'name' are incompatible.
              Type 'string' is not assignable to type '"any_string"'.ts(2322)
``` 

You couldn't use only `BaseFieldArrayProps`, because you need `fields` and `meta` props. With only `WrappedFieldArrayProps` you must define `name` and `component` props. I don't understand, how to fix this collision.

**Comment by m-b-davis** [comment] 2019-07-15 16:31
I'm not 100% sure on the structure of your interfaces here but I think I know what you mean.

There's two ways you can do this.

Passing props as an explicit prop in your parent (I think this is the simplest way, and more TS friendly)

```
interface CustomProps {
  customProp: string;
}

interface CustomComponentProps extends WrappedFieldArrayProps<any>, CustomProps {} 

class CustomComponent extends React.PureComponent<CustomComponentProps, {}> {
  render() {
    return null;
  }
}

const FieldArrayComponent = () => (
  <FieldArray
    name="any_string"
    component={CustomComponent}
    props={{
      customProp: "custom_prop"
    }}
  />
);
```

Or - if you need to pass these props through the parent then you need to define a separate CustomFieldArray class:

```
interface CustomProps {
  customProp: string;
}

interface CustomComponentProps extends WrappedFieldArrayProps<any>, CustomProps {} 

class CustomComponent extends React.PureComponent<CustomComponentProps, {}> {
  render() {
    return null;
  }
}

const FieldArrayCustom = FieldArray as new () => GenericFieldArray<any, CustomProps>;

const FieldArrayComponent2 = () => (
  <FieldArrayCustom
    name="any_string"
    component={CustomComponent}
    customProp= "custom_prop"
  />
);
```

You could do option #2 with inline generics in jsx, but it's a bit ugly:


```
const FieldArrayComponent2 = () => (
  <FieldArray<any, CustomProps>
    name="any_string"
    component={CustomComponent}
    customProp= "custom_prop"
  />
);
```

Here's the sandboxed example:
https://codesandbox.io/s/intelligent-cookies-s6xws

**Comment by BEGEMOT9I** [comment] 2019-07-16 12:00
@m-b-davis Well, thank you. As I understand it, if there is a need to use custom props, it is implied that I pass them through the `props`. At the same time, the typization of custom properties is partially lost and you need to memoize custom properties so that the rerender does not occur?
And one more question. If you use a custom component without additional properties, then without the `props` property, an error is thrown out (updated the original example: https://codesandbox.io/s/kind-shadow-us55u). How, then, is the component's interface correctly defined?

**Comment by m-b-davis** [comment] 2019-07-16 20:45
@BEGEMOT9I I'm not too sure on how memoization would work in this case without digging into it further...useMemo could be the answer if you need a workaround.

The case without any props is an interesting one actually. The way we set up the type was to supply a default argument of an empty object for props. In this case it's not actually working like that.

If we declare the array with types for props and array value, then it works as intended, i.e:

```
<FieldArray<{}, any>
        name="abc"
        component={CustomComponent}
 />
```
This could work if you need a workaround for no custom props.

But if you leave it to infer it, as it resolves down then we hit the type BaseFieldArrayProps, which P or {props: P} combined with BaseFieldArrayProps.

export type BaseFieldArrayProps<P = {}, FieldValue = any> = (P | { props: P}) & _BaseFieldArrayProps<P, FieldValue>;

This seems to to infer P as ALL the props to FieldArray - instead of removing name and valid and inferring the remainder.

Perhaps manually picking out these in BaseFieldArrayProps could help....haven't tested it but I'll look to do so at some point:

```
export type BaseFieldArrayProps<P = {}, FieldValue = any> = (Pick<P, Exclude<keyof P, 'name' | 'valid>> | { props: P}) & _BaseFieldArrayProps<P, FieldValue>;
```

**Comment by BEGEMOT9I** [comment] 2019-07-17 12:02
@m-b-davis May be just making `props` as optional param?

**Comment by orta** [comment] 2021-06-07 13:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:11 UTC
