### ISSUE TITLE
[@types/eslint] v8.4.4 missing from NPM registry 

### ISSUE THREAD

**Issue by TheNickm2** [DefinitelyTyped/DefinitelyTyped#61032] opened 2022-06-30 19:39 UTC
v8.4.4 of `@types/eslint` appears to be corrupt or missing from the NPM registry.

The latest version appears to have no README, nor is the tarball available via the NPM registry. 

Screenshot below shows v8.4.4 "README" is missing
![image](https://user-images.githubusercontent.com/25287325/176762980-c9a2978c-10cf-4c72-ad8f-a1e3f64c11d2.png)

NPM unable to find the tarball
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Update: This is almost certainly an issue with the NPM registry: https://status.npmjs.org/incidents/6wr25yb0b2dd - Leaving this issue open until the NPM registry issue is resolved to see if additional action items are necessary for the DefinitelyTyped team to fix the broken package (e.g. push another minor change to trigger the CI/CD again after the outage ends)

**Comment by subhankar-trisetra** [comment] 2022-06-30 19:41
Same Issue:
```
Arguments: 
  /Users/apple/.nvm/versions/node/v14.19.3/bin/node /Users/apple/.nvm/versions/node/v14.19.3/bin/yarn

PATH: 
  /Users/apple/.pyenv/shims:/Users/apple/.nvm/versions/node/v14.19.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Apple/usr/bin:/Users/apple/.nvm/versions/node/v14.19.3/bin

Yarn version: 
  1.22.19

Node version: 
  14.19.3

Platform: 
  darwin x64

Trace: 
  Error: https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/Users/apple/.nvm/versions/node/v14.19.3/lib/node_modules/yarn/lib/cli.js:696:66)
      at new ResponseError (/Users/apple/.nvm/versions/node/v14.19.3/lib/node_modules/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/Users/apple/.nvm/versions/node/v14.19.3/lib/node_modules/yarn/lib/cli.js:66215:16)
      at Request.emit (events.js:400:28)
      at Request.module.exports.Request.onRequestResponse (/Users/apple/.nvm/versions/node/v14.19.3/lib/node_modules/yarn/lib/cli.js:141767:10)
      at ClientRequest.emit (events.js:400:28)
      at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
      at HTTPParser.execute (<anonymous>)
      at TLSSocket.socketOnData (_http_client.js:515:22)

```

**Comment by trevordilley** [comment] 2022-06-30 19:43
Meeee toooo....

```
➜  application git:(migrate-to-nx) ✗ npm install -D @nrwl/react
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz - Not found
npm ERR! 404
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trevordilley/.npm/_logs/2022-06-30T19_38_53_264Z-debug-0.log
```

**Comment by rosskevin** [comment] 2022-06-30 19:43
And you can see there are zero successful downloads from the npmjs registry https://www.npmjs.com/package/@types/eslint

This is a bad package published, we need another pushed.  


![_types_eslint_-_npm](https://user-images.githubusercontent.com/136564/176763737-590c20c3-95c7-4b98-949c-bbd8d6a86c27.jpg)

**Comment by jeanfbs** [comment] 2022-06-30 19:44
Same error here, please anyone can see this issue with urgency

**Comment by willocho** [comment] 2022-06-30 19:44
The workaround is to pin @types/eslint to version 8.4.3 in your package.json

**Comment by jeanfbs** [comment] 2022-06-30 19:46
> The workaround is to pin @types/eslint to version 8.4.3 in your package.json

But for accross dependencies will not work :(

**Comment by snyamathi** [comment] 2022-06-30 19:49
```
$ curl -I https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz
HTTP/1.1 404 Not Found
```

**Comment by jeanfbs** [comment] 2022-06-30 19:52
> ```json
>   "resolutions": {
>     "@types/eslint": "8.4.3"
>   }
> ```

thanks @rosskevin

**Comment by mamadfar** [comment] 2022-06-30 19:56
saaaaaaaaaaaaaammmmmmmeeeeeee

**Comment by ivanbor8** [comment] 2022-06-30 19:57
> > @jeanfbs pin it in `resolutions`
> > ```json
> >   "resolutions": {
> >     "@types/eslint": "8.4.3"
> >   }
> > ```
> 
> Thanks, but won't work with npm versions that don't support resolutions. :c

Try installing the dependency locally with version 8.4.3 **temporarily**. It worked for me 😉

` npm i -D @types/eslint@8.4.3`

**Comment by hheavener-kyd** [comment] 2022-06-30 20:07
> guys just use `npm i @types/eslint@8.4.3` and done !

This doesn't work inside of a CI/CD pipeline where it's being required as a dependency of a dependency

**Comment by mamadfar** [comment] 2022-06-30 20:08
> > guys just use `npm i @types/eslint@8.4.3` and done !
> 
> This doesn't work inside of a CI/CD pipeline where it's being required as a dependency of a dependency

You're right but if you use docker, you can add another command to install @types/eslint before npm i

**Comment by kursonix** [comment] 2022-06-30 20:09
ehhh time to do some break :)

**Comment by hheavener-kyd** [comment] 2022-06-30 20:14
@wlee221

Ok so I added the `overrides` property to the `package.json` and tried running `npm i` to see if it would install 8.4.3 but I'm still getting the 404 error for 8.4.4. Am I missing something here? I've never needed to use overrides before so I'm not sure if I'm using it wrong or if it isn't working

**Comment by DenkSchuldt** [comment] 2022-06-30 20:15
> guys just use `npm i @types/eslint@8.4.3` and done !

This worked! ⭐⭐⭐⭐⭐

**Comment by hheavener-kyd** [comment] 2022-06-30 20:16
@rosskevin do we know if this is something that will be fixed today?

**Comment by darryl-monks** [comment] 2022-06-30 20:17
Can't run `npx create-react-app my-app`

**Comment by cgat** [comment] 2022-06-30 20:19
Same with the NestJS app generator `nest new myapp`

**Comment by Code-Conjurer** [comment] 2022-06-30 20:20
> Can't run `npx create-react-app my-app`

Same issue. Does anyone know a work-around, without having to setup react manually 😅

**Comment by martellato** [comment] 2022-06-30 20:22
> > Can't run `npx create-react-app my-app`
> 
> Same issue. Does anyone know a work-around, without having to setup react manually sweat_smile

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61032#issuecomment-1171610007

**Comment by CarlosJunioor** [comment] 2022-06-30 20:23
im legit having the same issue too.

**Comment by amareshsm** [comment] 2022-06-30 20:25
> > Can't run `npx create-react-app my-app`
> 
> Same issue. Does anyone know a work-around, without having to setup react manually 😅


Try adding the resolutions field.

```JSON

  "resolutions": {
    "@types/eslint": "8.4.3"
  },
```

**Comment by hheavener-kyd** [comment] 2022-06-30 20:25
> im legit having the same issue too.

As opposed to having the issue illegitimately?

**Comment by MehdiBenbahri** [comment] 2022-06-30 20:26
Same here... I just wanted to start making cool react app and then one of the most used package manager was shut down...
If you look carefully https://registry.npmjs.org/ and https://api.npmjs.org/downloads are down too...

**Comment by darryl-monks** [comment] 2022-06-30 20:27
First free night in a while and thought I'd do some React then run into this problem 😢 

Tried adding the resolutions property to `package.json` but running the command to create new react app doesn't work if there's an existing package file.

**Comment by cakirlarc** [comment] 2022-06-30 20:27
Serious issue for CI pipelines, needs urgent action.

**Comment by MehdiBenbahri** [comment] 2022-06-30 20:29
> I thought I was going mad, legit reinstalled both node and npm twice

This impostor syndrome when you try to learn react and you realize that you can't install a simple app.... xD

**Comment by SirVizzy** [comment] 2022-06-30 20:30
> First free night in a while and thought I'd do some React then run into this problem 😢
> 
> Tried adding the resolutions property to `package.json` but running the command to create new react app doesn't work if there's an existing package file.

Not even a free night and I wasted an hour trying to figure this out haha

**Comment by Rangyia** [comment] 2022-06-30 20:30
Guess this is a good time to learn how to build it from scratch 🗡️

**Comment by gabovanlugo** [comment] 2022-06-30 20:32
I can't create a new side project with CRA.

**Comment by darryl-monks** [comment] 2022-06-30 20:32
> > First free night in a while and thought I'd do some React then run into this problem 😢
> > Tried adding the resolutions property to `package.json` but running the command to create new react app doesn't work if there's an existing package file.
> 
> Not even a free night and I wasted an hour trying to figure this out haha

Haha I should have just gone on the PS5 as I'd planned but thought I'd be productive for a change.

**Comment by DrunkOldDog** [comment] 2022-06-30 20:33
> Guess this is a good time to learn how to build it from scratch 🗡️

![image](https://c.tenor.com/iDYg-7xD7M4AAAAC/burning-office-spongebob.gif)

**Comment by diegodsgarcia** [comment] 2022-06-30 20:33
Me 5 mins ago: It's not possible that eslint posted an empty NPM....
Me now: No way.... :O

**Comment by MehdiBenbahri** [comment] 2022-06-30 20:33
> Guess this is a good time to learn how to build it from scratch 🗡️

I already done this with cdn of react...
It's simple, but limited because most of the docs are not in ES 6 environnement of react.
But it's very useful when you start using cakePHP / symfony / anything with react.

**Comment by bsonmez** [comment] 2022-06-30 20:34
> Me 5 mins ago: It's not possible that eslint posted an empty NPM....
> Me now: No way.... :O

Exactly happened to me as well.

**Comment by largis21** [comment] 2022-06-30 20:34
> 
Me finally thinking it's time to move on to react...

**Comment by MehdiBenbahri** [comment] 2022-06-30 20:36
> > 
> 
> Me finally thinking it's time to move on to react...

Everyone here will create his react at the same time when the problem will be solved xD
It will be fun.

**Comment by annahansen229** [comment] 2022-06-30 20:37
> @jeanfbs pin it in `resolutions`
> 
> ```json
>   "resolutions": {
>     "@types/eslint": "8.4.3"
>   }
> ```

doesn't work to resolve broken create-react-app

**Comment by diegomontania** [comment] 2022-06-30 20:37
OMG I just want learn about angular projects and boom!

**Comment by MarioBanovac** [comment] 2022-06-30 20:38
why is this happening when I have a home task from the interview :(

**Comment by Rangyia** [comment] 2022-06-30 20:38
> > @jeanfbs pin it in `resolutions`
> > ```json
> >   "resolutions": {
> >     "@types/eslint": "8.4.3"
> >   }
> > ```
> 
> doesn't work to resolve broken `create-react-app`

The issue is because one of the dependencies relies on 8.4.4

Which is within the node_modules itself.

**Comment by AKhatabdev** [comment] 2022-06-30 20:38
"resolutions": {
    "@types/eslint": "8.4.3"
  },
  "overrides": {
    "@types/eslint": "8.4.3"
  },


THIS WORKS!!!

**Comment by Foozie3Moons** [comment] 2022-06-30 20:38
Always relevant whenever a random package breaks the internet: 
![image](https://user-images.githubusercontent.com/12791307/176774083-2dbc63e0-c281-4973-8974-83df83e0dc10.png)

**Comment by AlekseySamokhin** [comment] 2022-06-30 20:38
hahaha , i thought i was crazy

**Comment by annahansen229** [comment] 2022-06-30 20:39
> guys just use `npm i @types/eslint@8.4.3` and done !

doesn't work for fixing broken `create-react-app`

**Comment by CarlosX** [comment] 2022-06-30 20:41
doesn't work 😢

**Comment by xzwq** [comment] 2022-06-30 20:42
thats so funny

**Comment by MarioBanovac** [comment] 2022-06-30 20:42
> Does this happen often?

it happens mostly when you are a junior like me trying to learn haha

**Comment by evandroneder** [comment] 2022-06-30 20:43
same here

**Comment by artemmelnychenk0** [comment] 2022-06-30 20:43
My only way to fix it is to use already create app which was done by `create-react-app` with directory and work there. rpm start works with it.

**Comment by PatrickMalara** [comment] 2022-06-30 20:43
Yeah this is breaking my pipeline because my other dependencies use this...

**Comment by Jackpump** [comment] 2022-06-30 20:43
> 

worked for me on creating a new laravel nova tool

**Comment by AKhatabdev** [comment] 2022-06-30 20:44
> 

you need to -SKIP normal CRA install and modify PACKAGE.json then run NPM Install, might work?

**Comment by hheavener-kyd** [comment] 2022-06-30 20:45
> "resolutions": {
> "@types/eslint": "8.4.3"
> },

For those of you running CI/CD pipelines, try this. I don't know why you need both but this actually does seem to fix it for me. Thank you, @AKhatabdev.

**Comment by annahansen229** [comment] 2022-06-30 20:45
> > > @jeanfbs pin it in `resolutions`
> > > ```json
> > >   "resolutions": {
> > >     "@types/eslint": "8.4.3"
> > >   }
> > > ```
> > 
> > 
> > doesn't work to resolve broken `create-react-app`
> 
> The issue is because one of the dependencies relies on 8.4.4
> 
> Which is within the node_modules itself. Not "your project"

Makes sense why none of the posted solutions are working for `create-react-app` then. Thanks!

**Comment by Rangyia** [comment] 2022-06-30 20:47
> > "resolutions": {
> > "@types/eslint": "8.4.3"
> > },
> 
> For those of you running CI/CD pipelines, try this. I don't know why you need both but this actually does seem to fix it for me. Thank you, @AKhatabdev.

I wonder if other dependencies that rely on @types/eslint will get overriden as well to that version...?

**Comment by tgriffinrevel** [comment] 2022-06-30 20:47
Same

**Comment by MehdiBenbahri** [comment] 2022-06-30 20:48
> > > > @jeanfbs pin it in `resolutions`

The only way is to find a github repo with an already intialized react app, updated, with no code added.
Good luck.

**Comment by xzwq** [comment] 2022-06-30 20:48
how do we solve this?

**Comment by marteiduel** [comment] 2022-06-30 20:48
I thought I was the only one with this problem

**Comment by tkrafael** [comment] 2022-06-30 20:48
> time to learn how to install react

https://blog.bitsrc.io/create-react-app-without-create-react-app-b0a5806a92

**Comment by xzwq** [comment] 2022-06-30 20:50
It may sound funny, but I just started learning React right now.

**Comment by jhormanrus** [comment] 2022-06-30 20:50
i was here 😛

**Comment by bh-hsi** [comment] 2022-06-30 20:50
I was able to pin @types/eslint in an Angular project `package.json` with `npm i @types/eslint --save` - this may not help everyone, but we're on NPM 6.x.x, so resolutions aren't the answer.

**Comment by rmaximoc** [comment] 2022-06-30 20:50
same here

**Comment by jakehewitt** [comment] 2022-06-30 20:51
You can use CRA 4.0.3 in the meantime and upgrade later `npx create-react-app --scripts-version 4.0.3 myapp`

**Comment by largis21** [comment] 2022-06-30 20:52
Who is in charge of fixing this?

**Comment by xenoworf** [comment] 2022-06-30 20:52
> Does this happen often?

No, but it's also never guaranteed to not happen. Such is the nature of distributed systems. This is the price paid for the flexibility of letting your dependencies be unlocked. When everything works, it saves a lot of hassle. When a package is malformed or otherwise unavailable then you might see problems like this.

A couple ways to avoid such problems, each has a different price to pay:
1. Use a cache of npm packages - either locally or upstream in-between your build environment and NPM.org. Doing so will shield you from unavailabilities - but not from this particular problem (a new version is malformed and your project "sucks it in" because your deps are flexible)
2. Lock down your deps, or maybe just some deps. Doing so would have saved you from this particular problem _if you locked the exact version down to something < 8.4.4_. However the price is steep: you'll have to manually decide when and where to bump your dependency versions.

Personally I favor a mix: Cache all your packages, lock stable packages down but leave most of them unlocked. YMMV.

**Comment by zuqueto200** [comment] 2022-06-30 20:53
Adeus React - Foi bom enquanto durou <3

**Comment by daniel-miquiles** [comment] 2022-06-30 20:53
doesn't work in angular

**Comment by Bakon** [comment] 2022-06-30 20:53
> ![image](https://user-images.githubusercontent.com/49045807/176775754-2dc2c5bd-463e-4770-acd2-4ddd78082dae.png)
> 
> "resolutions": { "@types/eslint": "8.4.3" },
> 
> For users running lerna, or monorepos, this in fact overrides any package relying on @types/eslint, or any dependency for that matter that uses @types/eslint.
> 
> If you place it at root it solves the issue. However, IDK the risk of certain packages relying on a later version.

When using Turborepo, putting this resolution in the root package.json solved this for me 👌🏽 

Putting this at the app or package level did NOT fix this for me.

Thank you.

**Comment by cakirlarc** [comment] 2022-06-30 20:54
Houston we have a problem.
@pmdartus , @j-f1 , @saadq , @JasonHK , @bradzacher , @JounQin

**Comment by jmcdo29** [comment] 2022-06-30 20:56
[NPM just updated their status](https://status.npmjs.org/incidents/6wr25yb0b2dd), many packages that made a release recently are missing tarballs. This isn't specific to `@types/` it seems, but general to NPM

**Comment by AKhatabdev** [comment] 2022-06-30 20:56
Check my previous comment. @xzwq

**Comment by MehdiBenbahri** [comment] 2022-06-30 20:57
> > Does this happen often?
> 
> No, but it's also never guaranteed to not happen. Such is the nature of distributed systems. This is the price paid for the flexibility of letting your dependencies be unlocked. When everything works, it saves a lot of hassle. When a package is malformed or otherwise unavailable then you might see problems like this.
> 
> A couple ways to avoid such problems, each has a different price to pay:
> 
> 1. Use a cache of npm packages - either locally or upstream in-between your build environment and NPM.org. Doing so will shield you from unavailabilities - but not from this particular problem (a new version is malformed and your project "sucks it in" because your deps are flexible)
> 2. Lock down your deps, or maybe just some deps. Doing so would have saved you from this particular problem _if you locked the exact version down to something < 8.4.4_. However the price is steep: you'll have to manually decide when and where to bump your dependency versions.
> 
> Personally I favor a mix: Cache all your packages, lock stable packages down but leave most of them unlocked. YMMV.

And what is normally the solution ?
The dude who own this package must correct it ?

**Comment by victor-jaimes-puente** [comment] 2022-06-30 20:57
This is my first time having an issue. Pretty interesting. Have tried all of the above, nothing yet.

**Comment by MehdiBenbahri** [comment] 2022-06-30 20:57
> [NPM just updated their status](https://status.npmjs.org/incidents/6wr25yb0b2dd), many packages that made a release recently are missing tarballs. This isn't specific to `@types/` it seems, but general to NPM

we got the same probleme with yarn create react app :/

**Comment by Charly-Wolf** [comment] 2022-06-30 20:58
I started to learn React today, what a day xD

**Comment by CodingComrade** [comment] 2022-06-30 20:58
> My heart goes out to all the junior devs just starting out and thinking they will never understand web development because they can't create a new project. It's really not their fault and I feel for themmm

Me deciding to finally start learning React today lol Imposter syndrome immediately sets in telling me I'll never be employed if I can't figure out how to download a framework

**Comment by AKhatabdev** [comment] 2022-06-30 20:58
"overrides": {
    "@types/eslint": "8.4.3"
},
"resolutions": {
    "@types/eslint": "8.4.3"
},

OR

> > time to learn how to install react
> 
> 
> 
> https://blog.bitsrc.io/create-react-app-without-create-react-app-b0a5806a92

**Comment by hheavener-kyd** [comment] 2022-06-30 20:59
_Posting this here again in case it got lost above._

# STOP - Try this:

```json
"overrides": {
    "@types/eslint": "8.4.3"
},
"resolutions": {
    "@types/eslint": "8.4.3"
},
```

For those of you running CI/CD pipelines, try this. I don't know why you need both but this actually does seem to fix the issue. Thank you, @AKhatabdev.

**Comment by Foozie3Moons** [comment] 2022-06-30 20:59
https://status.npmjs.org/incidents/6wr25yb0b2dd

**Comment by Wanfadger** [comment] 2022-06-30 21:00
Got this error , when I run npm install on a  newly generated angular application.
npm i -D @types/eslint@8.4.3 fixed it for me and now project runs

**Comment by cakirlarc** [comment] 2022-06-30 21:01
> Looks like the issue might be with NPM:
> 
> https://status.npmjs.org/incidents/6wr25yb0b2dd

Suggestion, did not try yet on this hot issue:
maybe "yarn" will work.

**Comment by amareshsm** [comment] 2022-06-30 21:02
If `@types/eslint` is directly consumed then you can install version `8.4.3`.

    npm i -D @types/eslint@8.4.3
    

### for across dependencies:
```json
    "resolutions": {
      "@types/eslint": "8.4.3"
    }
```

For NPM 8+, use overrides:
``` JSON
  "overrides": {
    "@types/eslint": "8.4.3"
  }
```

If you are trying to create a new project using `create-react-app` as a workaround you can clone and use the below repository.

https://github.com/facebook/create-react-app/tree/main/packages/cra-template/template

npm status regarding this issue: https://status.npmjs.org/incidents/6wr25yb0b2dd

SO Question : https://stackoverflow.com/questions/72821556/what-to-do-when-the-npmregistry-is-missing-types-eslint-eslint-8-4-4-tgz

**Comment by darryl-monks** [comment] 2022-06-30 21:03
> You can use CRA 4.0.3 in the meantime and upgrade later `npx create-react-app --scripts-version 4.0.3 myapp`

Can confirm this works 😄

**Comment by xzwq** [comment] 2022-06-30 21:03
> I started to learn React today, what a day xD

me to :D

**Comment by amareshsm** [comment] 2022-06-30 21:04
> > I started to learn React today, what a day xD
> 
> me to :D

https://stackoverflow.com/questions/72821556/what-to-do-when-the-npmregistry-is-missing-types-eslint-eslint-8-4-4-tgz

**Comment by xenoworf** [comment] 2022-06-30 21:07
> > > Does this happen often?
> > 
> > 
> > No, but it's also never guaranteed to not happen. Such is the nature of distributed systems. This is the price paid for the flexibility of letting your dependencies be unlocked. When everything works, it saves a lot of hassle. When a package is malformed or otherwise unavailable then you might see problems like this.
> > A couple ways to avoid such problems, each has a different price to pay:
> > 
> > 1. Use a cache of npm packages - either locally or upstream in-between your build environment and NPM.org. Doing so will shield you from unavailabilities - but not from this particular problem (a new version is malformed and your project "sucks it in" because your deps are flexible)
> > 2. Lock down your deps, or maybe just some deps. Doing so would have saved you from this particular problem _if you locked the exact version down to something < 8.4.4_. However the price is steep: you'll have to manually decide when and where to bump your dependency versions.
> > 
> > Personally I favor a mix: Cache all your packages, lock stable packages down but leave most of them unlocked. YMMV.
> 
> And what is normally the solution ? The dude who own this package must correct it ?

Yes, that is the solution for this particular issue. Assuming you want v8.4.4, v8.LATEST, etc.

**Comment by xzwq** [comment] 2022-06-30 21:08
> the

thx bro its work

**Comment by Foozie3Moons** [comment] 2022-06-30 21:11
> > Looks like the issue might be with NPM:
> > https://status.npmjs.org/incidents/6wr25yb0b2dd
> 
> Suggestion, did not try yet on this hot issue: maybe "yarn" will work.

Yarn uses NPM

**Comment by JRSalica** [comment] 2022-06-30 21:12
i wanted to practice react today, npx is not working so i used vite with yarn to create a react project provisionally and it worked

**Comment by victor-jaimes-puente** [comment] 2022-06-30 21:12
> You can use CRA 4.0.3 in the meantime and upgrade later `npx create-react-app --scripts-version 4.0.3 myapp`

Also worked for just create-react-app, Im not sure about cross dependencies or ci/cd

**Comment by marteiduel** [comment] 2022-06-30 21:13
> You can use CRA 4.0.3 in the meantime and upgrade later `npx create-react-app --scripts-version 4.0.3 myapp`

Worked for me!

**Comment by jadir-junior** [comment] 2022-06-30 21:13
que b.o.

**Comment by DeborahK** [comment] 2022-06-30 21:15
> OMG I just want learn about angular projects and boom!

@diegomontania This worked for me after a failed ng new:

npm i -D @types/eslint@8.4.3

**Comment by jonesnc** [comment] 2022-06-30 21:18
> > > Looks like the issue might be with NPM:
> > > https://status.npmjs.org/incidents/6wr25yb0b2dd
> > 
> > 
> > Suggestion, did not try yet on this hot issue: maybe "yarn" will work.
> 
> Yarn uses NPM

We should make a distinction between the `npm` command and the NPM Registry. 

`yarn` is an alternative to the `npm` command. Both the `yarn` and `npm` commands use the NPM Registry by default to download packages.

It is the NPM Registry that is currently experiencing an outage, so it won't make a difference if you used the `npm` command or `yarn` command, they will both have this problem.

Case in point, I'm using `yarn` and am currently experiencing this exact issue.

**Comment by himani-chi** [comment] 2022-06-30 21:19
I need to install a generator. What workaround should I use?

**Comment by HanCai98** [comment] 2022-06-30 21:28
> I started to learn React today, what a day xD

You are not the only one ~

**Comment by cakirlarc** [comment] 2022-06-30 21:29
> > > > Looks like the issue might be with NPM:
> > > > https://status.npmjs.org/incidents/6wr25yb0b2dd
> > > 
> > > 
> > > Suggestion, did not try yet on this hot issue: maybe "yarn" will work.
> > 
> > 
> > Yarn uses NPM
> 
> We should make a distinction between the `npm` command and the NPM Registry.
> 
> `yarn` is an alternative to the `npm` command. Both the `yarn` and `npm` commands use the NPM Registry by default to download packages.
> 
> It is the NPM Registry that is currently experiencing an outage, so it won't make a difference if you used the `npm` command or `yarn` command, they will both have this problem.
> 
> Case in point, I'm using `yarn` and was recently experiencing this exact issue before implementing [#61032 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61032#issuecomment-1171671991).

@jonesnc , you are right, one more thing I learned today. :) But being so dependant on a single provider, npmjs.com, made me nervous again.

**Comment by AlecMMedeiros** [comment] 2022-06-30 21:31
As Mj said: You are not alone...I am here with you...

**Comment by brunomaruyama** [comment] 2022-06-30 21:33
> You can use CRA 4.0.3 in the meantime and upgrade later `npx create-react-app --scripts-version 4.0.3 myapp`

It worked! Thanks!

**Comment by mhanley00** [comment] 2022-06-30 21:34
> You can use CRA 4.0.3 in the meantime and upgrade later npx create-react-app --scripts-version 4.0.3 myapp

Hero! Thank you! Never have I ever found a GitHub issue that was playing out in real time, until now

**Comment by MrLuit** [comment] 2022-06-30 21:38
Version 8.4.5 was deployed about 5 minutes ago, trying it out right now: https://www.npmjs.com/package/@types/eslint

**Comment by grojas123** [comment] 2022-06-30 21:39
This error shows with a npx create-react-app my-app
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.5.tgz - Not found

**Comment by Wprosdocimo** [comment] 2022-06-30 21:40
Podiam remover a versão bugada, no amplify não estou conseguindo setar a versão 8.4.3, ele sempre pega a latest par mim...

**Comment by TheNickm2** [comment] 2022-06-30 21:43
> Version 8.4.5 was deployed about 5 minutes ago, trying it out right now: https://www.npmjs.com/package/@types/eslint
> 
> Update: didn't work unfortunately

Issue appears to be on the NPM registry side. Hopefully once they resolve things, packages will start publishing correctly again. At this time, I don't believe the DefinitelyTyped team can do anything to resolve as it's out of their hands :(

**Comment by LeoFC97** [comment] 2022-06-30 21:43
> 

Only english please :/

**Comment by JeffreyArt1** [comment] 2022-06-30 21:44
Same here

**Comment by LeoFC97** [comment] 2022-06-30 21:44
> Podiam remover a versão bugada, no amplify não estou conseguindo setar a versão 8.4.3, ele sempre pega a latest par mim...


Only english please :/

**Comment by 0xslipk** [comment] 2022-06-30 21:45
> You can use CRA 4.0.3 in the meantime and upgrade later `npx create-react-app --scripts-version 4.0.3 myapp`

Works for me also :D

**Comment by humarkx** [comment] 2022-06-30 21:47
> Podiam remover a versão bugada, no amplify não estou conseguindo setar a versão 8.4.3, ele sempre pega a latest par mim...

Não depende da equipa do DefinitelyTyped, neste momento tem de ser o NPM registry a resolver o que se passa do lado deles.

Next time, you should only use English on threads like these.

**Comment by cakirlarc** [comment] 2022-06-30 21:47
I wonder how hard it is to unpublish a package which has zero downloads. If it is a simple thing to do package owners reaction time is very important in this case. Even it is not their fault. By the way because it is a general issue with npmjs maybe one of your/my other packages also will fail to download. Just thinking.

**Comment by grojas123** [comment] 2022-06-30 21:49
> You can use CRA 4.0.3 in the meantime and upgrade later `npx create-react-app --scripts-version 4.0.3 myapp`

Thanks . Works .

**Comment by Wprosdocimo** [comment] 2022-06-30 21:55
Wouldn't it be possible to change the latest pointer to version 8.4.3 until I can upload a newer version that is responding?

**Comment by pedroslev** [comment] 2022-06-30 21:57
> Wouldn't it be possible to change the latest pointer to version 8.4.3 until I can upload a newer version that is responding?

Totally, as devs we run to fix prod bugs but this is taking hours? Not even a momentary workaround

**Comment by lordazzi** [comment] 2022-06-30 22:06
> # STOP - Try this:
> ```json
> "overrides": {
>     "@types/eslint": "8.4.3"
> },
> "resolutions": {
>     "@types/eslint": "8.4.3"
> },
> ```
> 
> For those of you running CI/CD pipelines, try this. I don't know why you need both but this actually does seem to fix the issue. Thank you, @AKhatabdev.

Don't work for me,
using angular 13, trying to install in a node:14.19.3 docker image

**Comment by trevordilley** [comment] 2022-06-30 22:13
> ```json
>  "resolutions": {
>     "@types/eslint": "8.4.3"
>   }
> ```

I mean, I'm fairly certain there is a small team of extremely stressed out devs trying to solve this right now. They need space and coffee and support.

**Comment by thejykim** [comment] 2022-06-30 22:13
npm package has been rolled back to 8.4.3: https://www.npmjs.com/package/@types/eslint

**Comment by cakirlarc** [comment] 2022-06-30 22:16
> npm package has been rolled back to 8.4.3: https://www.npmjs.com/package/@types/eslint
The below started to work again and install 8.4.3 versions.
npm i @types/eslint
yarn add @types/eslint

**Comment by grojas123** [comment] 2022-06-30 22:18
Now the npx create-react-app works .

**Comment by zuqueto200** [comment] 2022-06-30 22:20
NPM = OK ? TRUE

**Comment by salatielosorno** [comment] 2022-06-30 22:25
I have the same issue. Nothing works because my basecode doesn't use the dependency but my dependencies do. Is there any different that I can try?

**Comment by andrewbranch** [comment] 2022-06-30 22:26
> > Wouldn't it be possible to change the latest pointer to version 8.4.3 until I can upload a newer version that is responding?
> 
> Totally, as devs we run to fix prod bugs but this is taking hours? Not even a momentary workaround

We tried this right away and got errors. Tried it again just now, and as you noticed, it worked. npm hasn’t resolved the incident so I’m not sure we’re 100% in the clear, but I’m watching it closely and will keep bumping the tag around as needed. Thanks for your patience (I just learned this issue exists 🙃)

**Comment by leosenadev** [comment] 2022-06-30 22:27
the problem was solved without me doing anything, I just made it wait and gave the command: npx create-react-app myapp

**Comment by andrewbranch** [comment] 2022-06-30 22:28
Yeah, the tag was changed at 3:12pm PDT (16 minutes ago). Should be working @salatielosorno.

**Comment by libradito** [comment] 2022-06-30 22:30
is Working ! Woooo!

**Comment by rmfruit** [comment] 2022-06-30 22:34
Yeah, it looked like `8.4.4` and `8.4.5` were both bad. With the `dist` tag pointing at 8.4.3 my build no longer barfs 👍

**Comment by ctsstc** [comment] 2022-06-30 22:37
> ehhh time to do some break :)
This worked for me! :tada: Works now for me ;)

**Comment by andrewbranch** [comment] 2022-06-30 22:39
So, the 3:30pm run decided there was no new work to do. So now I just have to wonder if any other less widely-used packages are getting borked and we’re just not noticing 😬

**Comment by andrewbranch** [comment] 2022-06-30 22:41
`@types/react-copy-to-clipboard` failed around the same time. I think I’m going to shut down package publishing overnight (unless they tell us we’re good before ~5:00pm).

**Comment by cakirlarc** [comment] 2022-06-30 22:47
> I’m a little concerned that the package publisher, which runs every half hour on the half hour (so started a new run 1 minute ago) is going to attempt to republish it again, and I have no idea whether that will succeed or not (I think we’ve seen it fail twice). I’m going to try to watch it in real time here, but there’s a chance it might get momentarily broken again. If that happens, I’ll bump the `latest` tag again and then shut down the publisher until npm gives us the all-clear.

I do not "believe" https://www.npmjs.com/package/@types/eslint Versions tab. It is inaccurate.
Best way to check seems to be `npm i @types/eslint` in an empty folder.

**Comment by andrewbranch** [comment] 2022-06-30 22:50
Yeah, the npmjs.com UI is heavily cached. CLI should always tell you the latest info.

So case in point about not fixing this earlier: I’m running the command to move the `latest` tag on `@types/react-copy-to-clipboard`, and the CLI is telling me it worked, but it actually doesn’t seem to be changing anything. The same command that didn’t work for `@types/eslint` two hours ago but worked 45 minutes ago. Something is pretty screwed up on npm.

**Comment by salatielosorno** [comment] 2022-06-30 22:54
> Yeah, the tag was changed at 3:12pm PDT (16 minutes ago). Should be working @salatielosorno.

It is working now! 🎉

**Comment by andrewbranch** [comment] 2022-06-30 22:57
https://twitter.com/MylesBorins/status/1542643025725333504

> We are 99% we've identified the cause and have a solution to backfill impacted versions. Just finished manually fixing @types/eslint, now to update the incident and fix the rest.

**Closed** 2022-06-30 23:37 UTC

**Comment by TheNickm2** [comment] 2022-06-30 23:39
NPM registry fix is nearly completed and this package appears to have been fixed manually for the time being. Closed since no further action is required by the DefinitelyTyped team! 🎉

**Comment by andrewbranch** [comment] 2022-06-30 23:51
I’m getting close to signing off for the day; officially the status is

- The `@types/eslint` 8.4.4 and 8.4.5 tarballs have been restored and the `latest` tag pointed back to 8.4.5, so this one is totally done.
- `@types/react-copy-to-clipboard` is the only other broken package I know of and has not been restored yet, but my impression is the npm team knows which packages are affected and will fix all of them.
- Since the incident is not officially resolved, I’m leaving the publisher switched off overnight. Merged PRs on DefinitelyTyped will get published tomorrow morning (US Pacific time) when I turn it back on, assuming status.npmjs.com is green.

**Comment by cakirlarc** [comment] 2022-07-01 06:34
https://www.npmjs.com/package/@types/eslint?activeTab=versions
Currently npmjs reports correct versions. 8.4.4 and 8.4.5 are gone. Lets keep an eye on it.
![image](https://user-images.githubusercontent.com/4405476/176837731-7dc79a0e-7d74-4c59-a014-cc177490ba4e.png)

**Comment by antoci-alin** [comment] 2022-07-01 07:14
Works for me now!

**Comment by andrewbranch** [comment] 2022-07-01 15:49
> 8.4.4 and 8.4.5 are gone. Lets keep an eye on it.

They’re there, but you have to scroll down the page. I could have sworn the `latest` tag was back at 8.4.5 last night, but it’s at 8.4.3 now. Same thing with @types/react-copy-to-clipboard. Verified those versions are working though, so I’m going to try to move the `latest` tag back to what it should be and hopefully wrap this thing up.

**Comment by andrewbranch** [comment] 2022-07-01 15:56
Done, and the publisher is back up and running.


![That’s all, folks!](https://c.tenor.com/gUc8oy81HkgAAAAC/thats-all-folks-ending.gif)

**Comment by AKhatabdev** [comment] 2022-10-11 07:34
Hopefully it helps others. ☺️ 👍🏽

Awais S. Khatab
