### ISSUE TITLE
auth0-js module name regression on @types

### ISSUE THREAD

**Issue by lediur** [DefinitelyTyped/DefinitelyTyped#11583] opened 2016-09-28 19:28 UTC
- [x] I tried using the latest `auth0-js/auth0-js.d.ts` / `auth0-js/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `auth0-js/auth0-js.d.ts`
  - The authors of that type definition are cc/ @zhengbli @westy92 

The version of auth0-js on the `types-2.0` branch has a mismatched module name (`auth0` instead of `auth0-js`, which is the correct module name). I think the file on `master` branch is correct, but it keeps getting squashed during merges into `types-2.0`. Can I make a pull request to fix this, or can this change be merged into the `types-2.0` branch sometime?

**Comment by llwt** [comment] 2017-05-14 19:40
I'm running into an issue right now that I think is stemming from this. During AOT compilation with angular the lib is being pulled in from `node_modules/@types/auth0-js` instead of the `node_modules/auth0-js` dir and blowing up our production build.

Is there any update on this or something I can do to expedite getting this fixed?
@lediur @zhengbli @westy92

**Comment by llwt** [comment] 2017-05-14 19:43
This seems to be duplicate of #11430

**Comment by JaSpr** [comment] 2017-11-08 20:45
Any updates on this?  We are unable to compile with aot in an angular app because of this package.

**Comment by llwt** [comment] 2017-11-09 18:33
Just looked in our codebase to see if we had a fix and found:

```typescript
import {WebAuth, Authentication} from 'auth0-js';

@Injectable()
export class WebAuthenticationService implements AuthenticationService {
  // TODO: inject this into the DI layer using a factory in the web.module.ts
  /**
   * There is currently an issue with the type definitions that causes the AOT
   * build to attempt to load the auth0-js module from the node_modules/@types/auth0-js
   * directory instead of the actual node module. I'm not sure why, but for some reason
   * newing the WebAuth class here prevents the load issue.
   *
   * @see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11430
   * @see https://github.com/NathanWalker/angular-seed-advanced/issues/421
   */
  private auth0 = new WebAuth({
    //...
```

Would be nice to get a fix in for this.

**Closed** 2024-02-11 06:21 UTC
Labels: @types
