### ISSUE TITLE
[@types/styled-components] depends on `@types/react-native` which conflicts with DOM lib types

### ISSUE THREAD

**Issue by wyqydsyq** [DefinitelyTyped/DefinitelyTyped#37097] opened 2019-07-24 04:10 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Jessidhia @JKillian @eps1lon @flavordaaave

Given this `tsconfig.json` in a project using `@types/styled-components`, you get a bunch of errors like this:

```
node_modules/typescript/lib/lib.dom.iterable.d.ts:67:11 - error TS2300: Duplicate identifier 'FormData'.

67 interface FormData {
             ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:40:15
    40 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.
```

`tsconfig.json`
```
{
  "compilerOptions": {
    "target": "es6",
    "allowJs": true,
    "skipLibCheck": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "strictPropertyInitialization": false,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "jsx": "react",
    "typeRoots": ["./types", "./node_modules/@types"],
    "baseUrl": "src",
    "paths": {
      "@/*": ["*"]
    }
  },
  "include": [
    "types/*",
    "src/*",
    "node_modules/@/**/*"
  ]
}
```

I am not using `react-native` and there is absolutely no reason I can see that `styled-components` should be pulling this dependency into my project to begin with. Even though it is not inside the `package.json` of these types, my `yarn.lock` pulls it as a dependency:
```
"@types/styled-components@^4.1.18":
  version "4.1.18"
  dependencies:
    "@types/react" "*"
    "@types/react-native" "*"
    csstype "^2.2.0"
```

**Comment by joemckie** [comment] 2019-07-27 14:39
Duplicate of #33311

**Comment by orta** [comment] 2021-06-07 13:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:11 UTC
