### ISSUE TITLE
Types for APIGatewayEvent not compatible - aws-lambda

### ISSUE THREAD

**Issue by Simon-SDK** [DefinitelyTyped/DefinitelyTyped#46689] opened 2020-08-12 11:25 UTC
Authors: @simonbuchan, @SachinShekhar 

I found an issue with the types of (regular) APIGateWayEvent. It seems to simply copy the APIGateWayProxyEvent (Line 162: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c45d5b3a965365ba0263f756c4f4554a659850a6/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L162

In reality those two are not identical.

A regular non-proxy response from ApiGateWay does not include features like "queryStringParameters" or "multiValueQueryStringParameters", but does on the other hand include "query" which is missing as of now.

I'm still not that familiar with writing types, so I'd rather not try to pr an update myself :-)

Adding a "query" type seems to be quite simple, but not sure about omitting types that are exiting on APIGateWayProxyEvent but not on APIGateWayEvent
`query: { [name: string]: string } | null;`

**Comment by simonbuchan** [comment] 2020-08-12 12:49
The comment above is:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c45d5b3a965365ba0263f756c4f4554a659850a6/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L159

These are very old names that did not describe the actual type at all, which is why they were renamed to better, more descriptive names for precisely the reason that what you get from API Gateway can be essentially completely arbitrary (you seem to be actually describing v2 / "HTTP" apis). There's quite a few of these old names that could be marked as deprecated, across several trigger types, I guess.

**Comment by Simon-SDK** [comment] 2020-08-12 20:03
Ahh, I had missed the legacy part. Does that mean that these types need a complete makeover? I am actually using regular api gateway but without proxy (not the newer http v2). 
Could a solution be to add a “query?“ to APIGatewayProxyEventBase?

**Comment by SachinShekhar** [comment] 2020-08-12 20:26
If your use case is non-proxy, why do you want to mess into `api-gateway-proxy.d.ts` file?

**Comment by simonbuchan** [comment] 2020-08-12 23:09
Proxy here means the lambda proxy integration method of API gateway, which unfortunately has several other names. If you're not using that, then you're defining the mapping yourself, so there's no type we can usefully provide. If you're using the proxy integration, then maybe you've found a fault with the type, but it's very well established (probably the first!) so you've got a high burden to show the change is real

**Comment by Simon-SDK** [comment] 2020-08-13 11:18
I'm not sure I follow, so made a small example under.

When a lambda uses proxy integration, the event will look like this:
`curl https://long-url-here/?akey=here-is-a-key&anotherkey=wow`

**Response**
`{
    "resource": "/",
    "path": "/",
    "httpMethod": "GET",
    "headers": {REMOVED},
    "multiValueHeaders": { REMOVED },
    "queryStringParameters": {
        "akey": "here-is-a-key",
        "anotherkey": "wow"
    },
    "multiValueQueryStringParameters": {
        "akey": [
            "here-is-a-key"
        ],
        "anotherkey": [
            "wow"
        ]
    },
    "pathParameters": null,
    "stageVariables": null,
    "requestContext": {removed},
    "body": null,
    "isBase64Encoded": false
}`

When a lambda is non-proxy (e.g. regular rest api, and not the newer http api), the same event will look like this:
**Response**
`{
    "body": {},
    "method": "GET",
    "principalId": "",
    "stage": "dev",
    "cognitoPoolClaims": {
        "sub": ""
    },
    "enhancedAuthContext": {},
    "headers": {REMOVED},
    "query": {
        "akey": "here-is-a-key",
        "anotherkey": "wow"
    },
    "path": {},
    "identity": {REMOVED},
    "stageVariables": {},
    "requestPath": "/"
}`

So when the type  "APIGatewayEvent" ( or "APIGatewayProxyEvent" for that matter) its not possible to extract the query parameters like one normally would in a non-proxy lambda: 
`let {akey, anotherkey} = event.query  //Property 'query' does not exist on type 'APIGatewayEvent'`

As regular (non-proxy) is still widely used, I feel like this should be an issue to be fixed, but for now i'll have to do with "event: any" I guess :-)

**Comment by Simon-SDK** [comment] 2020-08-13 11:27
Just wanted to at a response example when using HTTP Api:

**Response**
`{
    "version": "1.0",
    "resource": "/test",
    "path": "/test",
    "httpMethod": "GET",
    "headers": {REMOVED},
    "multiValueHeaders": {REMOVED},
    "queryStringParameters": {
        "akey": "here-is-a-key",
        "anotherkey": "wow"
    },
    "multiValueQueryStringParameters": {
        "akey": [
            "here-is-a-key"
        ],
        "anotherkey": [
            "wow"
        ]
    },
    "requestContext": {
        "accountId": "removed",
        "apiId": "removed",
        "domainName": "my-domain",
        "domainPrefix": "removed",
        "extendedRequestId": "=",
        "httpMethod": "GET",
        "identity": {REMOVED},
        "path": "/test",
        "protocol": "HTTP/1.1",
        "requestId": "REMOVED=",
        "requestTime": "13/Aug/2020:11:22:41 +0000",
        "requestTimeEpoch": 1597317761891,
        "resourceId": "GET /test",
        "resourcePath": "/test",
        "stage": "$default"
    },
    "pathParameters": null,
    "stageVariables": null,
    "body": "{\"body-test\":\"some values here\"}",
    "isBase64Encoded": false
}`

**Comment by SachinShekhar** [comment] 2020-08-14 02:39
These types are only meant to be used in Lambda (package name is: `@types/aws-lambda`). For proxies which are not Lambda proxy, simply don't use this package.

**Comment by Simon-SDK** [comment] 2020-08-14 07:01
I know, these events are exactly how they look like when you console.log(event) inside a lambda on either of the 3 methods (proxy, regular and http api aka v2). What are you thinking I am doing?

Im a bit curious, how come the answer is "just dont use this package". The whole idea about the package is to ease the use of lambda when using typescript, but its not usable unless the lambda is either proxy or http apis. As I point out, the naming is not logical as "apigatewayevent" !== "apigatewayproxyevent", although it says so in the package!
As I told in the beginning, if I had more typescript experience I would come with a pr, but I dont, but other users might experience the same issue and not understand why it doesn't work for them.

**Comment by simonbuchan** [comment] 2020-08-14 07:18
I feel there's some confusion going on here, largely due to the very confusing API Gateway naming, so to be clear: 
* `APIGatewayEvent` is just an old name that you should not use, it is only there for compatibility with old code, the correct name is `APIGatewayProxyEvent`. It has always been the proxy event, and only the proxy event.
* `APIGatewayProxyEvent` which implements the [REST API (API Gateway v1) Lambda Proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format)
* The recently added `APIGatewayProxyEventV2`, which implements the [HTTP API (API Gateway v2) Lambda Proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)
* There is no, and should not be, any types for [REST API Custom lambda integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-custom-integrations.html) - the entire point is that you define what the shape of the event you get is, so we can't really provide any types here.
* Similarly, there is no types for the [REST API HTTP integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/setup-http-integrations.html), which can be configured to call lambdas if you're dedicated, since they also use custom defined request templates.
* The [HTTP API HTTP integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-http.html) seems to imply that if you forward to a lambda that the external user must provide lambda request headers and body literally, again there are no types we can provide.

The point is we can only provide types that are defined by AWS. The currently implemented cases don't have `query`. Be more specific about what configuration you are using, and what actual change you are requesting:
* You are using an integration that isn't covered above that has a defined type we can add as a new type. Please provide links to the relevant documentation.
* The integration for an existing type has changed, and we have to update the type. In this case, please give sufficient information on how to reproduce the changed payload. Note that the AWS console API Gateway tester can give slightly different payloads here: we model the actual APIs.
* Otherwise you are talking about something else: you need to be very specific about what you are referring to for us to help, preferably enough to re-create your setup. There are a *lot* of moving parts in API Gateway, and they re-use terminology a lot.

The meaning of "don't use this package" is that if you are using a custom integration, then you can simply define your own custom shape yourself, for example, using the [example custom integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-custom-integrations.html) with the mapping template of `{"application/json":"{\"greeter\":\"$input.params('greeter')\"}"}` you can define your own types as simply as:

```ts
interface GreeterEvent {
  greeter: string;
}
export async function handler(event: GreeterEvent) {
  // as in the example ...
}
```

You could optionally choose to reuse some of the other types from this package still, for example since there was no `responseTemplate` in the example you could use `Promise<APIGatewayProxyResult>` as the result type of `handler`, or `Context` if you want access to that:

```ts
import { Context, APIGatewayProxyResult } from "aws-lambda";
export async function handler(event: GreeterEvent, context: Context): Promise<APIGatewayProxyResult> {
  // as in the example ...
}
```

**Comment by orta** [comment] 2021-06-07 13:06
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:06 UTC
