### ISSUE TITLE
Make compatable all definitions with new compiler argument --strictNullChecks

### ISSUE THREAD

**Issue by bashor** [DefinitelyTyped/DefinitelyTyped#8714] opened 2016-03-24 20:34 UTC
More inforemation about strictNullChecks here: https://github.com/Microsoft/TypeScript/pull/7140

**Comment by vvakame** [comment] 2016-03-26 15:49
:+1: We'll start it when typescript 2.0 shipped.

**Comment by horiuchi** [comment] 2016-03-28 08:43
That's good feature! :+1:

**Comment by alexeagle** [comment] 2016-06-20 23:24
Could we start landing these changes on the `types-2.0` branch (is that meant for TS 2.0?)
We have started updating Google code to `--strictNullChecks` and have local modifications to `d.ts` files that we could upstream, if there was a place for them.

**Comment by cspotcode** [comment] 2016-09-22 14:32
Ditto what @alexeagle said; I would love to contribute updates to the declarations that I use so that they'll be ready to go when TS2.0 ships.  Should I just keep them in my fork?  Is there a branch I can submit PRs against?

**Comment by andy-ms** [comment] 2016-09-22 14:53
Hi @cspotcode, that branch is the `types-2.0` branch. Every package there *should* (many don't, but we're accepting PRs) have a `tsconfig.json`, and it would be great to turn on `"strictNullChecks": true` in as many of those as possible. (To create a `tsconfig.json`, just copy from a package nearby and change the `files`; they should all be identical except for `files`, `strictNullChecks`, and some add `jsx`.)

The `types-2.0` branch also gets published to the `@types` scope on NPM. We also manually merge in changes from `master` to `types-2.0` once in a while.

**Comment by alitaheri** [comment] 2016-10-29 10:53
@andy-ms Since typescript 2 has been published. Should we start enforcing `strictNullChecks`? My application fails sometimes because I have it enabled. but some definitions aren't compatible.

**Comment by andy-ms** [comment] 2016-10-29 11:58
It's up to you whether you want `strictNullChecks` in your own code, but a type definition with `| null` and `| undefined` used appropriately is strictly better than one without them — these will just be ignored if you're not using `strictNullChecks`.

**Comment by alitaheri** [comment] 2016-10-29 12:08
The problem is: When you use generics constraints, the `strictNullChecks` won't allow `null` or `undefined` to be assigned to types not including the corresponding `null` or `undefined` type:

```ts
interface Foo {
  a: number;
}

interface Bar<T extends Foo> {
  a(): T;
}

interface Baz<T extends Foo | null> {
  a(): T;
}

// strictNullChecks=true => error: [ts] Type 'null' does not satisfy the constraint 'Foo'.
// strictNullChecks=false => no error.
type Bad = Bar<null>; 
type Good = Baz<null>;

```

This gives me compilation errors simply because I have installed a library ( i.e. `@types/d3-selection` ). If the rule is enforced for all libraries like `noImplicitAny` then such edge cases won't occur. You can open `d3-selection` or `d3-focus`, enable `strictNullChecks` and see the compiler errors in the definition files.

**Comment by andy-ms** [comment] 2016-10-29 14:40
Then `d3-selection` and `d3-focus` should be upgraded. All libraries should have `strictNullChecks`, especially those that are already explicitly using the `null` type.

**Comment by Ledragon** [comment] 2018-02-15 19:55
You can follow the progress of  the d3-related modules in issue #23611

**Comment by orta** [comment] 2021-06-07 13:29
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:29 UTC
