### ISSUE TITLE
[@types/react-native] SectionList can't specify item/section type

### ISSUE THREAD

**Issue by Aure77** [DefinitelyTyped/DefinitelyTyped#37077] opened 2019-07-23 14:38 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy, @huhuanming, @iRoachie, @skn0tt, @timwangdev, @kamal, @alexdunne, @swissmanu, @a-tarasyuk, @mvdam, @esemesek, @mrnickel, @souvik-ghosh, @nossbigg, @saranshkataria, @franzmoro, @tykus160, @jakebloom, @ceyhun, @mcmar

I can't specify SectionList item/section type. If I use generic way, i got the following message:

> Expected 0 type arguments, but got 1.ts(2558)

```
<SectionList<MyItem> // not allowed
  renderItem={({ item, index, section }) => ( // item have type "any"
    <Text key={index}>{item}</Text>
  )}
  renderSectionHeader={({ section: { title } }) => ( // section is typed with SectionListData<any> so title as type "any"
    <Text style={{ fontWeight: "bold" }}>{title}</Text>
  )}
  sections={[
    { title: "Title1", data: ["item1", "item2"] },
    { title: "Title2", data: ["item3", "item4"] },
    { title: "Title3", data: ["item5", "item6"] }
  ]}
  keyExtractor={(item, index) => item + index}
/>
```

Generic typing is working on FlatList:
`<FlatList<MyItem> ...`

**Comment by Skn0tt** [comment] 2019-07-23 15:01
This could be because of this line: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/518db0303d72b139099b7abeca8c1ce09a008b4c/types/react-native/index.d.ts#L9228

Please try changing it locally to see if it helps.

**Comment by Aure77** [comment] 2019-07-23 15:28
If I remove this line, typescript doesn't recognize SectionList as a component :
> 'SectionList' only refers to a type, but is being used as a value here.ts(2693)

**Comment by Skn0tt** [comment] 2019-07-23 16:13
Removing this line is like removing it from the exports, this behavior is expected.
Try to change it to the following:

```tsx
interface MyItem {
  // your MyItem Type
}

export const SectionList = SectionListStatic<MyType>;
```

Also, change your own application code to `<SectionList ... />`.

These changes will hardcode your `MyItem` type into the definition of `SectionList`.

This is in no way a fix for the problem you‘re facing, it‘s just to find out where the problem lies. If it fixes your type error, I can make the required adjustments to the typings next week.
If it doesn‘t, I‘ll have a look at it myself this weekend.

**Comment by Aure77** [comment] 2019-07-25 16:59
I found a workaround to type SectionList by creating an intermediate typed component:
```
const MySectionList: SectionList<MyItem> = SectionList;
<MySectionList ... // use as normal SectionList
```
...

**Comment by Skn0tt** [comment] 2019-07-25 17:14
Alright. I‘m confident I know where the root cause of this bug is. I‘ll have a look this weekend when I‘m back at home.

**Comment by DGCarramona** [comment] 2020-03-30 14:00
Hello, I'm using version 0.62.0 and I'm facing the same issue.
Do you have any updates ? (If @Aure77 could say it works, I would know the error is on my side)

**Comment by orta** [comment] 2021-06-07 13:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:11 UTC
