### ISSUE TITLE
TS2339 @Types/moment-timezone. There is an error in the pipeline GitLab runner by error typed

### ISSUE THREAD

**Issue by rubenesda** [DefinitelyTyped/DefinitelyTyped#44441] opened 2020-05-02 15:12 UTC
Hello, I have had issues since yesterday with a test running in GitLab runner, I think there is a problem when GitLab runner tries to download the package @types/moment-timezone.  Because I got this error below

`Test suite failed to run
     TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
     server/app.ts:18:8 - error TS2339: Property 'tz' does not exist on type 'typeof moment'.`

I have installed in my package.json the package needs to run the test without issues.

`
"devDependencies": {
...
"@types/moment-timezone": "0.5.12",
...
},
"Dependencies": {
...
"moment": "2.24.0",
...
`
I have run my test locally and I haven't any problem but in the pipeline, I'm having this problem since yesterday. This is the first time that happened because before I have pushed and don't happen anything ie the Thursday and Wednesday don't have issues.

Did the version change yesterday? Has the moment or @types/moment-timezones new updates? or issues between versions?

I hope your answer soon.

**Comment by GuillaumeLachaud** [comment] 2020-05-03 15:32
Same for me here. I tried a clean install of the packages locally and still can't reproduce. It only happens on our build environment on Heroku

**Comment by rubenesda** [comment] 2020-05-05 17:16
@GuillaumeLachaud Can you resolve it? Have you already the issue?

**Comment by GuillaumeLachaud** [comment] 2020-05-06 05:01
I pinned moment and moment-timezone versions down:

```
 "dependencies": {
    "moment": "2.24.0",
    "moment-timezone": "0.5.28"
  },
  "resolutions": {
    "moment": "2.24.0"
  },
```

**Comment by orta** [comment] 2021-06-07 13:07
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:07 UTC
