### ISSUE TITLE
[D3] Refine Definitions/Technical Debt Reduction

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#23611] opened 2018-02-13 16:14 UTC
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache @Ledragon 

I am creating this issue as a replacement tracking issue for #11365, #11365 and #17846.

The following is a table to track refinements/technical debt related to D3 module definitions.
* **JSDoc:** Complete JSDoc comments including parameters and generics explanation
* **strictNullChecks:** Validated for `strictNullChecks` and compiler option set to `true`
* **strictFunctionTypes:** Validated for `strictFunctionTypes` and compiler option set to `true`
* **TS 2.3:** Minimum version of TS 2.3 and definitions use defaults for generics

| Definition| JSDoc | `strictNullChecks` | `strictFunctionTypes` | `TS 2.3` |
| --- | --- | --- | --- | --- |
| **d3** | N/A | 🔲 | 🔲 | ✅ |
| **d3-array** | 🔲  | ✅  | 🔲 | 🔲 |
| **d3-axis** | ✅ | ✅ | ✅ | ✅ |
| **d3-brush** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-chord** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-collection** | ✅ | ✅ | ✅ | ✅ |
| **d3-color** | 🔲 | ✅ | ✅ | ✅ |
| **d3-contour** | ✅ | ✅  | ✅ | 🔲 |
| **d3-dispatch** | ✅ | ✅ | ✅ | ✅ |
| **d3-drag** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-dsv** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-ease** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-fetch** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-force** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-format** | ✅ | ✅ | ✅ | ✅ |
| **d3-geo** | ✅ | ✅  | ✅  | ✅  |
| **d3-hexbin** | 🔲 | 🔲 | 🔲 | 🔲 |
| **d3-hierarchy** | 🔲 | 🔲 | 🔲 | 🔲 |
| **d3-interpolate** | 🔲 | 🔲 | 🔲 | 🔲 |
| **d3-path** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-polygon** | ✅ | ✅ | ✅ | ✅ |
| **d3-quadtree** | 🔲 | 🔲 | 🔲 | 🔲 |
| **d3-queue** | ✅ | 🔲 | 🔲 | 🔲 |
| **d3-random** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-request** | 🔲 | 🔲 | 🔲 | 🔲 |
| **d3-sankey** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-scale** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-scale-chromatic** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-selection** | ✅ | ✅  | ✅  | 🔲 |
| **d3-selection-multi** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-shape** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-time** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-time-format** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-timer** | ✅ | 🔲 | 🔲 | 🔲 |
| **d3-transition** | ✅ | ✅  | 🔲 | 🔲 |
| **d3-voronoi** | ✅ | 🔲 | 🔲 | 🔲 |
| **d3-zoom** | ✅ | ✅  | 🔲 | 🔲 |

"Outside" of core team maintenance:

| Module | JSDoc | `strictNullChecks` | `strictFunctionTypes` | `TS 2.3` |
| --- | --- | --- | --- | --- |
| **d3-hsv** | ✅ | ✅ | ✅ | ✅ |

**Comment by tomwanzek** [comment] 2018-02-13 16:20
@gustavderdrache @Ledragon Above I consolidated the few outstanding tasks to round of the oeuvre that is the set of D3 definitions.

A key question: Do we want to upgrade all definitions consistently to a TS >=2.3 constraint and in the process remove some of the functions/method overloads by using default assignments for generics?
I noticed that (inadvertently) some of the definitions already have the `// TypeScript Version: 2.3` constraint in the definitions header. E.g. **d3-geo**, which uses the `geoJson` definitions. These already use generic defaults.

Your thoughts on this matter would be more than welcome.

**Comment by julioca2** [comment] 2018-02-13 16:35
Entender esto hay que estudiarlo

**Comment by tomwanzek** [comment] 2018-02-13 21:10
If implementing a TS 2.3 minimum, we should also be able to use the `object` type instead of `any`, where appropriate. Came with TS 2.2. If I recall correctly, there were a handful of opportunities with object interpolators and in d3-collection.

**Comment by Ledragon** [comment] 2018-02-15 20:02
First thoughts:
* Due to the out-of-memory bug you encountered, should we not enforce 2.4 everywhere?
* I have a branch with `strictNullChecks` and `strictFunctionTypes` [here](https://github.com/Ledragon/DefinitelyTyped/tree/d3-geo-strictNullCheck). I will update it and submit a PR. I thought I did, but it does not seem so

I have to learn about default generics before I have an opinion on this :p

**Comment by tomwanzek** [comment] 2018-02-15 23:32
With TS 2.3 we are looking at a release from back in April 2017.
TS 2.4 was released June 2017.

So the big question is: are we creating issues in a large or negligible/no part of the installed base when forcing a minimum of 2.4 (rather than 2.3)?

**Comment by tomwanzek** [comment] 2018-02-15 23:38
I guess one of the added challenges is that we don't have a Changelog per se to flag potentially breaking changes to how the D3 definitions are consumed. And the obvious disconnect, that a breaking change could occur in a minor version release of the definitions, since they are aligned with the underlying D3 release cycle.

@gustavderdrache What's your take on TS 2.4 as the new minimum?

**Comment by tomwanzek** [comment] 2018-02-16 02:15
As seen in PR #23654, we appear to cascade quickly when going to TS 2.4 (even if it is just imposing the constraint for DT's sake without using any TS 2.4 features like string enums).

**Comment by tomwanzek** [comment] 2018-02-20 18:04
For clarity as per the new PR #23724 we can proceed with simply using TS 2.3. No need to push forward with TS 2.4 as of now.

**Comment by tomwanzek** [comment] 2018-02-20 18:06
@Ledragon If you want to open the PR you already had pending in your local **d3-geo** fork, then we can work through to check off the boxes above.

**Comment by Ledragon** [comment] 2018-02-20 18:14
I actually can't get it testing locally... So I think I can submit it, but I don't think it will pass the travis tests. I'll just go ahead and see

**Comment by Ledragon** [comment] 2018-02-20 18:18
#23794 submitted - not my proudest work, let's see how it goes...

**Comment by Ledragon** [comment] 2018-02-20 18:33
Okay, so the problem is as follows: `d3-geo` tests fail in TS 2.3, so I tried setting the version to 2.4. However, `d3` global is set to TS 2.3, so that does not work either. Any advice on how to proceed?

**Comment by tomwanzek** [comment] 2018-02-20 18:40
I'll look at the **g3-geo** PR and will put any review comments there to keep them focused. Unlike with the OoM bug I had with **d3-collection**, we have a proper error message to work with 😄

**Comment by Ledragon** [comment] 2018-03-06 18:40
Just submitted #24118 to update `d3-contour` to 1.2.0
I noticed that `d3-contour` types are already in `TS2.3`, and have `strictNullChecks` and `strictFunctionTypes` set to true :-)

**Comment by tomwanzek** [comment] 2018-03-06 19:04
Thanks for staying on top of **d3-contour**, made me notice that for some odd reason I did not have the repo on "Watching". Changed that! :smile:

Will look at the PR shortly.

**Comment by denisname** [comment] 2018-03-13 23:03
I am working on d3-axis and d3-format. I'm almost done. But have some questions...

In d3-format I want to use the same `Numeric` interface than in d3-array:

```typescript
interface Numeric {
    valueOf(): number;
}
```

But when doing this, in the d3 global definitions, I logically have the error: `Module 'd3-array' has already exported a member named 'Numeric'.` Is there a place to put shared types for d3 libraries?

Also in some d3 definitions (interpolate, scale, shape) you can find the union type `number | { valueOf(): number }`. Is `{ valueOf(): number }` not enough?

**Comment by tomwanzek** [comment] 2018-03-13 23:38
@denisname Thanks for volunteering for `d3-axis`, `d3-format` and later `d3-array` !!!

To your questions above:

(1) As a fundamental rule for writing the definitions for `d3-xxx` modules, the definitions must never introduce dependencies that do not exist among the underlying corresponding D3 modules. E.g. `d3-axis` has no dependency on `d3-array`, therefore, the definition `index.ts` file for `d3-axis` must not import from `d3-array`. This ensures loose coupling corresponding to the JS sources. So in case of doubt check the `dependencies` property of the underlying D3 module's `package.json` _Note: You can of course import from any package in the `d3-xxx-test.ts` file, this is even a good practice we followed in a number of packages for "integration" testing. I.e. there may be no formal dependency between two packages, but members of one are "naturally" used a input for the other. E.g. we are using `d3-selection` in a test in `d3-chord` to ensure  a chord path can be passed into a selection attribute setter without issues._

(2) You are correct, that the `Numeric` interface cannot be re-declared in any other  D3 module, which cannot import from `d3-array` in compliance with rule (1).

(3) Is `{ valueOf(): number }` not enough? Technically, yes. Practically, the intersection type, while having some redundancy, is declaratively probably clearer for a lot of human users. I.e. it shows that `number` is a valid type at first glance without mental acrobatics. :wink:

**Comment by denisname** [comment] 2018-04-02 12:38
About d3-color, why are the `prototype` all commented out? It has been done in this [commit](https://github.com/tomwanzek/d3-v4-definitelytyped/commit/69f94d8e6b77666acbdd169b5c775e605d57f8c1#diff-95a5408c15f9699b4f9fcfba278d6bf7) by @tomwanzek.

With the prototypes set back, we could use `instanceof` directly, without the need for a typeguard function:

```typescript
let cRGB: d3.RGBColor;
let cHSL: d3.HSLColor;

const c: d3.RGBColor | d3.HSLColor = d3.color("steelblue");

if (c instanceof d3.rgb) {
    cRGB = c;
} else {
    cHSL = c;
}
```

**Comment by tomwanzek** [comment] 2018-04-03 22:38
@denisname I have been hesitant to define `prototype` as part of the published API in an interface, it feels too hacky.

**Comment by denisname** [comment] 2018-04-04 16:04
For what I understand from today's [type guards spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#424-type-guards). This is now considered as a valid _construction_. See the list item:

> A type guard of the form `x instanceof C`, where x is not of type Any, `C` is of a subtype of the global type 'Function', and `C` has a property named 'prototype' [...]

I would like to propose a `strictNullChecks` version of `d3-color`. Which is just a one line change. This would be an opportunity to add `prototype` too.

**Comment by gustavderdrache** [comment] 2018-04-04 16:07
From my own testing, you need either the `prototype` property or a `new(): T` declaration for `instanceof` to properly narrow the type. I used the [`new(): Color`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3/v3/index.d.ts#L1472) variation in the v3 typings, and it might be useful if that idiom is still supported by D3v4 and above.

**Comment by tomwanzek** [comment] 2018-04-05 02:51
As either one seems fine, I think we might follow the v3 convention for continuity. Great work, both.

**Comment by denisname** [comment] 2018-04-13 14:15
@gustavderdrache

My understanding of why it works in d3 v3 is that the return type of `new()` is always the same as the  `prototype` type. But in d3 v4 we also have:

```typescript
export const color: ColorFactory;
export interface ColorFactory extends Function {
    (cssColorSpecifier: string): RGBColor | HSLColor;
    prototype: Color; // and not RGBColor | HSLColor !
}
```

Indeed, `d3.lab(0,0,0) instanceof d3.color` is true. Hence, if we change this interface to:

```typescript
export const color: ColorFactory;
export interface ColorFactory extends Function {
    (cssColorSpecifier: string): RGBColor | HSLColor;
    new (cssColorSpecifier: string): RGBColor | HSLColor;
}
```

We don't have as `prototype` for `ColorFactory` the type `Color`. And the following code fail to compile, while it should not.

```typescript
declare let l: d3.LabColor | null;
declare let c: d3.Color;
declare let nil: null;

if (l instanceof d3.color) {
    c = l; // l is not inferred as `d3.LabColor`...
} else {
    nil = l; // fail, l is a `d3.LabColor | null` should be a `null`
}
```

What is your opinion? Is there a way to make it work with `new`? Thanks.

**Comment by gustavderdrache** [comment] 2018-04-13 14:41
It looks like the `prototype` property for `color()` should be `Color` and not `RGBColor | HSLColor`, based on some testing:

```js
> d3.color.prototype === d3.rgb.prototype
false
> d3.rgb.prototype instanceof d3.color
true
```

The `color()` function returns RGB or HSL colors, but its prototype is a supertype of the other color spaces.

**Comment by tomwanzek** [comment] 2018-04-14 17:07
@denisname @Ledragon @gustavderdrache since you are all on this thread, just as a brief FYI: I intend to catch up on the open items which you are aware of this weekend.

**Comment by tomwanzek** [comment] 2018-04-14 21:05
Alright, d3-geo is out the door (thanks @ledragon) and I commented on @denisname 's unfortunately closed PR for `d3-format` and `d3-axis` regarding re-opening.

As a general note, I would recommend @denisname be added as another maintainer to definitions, they work on.

**Comment by Ledragon** [comment] 2018-04-18 19:41
I might have a look at `d3-color` next, and join it with an update to [1.1.0](https://github.com/d3/d3-color/releases/tag/v1.1.0). Should we open a separate issue for this upgrade?

**Comment by Ledragon** [comment] 2018-04-18 19:58
Also, welcome on board @denisname !

**Comment by denisname** [comment] 2018-04-18 20:03
@Ledragon Thanks.

I have an update ready for `d3-color` (no `lhc` and `gray` yet). I'm just stuck by [one little](#issuecomment-381149030) problem.

@gustavderdrache said:
> The color() function returns RGB or HSL colors, but its prototype is a supertype of the other color spaces.

Indeed and this can be _typed_ easily, see the first interface in my [comment](#issuecomment-381149030). But @tomwanzek [proposed](#issuecomment-378805513) to use only `new()` and avoid `prototype`. I think that in this particular case it is not possible. No?...

**Comment by gustavderdrache** [comment] 2018-04-18 20:35
After playing with it some more, I'm seeing the problem. You can set `new(): Color` in the `ColorConstructor` interface, but it doesn't actually cover the return value of the function:

```ts
declare namespace d3 {
  interface Color {
    // I forgot what was on the Color interface
    // This property exists just to make Color incompatible with {}
    __isColor: never;
    toString(): string;
  }

  interface RGBColor extends Color {
    r: number;
    g: number;
    b: number;
  }

  interface HSLColor extends Color {
    h: number;
    s: number;
    l: number;
  }

  interface LABColor extends Color {
    l: number;
    a: number;
    b: number;
  }

  interface ColorConstructor {
    (specifier: string): RGBColor | HSLColor;
    new(specifier: string): Color; // <- TS uses this for narrowing with instanceof
  }

  const color: ColorConstructor;
}

declare let l: d3.LABColor | null;
declare let c: d3.Color;
declare let nil: null;

if (l instanceof d3.color) {
  // Succeeds with l: d3.LABColor
  c = l;
} else {
  // Succeeds with l: null
  nil = l;
}
```

In conclusion: I think we have to expose the `prototype` property, because it's really the only way to cover the correct behavior of both the constructor and `instanceof` testing:

```ts
  interface ColorConstructor {
    (specifier: string): RGBColor | HSLColor;
    new(specifier: string): RGBColor | HSLColor;

    readonly prototype: Color; 
  }
```

**Comment by tomwanzek** [comment] 2018-04-24 04:02
Sorry, for the delay in getting back to this. Feel free to go with `prototype`, back in the day, it was my first impulse to address the `instanceof` as well. It just "felt" hacky, but as it is considered an acceptable practice, and if continuity with using `new()` as in D3v3 is not an option...Let's go with what works!

**Comment by denisname** [comment] 2018-05-07 07:34
@tomwanzek could you update the tracking table.

An ✅ should be set in columns `strictNullChecks` `strictFunctionTypes` and `TS 2.3` for libraries [`d3-axis`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25066), [`d3-color`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25211), [`d3-dispatch`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25387), [`d3-format`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25015), [`d3-polygon`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25538) and [`d3-hsv`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25515).

Also an ✅ should be set in column `JSDoc` for [`d3-dispatch`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25387), [`d3-polygon`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25538) and [`d3-hsv`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25515).

Thanks

**Comment by tomwanzek** [comment] 2018-05-13 22:07
@denisname for `d3-geo`s `GeoIdentityTranform`, I think we could do the following:
* Rename the misspelled interface (Great catch!) (including its use as a return type of `geoIdentity()`
* For the time being add
```ts
/**
 * @deprecated Misspelled name. Use GeoIdentityTransform.
 */
export type GeoIdentityTranform = GeoIdentityTransform;
```
* At a later convenient stage remove the misspelled type altogether.

**Comment by tomwanzek** [comment] 2018-05-13 22:10
@denisname 💯   @gustavderdrache @ledragon Thanks for all the hard work over the past little while. I updated the tracking table, looks so much prettier already! 'cause a pretty tracking table is what we are aiming for here :smile:

**Comment by gustavderdrache** [comment] 2018-05-13 22:36
> 'cause a pretty tracking table is what we are aiming for here

Absolutely! The improved type definitions are just a pleasant side effect.

**Comment by tomwanzek** [comment] 2018-05-19 23:31
Are any of you working on specific definitions right now for completion of the technical debt? While **d3-array** is in process. I would tackle the `strictFunctionTypes` in *d3-transition* next to bring it to parity with **d3-selection**.

**Comment by Ledragon** [comment] 2018-05-20 15:50
Not ATM. Will let y'all know if and when I do

**Comment by Ledragon** [comment] 2018-05-20 16:40
Working on #25582 to be able to stamp the 5.2.0 global bundle

**Comment by Ledragon** [comment] 2018-06-17 08:39
@denisname @tomwanzek @gustavderdrache 
Should we focus on this, or on updating d3 to the latest version? We are now 5 minor versions behind on the global package (though all sub-packages are ready for `5.2.0` I think). Shall I open a separate issue for tracking the global package status?

**Comment by tomwanzek** [comment] 2018-07-02 22:17
@Ledragon I will catch up with the open PRs tonight and parse all D3 module definitions for currency. If there are any lags, I will create one tracking issue to bring them up to par. As for priorities, I agree that currency should take priority over technical debt reduction.

**Comment by phil-lgr** [comment] 2018-07-18 21:36
Sorry to pollute this thread, I'm getting back into D3.js now for a new project.. and I was wondering if having inline TypeScript annotation was considered for D3? 

```
/** @type {SyncBailHook<Compilation>} */
shouldEmit: new SyncBailHook(["compilation"]),
```
In webpack, they started using it to check JavaScript with the TypeScript compiler.. big plus is the typing definitions live right next to the actual code.
https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L51

**Comment by Ledragon** [comment] 2018-07-20 16:11
Hi @phil-lgr 
There was a discussion on the `d3` issue tracker not so long ago, and it did not seem to be on the top of the priority list (i.e. Mike Bostock prefered focusing on developing the library itself rather than the typings). I can't seem to find a link to the thread. Maybe the question can be raised again thanks to this new information, but I don't think it likely to happen

**Comment by denisname** [comment] 2018-09-13 09:10
@tomwanzek could you update the tracking table.

An ✅ should be set in columns `strictNullChecks` `strictFunctionTypes` and `TS 2.3` for libraries [`d3-hexbin`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28577), [`d3-hierarchy`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27750), [`d3-quadtree`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27648), [`d3-queue`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28583), [`d3-request`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28580), [`d3-timer`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25973) and [`d3-voronoi`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28562).

Also an ✅ should be set in column `JSDoc` for [`d3-color`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25893), [`d3-hierarchy`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27619) and [`d3-quadtree`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27648).

Thanks

**Comment by orta** [comment] 2021-06-07 13:20
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:20 UTC
