### ISSUE TITLE
[@types/atom] Property 'registeredCommands' does not exist on type 'CommandRegistry'

### ISSUE THREAD

**Issue by idleberg** [DefinitelyTyped/DefinitelyTyped#49546] opened 2020-11-13 18:54 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aminya 

`atom.commands.registeredCommands` returns all commands registered by Atom core and packages. It is currently not supported by the type definitions.

> Property 'registeredCommands' does not exist on type 'CommandRegistry'.ts(2339)

**Comment by aminya** [comment] 2020-11-13 20:56
I was planning on adding all the missing types. I think I should do it incrementally.

**Comment by lierdakil** [comment] 2020-11-14 21:20
[There is no `registeredCommands` in the public API](https://flight-manual.atom.io/search/?utf8=%E2%9C%93&q=registeredCommands). We deliberately tried to avoid adding non-public methods to the type definitions, since there is zero guarantee those will even be available in the next patch release. Whether we succeeded, that's an open question, certainly a few undocumented albeit relatively stable things got through.

Adding _everything_ to the public type definitions is pure madness, that makes API either too rigid or too brittle to do anything with. Only the public guaranteed-to-be-mostly-stable interface should be there, and it's _mostly_ there, IIRC only a couple new things are missing.

@idleberg, if you want to use non-public internals, just add ambient definitions yourself. I'm opposed to adding anything not documented in the public API to the definitions, since those are much more succeptable to breakage.

**Comment by aminya** [comment] 2020-11-14 21:44
@lierdakil TypeScript provides some ways to mark some ways for marking some of the functions as internal. For example, we can define a decorator that throws a warning during the compile time. But "erroring" is not a good decision. 

I am not saying that we should provide everything, but there are some methods that are useful, and redefining them in every single package that needs them is not logical.

In my opinion, we can define a decorator that throws a warning during compile-time but allows the users to use them during runtime.

**Comment by lierdakil** [comment] 2020-11-14 23:00
@aminya, the issue is: there is no way to check that our definitions here are describing anything resembling what's actually there, save for going over the whole of Atom code base and looking long and hard at the implementation of every single definition. I hope we can agree that is infeasible. You can diff the (automatically generated) public API description to learn what changed between releases and make the necessary changes to the definitions. It's infeasible to diff the whole of code base, because there's simply too much noise to filter through.

Thus, including something that's not defined in the public API creates an invisible breakage point, and the only way it will eventually be caught is when end-user code breaks. This is exactly the problem that type definitions are supposed to fix. So, at least after a point, including anything not in the public API actually makes type definitions _less_ useful the more you add.

The public API + the non-public definitions we currently have here should be enough for the absolute majority of packages. In fact, if you're using something not in the type definitions, I would argue you're probably doing something weird and brittle and uncomfortably tied to Atom internals. I know that, because I do these things in Atom-TypeScript, and they've caused me quite a bit of trouble with subtle breakage between minor Atom versions. That's not to say that something like this has no place -- I do it after all -- but essentially endorsing careless use of internals via type definitions is in my opinion not a great strategy.

> we can define a decorator that throws a warning during compile-time

I'm only aware of `@deprecated` jsdoc comment being supported since TS 4.0, but in any case, peppering definition users with warnings along the lines of "we added this to type definitions, but we don't actually know if it's there, or if it works, or whether its interface had changed, so check for that yourself or don't use it" is in my opinion more annoying than useful, so I don't think it's a good strategy. If something in the non-public API is used by a lot of people, or that something is particularly useful for package authors, the right thing to do is to add that thing to the public API on the Atom side first, which would hopefully ensure some semblance of interface stability, and _then_ add it to the definitions -- but that can perhaps be a little tricky if you're not on the Atom team (and even then, perhaps not as simple as just doing it). If something's used by only one or two packages, there's no good reason to bother frankly.

***

Coming back to the issue at hand, I would argue in general there is no good reason to want to use `registeredCommands` at all. If your package depends on other packages, use service provider/consumer API. If there is no provider/consumer API, ask the developer of the package to add one (nicely). If you're trying to do some sneaky monkey-patching, that's a horrible idea, very brittle and with potential long-reaching ramifications, please rethink your approach. If you want to invoke some core handler, you should use `dispatch`. Granted, perhaps there is a legitimate use for it in some edge-case I didn't think of from the top of my head. But that's not a good reason to include that in the public API -- in the absolute majority of cases, `registeredCommands` shouldn't be used directly.

**Comment by orta** [comment] 2021-06-07 13:02
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:02 UTC
