### ISSUE TITLE
[@types/lodash] chain.find.value should return possibly undefined

### ISSUE THREAD

**Issue by dmelikhov** [DefinitelyTyped/DefinitelyTyped#43447] opened 2020-03-28 18:18 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow. No one answers :(](https://stackoverflow.com/q/60902862/4012848).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r @sandersn

I have a simple project using latest typescript, lodash and @types/lodash.  

In the following code `user` variable has type `User | undefined`
and I get a compile-time type error near `.id` as expected:
```typescript
interface User {
    id: number
}

const users: User[] = [];

const user = _.find(users, { id: 42 });
console.log(user.id);
```

and here I also expect the same error:
```typescript
const collectionChain = _.chain(users);
const objectChain = collectionChain.find({ id: 42 });
const user = objectChain.value();
console.log(user.id);
```
but now `user` variable has type `User`, the code compiles and I get a runtime error instead.

Am I missing something or is this a bug? Thanks.

Possibly related to #35400 #43283

**Comment by aj-r** [comment] 2020-03-29 03:06
I think this used to work correctly, but changed in ts3.1 due to
performance issues. The issue is that it's hard to support the full range
of return values in chain functions without killing the compiler. Open to
PRs if someone can figure out a way to do this.

However, instead of using chains, I recommend using lodash/fp and the flow
function. This allows tree shaking to work better (in builds that support
it).

**Comment by orta** [comment] 2021-06-07 13:33
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:33 UTC
