### ISSUE TITLE
error TS2411 on @types/mongoose-paginate-v2

### ISSUE THREAD

**Issue by kerolloz** [DefinitelyTyped/DefinitelyTyped#44404] opened 2020-05-01 02:12 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose-paginate-v2` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @linusbrolin @simonxca @woutgg @oktapodia @ChazEpps @gamsterx 

If you do not mention the authors the issue will be ignored.

```
> tsc

node_modules/@types/mongoose-paginate-v2/index.d.ts:70:9 - error TS2411: Property 'nextPage' of type 'number | null | undefined' is not assignable to string index type 'number | boolean | T[] | undefined'.

70         nextPage?: number | null;
           ~~~~~~~~

node_modules/@types/mongoose-paginate-v2/index.d.ts:71:9 - error TS2411: Property 'prevPage' of type 'number | null | undefined' is not assignable to string index type 'number | boolean | T[] | undefined'.

71         prevPage?: number | null;
           ~~~~~~~~

```

**Comment by gamsterx** [comment] 2020-05-01 09:27
Duplicate of #44285 

For a workaround please have a look at this [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44285#issuecomment-620652527).

**Comment by kerolloz** [comment] 2020-05-02 15:08
@gamsterx 
is there any fix coming soon?

**Comment by orta** [comment] 2021-06-07 13:07
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:07 UTC
