### ISSUE TITLE
Wrong typing for Inputmask#mask

### ISSUE THREAD

**Issue by dev054** [DefinitelyTyped/DefinitelyTyped#50070] opened 2020-12-10 20:58 UTC
- [x] I tried using the `@types/inputmask` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dmester

Currently the type of _Inputmask#mask_ is: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4486794741ccb9f18f562fefade043ac31e817de/types/inputmask/index.d.ts#L553

... however this return type could be either `Instance` or an object **with** `Instance` according to the code that lives in `inputmask` repo, as you can see here:

https://github.com/RobinHerbots/Inputmask/blob/7f3577e74715aa4e591113c3772f3b33c22982de/lib/inputmask.js#L78-L108

Actually it brings a bug in my app because I was doing something like this:

```ts
const inputMaskInstance = Inputmask(inputMaskOptions).mask(someElementRef);
...
inputMaskInstance.remove(); // boom, remove is not a function
```

That said, I'm unsure we could proper type the `mask` function and thus I would vote to return `unknown` instead, to force people to check it before using any property. WYDT, @dmester?

**Comment by dmester** [comment] 2020-12-11 07:44
I'm afraid I have not been able to reproduce this issue so far. In all my tests, an `Inputmask` instance has been returned. See test code below.

There are two return values in `mask()`:
* `this`, which is an `Inputmask` instance (unless you call it with `call` or `apply`, or in another way where `this` is lost).
* `elems[0].inputmask`, which is set to an `Inputmask` instance [here](https://github.com/RobinHerbots/Inputmask/blob/7f3577e74715aa4e591113c3772f3b33c22982de/lib/inputmask.js#L94).

I might have missed some case though.

However I did spot another error when the mask instances were removed in the wrong order with Inputmask 5 (see last test case in test code).

Test code:
```html
<input id="el">

<!-- v4 -->
<!--
<script src="https://cdn.jsdelivr.net/npm/inputmask@4.0.9/dist/inputmask/dependencyLibs/inputmask.dependencyLib.js"></script>
<script src="https://cdn.jsdelivr.net/npm/inputmask@4.0.9/dist/inputmask/inputmask.js"></script>
-->

<!-- v5 -->
<script src="https://cdn.jsdelivr.net/npm/inputmask@5.0.5/dist/inputmask.js"></script>

<script>

    var el = document.getElementById("el");

    const mask1 = Inputmask("99-99");
    console.log("mask1 is Instance:", mask1 instanceof Inputmask);

    const mask2 = new Inputmask({"mask": "(999) 999-9999"});
    console.log("mask2 is Instance:", mask2 instanceof Inputmask);

    const mask3 = mask1.mask(el);
    console.log("mask3 is Instance:", mask3 instanceof Inputmask);
    mask3.remove();
    console.log("mask3 removed");

    const mask4 = mask1.mask("el");
    console.log("mask4 is Instance:", mask4 instanceof Inputmask);
    mask4.remove();
    console.log("mask4 removed");

    const mask5 = mask2.mask("#el");
    console.log("mask5 is Instance:", mask5 instanceof Inputmask);
    mask5.remove();
    console.log("mask5 removed");

    const mask6 = mask2.mask([el]);
    console.log("mask6 is Instance:", mask6 instanceof Inputmask);
    mask6.remove();
    console.log("mask6 removed");

    // This case throws an error in version 5
    const mask7 = mask2.mask(el);
    console.log("mask7 is Instance:", mask7 instanceof Inputmask);
    const mask8 = mask2.mask("el");
    console.log("mask8 is Instance:", mask8 instanceof Inputmask);
    mask8.remove();
    console.log("mask8 removed");
    mask7.remove();
    console.log("mask7 removed");

</script>
```

Output v5:
```
mask1 is Instance: true
mask2 is Instance: true
mask3 is Instance: true
mask3 removed
mask4 is Instance: true
mask4 removed
mask5 is Instance: true
mask5 removed
mask6 is Instance: true
mask6 removed
mask7 is Instance: true
mask8 is Instance: true
mask8 removed

inputmask.js:1013 Uncaught TypeError: Cannot read property 'opts' of undefined
    at unmaskedvalue (inputmask.js:1013)
    at Inputmask.remove (inputmask.js:119)
```

**Comment by dev054** [comment] 2020-12-11 13:34
Hey @dmester thanks for the fast answer.. well, I'm afraid my use case is really difficult to simulate because I use Angular and I have a `@Directive` that uses `inputmask` under the hood so it could have happen even because of a DOM node destruction or something else.

Yet, I tried to do something using [jsfiddle](https://jsfiddle.net/6fmpc7rn/) and that's really interesting... when I print the return of a `Inputmask({...}).mask(...)` I get the following result:

![Captura de Tela 2020-12-11 às 10 23 43](https://user-images.githubusercontent.com/28629080/101908613-17c9c180-3b9b-11eb-8748-9da4d69c4612.png)

... as you can see there's no remove (HOWEVER I can call this function without problems, do you know why?) and also you can notice there are much options than what we have in `Inputmask.Instance`, so in any case, shouldn't these options be included in `Inputmask.Instance` to reflect it? Thanks again.

**Comment by dmester** [comment] 2020-12-12 14:51
**Regarding remove():**
It is defined on the prototype of `Inputmask`. You can see it by expanding `__proto__` at the bottom of the screenshot. The accessible interface is the union of what you see in the screenshot and the ancestor prototypes.

**Regarding the non-exposed properties:**
Only methods and properties documented at https://github.com/RobinHerbots/Inputmask are included in the typings. I have considered all other members as implementation details of Inputmask. Since JavaScript does not support private members (yet), documentation is the only way of knowing what members that are intended to be part of the public API.

**Comment by orta** [comment] 2021-06-23 08:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-23 08:09 UTC
