### ISSUE TITLE
refs field on custom react component not allowed

### ISSUE THREAD

**Issue by jbrownson** [DefinitelyTyped/DefinitelyTyped#5347] opened 2015-08-13 03:44 UTC
The following code:

``` typescript
/// <reference path="../typings/tsd.d.ts" />
import * as React from "react"

class ComponentA extends React.Component<{}, void> {
  render() { return <div>ComponentA</div> } }

class ComponentB extends React.Component<{}, void> {
  render() { return <ComponentA ref="a" /> } }
```

gives the following error:

```
at line 8, file [omitted] Property 'ref' does not exist on type '{}'.
```

This is in fact valid react code, and it works on elements like &lt;div&gt;, but not custom ones. I spent some time trying to dig into the code, but it's not obvious to me how the whole JSX.Element type works, it seems to be some magic in the TypeScript compiler. I thought I'd post it up here before I spent too much time in case it's obvious to someone else.

**Comment by vvakame** [comment] 2015-08-15 08:46
@jbrownson please send a pull requet. I'll review it.

**Comment by jbrantly** [comment] 2015-08-16 23:07
The issue is that the props for ComponentA are determined by the props that you specified when creating ComponentA. When you say `class ComponentA extends React.Component<{}, void>` you are saying that the props for ComponentA are `{}`. When you later try to use `ref` as a prop it does not work.

Try something like `class ComponentA extends React.Component<{ref: string}, void>`.

I can see if there's a way we can have a set of intrinsic properties like `ref`.

**Comment by use-strict** [comment] 2015-09-23 22:57
```typescript
interface ComponentAProps extends React.Props<ComponentA> {
}
class ComponentA extends React.Component<ComponentAProps, {}> {
}
```

**Comment by IanKemp** [comment] 2018-12-11 12:52
I see that the interface docs for `React.Props<T>` state that this interface is deprecated. Is there currently a non-deprecated way to achieve this? If not, then the deprecation warning should be removed.

**Comment by orta** [comment] 2021-06-07 13:46
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:46 UTC
