### ISSUE TITLE
rx-lite doesn't compile w/o DOM typings

### ISSUE THREAD

**Issue by justinfagnani** [DefinitelyTyped/DefinitelyTyped#13733] opened 2017-01-04 18:42 UTC
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @mhegazy

Some change in my project's dependencies brought in the latest rx-lite typings and now my project no longer compiles because rx-lite/index.d.ts references `NodeList`. This might have happened because of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13652 though the previous factoring also referenced `NodeList`.

I worked around this my by adding my own custom typing:

```typescript
declare namespace Rx {
  interface NodeList {}
  interface Node {}
}
```

Is there a way that rx-lite could provide these typings, or somehow fallback to the dom typings only if available?

**Comment by mhegazy** [comment] 2017-01-04 20:52
I do not think this is caused by my change specifically. The contents of `rx-lite` was there in `rx` before any ways. i think the issue is that the `fromEvent` should depend on a type that has `addEventListener` and not `Node` from DOM. I will get a fix for this out.

**Comment by justinfagnani** [comment] 2017-01-04 22:20
Thanks a lot @mhegazy 

Just curious, what would be the right approach if a package did depend on DOM types, but was also intended to be used in node? Would that force node projects to include the DOM types or skip type checking libs?

**Comment by mhegazy** [comment] 2017-01-05 04:52
I do not have a general recommendation to be frank. Do you have a framework in mind?

In this case RX used the concept of DOM events, and residing in the type seems like a reasonable way to model what the code does to check for the type at runtime. Structural type system to the rescue :)

This might not be possible in other cases if the code depends hevely on DOM types; I would assume in this case users will need to add the DOM, or maybe split the library into a non-DOM specific part and a DOM specific one.

**Closed** 2017-01-05 17:36 UTC
