### ISSUE TITLE
[@types/react-redux] connect(mapStateToProps, null)(Component) infers wrong prop type for resulting component in TS 3.6.2

### ISSUE THREAD

**Issue by beark** [DefinitelyTyped/DefinitelyTyped#38167] opened 2019-09-05 21:51 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-redux` package and had problems.
    - I tried with `@types/react-redux` v7.0.6 and v7.1.2
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
    - I tried with `typescript` v3.5.2 and v3.6.2
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang  @NicholasBoll @mDibyo @Kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @MrWolfZ 

Today I tried updating typescript from 3.5.2 to 3.6.2 and noticed that I was getting a type error when trying to use a connected component--where previously there was none. [Playground link](https://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAbzgYwgOzQU2fAvnAMyghDgHIpMBDHAWkoBMBXADzIG4AoUSWOAKjhUAznABK1HIWKkKkmB06cYATzCY4AZRKYACsTCiAvIk5whwmFGBoA5gC44l63bNC0TEACNMURx+9fTlwlAiY0HGB0OBAqME0YKhhMABUIfQhDAApLJMxHJGEdXOT-Tx8oOFwASgL3ct8ywMr8BDdKGCYoNER65scSzAA6IpBMQZCQzlQ0SzgAYRJILDR4EyywA2FHbTGMw2q4IwA+U3MOrp6AHgZgADdjhE3M4SGRKxtbXCett4CK3BXAD0tweXCmMzmiww2GSDEW4HQmFWRxQ6CwOCysXiiWSaX2wgANHAPAAbUnVLII5bImDVJSQ+ApcZrOBZQ4nM5wC7dOBXaEYuHUpEo94uWxGABEo0wMAAFp9JXAgcdgpwgA) to a fairly minimal repro, code also included below for reference:

```ts
import { connect } from 'react-redux';
import * as React from 'react';

type SomeProps = {
  astring: string
  anumber: number
}

function mapStateToProps(state: { somestate: number }): { anumber: number } {
  return { anumber: state.somestate}
}

const Component = (props: SomeProps) => {
  return <div>{props.astring}{props.anumber}</div>;
}

const ConnectedComponent = connect(mapStateToProps, null)(Component)

const Test = () => {
  // Ok in 3.5.x, error in 3.6.x
  return <ConnectedComponent astring="something" />
}
```

Note that the TS playground doesn't yet have 3.6, so the link above is to 3.5.1, where it actually works as expected. To observe the discrepancy, hover over `ConnectedComponent` in the playground and note that its type is

```ts
const ConnectedComponent: ConnectedComponentClass<
  (props: SomeProps) => JSX.Element,
  Pick<SomeProps, "astring">
>
```

Now, copy+paste the code from the playground into any React+redux project in latest vscode (which uses TS 3.6.2), and note that the inferred type is now

```ts
const ConnectedComponent: ConnectedComponentClass<
    (props: SomeProps) => JSX.Element,
    Pick<SomeProps, "astring" | "anumber">
>
```

Note `anumber`, which should not be there, since it is provided by `mapStateToProps`.

**Comment by val1984** [comment] 2019-09-06 05:19
You can fix it by removing the unused null parameter in your connect call. Haven't had time to seek the root cause for this but doing so fixed the errors in my projects.

**Comment by beark** [comment] 2019-09-06 16:59
That does indeed seem to work around the issue, thanks! Not entirely sure why we were explicitly passing `null` to begin with (I did not write the code in question, I just discovered this type error when I upgraded TS)...

Anyway, I did a little bit of digging and think I found the root cause, though I'm not sure what the _correct_ fix is. Starting from the beginning, the connect signature that gets matched is:

```ts
interface Connect {
    <TStateProps = {}, TDispatchProps = {}, TOwnProps = {}, State = {}>(
        mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps, State>,
        mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
    ): InferableComponentEnhancerWithProps<
        TStateProps & ResolveThunks<TDispatchProps>,
        TOwnProps
    >;
}
```

This gets instantiated with:
```ts
type TStateProps = { anumber: number };
type TDispatchProps = null;
type TOwnProps = {};
type State = { somestate: number };
```

This in turn instantiates `InferableComponentEnhancerWithProps` with:
```ts
type TInjectedProps = { anumber: number } & ResolveThunks<null>;
type TNeedsProps = {};
```

Now, `ResolveThunks<null>` evaluates to simply `null`. Meaning, `TInjectedProps = never`. This is the difference between 3.5.x and 3.6.2: `{ anumber: number } & null = never` in 3.6.2, but _not_ in 3.5.x. This then leads to:
```ts
type WhereThingsGoWrong =
  <C extends ComponentType<Matching<never, GetProps<C>>>>(
    component: C
  ) => ConnectedComponentClass<C, Omit<GetProps<C>, keyof Shared<never, GetProps<C>>> & {}>
```

And there we have it, `Shared<never, GetProps<C>>` is always simply `{}`, so we `Omit` nothing from the props of `C`.

**Comment by esetnik** [comment] 2019-12-17 18:04
Note that I have what I believe is a related issue. `children` prop is not passed correctly.

```ts
Type '{ children: Element; name: string; }' is not assignable to type 'IntrinsicAttributes & Pick<{ name: string; }, "name">'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Pick<{ name: string; }, "name">'.
```

```tsx
const TestComponent: React.FC<{ name: string }> = ({ name, children }) => (
  <div>
    {name}
    {children}
  </div>
);

const ConnectedTestComponent = connect()(TestComponent);

export const AnotherComponent: React.FC = () => {
  return (
    <ConnectedTestComponent name="test">
      <div>child</div>
    </ConnectedTestComponent>
  );
};
```

**Comment by orta** [comment] 2021-06-07 14:08
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:08 UTC
