### ISSUE TITLE
shopify-buy has incorrect types

### ISSUE THREAD

**Issue by chrisworman-pela** [DefinitelyTyped/DefinitelyTyped#43903] opened 2020-04-14 20:50 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/shopify-buy` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @openminder, @straiforos, @kilinkis

There appears to be incorrect interfaces in @types/shopify-buy 1.11.0

### CheckoutResource.addLineItems
The `CheckoutResource` interface indicates that `addLineItems` takes in a array of `LineItem` as its second parameter, but you get the following runtime error if that's actually what you pass in:
```
Error: [{"message":"Variable lineItems of type [CheckoutLineItemInput!]! was provided invalid value for 0.variant_id (Field is not defined on CheckoutLineItemInput)
```

### CheckoutResource.fetch/create & Cart
According to the `CheckoutResource` interface, the `fetch` (resp. `create`) returns a (promise-wrapped) `Cart`.

The `Cart` interface indicates a property called `checkoutUrl` should exist, but at runtime you can see the correct property name is `webUrl`.  In fact the runtime properties of a `Cart` object returned by a `fetch` or `create` call do not match the `Cart` interface at all.  Here are the runtime properties of the object returned by, for example, `CheckoutResource.fetch`:
```
id: (...)
ready: (...)
requiresShipping: (...)
note: (...)
paymentDue: (...)
paymentDueV2: (...)
webUrl: (...)
orderStatusUrl: (...)
taxExempt: (...)
taxesIncluded: (...)
currencyCode: (...)
totalTax: (...)
totalTaxV2: (...)
lineItemsSubtotalPrice: (...)
subtotalPrice: (...)
subtotalPriceV2: (...)
totalPrice: (...)
totalPriceV2: (...)
completedAt: (...)
createdAt: (...)
updatedAt: (...)
email: (...)
discountApplications: (...)
appliedGiftCards: (...)
shippingAddress: (...)
shippingLine: (...)
customAttributes: (...)
order: (...)
lineItems: (...)
type: (...)
```

The runtime properties seem to agree with the [official Shopify documentation for their API](https://shopify.dev/docs/storefront-api/reference/object/checkout).

**Comment by aethys256** [comment] 2020-05-17 13:19
Hello, I can confirm the issue, it is mostly because the SDK is in v2.x while the available types are meant for v1.x 😕

**Comment by Pushedskydiver** [comment] 2020-06-14 12:22
I too have come across a similar issue. When trying to access the `variantForOptions` product helper method I get a `Property 'helpers' does not exist on type 'ProductResource'.` error message.

I have managed to resolve this temporarily by creating a new `shopify-buy/index.d.ts` under the `@types` folder which contains the following code:

```
declare module 'shopify-buy' {
  export interface ProductHelpers {
    variantForOptions(product: ShopifyBuy.Product, options: ShopifyBuy.Option): ProductVariant
  }

  export interface ProductResource extends ShopifyBuy.ProductResource {
    helpers: ProductHelpers
  }
}
```

**Comment by EricSSartorius** [comment] 2020-12-09 22:07
I was able to get rid all my errors by adding the following file to extend the types:
```

namespace ShopifyBuy {
  export interface CheckoutResource {
    updateLineItems(
      checkoutId: string | number,
      lineItems: AttributeInput[]
    ): Promise<Cart>

    updateAttributes(
      checkoutId: string | number,
      input: CustomAttribute[]
    ): Promise<Cart>
  }

  export interface VariableValues {
    id: string | number
  }

  export interface CustomAttribute {
    key: string
    value: string
  }

  export interface Product {
    id: string | number
    handle: string
  }

  export interface UnitPriceMeasurement {
    measuredType: string
    quantityUnit: string
    quantityValue: number
    referenceUnit: string
    referenceValue: number
  }

  export interface SelectedOptions {
    name: string
    value: string
  }

  export interface Image {
    id: string | number
    src: string
    altText: string
  }

  export interface CompareAtPriceV2 {
    amount: string
    currencyCode: string
  }

  export interface CompareAtPrice {
    amount: string
    currencyCode: string
  }

  export interface Price {
    amount: string
    currencyCode: string
  }

  export interface PresentmentPrices {
    hasNextPage: boolean
    hasPreviousPage: boolean
    variableValues: VariableValues

    compareAtPrice: CompareAtPrice
    price: Price
  }

  export interface PriceV2 {
    amount: string
    currencyCode: string
  }

  export interface Variant {
    id: string | number
    title: string
    price: string
    weight: number
    available: boolean
    sku: string
    compareAtPrice: string
    unitPrice: string

    product: Product
    unitPriceMeasurement: UnitPriceMeasurement
    selectedOptions: [SelectedOptions]
    image: Image
    compareAtPriceV2: CompareAtPriceV2
    presentmentPrices: [PresentmentPrices]
    priceV2: PriceV2
  }

  export interface LineItems {
    id: string | number
    title: string
    quantity: number
    hasNextPage: boolean
    hasPreviousPage: boolean
    variableValues: VariableValues

    discountAllocations: [string]
    customAttributes: [CustomAttribute]
    variant: Variant
  }

  export interface TotalPriceV2 {
    amount: string
    currencyCode: string
  }

  export interface SubtotalPriceV2 {
    amount: string
    currencyCode: string
  }

  export interface LineItemsSubtotalPrice {
    amount: string
    currencyCode: string
  }

  export interface TotalTaxV2 {
    amount: string
    currencyCode: string
  }

  export interface PaymentDueV2 {
    amount: string
    currencyCode: string
  }

  export interface Cart {
    id: string | number
    ready: boolean
    requiresShipping: boolean
    note: string
    paymentDue: string
    webUrl: string
    orderStatusUrl: string
    taxExempt: boolean
    taxesIncluded: boolean
    currencyCode: string
    totalTax: string
    subtotalPrice: string
    totalPrice: string
    completedAt: string | null
    createdAt: string
    updatedAt: string
    email: string
    shippingAddress: string
    shippingLine: string
    order: string

    lineItems: [LineItems]
    customAttributes: [string]
    appliedGiftCards: [string]
    discountApplications: [string]
    totalPriceV2: TotalPriceV2
    subtotalPriceV2: SubtotalPriceV2
    lineItemsSubtotalPrice: LineItemsSubtotalPrice
    totalTaxV2: TotalTaxV2
    paymentDueV2: PaymentDueV2
  }
}
```

**Comment by straiforos** [comment] 2020-12-10 00:51
This Types library is out of date with the V2.

This was intended for V1. I personally wrote the V0->V1 with some minor flaws that others submitted fixes for. If you could please update the version number and the interfaces to match the new model it would be greatly appreciated. I did not end up needing the SDK since my project fell through. 

Good luck, happy to code review and match to the API documents.

**Comment by EricSSartorius** [comment] 2020-12-10 01:26
@straiforos that makes a lot of sense, thanks. I will try and find some time to update to V2 sooner than later.

**Comment by orta** [comment] 2021-06-23 08:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-23 08:09 UTC

**Comment by DevTalent1121** [comment] 2022-11-10 00:12
> If you know how to fix the issue, make a pull request instead.
> 
> * [x]  I tried using the `@types/shopify-buy` package and had problems.
> * [x]  I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
> * [x]  I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
> * [x]  [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
>   
>   * Authors: @openminder, @straiforos, @kilinkis
> 
> There appears to be incorrect interfaces in @types/shopify-buy 1.11.0
> 
> ### CheckoutResource.addLineItems
> The `CheckoutResource` interface indicates that `addLineItems` takes in a array of `LineItem` as its second parameter, but you get the following runtime error if that's actually what you pass in:
> 
> ```
> Error: [{"message":"Variable lineItems of type [CheckoutLineItemInput!]! was provided invalid value for 0.variant_id (Field is not defined on CheckoutLineItemInput)
> ```
> 
> ### CheckoutResource.fetch/create & Cart
> According to the `CheckoutResource` interface, the `fetch` (resp. `create`) returns a (promise-wrapped) `Cart`.
> 
> The `Cart` interface indicates a property called `checkoutUrl` should exist, but at runtime you can see the correct property name is `webUrl`. In fact the runtime properties of a `Cart` object returned by a `fetch` or `create` call do not match the `Cart` interface at all. Here are the runtime properties of the object returned by, for example, `CheckoutResource.fetch`:
> 
> ```
> id: (...)
> ready: (...)
> requiresShipping: (...)
> note: (...)
> paymentDue: (...)
> paymentDueV2: (...)
> webUrl: (...)
> orderStatusUrl: (...)
> taxExempt: (...)
> taxesIncluded: (...)
> currencyCode: (...)
> totalTax: (...)
> totalTaxV2: (...)
> lineItemsSubtotalPrice: (...)
> subtotalPrice: (...)
> subtotalPriceV2: (...)
> totalPrice: (...)
> totalPriceV2: (...)
> completedAt: (...)
> createdAt: (...)
> updatedAt: (...)
> email: (...)
> discountApplications: (...)
> appliedGiftCards: (...)
> shippingAddress: (...)
> shippingLine: (...)
> customAttributes: (...)
> order: (...)
> lineItems: (...)
> type: (...)
> ```
> 
> The runtime properties seem to agree with the [official Shopify documentation for their API](https://shopify.dev/docs/storefront-api/reference/object/checkout).

Is that working?

**Comment by DevTalent1121** [comment] 2022-11-10 00:15
> I was able to get rid of most of my errors by adding the following file to extend the types:
> 
> ```
> 
> namespace ShopifyBuy {
>   export interface CheckoutResource {
>     updateLineItems(
>       checkoutId: string | number,
>       lineItems: AttributeInput[]
>     ): Promise<Cart>
> 
>     updateAttributes(
>       checkoutId: string | number,
>       input: { customAttributes: CustomAttribute[] }
>     ): Promise<Cart>
>   }
> 
>   export interface VariableValues {
>     id: string | number
>   }
> 
>   export interface CustomAttribute {
>     key: string
>     value: string
>   }
> 
>   export interface Product {
>     id: string | number
>     handle: string
>   }
> 
>   export interface UnitPriceMeasurement {
>     measuredType: string
>     quantityUnit: string
>     quantityValue: number
>     referenceUnit: string
>     referenceValue: number
>   }
> 
>   export interface SelectedOptions {
>     name: string
>     value: string
>   }
> 
>   export interface Image {
>     id: string | number
>     src: string
>     altText: string
>   }
> 
>   export interface CompareAtPriceV2 {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface CompareAtPrice {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface Price {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface PresentmentPrices {
>     hasNextPage: boolean
>     hasPreviousPage: boolean
>     variableValues: VariableValues
> 
>     compareAtPrice: CompareAtPrice
>     price: Price
>   }
> 
>   export interface PriceV2 {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface Variant {
>     id: string | number
>     title: string
>     price: string
>     weight: number
>     available: boolean
>     sku: string
>     compareAtPrice: string
>     unitPrice: string
> 
>     product: Product
>     unitPriceMeasurement: UnitPriceMeasurement
>     selectedOptions: [SelectedOptions]
>     image: Image
>     compareAtPriceV2: CompareAtPriceV2
>     presentmentPrices: [PresentmentPrices]
>     priceV2: PriceV2
>   }
> 
>   export interface LineItems {
>     id: string | number
>     title: string
>     quantity: number
>     hasNextPage: boolean
>     hasPreviousPage: boolean
>     variableValues: VariableValues
> 
>     discountAllocations: [string]
>     customAttributes: [CustomAttribute]
>     variant: Variant
>   }
> 
>   export interface TotalPriceV2 {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface SubtotalPriceV2 {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface LineItemsSubtotalPrice {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface TotalTaxV2 {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface PaymentDueV2 {
>     amount: string
>     currencyCode: string
>   }
> 
>   export interface Cart {
>     id: string | number
>     ready: boolean
>     requiresShipping: boolean
>     note: string
>     paymentDue: string
>     webUrl: string
>     orderStatusUrl: string
>     taxExempt: boolean
>     taxesIncluded: boolean
>     currencyCode: string
>     totalTax: string
>     subtotalPrice: string
>     totalPrice: string
>     completedAt: string | null
>     createdAt: string
>     updatedAt: string
>     email: string
>     shippingAddress: string
>     shippingLine: string
>     order: string
> 
>     lineItems: [LineItems]
>     customAttributes: [string]
>     appliedGiftCards: [string]
>     discountApplications: [string]
>     totalPriceV2: TotalPriceV2
>     subtotalPriceV2: SubtotalPriceV2
>     lineItemsSubtotalPrice: LineItemsSubtotalPrice
>     totalTaxV2: TotalTaxV2
>     paymentDueV2: PaymentDueV2
>   }
> }
> ```
> 
> still some existing errors though. I wonder how these types got so far from the actual source

Hello @EricSSartorius 
What is the latest version of the @type/index.d.ts file? I can not build my project with currently online library. version is 2.10.10

**Comment by EricSSartorius** [comment] 2022-11-10 00:30
@DevTalent1121 hey not gonna lie, I haven't used thE Shopify API in about 3 years since switching jobs so I'm not too up to date on this anymore. My apologies.

**Comment by DevTalent1121** [comment] 2022-11-10 01:59
@EricSSartorius. You are welcome. It seems that shopify-buy types never matched properly with Shopify graphQL response.  Thank you!
