### ISSUE TITLE
[mongoose] problems using generic type (<T extends Document>)

### ISSUE THREAD

**Issue by jakubjirkal** [DefinitelyTyped/DefinitelyTyped#46550] opened 2020-08-04 14:48 UTC
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inapprsuopriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@horiuchi 
@lukasz-zak 
@jendrikw
@ethanresnick
@vologab
@jussikinnula
@ondratra
@alfirin
@idandrd
@various89
@Fazendaaa
@NormanPerrin 
@stablio
@emmanuelgautier
@frontendmonster
@mingchen
@penumbra1
@HughKu
@niuware
@vladmel1234
@jloveridge
@grimmer0125
@richarddd
@ToucheSir
@borfig
@dinodeSimon
@anthony-kenikh
@iamchathu
@lkho
@tomyam1
@nephix
@rlaace423
@ChazEpps
@avaly
@JanNemcik
@cl3dson
@richardsimko
@ith
@jeremyben
@andreialecu
@tHBp

Hey!
I've updated @types/mongoose to v5.7.34. 
I believe there is a bug when using generic types.

Let's say I have this document, model and data:
```ts
interface User {
    name: string;
    password: string;
}
type UserDocument = User & Document;
const schema = new Schema({name: {type: String}, password: {type: String}});
const userModel: Model<UserDocument> = model('User', schema);
const user: User = {name: "someName", password: '********'};
```

These functions work as expected:
```ts
const typedFindById = async (model: Model<UserDocument>, inputId: string) => {
    model.find({id: inputId});
}
typedFindById(userModel, 'someId');

const typedCreateDoc = async (model: Model<UserDocument>, doc: User) => {
    return model.create(doc);
};
typedCreateDoc(userModel, user);
```

I need to wrap those functions for any type extending Document. In the past versions (v5.5.X) of @types/mongoose, I've used it like this:
```ts
const genericFindById = async <T extends Document>(model: Model<T>, inputId: string) => {
    return model.find({id: inputId});
    // Argument of type '{ id: string; }' is not assignable to parameter of type 'MongooseFilterQuery<Pick<T, Exclude<keyof T, "toString" |...
    // Type '{ id: string; }' is not assignable to type '{ [P in keyof Pick<T, Exclude<keyof T, "toString" | ...
}
genericFindById(userModel, 'someId');

const genericCreateDoc = async <A, T extends Document & A>(model: Model<T>, doc: A) => {
    return model.create(doc);
    // Argument of type 'A' is not assignable to parameter of type 'CreateQuery<T>'.
};
genericCreateDoc(userModel, user);
```
I'm not able to figure out why this happens. I believe this is a correct implementation.
Is this a bug?

Thanks for your reply!

**Comment by andreialecu** [comment] 2020-08-04 15:08
The correct signature for your `genericCreateDoc` would be:

```ts
const genericCreateDoc = async <T extends mongoose.Document>(model: mongoose.Model<T>, doc: mongoose.CreateQuery<T>) => {
    return model.create(doc);
};
```

For your second case I'm not sure what's going on without investigating, but why not use `model.findById(inputId)` instead?

**Comment by jakubjirkal** [comment] 2020-08-04 15:34
> The correct signature for your `genericCreateDoc` would be:
> 
> ```ts
> const genericCreateDoc = async <T extends mongoose.Document>(model: mongoose.Model<T>, doc: mongoose.CreateQuery<T>) => {
>     return model.create(doc);
> };
> ```
> 
> For your second case I'm not sure what's going on without investigating, but why not use `model.findById(inputId)` instead?

`genericFindById` was just a simplified example of this scenario:
```ts
interface User {
    name: string;
    password: string;
}
type UserDocument = User & Document;

interface Admin extends User {
    someAdminValue: string
}
type AdminDocument = Admin & UserDocument;
const adminModel: Model<AdminDocument> = model('Admin', adminSchema);

const getUserByName = async <T extends UserDocument>(model: Model<T>, inputName: string) => {
    return model.find({name: inputName});
    // Argument of type '{ name: string; }' is not assignable to parameter of type 'MongooseFilterQuery<Pick<T, Exclude<keyof T, "toString" | ...
    // Type '{ name: string; }' is not assignable to type '{ [P in keyof Pick<T, Exclude<keyof T, "toString" | ...
}
getUserByName(adminModel, 'someName');
```

Shouldn't this be correct?

**Comment by andreialecu** [comment] 2020-08-04 15:41
There seems to be some sort of problem when using generics `extends` with `find`.

```ts
const genericFindById1 = async <T extends mongoose.Document>(model: mongoose.Model<T>, inputId: string) => {
    return model.find({ _id: inputId }); // error
};

const genericFindById2 = async (model: mongoose.Model<mongoose.Document>, inputId: string) => {
    return model.find({ _id: inputId }); // ok
};
```

Caused by `MongooseFilterQuery<T>` somehow. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L168-L177

cc @avaly 

As a workaround you could use `return model.find({ name: inputName } as any)` to get past the error.

**Comment by avaly** [comment] 2020-08-04 16:25
AFAIK `mongoose.Document` has `_id: any`. If you defined your `_id` in your model interface as `ObjectId` or `string`, it should work. :crossed_fingers:

**Comment by andreialecu** [comment] 2020-08-04 18:02
@avaly While troubleshooting it I tried adding the `_id` to the model in various ways but couldn't get past the error. I didn't look to deeply into it, but if you copy the code above to one of the tests you can see it yourself.

**Comment by jakubjirkal** [comment] 2020-08-05 10:14
Thanks for your response. 
@avaly Wouldn't re-defining _id in model interface be unnecessary? It would be very time consuming to do so in large codebase as well.

Will you be looking further into it / fixing it? It would help a lot.

**Comment by andreialecu** [comment] 2020-08-05 11:44
Simpler repro:

```ts
interface User {
    name: string;
    password: string;
}
type UserDocument = User & mongoose.Document;

const getUserByName = async <T extends UserDocument>(model: mongoose.Model<T>, inputName: string) => {
    return model.find({name: "test"});
    // Argument of type '{ name: string; }' is not assignable to parameter of type 'MongooseFilterQuery<Pick<T, Exclude<keyof T, "toString" | ...
    // Type '{ name: string; }' is not assignable to type '{ [P in keyof Pick<T, Exclude<keyof T, "toString" | ...
}
```

**Comment by andreialecu** [comment] 2020-08-05 12:18
I've done some more digging and I believe this is a current TypeScript limitation. 

The following fails to compile and it is similar to the conditional used in `MongooseFilterQuery<T>`:

```ts
export type Conditional<T> = {
    [P in keyof T]?: T[P] extends number 
        ? T[P]
        : T[P]
} 

interface User {
    name: string;
    password: string;
}

const foo = <T extends User>(user: T) {
    let x: Conditional<T> = {} as Conditional<T>;
    x.name = "test";
    // Type '"test"' is not assignable to type '(T["name"] extends number ? T["name"] : T["name"]) | undefined'.(2322)
}
```

See https://github.com/microsoft/TypeScript/issues/39521 for a similar report, apparently a fix is on the way. You may need to resort to a workaround for now.

**Comment by ClementeSerrano** [comment] 2020-11-15 01:32
Hey guys! Any updates on this?

**Comment by orta** [comment] 2021-06-07 13:06
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:06 UTC
