### ISSUE TITLE
Typings for ts 2.1

### ISSUE THREAD

**Issue by mkusher** [DefinitelyTyped/DefinitelyTyped#13154] opened 2016-12-07 17:45 UTC
There should be a way to add typings for specific version of ts(e.g. `2.1`). The tests should run on ts 2.1 and packages should require typescript 2.1 in their package.json. 
So what is the best way to do it?

**Comment by ericanderson** [comment] 2016-12-08 02:28
Does DefinitelyTyped manage the @types space on nom?

**Comment by johnnyreilly** [comment] 2016-12-08 07:27
You should probably direct this question here: 

https://github.com/Microsoft/types-publisher

**Comment by mkusher** [comment] 2016-12-08 10:23
@johnnyreilly yeah, I think the problem also includes improving infrastructure of DT. How can we now specify on which ts version run tests in the package?
For example: I have idea of fixing https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7003 [here](https://github.com/mkusher/DefinitelyTyped/commit/ac03ef21f5f30160dc1889f3edf3b71274427c21), but I need somehow specify ts version for tests.

**Comment by JKillian** [comment] 2016-12-09 03:42
See https://github.com/Microsoft/types-publisher/issues/214 also

**Comment by andy-ms** [comment] 2016-12-15 20:22
Closing as duplicate of Microsoft/types-publisher#214

**Closed by andy-ms** 2016-12-15 20:22 UTC
