### ISSUE TITLE
[@types/snoowrap] TS1062 - Type is referenced directly or indirectly in the fulfillment callback of its own 'then' method.

### ISSUE THREAD

**Issue by Murreey** [DefinitelyTyped/DefinitelyTyped#33139] opened 2019-02-17 18:34 UTC
- [x] I tried using the `@types/snoowrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vitosamson @TheAppleFreak @willwull 

---

I'm seeing the TS1062 error when trying to await the Promise returned by  `VoteableContent.expandReplies()`. 

Code snippet (I've cut a lot out):
```
async replies(content: Submission | Comment): Promise<string[]> {            
    await content.expandReplies()
}
```

Also seeing it with `snoowrap.getSubmission`:

```
const content = await this.snoowrap.getSubmission(comment.link_id)
```

Using TypeScript v3.3.3, snoowrap v1.15.2, @types/snoowrap v1.15.3.

**Comment by willwull** [comment] 2019-02-17 20:25
I'm getting the same error in my own code, but I'm not really sure what's causing it, since I didn't write the majority of the types :( 
Hoping the other authors might have more insight.

As a workaround, it seems to work for me when using `.then()` instead of `await`.

**Comment by vitosamson** [comment] 2019-02-17 21:46
I think the issue is likely because `expandReplies()` is typed as returning `Promise<T>` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/snoowrap/dist/objects/VoteableContent.d.ts#L87) instead of `Promise<this>`, like this rest of the methods of that class.

Can you try making that change locally and see if it resolves the error?

**Comment by Murreey** [comment] 2019-02-17 22:56
No luck with `Promise<this>` unfortunately, still the same error.

**Comment by vitosamson** [comment] 2019-02-19 15:58
This looks like a Typescript issue. The current types work fine under `typescript@~3.0.0`, but break after `typescript@~3.1.0`. 

I don't see anything in the [3.1 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html) that would affect these types. Can you open an issue in the TS repo about it?

**Comment by Murreey** [comment] 2019-02-20 09:59
I'm also seeing it running`typescript@^2.8.3` - specifically it starts happening when I update `@types/snoowrap` from 1.14.3 to 1.15.0.

**Comment by Offlein** [comment] 2019-09-03 02:25
Sorry @vitosamson, to be clear, an issue should be opened on the https://github.com/microsoft/TypeScript repo, yes? Not ts-node?

**Comment by TheAppleFreak** [comment] 2019-09-03 16:49
I think this one might be on me :( I don't recall the specifics of it, but I believe that 1.15 was a relatively small change that I made to let `await` actually work with Snoowrap. Before that, IIRC, it complained any time you would try to do so. 

There's not much on this particular error elsewhere, but searching the term did pull up [an issue on the Ember repository](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23238) where they had the same issue. It appears they fixed it by changing out some Promises in their typings to use a different type of Proxy instead. Not entirely sure how this would work out for this particular issue, but at least we have something to go on.

**Comment by Offlein** [comment] 2019-09-03 18:21
@TheAppleFreak Ah, indeed... Thanks. I'm afraid I know almost nothing about this stuff, but I did read the Ember post earlier, and saw the parallels about proxies. But I was confused because I thought simply using promises in general meant that your code would work with `await` and `async`, and I guess I'm due to read up on ES6 proxies, because I don't fully understand how they're different. I guess a proxy... lets you chain asynchronous methods?

Anyway, if I'd like to help, do you have any advice? As in, should I just learn about ES6 proxies and then read through Snoowrap code? Or learn about Snoowrap's proxy in specific?

**Comment by orta** [comment] 2021-06-07 13:37
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:37 UTC
