### ISSUE TITLE
@types/node-schedule should not depend on @types/node

### ISSUE THREAD

**Issue by whitecolor** [DefinitelyTyped/DefinitelyTyped#13545] opened 2016-12-25 11:10 UTC
I believe `@types/node-schedule` should not depend on `@types/node` (currently it is in `dependencies`), it should be added in `peerDependencies`, because otherwise it may result in conflicts, with other installed version (maybe on the upper level of the project).

I don't get where the `package.json can` be contributed to? I see no `package.json` here:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/node-schedule

cc @cyrilschumacher @flowpl

**Comment by andy-ms** [comment] 2016-12-29 23:09
Duplicate of #13546.

**Closed by andy-ms** 2016-12-29 23:09 UTC
