### ISSUE TITLE
mathjs missing properties

### ISSUE THREAD

**Issue by xenburn** [DefinitelyTyped/DefinitelyTyped#44234] opened 2020-04-25 23:55 UTC
New to Typescript and i'm not positive about adding anything for mathJs without breaking it
using definitions from types/mathjs/index.d.ts

import { create, all} from 'mathjs'
const math = create(all, {
  number: 'BigNumber', // Default type of number:
  precision: 64 // Number of significant digits for BigNumbers
})
// these functions are both on the math object i created and work correctly
math.isFraction
math.isBigNumber
//errors i'm getting are 
Property 'isFraction' does not exist on type 'Partial<MathJsStatic>'
Property 'isBigNum' does not exist on type 'Partial<MathJsStatic>'
 they aren't exported via the main mathjs library either so
I'm choosing to import them directly for now.
import { isFraction, isBigNumber } from 'mathjs/lib/utils/is'

/cc @siavol @andnp @bradbesserman @pawkrol @charlee @mark-wiemer

**Comment by mark-wiemer** [comment] 2020-05-09 14:55
I don't know much about MathJS or TS either, to be honest, but it looks like the issue is in the return type of `create`. Since it returns a `Partial<MathJsStatic>`, TS assumes that all [properties are optional](https://www.typescriptlang.org/docs/handbook/utility-types.html) and is only checking [properties of `MathJsStatic`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mathjs/index.d.ts#L44). I'm not sure if `MathJsStatic` matches the type of the object you're trying to create, as I don't use `create` in my code. Could you explain a little bit more about what you're trying to do and what properties you expect your object to have?

**Comment by orta** [comment] 2021-06-07 13:07
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:07 UTC
