### ISSUE TITLE
Typescript type error for lodash _.forOwn function

### ISSUE THREAD

**Issue by phantomodm** [DefinitelyTyped/DefinitelyTyped#25297] opened 2018-04-25 16:11 UTC
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel , @aj-r 

I'm developing a project using Angular and having a problem with a typescript type error. I want to use _.forOwn(db,(value: string, key: number)=>{ }).  I'm not literally entering the type, I put here for what the definition is suppose to be. 

Typescript throws an error against the **value** reporting that type should be number, instead of string.. The key is of type string, instead of number. 

Using StackBlitz the same code works without issue. Using lodash 4.17.5, @types/lodash4.14 and typescript 2.5.3 . Thanks for help. 

-AJ

`_.forEach(customData,(d)=>{
        _.forEach(d,(f)=>{
            _.forOwn(f,(value,key)=>{
                console.log(value.info);
            })
        })
    })`

**Comment by aj-r** [comment] 2018-04-25 18:05
We'll need a more complete example to reproduce this. What is `db`?

Also formatting tip: use triple-backtick (```) for multiline code.

**Comment by phantomodm** [comment] 2018-04-25 18:54
Hello,
db is the json data in the following format. Thanks for the tip.
```
var db = [{"one":[{"a": "apple","b":"banana"}] },
          {"two":[{"a": "pear","b":"grape"}] },
          {"three":[{"a": "kiwi","b":"mango"}]
         }]
```

**Comment by aj-r** [comment] 2018-04-29 17:13
I can't reproduce any issue. In your code, note that `f` is still an array based on the `db` you gave me, so you probably wanted a third `forEach` loop?

Here is the code I'm using (TS 2.8, `@types/lodash@4.14.108`):

```ts
const db = [
    {
        "one": [
            {"a": "apple","b":"banana"}
        ]
    },
    {
        "two":[
            {"a": "pear","b":"grape"}
        ]
    },
    {
        "three":[
            {"a": "kiwi","b":"mango"}
        ]
    },
];

_.forEach(db, (d) => {
    _.forEach(d, (f) => {
        _.forEach(f, (item) => {
            _.forOwn(item, (value, key) => {
                console.log(typeof value); // string
            });
        });
    });
});
```

**Comment by phantomodm** [comment] 2018-05-24 13:07
thanks.. I'll try this out.

**Comment by IlyaSavich** [comment] 2019-05-11 15:47
Hi, I also got some error with this function
```
interface IA {
    p1: string;
    p2: number;
}

const a: IA[] = [];

_.forOwn(a, ({ p1, p2 }) => {
    console.log(p1, p2);
});

// TS2339: Property 'p1' does not exist on type 'number | IA | (() => string) | (() => string) | (() => IA | undefined) | ((...items: IA[]) => number) | { (...items: ConcatArray<IA>[]): IA[]; (...items: (IA | ConcatArray<IA>)[]): IA[]; } | ((separator?: string | undefined) => string | ... ...
```

**Comment by aj-r** [comment] 2019-05-11 22:44
@IlyaSavich normally you don't use `forOwn` to iterate over an array, you use `forEach` or a `for..of` loop.

The issue is that the TS compiler can't tell the difference between own and inherited properties, so it thinks that properties like `Array.length` and `Array.push` could be enumerated too. There isn't really a good way to fix this.

**Comment by orta** [comment] 2021-06-07 13:39
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:39 UTC
