### ISSUE TITLE
[@types/jquery] Error with union types

### ISSUE THREAD

**Issue by chapterjason** [DefinitelyTyped/DefinitelyTyped#29312] opened 2018-10-01 11:34 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu, @borisyankov, @Steve-Fenton, @Diullei

**Versions:**
`typescript@3.1.1`
`@types/jquery@3.3.10`
`jquery@3.3.1`

**Code:**
```
import * as $ from "jquery";

function test(selector: string | string[]) {
  const selected = $(selector);

  selected.addClass('test');

  return selected;
}

test(".test");
```

**Error:**
Error shown here `$(selector);`
```
Argument of type 'string | string[]' is not assignable to parameter of type 'PlainObject<any>'.
  Type 'string' is not assignable to type 'PlainObject<any>'.
(parameter) selector: string | string[]
```

**Example:** [Stackblitz](https://stackblitz.com/edit/typescript-szbshm)

Also got something weird with `.on` and the `PlainObject`, but can't reproduce.

**Comment by leonard-thieu** [comment] 2018-10-01 12:11
While this does reveal a bug with the declarations, the code as written might not have intended behavior. Calling `$(string[])` results in a jQuery object containing strings and not selected elements. Also, `$(string[])` is undocumented and possibly unsupported by jQuery.

**Comment by leonard-thieu** [comment] 2018-10-02 13:36
Right. I'm looking into it.

**Comment by leonard-thieu** [comment] 2018-10-10 17:05
Will be fixed by #29612. Thanks for reporting this!

**Comment by leonard-thieu** [comment] 2018-10-11 11:42
This will actually need to be delayed until TypeScript 3.1 features become available on DefinitelyTyped. Sorry!

**Comment by leonard-thieu** [comment] 2018-10-11 13:46
@andy-ms can give you a timeline for that.

**Comment by mqudsi** [comment] 2019-03-11 18:13
The decision was made [to reject the fix for this problem](https://github.com/DefinitelyTyped/DefinitelyTyped/29612) as it would bump up the required TypeScript version. Is there a workaround such as extending the `JQueryStatic` interface? 

The thing is that my code compiled against the latest version of the jq definitions when using tsc 3.0.3, but upgrading to 3.3 caused this error to present.

**Comment by adumesny** [comment] 2020-08-09 17:10
I'm getting the error as well using `string | HTMLElement` (which is valid), latest rev "@types/jquery": "^3.5.1" and `typescript@3.4.5`

the link above for the rejection is broken. Too bad there isn't a fix.

**Comment by orta** [comment] 2021-06-07 16:38
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 16:38 UTC
