### ISSUE TITLE
[@types/fs-extra] Errors with @types/node@10

### ISSUE THREAD

**Issue by frangio** [DefinitelyTyped/DefinitelyTyped#44946] opened 2020-05-21 02:05 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz @ffflorian

The types for `fs-extra` reference some members from `@types/node` directly that are only present in Node 12+. This causes compilation to fail when combined with `@types/node@10`, which should work because `fs-extra` supports Node 10. The problem is that since `fs-extra` re-exports members from the native `fs`, those have been copied into `@types/fs-extra`. I believe it would be better to not do that manually and instead if possible re-export `typeof import('fs')` so that it picks up whatever is in the environment. Unfortunately I don't have time to work on this myself.

```
node_modules/@types/fs-extra/index.d.ts:188:87 - error TS2694: Namespace '"fs"' has no exported member 'Dir'.

188 export function opendir(path: string, cb: (err: NodeJS.ErrnoException | null, dir: fs.Dir) => void): void;
                                                                                          ~~~

node_modules/@types/fs-extra/index.d.ts:191:17 - error TS2694: Namespace '"fs"' has no exported member 'OpenDirOptions'.

191     options: fs.OpenDirOptions,
                    ~~~~~~~~~~~~~~

node_modules/@types/fs-extra/index.d.ts:192:53 - error TS2694: Namespace '"fs"' has no exported member 'Dir'.

192     cb: (err: NodeJS.ErrnoException | null, dir: fs.Dir) => void,
                                                        ~~~

node_modules/@types/fs-extra/index.d.ts:194:52 - error TS2694: Namespace '"fs"' has no exported member 'OpenDirOptions'.

194 export function opendir(path: string, options?: fs.OpenDirOptions): Promise<fs.Dir>;
                                                       ~~~~~~~~~~~~~~

node_modules/@types/fs-extra/index.d.ts:194:80 - error TS2694: Namespace '"fs"' has no exported member 'Dir'.

194 export function opendir(path: string, options?: fs.OpenDirOptions): Promise<fs.Dir>;
                                                                                   ~~~

node_modules/@types/fs-extra/index.d.ts:265:52 - error TS2694: Namespace 'NodeJS' has no exported member 'ArrayBufferView'.

265 export function writev(fd: number, buffers: NodeJS.ArrayBufferView[], position: number, cb: (err: NodeJS.ErrnoException | null, bytesWritten: number, buffers: NodeJS.ArrayBufferView[]) => void): void;
                                                       ~~~~~~~~~~~~~~~

node_modules/@types/fs-extra/index.d.ts:265:167 - error TS2694: Namespace 'NodeJS' has no exported member 'ArrayBufferView'.

265 export function writev(fd: number, buffers: NodeJS.ArrayBufferView[], position: number, cb: (err: NodeJS.ErrnoException | null, bytesWritten: number, buffers: NodeJS.ArrayBufferView[]) => void): void;
                                                                                                                                                                          ~~~~~~~~~~~~~~~

node_modules/@types/fs-extra/index.d.ts:266:52 - error TS2694: Namespace 'NodeJS' has no exported member 'ArrayBufferView'.

266 export function writev(fd: number, buffers: NodeJS.ArrayBufferView[], cb: (err: NodeJS.ErrnoException | null, bytesWritten: number, buffers: NodeJS.ArrayBufferView[]) => void): void;
                                                       ~~~~~~~~~~~~~~~

node_modules/@types/fs-extra/index.d.ts:266:149 - error TS2694: Namespace 'NodeJS' has no exported member 'ArrayBufferView'.

266 export function writev(fd: number, buffers: NodeJS.ArrayBufferView[], cb: (err: NodeJS.ErrnoException | null, bytesWritten: number, buffers: NodeJS.ArrayBufferView[]) => void): void;
                                                                                                                                                        ~~~~~~~~~~~~~~~

node_modules/@types/fs-extra/index.d.ts:267:52 - error TS2694: Namespace 'NodeJS' has no exported member 'ArrayBufferView'.

267 export function writev(fd: number, buffers: NodeJS.ArrayBufferView[], position?: number): Promise<WritevResult>;
                                                       ~~~~~~~~~~~~~~~
```

**Comment by ffflorian** [comment] 2020-05-21 06:25
@frangio 
> The types for `fs-extra` reference some members from `@types/node` directly that are only present in Node 12+. 

Which members are that? Can you post an error message or something like that?

**Comment by frangio** [comment] 2020-05-21 22:40
I forgot to specify, I'm sorry. I've edited the original post with the error messages.

**Comment by karfau** [comment] 2020-05-24 11:23
Same issue here.

**Comment by ffflorian** [comment] 2020-05-25 18:44
@peterblazejewicz can you take a look?

**Comment by ffflorian** [comment] 2020-05-27 11:28
@frangio I can reproduce the error. Unfortunately I don't have a solution for that beside upgrading `@types/node` to 14.x or downgrading `@types/fs-extra` to 8.1.0.

We are already exporting `* from 'fs'`, but since fs-extra adds a promisified version of `opendir()` and `writev()`, these need to be reflected in the types. Since there is no conditional types export yet AFAIK, there is not much we can do in my opinion.

**Comment by frangio** [comment] 2020-05-27 14:48
The ["forward declarations"](https://github.com/microsoft/TypeScript/issues/31894) feature in TypeScript's 4.0 roadmap may be of use here. 

Alternatively, I've built a package which is similar to `fs-extra` in that it re-exports promisified Node.js functions and solves the issue using mapped types. The same approach could be used here, but it would increase the complexity of the type definitions.

https://github.com/frangio/promisified/blob/a868d31d801237f61f60aa026bb7303fd8dfa3cb/internal.d.ts#L5-L7

**Comment by peterblazejewicz** [comment] 2020-05-27 14:52
> @peterblazejewicz can you take a look?
Yes, sorry for delay. I can see the problem, not sure myself how to properly manage different iterations of node versions and types

**Comment by clarkgrg** [comment] 2020-11-10 16:29
For some reason if I npm install @types/node the package manager install a v10.10 version of node???  That's odd.  So I forced npm to install the latest version of @types/node@14.14.7 and that seemed to fix it

**Comment by dperez3** [comment] 2020-12-12 02:25
I did some digging in regards to the error for just the `OpenDirOptions` type specifically, and here's what I came up with...

(I presume the same issue is at play for the other types.)

#### May 15, 2020
`@types/fs-extra` merged a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44499/files#diff-cfd53b4251aad7f2ff6407d866c5f581f741a7458cbe9f15c90814642f4a27c4R254) which introduced (first?) usages of new fs type, `fs.OpenDirOptions`.

`fs.OpenDirOptions` is not exposed by `@types/node` at this time.

#### May 20, 2020
This issue is posted. `@types/node` still does not expose `fs.OpenDirOptions`.

#### 🚀 Sep 16, 2020
`@types/node` is [updated with new type](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f621a2d639f01584eb88975c182a61a52d4d7a8b#diff-7f158a554fa347425a7b13a05029bfe72feb14c0c3225d722b4eef1677e0f9e6R2119), `fs.OpenDirOptions`.

At this point, a version of `@types/node` is now available which will properly play nice with `@type/fs-extra`.

#### ✔ Nov 10, 2020
@clarkgrg posts [his comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44946#issuecomment-724815197) with a workaround coinciding with my findings in this comment.

---

### Solution?
I suspect it would be wise to update `@types/fs-extra` with a dependency specification on the version of `@types/node` that supports `fs.OpenDirOptions`. Judging by the presence of `package.json` in some of the other types in the `/types/` folder of this repo, I guess that could also be added here to this repo's `/fs-extra/` folder.

This way, user's don't accidentally pair incompatible packages together.

**Comment by karfau** [comment] 2020-12-17 00:24
> ```json
> "{the earliest version that fixes it}"
> ```

Maybe rather `">={the earliest version that fixes it}"`?

**Comment by surveshoeb** [comment] 2021-02-17 10:11
Any update on this issue?

**Comment by karfau** [comment] 2021-02-17 12:17
@surveshoeb Not really since I didn't have time to tackle it.

@dperez3 I think it's not an option to "enforce" using `@types/node` with xmldom, since the min issue here is that people want to also use it int he browser, where node is not available.

**Comment by surveshoeb** [comment] 2021-02-17 12:24
I have fixed this issue by upgrading **npm** to version 7.5.4 which is latest and downgraded the **fs-extra** to 8.0.1

**npm upgrade**
```
sudo npm install -g npm@7.5.4
```

**fs-extra downgrade**
```
npm i fs-extra@8.0.1
```

**Comment by osalkanovic** [comment] 2021-03-03 21:25
> Strangely I run into this issue after building multiple times without problem. I did not update any packages or install some new ones, the error just appeared. I came here after a google search to see what the reason could be. Currently I am using Node 10 and fs-extra 9.0.1. The only difference is my build complains about 2 missing exported members in 3 places BaseEncodingOptions and BufferEncodingOptions.

I have the same issue :/ did you found a solution?

**Comment by osalkanovic** [comment] 2021-03-03 21:32
> Strangely I run into this issue after building multiple times without problem. I did not update any packages or install some new ones, the error just appeared. I came here after a google search to see what the reason could be. Currently I am using Node 10 and fs-extra 9.0.1. The only difference is my build complains about 2 missing exported members in 3 places BaseEncodingOptions and BufferEncodingOptions.

try yarn add @types/node

**Comment by ncoonrod** [comment] 2021-03-09 05:02
What worked for me was upgrading @types/node to 14.14.32.

**Comment by swtrse** [comment] 2021-03-09 10:14
> 
> 
> > Strangely I run into this issue after building multiple times without problem. I did not update any packages or install some new ones, the error just appeared. I came here after a google search to see what the reason could be. Currently I am using Node 10 and fs-extra 9.0.1. The only difference is my build complains about 2 missing exported members in 3 places BaseEncodingOptions and BufferEncodingOptions.
> 
> I have the same issue :/ did you found a solution?

Yes I did. The project I am working on is a dependency hell, I never experienced anything like this with .net, however I am not sure I can blame this on the development environment, I am more convinced that the devs are at fault.
Well however my solution was to downgrade @types/fs-extra to 8.x. Somehow in the build process fs-extra must have been updated because BaseEncodingOption and BufferEncoding Options are in fact not defined in @types/node v10. Since I am unable to upgrade @types/node without breaking many other dependencies I got that route. I also stuck with node v10 which I am not happy about.
The only thing I can blame on fs-extra is maybe that it does not check and at least warn about an incompatible @types/node version in use.
However like @ncoonrod mentions once you figured it out it is easy just update @types/node to a version that does define this properties or downgrade fs-extra to a version that do not require the properties.

**Comment by rrthomas** [comment] 2021-04-15 19:17
> For some reason if I npm install @types/node the package manager install a v10.10 version of node???

I had this exact problem, and in my case the reason was a `devDependencies` entry automatically added by `npx oclif single`. Removing it fixed the problem: `npm install @types/node` then installed v14 (I am using node v14).

**Comment by pitops** [comment] 2021-09-20 18:01
Oclif installed `@types/node: ^10` - Had to update to latest @types/node for this issue to go away

**Comment by appy-one** [comment] 2022-05-13 11:06
> The ["forward declarations"](https://github.com/microsoft/TypeScript/issues/31894) feature in TypeScript's 4.0 roadmap may be of use here.

Thanks @frangio, adding placeholder type definitions in my project worked to fix the compile errors.

*placeholders.d.ts*:
```typescript
/**
 * When using @types/node@10.17.60 to check for backward compatibility with Node.js 10,
 * tsc will throw errors on @types/fs-extra that references types `fs.Dir`, 
 * `fs.OpenDirOptions` and `fs.RmDirOptions`, which are not declared.
 * @see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44946
 */
declare module 'fs' {
    interface Dir {}
    interface OpenDirOptions {}
    interface RmDirOptions {}
}
```

There's no need to reference this file anywhere, tsc will pick it up automatically if it's in your input folder

**Comment by jakebailey** [comment] 2024-02-09 12:45
From what I can tell, this is all fixed.

**Closed by jakebailey** 2024-02-09 12:45 UTC
