### ISSUE TITLE
[@types/prop-types] PropTypes.shape throws errors when using optionals in TypeScript 3.9.2+

### ISSUE THREAD

**Issue by nweber-gh** [DefinitelyTyped/DefinitelyTyped#45094] opened 2020-05-27 13:56 UTC
- [x] I tried using the `@types/prop-types` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DovydasNavickas @ferdaber @eps1lon

When using optionals inside of `PropTypes.shape` with TypeScript version 3.9.2+ the value is interpreted as `<type> | undefined | null` which causes an error with prop-types which is expecting `<type> | undefined`.

This works as expected with TypeScript 3.8.3.

**Error**

>Type 'Validator<InferProps<{ value: Requireable<string>; }>>' is not assignable to type 'Validator<{ value?: string | undefined; }>'. Type 'InferProps<{ value: Requireable<string>; }>' is not assignable to type '{ value?: string | undefined; }'. Types of property 'value' are incompatible. Type 'string | null | undefined' is not assignable to type 'string | undefined'. Type 'null' is not assignable to type 'string | undefined'.

**Code**
```ts
import PropTypes from 'prop-types';
import React from 'react';

type FooProps = {
  icon: {
    value?: string;
  };
};

export const FooComponent: React.FC<FooProps> = () => null;

FooComponent.propTypes = {
  icon: PropTypes.shape({
    value: PropTypes.string
  }).isRequired
};
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.9.2#code/JYWwDg9gTgLgBABShMAVAnmApgZzgM2RDgHIxkwBaGTXEgbgChRJY4AlLAQwGN5CIxElG58GjRjWxwAYhAhIUeALxwA3ozhxgPCADsAXOs1a4ANy4AbAK5YA-EZwwowPQHMmWgL5MfErAAerPC6ek6y8gDCgpB6WHowRpy8MAB0MpEAPHIKFDgAfHCqABQAlEWFetaWlkyMOdHg+vFp5CgY2CrGWjr6RopotDipOAAWXNjFGqbmVrb9FB24I86ubiZepanAOJwAjtbAIgAmjH5AA)

**Comment by ferdaber** [comment] 2020-05-27 13:58
This is intended. The prop-types package does not differentiate between `null` or `undefined` for non-required props, so your own TypeScript-derived types for your props has to match the runtime behavior.

**Comment by nweber-gh** [comment] 2020-05-27 14:01
Could you elaborate? I assume that there was an underlying change to TypeScript to cause this, but I'm afraid I'm not seeing what happened.

This code does compile on 3.9.2:
```
import PropTypes from 'prop-types';
import React from 'react';

type FooProps = {
  icon: {
    value?: string | null;
  };
};

export const FooComponent: React.FC<FooProps> = () => null;

FooComponent.propTypes = {
  icon: PropTypes.shape({
    value: PropTypes.string
  }).isRequired
};
```

I added a `| null` to the optional in the `type` definition. But I'm still not understanding why that is required.

**Comment by ferdaber** [comment] 2020-05-27 14:05
If, say, you don't have TypeScript at all and you just have prop-types, if you create a component `FooComponent` whose `.propTypes` is this:
```js
FooComponent.propTypes = {
  someValue: PropTypes.string
}
```

prop-types will validate that `someValue` is either a string, or nullish (aka `null` or `undefined`), it does not differentiate between the two.

When you add in your TypeScript types, you have to allow `null` on top of just `string | undefined` (which is what `{ someValue?: string }` represents), to match what prop-types expects.

**Comment by nweber-gh** [comment] 2020-05-27 14:06
That makes sense. But why is the explicit `null` not required in TypeScript 3.8.3 or earlier?

**Comment by nweber-gh** [comment] 2020-05-27 14:08
And why does this only impact `PropTypes.shape`? If this is the case, I would expect this code to error as well:

```
import PropTypes from 'prop-types';
import React from 'react';

type FooProps = {
  name?: string;
};

export const FooComponent: React.FC<FooProps> = () => null;

FooComponent.propTypes = {
  name: PropTypes.string
};
```

**Comment by ferdaber** [comment] 2020-05-27 14:11
That might've been a regression introduced in an earlier TS version that got corrected in the latest version 🤔

**Comment by jknight12882** [comment] 2020-07-25 17:23
Any update in this? I’m running into this same issue using `PropTypes.shape()` using TS@3.9.7

**Comment by nweber-gh** [comment] 2020-07-27 14:15
I haven't seen any movement, so we've just been dealing with it and using `| null` for optionals.

**Comment by ferdaber** [comment] 2020-07-27 14:23
Sorry, to clarify: the error that TypeScript presents is the intended behavior for this library's types. If you use prop-types, you *must* include both `undefined | null` in your props' type definitions to accommodate for how the prop-types runtime checks props.

**Comment by nweber-gh** [comment] 2020-07-27 14:34
I don't think that this tracks with how `defaultProps` works though.

e.g.,
```
class FooComponent extends React.Component {
  static defaultProps = {
    bar: "default value"
  };

  render() {
    const { bar } = this.props;
    return <div>{bar}</div>;
  }
}
```

This component will render...

- `<FooComponent bar="hello" />` The content "hello".
- `<FooComponent />`The content "default value".
- `<FooComponent bar={null} />`Nothing, as the value is explicitely `null`.

To me, this indicates that React clearly interprets `null` and `undefined` as different types of values, just as TypeScript considers them to be different.

When I'm defining props, if I mark a prop as optional I consider that to mean that it's potentially `undefined` (and likewise that the `defaultProps` would apply to it). Marking a prop as potentially `null` means that it can explicitely have a value of `null` - not just that the prop may not be provided.

If this is working as intended, it feels like it's incorrectly implemented to me.

**Comment by ferdaber** [comment] 2020-07-27 14:56
The package "react" interprets `null` and `undefined` differently, like your above example. The package "prop-types", however, does not. If you set your prop `bar` to be `PropTypes.string`, it will happily accept either `null` or `undefined` without logging a prop type error. In this respect TypeScript is more powerful than prop-types in that it can differentiate between the two.

**Comment by jknight12882** [comment] 2020-07-27 15:22
I think the issue is that there is conflicting behavior with how `prop-types` works when used in `PropTypes.shapes()`. Consider the following example: 
```
type FakeType = {
  anotherOptionalString?: string,
};

const FakeComponent: FunctionComponent<{ optionalString?: string, fakeType?: FakeType }> = (props) => (
  <>
    <p>{props.optionalString}</p>
    <p>{props?.fakeType?.anotherOptionalString}</p>
  </>
);

const FakeTypeProps: Requireable<FakeType> = PropTypes.shape({
  anotherOptionalString: PropTypes.string, // <-- this causes a compiler error for assignment to null
});

FakeComponent.propTypes = {
  optionalString: PropTypes.string, // <-- this does NOT cause a compiler error for assignment to null
  fakeType: FakeTypeProps,
};
```

In one instance, optional prop types do not require explicit `null`, and in another, they do

**Comment by salemhilal** [comment] 2020-10-23 16:57
I have similar problems, but with built-in components. For example, the anchor tag's types are all similarly optionally undefined:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e47aff8a3a1331d0c540550db79dd5065ab735e5/types/react/index.d.ts#L1935-L1945

At the same time, the inferred type of `PropTypes.string` is `string | null | undefined`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e47aff8a3a1331d0c540550db79dd5065ab735e5/types/prop-types/index.d.ts#L64

I want to keep both propTypes and TypeScript types because the component I'm working on could be used in either context. It seems as though the type mismatch makes something that should be straightforward (accepting an optional string and passing it to a child) pretty tricky.

For example, this JSX block
```jsx
<a href="https://example.com/#" type={null}>link with null</a>
<a href="https://example.com/#" type={undefined}>link with undefined</a>
<a href="https://example.com/#" type={"type"}>link with string</a>
```

renders without problem into this HTML in React 17.
```
<a href="https://example.com/#">link with null</a>
<a href="https://example.com/#">link with undefined</a>
<a href="https://example.com/#" type="type">link with string</a>
```

However, if I add a string as a prop, I can't assign that prop directly to `type`, since the string could be null.

I put together a Codesandbox example to demonstrate this a bit further:
https://codesandbox.io/s/react-typescript-playground-forked-5wp7y?file=/src/index.tsx

I'm having a hard time finding how to run a the TypeScript checker on an example like above in a way that's easily sharable, but locally I end up with `Type 'string | null | undefined' is not assignable to type 'string | undefined'.

**Comment by salemhilal** [comment] 2020-10-27 20:21
Ok, I figured it out. This CodeSandbox reproduces the type mismatch: 
https://codesandbox.io/s/infer-prop-types-mismatch-8ybqj?file=/src/App.tsx

**Comment by orta** [comment] 2021-06-07 13:06
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:06 UTC

**Comment by dmaier-indeed** [comment] 2021-10-07 18:04
Is there any follow-up on this?

**Comment by dPowNextdoor** [comment] 2021-11-04 18:11
> Is there any follow-up on this?

Bump! Yes please fix this, it makes JS/TS interoperability impossible.

**Comment by D-Pow** [comment] 2021-11-05 18:15
While not perfect, this workaround works for me:

```typescript
import type { InferProps as PropTypesInferProps } from 'prop-types';


/**
 * Companion to built-in `keyof` except for getting all value types of an Object
 * instead of keys.
 */
export type ValueOf<O, K extends keyof O> = O[K];

/**
 * Companion to built-in `Omit` except for omitting all value types of an Object
 * instead of keys.
 */
export type OmitValues<O, V> = {
    [ K in keyof O ]: Exclude<ValueOf<O, K>, V>;
};

/**
 * Extracts types of JSX component props defined using PropTypes.
 *
 * `PropTypes.InferProps` has a bug where they inject `null` as a possible type for
 * JSX `propTypes` (e.g. `type | null | undefined`) but non-required types can only
 * be `type | undefined`.
 *
 * This fixes the bug by stripping out the `null` values from the resulting
 * `PropTypes.InferProps` call.
 *
 * @see [PropTypes.InferProps bug]{@link https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45094}
 */
export type InferProps<O> = OmitValues<PropTypesInferProps<O>, null>;
```

It works for nested object props as well. However, it only enforces `.isRequired` if it's in said nested object, i.e.

```javascript
MyComponent.propTypes = {
    className: PropTypes.string,
    // Not enforced, but still shows errors in the console
    someFunc: PropTypes.func.isRequired,
    nestedObj: PropTypes.shape({
        // Enforced if `nestedObj` is specified since `nestedObj` isn't marked with `.isRequired`
        obj: PropTypes.shape({
            // Enforced if `obj` is specified (which it has to be if `nestedObj` is)
            func: PropTypes.func.isRequired,
            obj: PropTypes.object,
            arr: PropTypes.arrayOf(PropTypes.oneOfType([ PropTypes.string, PropTypes.number ])),
        }).isRequired,
    }),
};
```
