### ISSUE TITLE
@types/node Interface 'NodeModule' incorrectly extends interface 'Module'.

### ISSUE THREAD

**Issue by KimWooHyun** [DefinitelyTyped/DefinitelyTyped#25908] opened 2018-05-21 07:20 UTC
- [x] I tried using the @types/node package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Mention the authors (see Definitions by: in index.d.ts) so they can respond.
  - Authors: @Flarna, @islishude

Compilation cannot succeed with the version 10.1.2 installed. The error is
```
node_modules/@types/node/index.d.ts(234,11): error TS2430: Interface 'NodeModule' incorrectly extends interface 'Module'.
  Types of property 'hot' are incompatible.
    Type '{ accept: Function; }' is not assignable to type 'Hot | undefined'.
      Type '{ accept: Function; }' is not assignable to type 'Hot'.
        Property 'decline' is missing in type '{ accept: Function; }'.
```
I saw [#19601](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19601) and tried to solve the problem.
but can't solved it.

**Comment by Flarna** [comment] 2018-05-21 19:19
Could you please provide which other type definitions (incl. version) you use in your setup?

**Comment by KimWooHyun** [comment] 2018-05-23 01:42
@Flarna 

I setup to this and an error occurred.
`@types/storybook__react (v 3.0.7)`

And I setup to
```
@types/storybook__addon-backgrounds (v 3.2.0)
@types/storybook__addon-knobs (v 3.3.1)
@types/webpack-env (v 1.13.6)
```

**Comment by Flarna** [comment] 2018-05-23 06:30
Hmm, can't reproduce this by only using above modules. Are there no other modules or leftovers?

**Comment by KimWooHyun** [comment] 2018-06-20 04:52
@Flarna 
Oh, I'm sorry to late.
As a result of checking, there was a conflict with the [library](https://github.com/spoqa/aeiou) used internally.
It is now solved.

**Comment by Flarna** [comment] 2018-06-20 05:54
@KimWooHyun Good to here. Please close the issue.

**Closed** 2018-06-20 05:58 UTC
