### ISSUE TITLE
styled-components Babel macro with TypeScript and Create React App

### ISSUE THREAD

**Issue by soavie** [DefinitelyTyped/DefinitelyTyped#30915] opened 2018-11-29 10:47 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Kovensky 

I opened styled-components/styled-components#2253 yesterday, but was referred over here because they don't maintain the types there since v4. I hope I've come to the right place.

Full environment/reproduction details are included in that ticket, so I'll include a more succinct summary here:

When I follow the [styled-components TypeScript docs](https://www.styled-components.com/docs/api#typescript), but instead try to import from the babel macro submodule (i.e. `styled-components/macro` instead of `styled-components`), I get the following error:

```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'name' of undefined
    at :3000/Users/ginosoave/work/playground/sc-macro/node_modules/babel-plugin-macros/dist/index.js:89
```

I'm kind of new to both TypeScript and babel-plugin-macros. Please can anyone either help me resolve this issue or point me in the right direction?

**Comment by DevanB** [comment] 2018-11-29 21:38
I, too, am having this issue, and haven't figured out the cause or solution.

**Comment by Funkyskank** [comment] 2019-01-05 17:51
Have same error, any suggestions to fix it?

**Comment by mshroomhead** [comment] 2019-01-16 13:42
Did anyone figured out a solution?

**Comment by sandiiarov** [comment] 2019-02-20 01:21
It is working for me.
```js
import * as styledComponents from 'styled-components';
import styled from 'styled-components/macro';

interface ThemeInterface {
  primaryColor: string;
  primaryColorInverted: string;
}

const {
  css,
  createGlobalStyle,
  keyframes,
  ThemeProvider,
} = styledComponents as styledComponents.ThemedStyledComponentsModule<
  ThemeInterface
>;

export { css, createGlobalStyle, keyframes, ThemeProvider };
export default styled as styledComponents.ThemedStyledInterface<ThemeInterface>;
```

**Comment by sebastien-p** [comment] 2019-02-27 15:57
https://github.com/styled-components/styled-components/issues/2253#issuecomment-467918257

**Comment by sandiiarov** [comment] 2019-02-27 16:37
https://github.com/styled-components/styled-components-website/issues/392#issuecomment-447067722

**Comment by chriserickson** [comment] 2019-03-12 17:49
Have you tried submitting this against babel-plugin-macros?

Looking at the stack you reported, it seems like an issue in there. (I'm also seeing it)

**Comment by chriserickson** [comment] 2019-03-12 18:26
https://github.com/styled-components/styled-components/issues/2423

**Comment by chriserickson** [comment] 2019-03-12 18:44
I was able to work around the issue using what is shown here:
https://github.com/styled-components/styled-components/issues/2368#issuecomment-462507866

**Comment by orta** [comment] 2021-06-07 13:14
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:14 UTC
