### ISSUE TITLE
[@types/react-router-dom]: withRouter HoC produces compile error: "Property 'match' is missing in type '{}'."

### ISSUE THREAD

**Issue by simonvizzini** [DefinitelyTyped/DefinitelyTyped#17181] opened 2017-06-14 13:37 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin, @mrk21, @vasek17 and many more, should I really mention them all?

I did a Google search and found two other people with the same problem, but no solution so far:
https://stackoverflow.com/questions/44118060/react-router-dom-with-typescript
https://github.com/Microsoft/vscode/issues/27235

Minimal code example:

````javascript
const MyRouterComponent = withRouter(
  class MyComponent extends React.Component<RouteComponentProps<any>, any> {
    render() {
      return <div />;
    }
  }
)

class MainComponent extends React.Component<any, any> {
  render() {
    /* This line produces following compile error:
       error TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RouteComponentProps<any>, ComponentState...'.
          Type '{}' is not assignable to type 'Readonly<RouteComponentProps<any>>'.
            Property 'match' is missing in type '{}'.
    */
    return <MyRouterComponent />
  }
}
````

I understand what the problem is: ``MyRouterComponent`` expects props which I didn't explicitly pass, because ``withRouter`` will take care of that. So how does one use ``withRouter`` with TS correctly?

**Comment by hafuta** [comment] 2017-06-15 14:40
I'm having the same issue, following

**Comment by simonvizzini** [comment] 2017-06-15 15:32
@hafuta, are you suggesting that this has worked in previous versions? I'm trying to use ``withRouter`` for the first time, so I don't know. I'm using the latest versions of everything.

As a temporary workaround I figured out this:

````javascript
return <MyRouterComponent { ...({} as RouteComponentProps<any>) } />
````

TS compiler is happy and ``withRouter`` injects the correct router props afterwards.

**Comment by hafuta** [comment] 2017-06-15 16:20
@simonvizzini, yes, it worked for me before upgrading some packages. I'm using more or less the same workaround, I'm just passing nulls, the `withRouter` function does inject the right values.

`<DashboardMenu match={null} location={null} history={null} />`

**Comment by AlgusDark** [comment] 2017-07-07 06:18
@simonvizzini You need to do something like:
```
const MyRouterComponent = withRouter<{}>(
  class MyComponent extends React.Component<RouteComponentProps<{}>, any> {
    render() {
      return <div />;
    }
  }
)

class MainComponent extends React.Component<any, any> {
  render() {
    return <MyRouterComponent />
  }
}
```

Since before, withRouter typing was:
`export function withRouter(component: React.SFC<RouteComponentProps<any>> | React.ComponentClass<RouteComponentProps<any>>): React.ComponentClass<any>;`

and now is:
`export function withRouter<P>(component: React.SFC<RouteComponentProps<any> & P> | React.ComponentClass<RouteComponentProps<any> & P>): React.ComponentClass<P>;`

**Comment by simonvizzini** [comment] 2017-07-07 11:42
@AlgusDark thank you very much! This indeed works. I'm now having a different problem, but I think I'm just doing it wrong. For example, this produces a compiler error:

````js
interface Props {
  propA: string;
  propB: number;
}

const MyRouterComponent = withRouter<Props>(
  class MyComponent extends React.Component<RouteComponentProps<Props>, any> {
    render() {
      return <div />;
    }
  }
)

class MainComponent extends React.Component<any, any> {
  render() {
    return <MyRouterComponent />
  }
}
````

Instead I have to do something like this:

````js
class MyComponent extends React.Component<RouteComponentProps<{}> & Props, any> {
````

Looking at the type definition, it seems obvious why the first approach doesn't work, but is the second approach really the correct way? It doesn't seem to be very intuitive to me, but then again, I'm still learning TypeScripts type system so I'm probably just missing something.

**Comment by AlgusDark** [comment] 2017-07-07 15:55
Maybe @mhegazy can help us with this, he did the changes at [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/fe1b612ef0d9ffd45114431adac61b5e6ee1173f).

**Comment by guilhermehubner** [comment] 2017-07-20 17:29
I've found a way to solve this problem as you can see below:

```ts
type OwnProps = RouteComponentProps<{id: number}>;

const mapStateToProps = (state: GlobalStateType, ownProps: OwnProps): StateToPropsType => ({
        id: ownProps.match.params.id
});

type PropsType = StateToPropsType & DispathToPropsType & OwnProps;

class MyPage extends React.Component<PropsType, StateType> {
   ...
}

const mapDispatchToProps = (dispatch: DispatchType): DispathToPropsType => ({
    ...
});

export default withRouter(connect<StateToPropsType, DispathToPropsType, OwnProps> (
    mapStateToProps,
    mapDispatchToProps
)(MyPage));
```

In router: 
```ts
<Provider store={store}>
   <BrowserRouter>
      <Switch>
         <Route path="/:id(\d+)" component={MyPage} />
      <Switch>
  <BrowserRouter>
</Provider>
```

**Comment by ligaz** [comment] 2017-09-28 12:12
React Redux typings use a neat trick with [`Omit` mapped type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts#L23-L41). Maybe this pattern can be used here as well?

**Comment by chrispaynter** [comment] 2017-10-16 23:37
For people like me who were struggling with the same original problem as this thread started on, the answer on [this thread](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17355#issuecomment-336022780) solved my typescript compilation issues when using withRouter.

**Comment by Grmiade** [comment] 2017-10-25 17:09
I write this module augmentation:

react-router-dom.d.ts
```typescript
import { RouteComponentProps, withRouter } from 'react-router-dom'

declare module 'react-router-dom' {
  // Diff / Omit taken from https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-311923766
  type Diff<T extends string, U extends string> = ({[P in T]: P } & {[P in U]: never } & { [x: string]: never })[T]
  type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>

  export function withRouter<P extends RouteComponentProps<any>>(
    component: React.ComponentType<P>
  ): React.ComponentClass<Omit<P, keyof RouteComponentProps<any>>>
}
```

It works for me. What do you think?

**Comment by antonmedv** [comment] 2017-10-29 07:59
Same issue here:
```js
import React from 'react'
import { NavLink } from 'react-router-dom'
import { withRouter, RouteComponentProps } from 'react-router'
import { Project } from 'state'

interface Props {
  className: string
}

class SideBar extends React.Component<Props & RouteComponentProps<any>> {
  render() {
    const { className, match: { params: { project } } } = this.props
    return (
       <h1>{project}</h1>
    )
  }
}

export default withRouter(SideBar)
```

```js
class Project extends React.Component<{}> {
  render() {
    return (
        <SideBar className="project__sidebar"/>
    )
  }
}
```

Got:

```
./src/components/Project.tsx
(14,18): error TS2322: Type '{ className: "project__sidebar"; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<SideBar> & Readonly<{ children?: ReactNode; }> & R...'.
  Type '{ className: "project__sidebar"; }' is not assignable to type 'Readonly<Props & RouteComponentProps<any>>'.
    Property 'match' is missing in type '{ className: "project__sidebar"; }'.
```

**Comment by Grmiade** [comment] 2017-10-29 09:33
Use my module augmentation to extract props correctly. 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17181#issuecomment-339401310
We should do a PR with these modifications.

**Comment by Grmiade** [comment] 2017-10-29 09:34
I will try to propose a PR today.

**Comment by mekwall** [comment] 2017-11-06 14:20
@Grmiade Any progress on this?

**Comment by Grmiade** [comment] 2017-11-06 19:49
Sorry, I was overwhelmed these days, I will try this week

**Comment by jbmilgrom** [comment] 2017-12-15 20:48
This PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21329, in particular [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21329/files#diff-bc5f906a3af0cde1a95a8a23cb993e96R107) looks to have changed the meaning of the generic `P` in `withRouter<P>`. Previously, it meant the "own" properties expected by the Component returned by `withRouter`; now, it means to also include the properties injected by `withRouter` e.g. `match`. Is my understanding of this change correct? Is this the intended behavior?

This change broke a large swath of our application as we were depending on it meaning the "own" properties. I'm trying to figure out if I should update the application to reflect this new meaning or make a new issue.

Thanks!

**Comment by Grmiade** [comment] 2017-12-15 22:05
@jbmilgrom Your understanding is correct 👍 
With this changes, it's not longer required to specify your "own" properties. It's inferred 🎉 
I think you should update your application by removing your useless return type. You can found an example [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/test/WithRouter.tsx).

**Comment by Grmiade** [comment] 2017-12-15 22:16
According to me, specify his "own" properties expected by the component returned is a bad idea. It's too permissive and authorize the cheat :/ `withRouter`'s definition is the only one able to define the real return type. If you see what I mean ;) Thereby your typing becomes safe 💪

**Comment by jbmilgrom** [comment] 2017-12-15 23:33
I think you're right, thanks for the quick response!

In our use cases, the consumers of the component returned by `withRouter` care only about "own" props when trying to guarantee its correct use, which is accomplished both with and without this change, but I'm glad the new type now more accurately reflects whats going on.

**Comment by crucialfelix** [comment] 2017-12-18 14:03
This example: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/test/WithRouter.tsx 

is not working for me. The parent component that is trying to use this withRoutered component is being scolded that it hasn't supplied `match` which is of course an internal prop.

**Comment by Grmiade** [comment] 2017-12-18 18:38
@crucialfelix Look this PR :)
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21799

**Comment by QuantumInformation** [comment] 2017-12-21 11:08
I get this error on windows only.

**Comment by joeaguy** [comment] 2018-02-01 19:40
Something this simple worked for me:

```typescript
class BranchesList extends React.Component<
  { branches: BranchesModelType } & RouteComponentProps<{ page: number }>,
  {}
> {
  public render() {
 // render something here
    );
  }
}

export default withRouter(BranchesList) as typeof BranchesList;
```

typeof is always such a life saver.

**Comment by Grmiade** [comment] 2018-02-01 20:31
This issue is fixed I think. With https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21799 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21329. Can someone close it?

**Closed** 2018-02-02 09:04 UTC

**Comment by nujey** [comment] 2018-12-14 03:54
I have the same problem. but I took another method.
create new file in  src/history.js
`import createHistory from 'history/createBrowserHistory'

export default createHistory()`
and change the index.tsx
`import { Router } from 'react-router-dom';

ReactDOM.render(
  <BrowserRouter history={history}>
    <App />
  </BrowserRouter>
  , document.getElementById('root') as HTMLElement
);`
and In the component, I can use the history.push("/path")
`import history from '../../untils/history'
  class ReviseCenter extends React.Component{
     handleHistory () {
        history.push('/home')
     }
   }`
if I use **`withRouter`** it's wrong
