### ISSUE TITLE
@types/react-redux: @connect class decorator is broken

### ISSUE THREAD

**Issue by haizz** [DefinitelyTyped/DefinitelyTyped#19020] opened 2017-08-16 10:35 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @seansfkelley @thasner @kenzierocks @clayne11 @tansongyang 

```
  "devDependencies": {
    "typescript": "^2.4.2"
  },
  "dependencies": {
    "@types/react-redux": "5.0.3",
    "react": "^15.6.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2"
  }
```

```typescript
import * as React from 'react';
import { connect } from 'react-redux';

@connect()
class MyComponent extends React.Component<any, any> {
    get property(): string { return "value" }
}
```

Error on `@connect` line:
```
Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<Pick<any, any>>' is not assignable to type 'typeof MyComponent'.
    Type 'Component<Pick<any, any>, ComponentState>' is not assignable to type 'MyComponent'.
      Property 'property' is missing in type 'Component<Pick<any, any>, ComponentState>'.
```

It does not even work with just simple `render()` either:

```typescript
@connect()
class MyComponent extends React.Component<any, any> {
    render() {
        return (<div></div>);
    }
}
```

```
Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<Pick<any, any>>' is not assignable to type 'typeof MyComponent'.
    Type 'Component<Pick<any, any>, ComponentState>' is not assignable to type 'MyComponent'.
      Types of property 'render' are incompatible.
        Type '() => false | Element' is not assignable to type '() => Element'.
          Type 'false | Element' is not assignable to type 'Element'.
            Type 'false' is not assignable to type 'Element'.
```

It works with an empty Component class (which is covered by a test case) but it's just an useless trivial situation.

**Comment by thasner** [comment] 2017-08-16 13:42
this is a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9951

decorator usage is not supported

**Comment by zheeeng** [comment] 2017-08-22 07:53
+1

**Comment by Lazarencjusz** [comment] 2018-06-20 06:31
It is duplicated but I can't see it is fixed...

**Comment by GaryGolf** [comment] 2019-03-27 09:10
try
const { connect } = require('react-redux');

**Comment by bdteo** [comment] 2019-04-15 01:29
Any updates on this?

**Comment by xahon** [comment] 2019-05-26 04:29
The thing that makes us to define props interfaces before class and define export below the class. So if you want to add another thing in your connect you must jump around file instead of making it in one place

**Comment by orta** [comment] 2021-06-07 13:23
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:23 UTC
