### ISSUE TITLE
[@types/nightmare] Compile error when passing a callback with arguments to .evaluate()

### ISSUE THREAD

**Issue by piousdeer** [DefinitelyTyped/DefinitelyTyped#28178] opened 2018-08-16 16:49 UTC
- [x] I tried using the `@types/nightmare` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @samyang-au @Bleser92 

### Package versions
- `typescript@3.0.1`
- `nightmare@3.0.1`
- `@types/nightmare@2.10.4`

### Code
Taken straight from Nightmare's [.evalute() example usage](https://github.com/segmentio/nightmare#evaluatefn-arg1-arg2):
```js
const selector = 'h1'
nightmare
  .evaluate((selector: string) => {
    // now we're executing inside the browser scope.
    return (document.querySelector(selector) as HTMLHeadingElement).innerText
  }, selector) // <-- that's how you pass parameters from Node scope to browser scope
  .then(text => {
    // ...
  })
```

### Issue
I am getting this compile error.
```
error TS2345: Argument of type '(selector: string) => string' is not assignable to parameter of type '() => string'.
```

**Comment by boqusi** [comment] 2018-08-19 10:36
@horiuchi, @samyang-au, @Bleser92, any updates on the issue?

**Comment by JamesRArroyo** [comment] 2018-12-18 16:47
@piousdeer I am also running into the same problem. Did you ever find a solution to this?

**Comment by piousdeer** [comment] 2018-12-22 10:52
@JamesRArroyo unfortunately not. I had to uninstall @types/nightmare completely.

**Comment by mingos777** [comment] 2019-02-18 15:01
I've hit the same issue. The problem is that the type definitions are for Nightmare v2, while the current version is v3. The `evaluate` signature has changed since v2 - a mandatory callback argument has been removed. This is why TypeScript will not be able to work with this package until it it properly rewritten for v3.

As a temporary measure, I modified the typings, index.d.ts, lines 38-43:

```
evaluate<T1, T2, T3, R>(fn: (arg1: T1, arg2: T2, arg3: T3) => R, arg1: T1, arg2: T2, arg3: T3): Nightmare;
evaluate<T1, T2, R>(fn: (arg1: T1, arg2: T2) => R, arg1: T1, arg2: T2): Nightmare;
evaluate<T, R>(fn: (arg: T) => R, arg: T): Nightmare;
evaluate<T>(fn: (arg: T) => void, arg: T): Nightmare;
evaluate<R>(fn: () => R): Nightmare;
evaluate(fn: () => void): Nightmare;
```

So now I can write something like this:

```
import * as Nightmare from "Nightmare";

const nightmare = new Nightmare({
	show: true
});

const input: number = 0;

(async () => {
  await nightmare.goto("https://github.com/")
    .wait("h1")
    .evaluate<number, string>( // number = argument type, string = output type
      (_input: number) => {
        const title: any = document.querySelectorAll("h1");
        return title[_input].textContent as string;
      },
      input
    )
    .end()
    .then((result: string) => {
      console.log(result);
    });
})();
```

@horiuchi @samyang-au @Bleser92  Can we expect typings for Nightmare v3 anytime soon?

**Comment by EmmaGoodliffe** [comment] 2020-03-24 19:12
@mingos777 - so helpful! Thank you!

If you don't want to run `.end()` before getting the results from the `.evaluate()`, you can altar those lines (38-43) in `node_modules/@types/nightmare/index.d.ts` to:

```typescript
evaluate<T1, T2, T3, R>(fn: (arg1: T1, arg2: T2, arg3: T3) => R, arg1: T1, arg2: T2, arg3: T3): Nightmare | Promise<R>;
evaluate<T1, T2, R>(fn: (arg1: T1, arg2: T2) => R, arg1: T1, arg2: T2): Nightmare | Promise<R>;
evaluate<T, R>(fn: (arg: T) => R, arg: T): Nightmare | Promise<R>;
evaluate<T>(fn: (arg: T) => void, arg: T): Nightmare;
evaluate<R>(fn: () => R): Nightmare | Promise<R>;
evaluate(fn: () => void): Nightmare;
```

So that you can run code like this:

```typescript
(async () => {
  const result = (await nightmare.goto("https://github.com/")
    .wait("h1")
    .evaluate<number, string>( // number = argument type, string = output type
      (_input: number) => {
        const title: any = document.querySelectorAll("h1");
        return title[_input].textContent as string;
      },
      input
    )) as string;
  console.log(result);
})();
```

**Comment by orta** [comment] 2021-06-07 13:16
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:16 UTC
