### ISSUE TITLE
Issue using  @types/request-promise-native 

### ISSUE THREAD

**Issue by jpike88** [DefinitelyTyped/DefinitelyTyped#28287] opened 2018-08-22 05:36 UTC
I'm getting the following error:

`Default export of the module has or is using private name 'request.UriOptions'`

My code looks like below:

```
import * as request from 'request-promise-native';

export default {
   request
}
```

This shouldn't be erroring, it's a perfectly valid bit of code.

**Comment by jpike88** [comment] 2018-08-22 05:37
@gustavohenke @mastermatt

**Comment by mastermatt** [comment] 2018-08-22 14:58
I have to say, I'm stumped by this. 
@jpike88 can you provide more details such as your TS version, config, and how you're executing the transpile?

Maybe @andy-ms has insight for us.

**Comment by andy-ms** [comment] 2018-08-22 17:09
@jpike88 I can't reproduce this error when testing with `typescript@next`.

**Comment by jpike88** [comment] 2018-08-23 10:15
I am unable to update to typescript@3.x due to their broken resolveJsonModule functionality. Is there a way to have this not break for <3.0?

**Comment by andy-ms** [comment] 2018-08-23 17:12
We're not publishing new 2.9 releases any more. Please file an issue about `resolveJsonModule` if you're still having problems in `typescript@next`.

**Comment by orta** [comment] 2021-06-07 13:16
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:16 UTC
