### ISSUE TITLE
Bug - react-router fails compilation when disallowing implicit any

### ISSUE THREAD

**Issue by RichardJECooke** [DefinitelyTyped/DefinitelyTyped#9570] opened 2016-06-06 14:48 UTC
ERROR in /home/rje/projects/ekaya/client/typings/browser/definitions/react-router/index.d.ts
(172,77): error TS2503: Cannot find namespace 'JSX'.

ERROR in /home/rje/projects/ekaya/client/typings/browser/definitions/react-router/index.d.ts
(179,3): error TS7010: 'stringifyQuery', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in /home/rje/projects/ekaya/client/typings/browser/definitions/react-router/index.d.ts
(194,3): error TS7010: 'onError', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in /home/rje/projects/ekaya/client/typings/browser/definitions/react-router/index.d.ts
(199,3): error TS7010: 'onUpdate', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in /home/rje/projects/ekaya/client/typings/browser/definitions/react-router/index.d.ts
(205,35): error TS2503: Cannot find namespace 'JSX'.

ERROR in /home/rje/projects/ekaya/client/typings/browser/definitions/react-router/index.d.ts
(277,3): error TS7010: 'onClick', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in /home/rje/projects/ekaya/client/typings/browser/definitions/react-router/index.d.ts
(340,3): error TS7010: 'push', which lacks return-type annotation, implicitly has an 'any' return type.

**Comment by vvakame** [comment] 2016-06-08 10:31
I can't reproduce your error.

```
$ tsc -v
Version 1.8.10
$ tsc --noImplicitAny react-router/react-router.d.ts
```

do you use typings?
cc/ @blakeembrey

**Comment by RichardJECooke** [comment] 2016-06-10 09:33
Yes, I'm using typings. Does that mean it should or shouldn't work?

**Comment by blakeembrey** [comment] 2016-06-10 17:31
@vvakame I believe this is an issue with an author for Typings, not DefinitelyTyped.

@RichardJECooke I believe you've installed the definition from https://github.com/andrew-w-ross/typings-react-router. I'm going to check it out, it may be an outdated reference in the registry or they may have issues in the typings. There's a few open issues I see.

/cc @vslinko @andrew-w-ross

**Comment by blakeembrey** [comment] 2016-06-10 17:34
Until it's patched, you can install the definitions from DefinitelyTyped using `typings install dt~react-router --global`. It's a bummer, I'll try to sort something out.

**Comment by mikekidder** [comment] 2016-07-01 04:11
Would like to mention that with react-router you need to do this if you using DT w/ Typings

```
typings install dt~react-router --global
typings install dt~react-router/history --global
```

This is due to fact typings install will strip any references, so need to install the right history.

**Comment by orta** [comment] 2021-06-07 13:44
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:44 UTC
