### ISSUE TITLE
openpgp.initWorker() not honoring the path

### ISSUE THREAD

**Issue by groberts817** [DefinitelyTyped/DefinitelyTyped#34664] opened 2019-04-11 15:06 UTC
I have tried using the @types/openpgp versions 4.4.2 and 4.4.3 and had problems changing the path of the Worker. It used to be called with `openpgp.initWorker({path: 'path_name'})`, passing in an object with a path attribute. Now with the change made in 4.4.2 (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/61cd5418176bcbf97106cf8dd3ea7504ebeff9ce#diff-da2618094da363d4f8dd8d0a5269abcdR4708), the initWorker expects a string instead of an object, and is called using `openpgp.initWorker('path_name')`. Unfortunately, the javascript still expects an object with a path attribute: https://github.com/openpgpjs/openpgpjs/blob/f018f60b9c5aadb608f162eeb86f45a5d03b452c/src/openpgp.js#L67. Passing in the path as a string does not work, and the worker still uses the default. Here's a jsfiddle demonstrating the issue: https://jsfiddle.net/kgauhdcn/

@SardineFish @weswigham @errietta

**Comment by SardineFish** [comment] 2019-04-11 15:19
I found this issue caused by jsdoc generator. Will fix it soon.

**Comment by SardineFish** [comment] 2019-04-11 15:39
Fixed in [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34666](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34666)

**Comment by orta** [comment] 2021-06-07 13:12
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:12 UTC
