### ISSUE TITLE
[RFC] React 18 and types-only breaking changes

### ISSUE THREAD

**Issue by eps1lon** [DefinitelyTyped/DefinitelyTyped#46691] opened 2020-08-12 11:51 UTC
Edit: We're likely not doing that in 17 but 18 to make the 17 upgrade as easy as possible. See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691#issuecomment-672840456 for more context.

Among active contributors we talked informally about making some breaking changes to `@types/react` in an upcoming major release of React that we think will improve the typings long-term. Now that a [release candidate for React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html) is available we should formalize what breaking changes we want to make.

GitHub issues is not the best place for discussing umbrella topics (no threading) but hopefully this will do.

## breaking changes

- remove `@deprecated` types 
  These can be flagged in `tslint`
  - [x] `ReactType` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56049, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56396)
  - [x] `SFCElement` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56397)
  - [x] `SFCFactory` (currently no usage in published `@types/` packages)
  - [x] `SFC` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56052, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56402)
  - [x] `StatelessComponent` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56399)
  - [x] `RefForwardingComponent` (Accidental usage removed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56414 which shows how the old name looks right but is most likely misused)
  - [x] `Props` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56416)
- [x] remove implicitly typed `children` from `React.FC` (and the corresponding overload of `React.memo`)
  In TypeScript it's generally easier to add types than remove them. 
  Closes #33006
  Closes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34237
- Require TypeScript 3.?
  Depending on the time frame we should align with the default [supported version in DefinitelTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-29-and-earlier). From the usage stats in VSCode these older TypeScript versions are rarely used.
  Using TypeScript 3.x would allow us to replace `any` with `unknown` which is probably the change with the biggest impact.
  - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52873
- ~Remove `event.persist()`?~
  - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691#issuecomment-672839026
- [x] Remove `{}` from `ReactFragment` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56026)
- [x] `this.context` will be `unknown`

@gaearon Should we hold off with removing deprecated React features? We currently flag the following features as deprecated:
- deprecated lifecycles (cWM, cWRP, cWU, `UNSAFE_` prefixed lifecycles)
  Maybe removing the unprefixed ones is a viable migration path?
- class component constructors with context as the second argument
- class components `this.refs` i.e. string refs

## features

Already part of `next.d.ts`

## How to go about it?

See #46690 where we can test the approaches. Ideally `@types` would understand pre-releases but I couldn't find documentation about it so we have to be practical about the approach chosen.

## `@types/react` authors
@johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @DovydasNavickas, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @hotell, @franklixuefei, @Jessidhia, @saranshkataria, @lukyth, @eps1lon, @zieka, @dancerphil, @dimitropoulos, @disjukr, @vhfmag, @hellatan

**Comment by ferdaber** [comment] 2020-08-12 11:56
I think one change we should consider is finally moving the JSX namespace under `React.createElement`. This will finally allow consumers to use multiple JSX compilers in the same codebase without the intrinsic elements colliding with each other.

**Comment by ferdaber** [comment] 2020-08-12 11:58
From the TS docs:
> The factory chosen will also affect where the JSX namespace is looked up (for type checking information) before falling back to the global one. If the factory is defined as React.createElement (the default), the compiler will check for React.JSX before checking for a global JSX. If the factory is defined as h, it will check for h.JSX before a global JSX.

**Comment by gaearon** [comment] 2020-08-12 12:24
> Remove event.persist()?

It hasn’t been deleted, just doesn’t do anything now. So I don’t think it should be removed.

**Comment by gaearon** [comment] 2020-08-12 12:27
One important note about this release that might not be obvious from the blog post.

**It is very important that React 17 is easy to upgrade to because for legacy screens in huge apps it might be the last release they will upgrade to.**

This is why even already announced deprecations (like removing UNSAFE versions, legacy context, renderSubtree) are **not** included in this release. They will be in 18 instead.

The goal of 17 is to fix event delegation so that Gradual Upgrades become a feasible strategy for legacy apps when React 18 comes out. So any extra breaking changes in React 17 defeat the purpose.

Can we postpone any major breakages to 18 in typings as well?

**Comment by eps1lon** [comment] 2020-08-12 12:40
> Can we postpone any major breakages to 18 in typings as well?

Works for me. Though at some point the typings have to include some breaking changes exclusive to types. 

The way TypeScript works might also prevent having multiple major versions of react (with their respective typings) in a codebase anyway (since they affect the global namespace). So that is definitely something we should investigate in the coming months. We might have to release a breaking change during the v17 lifetime in order to support multiple react versions with their typings in a codebase.

**Comment by gaearon** [comment] 2020-08-12 12:43
Seems like porting https://github.com/reactjs/react-gradual-upgrade-demo to TS and figuring out what the issues are is going to be the next step.

**Comment by ferdaber** [comment] 2020-08-12 12:51
Regardless of when we release this (with 17 vs with 18), we should probably start work on this fork anyway, so we can be better prepared when the time comes. We unfortunately cannot add runtime warnings (only deprecation annotations which aren't always possible to make obvious in an IDE) so we don't have the advantage of being able to warn users effectively.

**Comment by OliverJAsh** [comment] 2020-08-12 18:25
Could we also consider fixing https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35622, whenever we make the other breaking changes mentioned here?

**Comment by eps1lon** [comment] 2020-08-12 18:41
> Could we also consider fixing #35622, whenever we make the other breaking changes mentioned here?

I think that would be fixed by removing implicit `children`. That one is already included in the list.

**Comment by OliverJAsh** [comment] 2020-08-12 19:31
Hmm, but what if you still wanted to allow any `ReactNode` as a child, e.g. you specified `children: ReactNode` explicitly?

**Comment by eps1lon** [comment] 2020-08-12 22:57
> Hmm, but what if you still wanted to allow any `ReactNode` as a child, e.g. you specified `children: ReactNode` explicitly?

You could still do that which we usually recommend. By removing implicit `children` any `children` type that is too wide is responsibility of the typings author and no longer ours.

**Comment by OliverJAsh** [comment] 2020-08-13 04:49
We would still need a type that represents a valid React child node. `ReactNode` should be that but currently it includes `{}` which makes it useless, since that type is assignable to lots of things. As a breaking change I would like to see `{}` removed so we can actually rely on `ReactNode` when we want our components to accept children of type `ReactElement`, fragment, boolean, string or number.

**Comment by eps1lon** [comment] 2020-08-13 09:47
> but currently it includes {}

Right, forgot about that. Let's discuss a possible path forward in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35622#issuecomment-673378489 and then include it here.

**Comment by bela53** [comment] 2020-08-13 12:32
I would like to see  adjustments for the [`FC`/`FunctionComponent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b4330da/types/react/index.d.ts#L547) and class component [`render`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b4330da/types/react/index.d.ts#L494) return type as well. 

In their current form, these types can either lead to run-time errors or are too restrictive compared to the [possible vanilla React return values](https://reactjs.org/docs/react-component.html#render) (the link is about `render` in classes, though the same applies for function components).

### Status quo:
1. `FC` type only accepts `JSX.Element | null`. `boolean`, `string`, `number` and `Array` are currently missing.
2. class `render` accepts `ReactNode`, which is too wide.

[`ReactNode`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b4330da/types/react/index.d.ts#L239) accepts a wide range of types (due to `{}`). So if you return `undefined` or arbitrary object values (which is possible with types) by accident, run-time errors are triggered later on.

### Possible solution

I would consider an explicit `RenderReturnType` type useful and practicable, like:
```
type RenderReturnType = ReactChild | ReactNodeArray | boolean | null | Array<RenderReturnType>;

class Component<P, S> {
  render(): RenderReturnType;  
  // ...
}

interface FunctionComponent<P = {}> {
  (props: PropsWithChildren<P>, context?: any): RenderReturnType;
  // ...
}

// common existing types
type ReactText = string | number;
type ReactChild = ReactElement | ReactText;
interface ReactNodeArray extends Array<ReactNode> {}
type ReactFragment = {} | ReactNodeArray;
```

Maybe there is also potential to combine `RenderReturnType` with `ReactNode`, if `{}` is excluded, as proposed by @OliverJAsh . But then `ReactNode` still includes `undefined`, which is invalid. Hence I propose an explicit type for function and class component return values.

What do you think?

**Comment by eps1lon** [comment] 2020-08-13 12:50
@bela53 We can't do anything about the return type of components. TypeScript restricts  these. We need https://github.com/microsoft/TypeScript/issues/21699 first.

**Comment by bela53** [comment] 2020-08-14 15:12
@eps1lon thanks for the link - certainly helps to understand that the issue is more compiler related. The `FC` type definition seems to be hardwired into the compiler itself  (e.g. changing the type definitions of the react `.d.ts` file has no effect). I mistakenly thought, this had changed since [TS 2.8 local JSX namespaces](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#locally-scoped-jsx-namespaces). 

Though microsoft/TypeScript#21699 has a bigger scope than my suggestion, as it intends to implement custom JSX types looked up dynamically by inferring from the JSX factory function.

Since the issue is stale since long time, I would be just happy, if they change *static* render return types in accordance with vanilla React like mentioned above. I wonder why this already hasn't been done with a breaking change.

**Comment by ferdaber** [comment] 2020-08-14 16:58
I'm not sure what you mean by "static" though, the allowed return types are dictated by the factory function itself— React allows some subset of types, and maybe something like Vue (where fragments are not yet supported) does not allow returning arrays yet.

**Comment by bela53** [comment] 2020-08-14 17:45
Here is a simple [example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wCg0IA7AZ3gFkBPAYVzDgF44AKASg4D4CmCBHxwA9ACo4KanACulANaUIAd0oy5AKQDKADQB0AUQA2SEEkrwAPnErzTpuJPHkqtOACtqADw5wADyMLOASguLicEhQOFDUADRaMnAU4CgwwABG5nCYihjAVKmscEQw8lCawHKYwL5IACZwMBBwekZmFla29o6mQA) to illustrate what I mean by static:
```
import React from "react"
const MyComp = () => "foo" // valid comp, but TS errors
const jsx = <MyComp /> // errors, function component return type is statically fixed to JSX.Element | null 
```
The default jsx factory is `React.createElement`, whose overload for above function is looked up in React namespace:
```
function createElement<P extends {}>(
  type: FunctionComponent<P>,
  props?: Attributes & P | null,
  ...children: ReactNode[]): FunctionComponentElement<P>;
```
Now, even if I change the `FunctionComponent` definition inside `index.d.ts` of my local `@types/react` to something like:
```
 interface FunctionComponent<P = {}> {
     (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null | string; // add string
 }
```
, it won't be respected and the error still occurs.

This let me assume, there is one static, hard wired place, containing the `FC` return type `JSX.Element | null`. If I remember correctly, other issues mentioned this as well.

**Comment by ferdaber** [comment] 2020-08-14 17:49
Yes, the technical procedure is that the compiler covariantly checks that the return type of a specific JSX constructor is assignable to the `JSX.Element` type (which can be defined differently for a specific factory function). The issue is that `JSX.Element` _has_ to be black boxed to an object since you need to sometimes access the VDOM object, because the return value of a JSX expression is deferred through that VDOM object.

**Comment by bela53** [comment] 2020-08-14 19:40
I see, thank you. So basically the crux is, that there is no distinction between a JSX expression type and the component return type, which leads to microsoft/TypeScript#21699 again.

The compiler looks up the jsx factory function `React.createElement`, sees `FunctionComponent` as type parameter and enforces its return type as `JSX.Element`, which is defined in the global JSX namespace. There is no room for other values like `string`, `number` or `Array`, `JSX.Element` must be an object, as you say. If I understand correctly, the RFC strives to read the specific `FunctionComponent` type from the `createElement` overload parameter, so we are able to make it more specific.

Fun fact: With following definitions in `@types/react/index.d.ts`, `string` *is* possible with current types (but doesn't feel right):
```
declare global {
    namespace JSX {
        type Element = React.ReactElement<any, any> | string
       // ...
    }
```

Sorry for somewhat having hijacked the issue :-). Let's root for the TS one to be (hopefully) resolved soon <sub>TM</sub>.

**Comment by ferdaber** [comment] 2020-08-14 20:15
Yup! That's correct, and what you did would be the correct choice in "fixing" this (you /have/ to change the type of `JSX.Element` instead of the return type of function components), but the issue would be that now you can no longer access the VDOM properties of a generated JSX element (which admittedly is a far rarer use case but must still be valid)

**Comment by jleider** [comment] 2020-11-13 20:32
I would like to see default type parameters for react HTML elements.

All the React specific HTML element types take a `T` as their type parameter with no default types. This causes any library users to provide the default HTML element type at every usage. These should likely default to their respective HTML Element types.

For example why should you have to provide the HTML element type:

`type In = React.InputHTMLAttributes<HTMLInputElement>`

When you already know you are dealing with an Input HTML element?

`type In = React.InputHTMLAttributes`

Here is an example of the change: https://github.com/jleider/DefinitelyTyped/pull/9

**Comment by Andarist** [comment] 2021-11-02 12:10
@eps1lon would it be possible to consider migrating away from the **global** JSX namespace? This has caused me many headaches in the past (in combination with other libraries defining the global JSX namespace in a single node_modules). Since TS is capable of using a local JSC namespace since 2.8 I think it would be great if we could start using this here, lead with an example - cause I suspect that other libraries just copy over what React does (and hence conflicting types in projects). For reference: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#locally-scoped-jsx-namespaces , https://github.com/microsoft/TypeScript/pull/22207

**Closed** 2022-04-07 17:11 UTC

**Comment by mh-alahdadian** [comment] 2022-04-10 07:44
> [`ReactNode`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b4330da/types/react/index.d.ts#L239) accepts a wide range of types (due to `{}`). So if you return `undefined` or arbitrary object values (which is possible with types) by accident, run-time errors are triggered later on.

With release of react 18 [according to blog and  PRs of react](https://github.com/facebook/react/pull/21869) it is allowed to return undefined so using ReactNode as return type of FunctionComponent and ComponentClass render is a good choice
