### ISSUE TITLE
Property 'from' does not exist on type '{}'

### ISSUE THREAD

**Issue by fr3gu** [DefinitelyTyped/DefinitelyTyped#41674] opened 2020-01-17 08:18 UTC
I now get compilation errors in a project where i use react-router-dom. react-router-dom is using createBrowserHistory() and I'm accessing location.state in my code.

Can I prevent the TypeScript compiler from caring about this?

Error introduced by the following change:
#41580

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin, @ngbrown, @rokoroku, @danielnixon 

If you do not mention the authors the issue will be ignored.

(edit: grammar)

**Comment by danielnixon** [comment] 2020-01-17 08:22
@OliverJAsh as predicted: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41580#pullrequestreview-342476512

**Comment by fr3gu** [comment] 2020-01-17 08:28
I should mention that the workaround is to do `npm install @types/history@4.7.3 --save-dev` for anyone ending up here.

**Comment by OliverJAsh** [comment] 2020-01-17 09:15
If you don't care about type checking history location state, you can opt out by casting it to any?

**Comment by adambowles** [comment] 2020-01-17 09:26
Any way describe the expected shape of the state?

**Comment by danielnixon** [comment] 2020-01-17 09:43
> Any way describe the expected shape of the state like is done for the params?

@adambowles: yep. Both `History` and `Location` have a single type param, so wherever you have one of those (either as a member of your own type or as a function parameter) replace them with `History<MyHistoryStateType>` or `Location<MyHistoryStateType>`.

**Comment by adambowles** [comment] 2020-01-17 09:53
@danielnixon Thanks

FYI for anyone else landing here I implemented location state shape like this:
```
interface Props extends RouteComponentProps<
  any,
  any,
  { myStateProp?: string },
> {
  myNormalProp: boolean;
}
```

**Comment by fr3gu** [comment] 2020-01-17 09:56
> If you don't care about type checking history location state, you can opt out by casting it to any?

As I stated, _I'm_ not implementing createBrowserHistory, react-router-dom is. So opting for any is not an option.

**Comment by danielnixon** [comment] 2020-01-17 10:59
Another instance of this: https://stackoverflow.com/questions/59772843/routecomponentprops-location-state-property-does-not-exists-on-type

**Comment by danielnixon** [comment] 2020-01-17 11:15
This looks related: https://stackoverflow.com/questions/59772843/routecomponentprops-location-state-property-does-not-exists-on-type

**Comment by fr3gu** [comment] 2020-01-17 11:26
> If you don't care about type checking history location state, you can opt out by casting it to any?

Of course. Thanks.

**Comment by danielnixon** [comment] 2020-01-17 11:39
>I don't like to loose the type checking so we reverted to version 4.7.3.

But the state type param defaults to `any` in 4.7.3, so you're no safer unless you specify that type param. this applies equally to 4.7.3 without the cast to `any` and 4.7.4 with the cast to `any`.

**Comment by fr3gu** [comment] 2020-01-17 11:45
> > I don't like to loose the type checking so we reverted to version 4.7.3.
> 
> But the state type param defaults to `any` in 4.7.3, so you're no safer unless you specify that type param. this applies equally to 4.7.3 without the cast to `any` and 4.7.4 with the cast to `any`.

Yes, sure. My phrasing was a bit off. I don't like to explicitly casting this to any, especially when I'm not the one using the method that should supply the generic type param. Does that make sense?

**Comment by evertbouw** [comment] 2020-01-20 08:46
I can't add proper types any more
```ts
<Prompt
    when={dirty}
    message={(location: Location<{ forced?: boolean }>) => location.state?.forced || "Are you sure you want to leave?"}
// `Type 'Location<PoorMansUnknown>' is not assignable to type 'Location<{ forced?: boolean | undefined; }>'.`
/>
```

**Comment by danielnixon** [comment] 2020-01-20 09:15
@evertbouw this PR should help: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41730

Once that PR lands, you can replace `<Prompt` with `<Prompt<{ forced?: boolean }>`.

**Comment by danielnixon** [comment] 2020-01-20 20:41
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37825 would have fixed `Prompt` too.

**Comment by danielnixon** [comment] 2020-01-22 10:32
This looks related too: https://stackoverflow.com/questions/59752515/react-typescript-add-location-state-to-react-router-component

**Comment by danielnixon** [comment] 2020-01-23 01:07
This issue is unlikely to be fixed (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41675#pullrequestreview-346777995) so shall we just close it?

**Comment by danielnixon** [comment] 2020-01-28 10:16
Another one: https://stackoverflow.com/questions/59931804/property-background-does-not-exist-on-type-react-router-modal

**Comment by OliverJAsh** [comment] 2020-01-28 11:24
Can we close this issue now? This is not a bug?

**Comment by danielnixon** [comment] 2020-01-31 01:30
This has broken my usage of `createPath` too (see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/history/PathUtils.d.ts#L9 ) because `createPath` is missing the generic type param.

@johnnyreilly please reconsider merging https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41675

See also [this comment](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1f36fb3afd908ffa206570c4f0ecae4178f6944e#r36816585), where the number of thumbs up imply support for reverting this change.

**Comment by tsujp** [comment] 2020-02-06 10:40
I cannot use `props.location.state` at all as it complains any type I add doesn't exist on `PoorMansUnknown`.

**Comment by miller-productions** [comment] 2020-03-21 03:29
Hi there, just joining in the discussion in relation to this. Hoping that's ok?

I've asked a [question on StackOverflow in relation to this](https://stackoverflow.com/questions/60768879/in-typescript-what-is-type-poormansunknown-null-undefined-and-how-woul) use of PoorMansUnknown, but I just realised the question was probably more suited to being posted here directly...

If anyone has any thoughts on it... just trying to learn as I go at the moment and this one has me a bit stumped.

Thanks,
Dan

**Comment by OliverJAsh** [comment] 2020-03-21 13:43
@danielnixon

> `createPath` is missing the generic type param.

Can you elaborate on what the problem is you're facing and how it's related to this change?

Side note: it looks like `createPath` misuses generics. It should be re-written as:

```ts
export function createPath(location: LocationDescriptorObject<any>): Path;
Terms
```

Reasoning: the generic is only used by one param and is not used by the return type. See:

- https://twitter.com/SeaRyanC/status/1118634571564630016
- https://github.com/fimbullinter/wotan/blob/def90abb18a3736d7b177a9f9a0b9b624b302f3a/packages/mimir/docs/no-misused-generics.md

---

@tsujp There are examples in the tests: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ee646ad6a1cd47f71f099c0a03686d8f3547f3b0/types/react-router/test/examples-from-react-router-website/Auth.tsx#L72-L102

---

@miller-productions I answered on StackOverflow. 😄 Hope that helps!

**Comment by alan-ws** [comment] 2020-04-15 18:02
If you want to get around this in not a type safe way and only if you are sure you are getting the values, try this.

```js
const { valueX, valueY } = location.state as any
```

**Comment by m5khan** [comment] 2020-11-17 17:23
This worked for me:

```typescript
import { RouteComponentProps } from 'react-router-dom';

type LocationState = {
  //...
}

type Mock = {
  [key: string]: string | undefined;
}

type WithLocatonState= RouteComponentProps<Mock, Mock, LocationState>;
```

**Comment by orta** [comment] 2021-06-07 13:09
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:09 UTC
