### ISSUE TITLE
[@types/mongodb] $addToSet not allowing to set value to array that can be undefined

### ISSUE THREAD

**Issue by helios1138** [DefinitelyTyped/DefinitelyTyped#40381] opened 2019-11-14 15:10 UTC
Authors: @CaselIT, @alanmarcell, @bitjson, @dante-101, @mcortesi, @EnricoPicci, @AJCStriker, @julien-c, @daprahamian, @denys-bushulyak, @BastienAr, @sindbach, @geraldinelemeur, @jishi, @various89, @angela-1, @lirbank, @hector7, @floric, @erikc5000, @Manc, @jloveridge, @ranguna, @HosseinAgha, @albertossilva, @Rauno56

I have a DB record interface with a field like
```ts
array?: ObjectID[] | null
```
then I'm trying to call an update operation with
```ts
$addToSet: { array: value },
```
and I get a TS error
```
Types of property '$addToSet' are incompatible.
  Type '{ array: ObjectID; }' is not assignable to type 'SetFields<Card>'.
    Type '{ array: ObjectID; }' is not assignable to type 'NotAcceptedFields<Card, any[]>'.
      Types of property 'array' are incompatible.
        Type 'ObjectID' is not assignable to type 'undefined'.
```
if I define the field simply as
```ts
array: ObjectID[]
```
it works as expected

I believe this is a bug because I want to describe the database record in a safe way, where fields might or might not exist and it is a perfectly valid mongo operation to call `$addToSet` with a non-existing field, which will result in creating the array with the provided value the first time it's called.

**Comment by Manc** [comment] 2019-12-16 14:18
I just hit the same problem after upgrading my own project from `"@types/mongodb": "^3.1.22"` to `^3.3.13`.

The issue must be somewhere here:

```
$addToSet?: SetFields<TSchema>;
```

And…

```
export type SetFields<TSchema> = ({
    readonly [key in KeysOfAType<TSchema, any[]>]?: Unpacked<TSchema[key]> | AddToSetOperators<TSchema[key]>;
} &
    NotAcceptedFields<TSchema, any[]>) & {
    readonly [key: string]: AddToSetOperators<any> | any;
};
```

I don't fully understand this yet, but we somehow have to not only allow Array types (`any[]`), but also optional arrays.

I also discovered that this "only" causes an error if `strictNullChecks` are turned off. I highly recommend that we turn on `strictNullChecks` in `tsconfig.json` to make it compatible with projects in `strict` mode, which currently also causes a few tests to fail.

Reminder: It is considered **wrong** setting `strictNullChecks` to `false` ([see README](https://github.com/DefinitelyTyped/DefinitelyTyped#some-packages-have-no-tslintjson-and-some-tsconfigjson-are-missing-noimplicitany-true-noimplicitthis-true-or-strictnullchecks-true)).

I've created a branch with an additional (currently failing) test: https://github.com/Manc/DefinitelyTyped/commit/644eefdb0690a5eac4ece138ea1b1598ed3a25e9

**Comment by nicu-chiciuc** [comment] 2020-01-27 10:05
We've also stumbled upon this error. I think the cause is `KeysOfAType` and `KeysOfOtherType`.
Basically if you have some type:
```
type Something = {
  optionalArray?: string[];
  normalArray: string[];
  notArray: string;
};
```

And try: 
```
type ArraysOfSomething = KeysOfAType<Something, any[]>;
```

Then `ArraysOfSomething` will have just the values: `type ArraysOfSomething = "normalArray" | undefined`.

The desired behavior would be to also include the `"optionalArray"` value. A solution would be to redefine `SetFields` to account for this case. I make a PR and see if someone raises any concerns.

**Comment by nicu-chiciuc** [comment] 2020-01-28 08:49
The PR #41879 has been merged so this issue could be closed, although it will work just for optional type but not for union types that have an array and a null.

**Comment by helios1138** [comment] 2020-03-16 14:37
@nicu-chiciuc `@types/mongodb@3.5.2`, this issue is still there

**Comment by helios1138** [comment] 2020-06-10 08:46
`@types/mongodb@3.5.20`, the issue still present :(

**Comment by mfpopa** [comment] 2020-06-14 04:43
The issue still exists in `@types/mongodb@3.5.20`.

Here is how to test it:

```TypeScript
import { MongoClient, Collection } from 'mongodb';

interface User {
  email: string;
}

async () => {
  const client = await MongoClient.connect('mongodb://localhost:27017', {
    appname: 'LinkScore',
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  const collection: Collection<User> = client.db('test').collection('users');

  await collection.findOneAndUpdate({
    email: 'test@gmail.com'
  }, {
    $addToSet: {
      email: 'new_email@gmail.com', // (property) email?: undefined  Type 'string' is not assignable to type 'undefined'.ts(2322)
      randomField: true,
    }
  });
};
```

The `email` should be string as defined on the `User` interface, but it expects to be `undefined`. However, when using properties that are not part of the interface, like `randomField` that I added in the example, these work without type errors.

From my investigation, the issue is caused by `NotAcceptedFields<TSchema, any[] | undefined>` which is part of the `SetFields<TSchema>` type defintion.

**Comment by mfpopa** [comment] 2020-06-14 04:45
The issue still exists in `@types/mongodb@3.5.20`.

Here is how to test it:

```TypeScript
import { MongoClient, Collection } from 'mongodb';

interface User {
  email: string;
}

async () => {
  const client = await MongoClient.connect('mongodb://localhost:27017', {
    appname: 'My Application',
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  const collection: Collection<User> = client.db('test').collection('users');

  await collection.findOneAndUpdate({
    email: 'test@gmail.com'
  }, {
    $addToSet: {
      email: 'new_email@gmail.com', // (property) email?: undefined  Type 'string' is not assignable to type 'undefined'.ts(2322)
      randomField: true,
    }
  });
};
```

The `email` should be string as defined on the `User` interface, but it expects to be `undefined`. However, when using properties that are not part of the interface, like `randomField` that I added in the example, these work without type errors.

From my investigation, the issue is caused by `NotAcceptedFields<TSchema, any[] | undefined>` which is part of the `SetFields<TSchema>` type defintion.

**Comment by mfpopa** [comment] 2020-06-14 06:48
After doing after investigation and playing about I think this is how the `SetFields<TSchema>` should look like:

```TypeScript
export type SetFields<TSchema> = {
    readonly [key in keyof TSchema]?: Required<TSchema>[key] extends any[] ? Required<TSchema>[key][0] | AddToSetOperators<Array<TSchema[key]>> : TSchema[key];
}
```

This allows the following configuration to works correctly:

```TypeScript
interface User {
  email: string;
  active: boolean;
  position: number;
  strings: string[];
  optionalStrings?: string[];
  numbers: number[];
  booleans: boolean[];
  subDocument: {
    _id: ObjectId;
    fieldOne: string;
    fieldTwo?: number;
    array: boolean[];
  };
}

(async () => {
  const client = await MongoClient.connect('mongodb://localhost:27017', {
    appname: 'My Application',
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  const collection: Collection<User> = client.db('test').collection('users');

  await collection.findOneAndUpdate(
    {
      email: 'test@gmail.com',
    },
    {
      $addToSet: {
        email: 'new_test@gmail.com',
        active: true,
        position: 1,
        strings: 'potato',
        optionalStrings: {
          $each: [],
        },
        numbers: 200,
        booleans: {
          $each: [],
        },
        subDocument: {
          _id: new ObjectId(),
          fieldOne: '',
          // fieldTwo: 132, // <-- intentionally left out optional field
          array: [true, false],
        },
      },
    },
  );
})();
```

I am not sure if there are other scenarios that `$addToSet` needs to cover. For example, this will not work for tuple array with different types, like `tuple: [string, number, boolean]`. But I am not sure how common a scenario that is or if it's even possible to infer the type of each type in the tuple.

**Comment by thisVioletHydra** [comment] 2021-01-21 20:42
not fixed 
![image](https://user-images.githubusercontent.com/11839238/105409988-5646a780-5c42-11eb-8cdb-57db91320d2a.png)

**Comment by TheJzoli** [comment] 2021-03-30 23:03
@nicu-chiciuc I have an optional _id field that is of ObjectId type in my IUser interface, and if I pass an object to addToSet where I haven't declared that _id field (i.e. it's undefined),  it throws:
```
Type 'IUsers' is not assignable to type 'WithId<LeanDocument<IUsers>>'.
         Type 'IUsers' is not assignable to type '{ _id: ObjectId; }'. 
          Types of property '_id' are incompatible.
             Type 'ObjectId | undefined' is not assignable to type 'ObjectId'.               
                Type 'undefined' is not assignable to type 'ObjectId'.
```

**Comment by TheJzoli** [comment] 2021-03-30 23:23
@nicu-chiciuc I still encountered an optional type that doesn't work. I have an optional _id field of type ObjectId in my IUser interface (which extends Document), if I pass an object to $addToSet where I haven't defined the _id (i.e. it's undefined), I get this error thrown at me: 
```
Type 'IUser' is not assignable to type 'WithId<LeanDocument<IUser>> | AddToSetOperators<WithId<LeanDocument<IUser>>[]> | undefined'.
       Type 'IUser' is not assignable to type 'WithId<LeanDocument<IUser>>'.
         Type 'IUser' is not assignable to type '{ _id: ObjectId; }'.
           Types of property '_id' are incompatible.
             Type 'ObjectId | undefined' is not assignable to type 'ObjectId'.
               Type 'undefined' is not assignable to type 'ObjectId'.
```

**Comment by TheJzoli** [comment] 2021-04-07 17:07
> @nicu-chiciuc I still encountered an optional type that doesn't work. I have an optional _id field of type ObjectId in my IUser interface (which extends Document), if I pass an object to $addToSet where I haven't defined the _id (i.e. it's undefined), I get this error thrown at me:

My problem was that I was using the wrong ObjectId in my type definition. I was using mongoose.Schema.Types.ObjectId instead of mongoose.Types.ObjectId. It's fixed now that I changed it.

**Comment by LinusU** [comment] 2023-07-24 10:47
The `@types/mongodb` packages has been removed and typings are now shipped upstream as part of the `mongodb` package, so this issue can be closed...

**Closed** 2023-10-20 05:52 UTC
