### ISSUE TITLE
[@types/react] TypeScript ignores required props if defaultProps is defined and declared as Props

### ISSUE THREAD

**Issue by egorovsa** [DefinitelyTyped/DefinitelyTyped#29679] opened 2018-10-12 09:30 UTC
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention] the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Asana, @AssureSign, @Microsoft, @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @hotell, @franklixuefei

- [x] "react": "^16.5.2",
- [x] "@types/react": "^16.4.16",
- [x] "typescript": "^3.1.1",

**Case 1:** 
```
// UIComponent.tsx
interface Props {
    propA: boolean;
    propB: boolean;
}

class UIComponent extends React.Component<Props> {....
```
and attach UIComponent to some another component

```
// AnotherComponent.tsx is using UIComponent
interface Props {
    someProps: any;
}

class AnotherComponent extends React.Component<Props> {
    public render(){
         return (){
              ...
              <UIComponent propA={true}/>
              ...
         }
```
as we did not attach propB we will have a typescript Error like propB is missing. That is true

**Case 2:** 
add default props
```
// UIComponent.tsx
interface Props {
    propA: boolean;
    propB: boolean;
}

class UIComponent extends React.Component<Props> {
    public static defaultProps:Partial<Props> ={
        propB : false
    }
...
```
and attach UIComponent to some another component

```
// AnotherComponent.tsx is using UIComponent
interface Props {
    someProps: any;
}

class AnotherComponent extends React.Component<Props> {
    public render(){
         return (){
             <>
                  <UIComponent propA={true}/>
              </>
         }
}
```
Now script will be compiled even if you would not pass propB to UIComponent 
it also be compiled if you would not pass any props 
because defaultProps was defined and declared as Props

**Comment by vladferix** [comment] 2018-10-23 10:55
Yes, I have the same problem

**Comment by Hotell** [comment] 2018-11-19 05:41
Everything works as expected.

don't cast defaultProps to `Partial<Props>` , with that you are breaking the proper functionality.

![image](https://user-images.githubusercontent.com/1223799/48688353-c68bb580-ec00-11e8-816b-2ff3354ea354.png)

If you have any other questions please ask, otherwise you can close this issue. 

cheers

**Comment by Hotell** [comment] 2018-11-19 05:44
Pro tip: 

Use runtime information to create types:

In your case:

```tsx
type Props = {    
    propB: boolean
  } & typeof defaultProps

  const defaultProps = {
    propB: false
  }

  class UIComponent extends React.Component<Props> {
    static defaultProps = defaultProps

    render(){
      return <>{this.props.propB}</>
    }
  }
```

To learn more check https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680

**Comment by bySabi** [comment] 2019-01-22 11:52
@Hotell Skateboarder ! I have a question :-)

I have a wrapped component [NavigationEvents](https://github.com/bySabi/react-navigation-core/blob/move_to_typescript/src/views/NavigationEvents.tsx) from HOC [withNavigation](https://github.com/bySabi/react-navigation-core/blob/move_to_typescript/src/views/withNavigation.tsx).  `NavigationEvents` have a required prop [navigation](https://github.com/bySabi/react-navigation-core/blob/move_to_typescript/src/views/index.ts#L32) but this prop is setup inside [a React Context Comsumer](https://github.com/bySabi/react-navigation-core/blob/move_to_typescript/src/views/withNavigation.tsx#L23) on `withNavigation`

This way `NavigationEvents` can be use without a explicit `navigation`prop inside the matching [React Context Provider](https://github.com/bySabi/react-navigation-core/blob/move_to_typescript/src/views/__tests__/NavigationEvents-test.tsx#L83)

The problem is that `NavigationEvents`[inside the context provider](https://github.com/bySabi/react-navigation-core/blob/move_to_typescript/src/views/__tests__/NavigationEvents-test.tsx#L83) fail check due `navigation` prop is required. This can be solve setting `navigation` to optional but this force users of `NavigationEvents` to use unnecessary `bang` operators.

How would you do it?

**Comment by ferdaber** [comment] 2019-01-22 22:18
It sounds like you're describing a standard injected-prop situation with an HOC. This is probably how you want to type your `withNavigation` function: https://github.com/sw-yx/react-typescript-cheatsheet/blob/master/ADVANCED.md#higher-order-components-hocs

For your `NavigationEvents`, you want its own props to have `navigation` be required, which `withNavigation` will omit in the resulting component.

**Comment by FlorianWendelborn** [comment] 2019-10-01 12:22
> don't cast defaultProps to Partial<Props> , with that you are breaking the proper functionality.

How do we ensure that `defaultProps` don’t contain conflicting types/typos then? I can type literally anything into `defaultProps` if I don’t cast them to `Partial<Props>`.

**Comment by orta** [comment] 2021-06-07 16:37
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 16:37 UTC
