### ISSUE TITLE
Issue with latest selenium-webdriver definition

### ISSUE THREAD

**Issue by massimocode** [DefinitelyTyped/DefinitelyTyped#13461] opened 2016-12-20 11:20 UTC
Sorry I don't have much more info as I can't currently spend time investigating the root cause but I thought I would bring this discussion to your attention http://stackoverflow.com/questions/41232228/running-npm-start-fails-due-to-error

I have used the workaround suggested in that link to be able to continue using protractor.

**Comment by andy-ms** [comment] 2016-12-20 16:08
Looks like a duplicate of angular/protractor#3848.

**Closed by andy-ms** 2016-12-20 16:08 UTC

**Comment by AbdoulayeKarimTraore** [comment] 2016-12-22 13:39
@andy-ms @cnishina the problem was fixed but it looks like the commit that fixed the version was not included in the 4.0.14 version of protractor because i'm still having the same problem with the selenium-webdriver typings. Thanks in advance.

**Comment by andy-ms** [comment] 2016-12-22 14:33
Doing `npm install protractor` and compiling a simple file `import { } from "protractor";` works for me (and doesn't work with `npm install protractor@4.0.13`). Could you share a sample project that reproduces your problem? (Also might want to check the versions of your node_modules.)

**Comment by AbdoulayeKarimTraore** [comment] 2016-12-22 21:49
Sorry for the belated response, my use case is a bit different. At our company we are building a set of internal components following the PageObject Model, thus we have classes that represent page and have a number of methods and we are using TypeScript. So a a page and test might look like this: 
```javascript
// page code
'use strict'

export class TestPage {
     name: string;
     constructor(name: string){
          this.name = name;
     }
     addTodo(todo: string): webdriver.promise.Promise<string> {
               element(by.model('todoList.todoText')).sendKeys('write first protractor test');
               return element(by.css('[value="add"]')).click();
     }
} 

//test file
'use strict';
import { testPage } from '...'
     describe( 'test ', function () {
     it ('click test', () => {
          var page = new TestPage('todo');
           browser.get('https://angularjs.org');
          page.addTodo('make test work');
     });
});

```
compiling this code will yield a TS2503 in the test page file because it cannot find the webdriver namespace, in my node_modules file protractor is at 4.0.14, I deleted the node_modules folder and did npm install multiple times but it still gave me the errors, it was only when I installed @types/selenium-webdriver@2.53.31 to replace the @2.53.37 one that protrarctor install that it dissapeared.

**Comment by cnishina** [comment] 2016-12-22 22:27
@AbdoulayeKarimTraore Using `webdriver` globally was not the intent of the previous type version. The new version fixes that issue and Protractor's latest release has these fixes. So looking at your snippet, webdriver was not imported which is why `addToDo` has a type error.

There are several ways you can get fix this:

1. import protractor and protractor exports promise from webdriver.promise:

```
addToDo(todo: string): protractor.promise.Promise<string> {
```

2. import selenium-webdriver as webdriver:

```
import * as webdriver from 'selenium-webdriver';

addToDo(todo: string): webdriver.promise.Promise<string> {
```

3. import promise from selenium-webdriver

```
import {promise} from 'selenium-webdriver';

addToDo(todo: string): promise.Promise<string> {
```

**Comment by AbdoulayeKarimTraore** [comment] 2016-12-22 22:36
OK thanks @cnishina, I'll try the first and third method, the second one didn't work for me, I already tried it. And thanks again for the quick response.
