### ISSUE TITLE
Error: Interface 'Response<ResBody>' incorrectly extends interface 'Response'

### ISSUE THREAD

**Issue by TheInvoker** [DefinitelyTyped/DefinitelyTyped#46639] opened 2020-08-09 18:21 UTC
When I compile from typescript I get this bug

```
node_modules/@types/express-serve-static-core/index.d.ts:505:18 - error TS2430: Interface 'Response<ResBody>' incorrectly extends interface 'Response'.
  Types of property 'locals' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'i18nAPI': locale, __, __n, __mf, and 5 more.

505 export interface Response<ResBody = any> extends http.ServerResponse, Express.Response {
                     ~~~~~~~~

```

from my package.json 

```
    "dependencies": {
        "@types/i18n": "^0.8.6",
        "@types/jest": "^26.0.7",
        "@types/moment": "^2.13.0",
        "@types/node": "^14.0.26",
        "@types/node-schedule": "^1.3.0",
        "@types/ws": "^7.2.6",
        "@typescript-eslint/eslint-plugin": "^3.7.0",
        "@typescript-eslint/parser": "^3.7.0",
        "@types/express": "^4.17.7",
        "chokidar": "^3.4.1",
        "dblapi.js": "^2.4.0",
        "discord.js": "^12.2.0",
        "eslint": "^7.5.0",
        "eslint-plugin-jest": "^23.18.2",
        "express": "^4.17.1",
        "findit2": "^2.2.3",
        "i18n": "^0.10.0",
        "jest": "^26.1.0",
        "moment": "^2.27.0",
        "node-schedule": "^1.3.2",
        "npm-check-updates": "^7.0.3",
        "tree-kill": "^1.2.2",
        "ts-jest": "^26.1.4",
        "typescript": "^3.9.7"
    }
```

Anyone know what's wrong?

**Comment by roymilder** [comment] 2020-08-12 06:37
had the same error. you've probably defined/extended your own Response interface somewhere in your code.
change your definition to:

```
interface Response {
locals: Record<any, _your interface definition_>;
}
```

check ```node_modules/@types/express-serve-static-core/index.d.ts#845```

**Comment by HyperCharlie** [comment] 2020-08-13 21:01
I'm getting this right now as well; I just double checked and I do not have "Response" anywhere in my codebase, so I definitely haven't tampered with it. I'm seeing this in VSCode on Windows.

**Comment by TheInvoker** [comment] 2020-08-13 21:10
I was able to fix this error. I first tried to re-create this as a minimal code needed to re-produce (in a sub folder in my main project) and everything worked fine, and then I started copying  all my main files into that minimal example and it still worked. Pretty soon I had my whole project in that sub folder and it worked there. So then I just deleted my main code and moved the sub folder contents up a level and it still worked there...... Not sure what is the difference. I have a hunch it may be the ordering of dependencies listed in the package.json might of changed which made it work...

**Comment by eschirtz** [comment] 2020-08-31 01:33
I'm still having this issue, wondering if there are any updates? Thanks!

**Comment by drtyh2o** [comment] 2020-09-19 14:51
I am pretty sure this is related to a recent update to `@types/express-serve-static-core` that changed the declaration of `Response.locals` from `any` to `Record<string, any>` .... this basically defines it as an object with potentially infinite properties and prevents constraining it to a more specific type. This is a rare example where the previous `any` type was actually more useable.

**Comment by Aidenir** [comment] 2021-05-05 07:06
Any updates on this? Rebuilding the entire project can hardly be a real solution?

**Comment by didiermunezero** [comment] 2021-06-05 18:08
I also have this error, and i got it after updating

**Comment by didiermunezero** [comment] 2021-06-05 18:09
would like to get solution

**Comment by Deagler** [comment] 2021-06-06 02:14
I started getting this error after setting up hoisting in our monorepo (lerna)

Seems like our Apollo Express Server started using `typescript@3.8.3` when it should have been using `typescript@4.1.2`...

Added typescript to our `no-hoist` list and it was fixed. The fix might just be upgrading typescript @didiermunezero

**Comment by julianurregoar** [comment] 2021-06-06 02:24
I added `"skipLibCheck": true` in tsconfig.json, so it worked for me.

**Comment by didiermunezero** [comment] 2021-06-06 06:41
Well this error has risen when i upgraded my versions prompted by dependabot,

**Comment by didiermunezero** [comment] 2021-06-06 06:43
> I added `"skipLibCheck": true` in tsconfig.json, so it worked for me.

I am going to try this to

**Comment by Dmarcotrigiano** [comment] 2021-06-06 21:23
> I added `"skipLibCheck": true` in tsconfig.json, so it worked for me.

This worked for me, thank you very much.

**Comment by flyon** [comment] 2021-06-08 03:28
just bumping this up, recently upgraded to typescript 4 and now I'm getting this error. skipLibCheck seems like an ugly work around. I do indeed think the changes in `@types/express-serve-static-core` are the problem as described by @drtyh2o

**Comment by andrewtran1995** [comment] 2021-06-08 19:09
I got a similar error message which I was able to get around by explicitly adding `@types/express` as a dependency, thereby forcing version `4.17.12` instead of `4.17.11`. It seems like `4.17.12` may include a fix?

**Comment by olliepotter** [comment] 2021-06-09 01:20
> I got a similar error message which I was able to get around by explicitly adding `@types/express` as a dependency, thereby forcing version `4.17.12` instead of `4.17.11` (it seems like `4.17.12` may include a fix?). This is definitely preferable to enabling `skipLibCheck`.

This didn't work for me :(

**Comment by laktak** [comment] 2021-06-10 18:11
I got it working after adding
```
    "@types/express-serve-static-core": "^4.17.21",
```

before package-lock.json showed v4.17.19 - apparently .21 includes a fix.

**Comment by flyon** [comment] 2021-06-11 12:26
yes @laktak that worked, thanks! I wasnt explicitly depending on that type, just @types/express, but I'm sure those types will catch up soon enough. Adding this to package.json works for now.

**Comment by didiermun** [comment] 2021-06-11 14:10
> > I got a similar error message which I was able to get around by explicitly adding `@types/express` as a dependency, thereby forcing version `4.17.12` instead of `4.17.11` (it seems like `4.17.12` may include a fix?). This is definitely preferable to enabling `skipLibCheck`.
> 
> This didn't work for me :(

did you try all the methods talked about by different people @olliepotter ??

**Comment by veritem** [comment] 2021-06-12 17:24
` "skipLibCheck": true` worked like a charm thanks 🎉

**Comment by ulivz** [comment] 2021-06-17 08:18
`skipLibCheck` is not a good idea.

**Comment by veritem** [comment] 2021-06-17 10:24
@ulivz  it works for now! when folks working on express fix the generic type issue we should definitely remove it

**Comment by Note45** [comment] 2021-06-17 17:38
I had the same error. To work properly, I deleted the file yarn.lock and the folder node_modules and executed `yarn install`.

**Comment by jlborrero** [comment] 2021-06-18 14:53
# rm -rf node_module;
# rm yarn.lock;
# yarn install;

And it worked correctly.

**Comment by aljoshakoecher** [comment] 2021-06-19 12:49
> I got it working after adding
> 
> ```
>     "@types/express-serve-static-core": "^4.17.21",
> ```
> 
> before package-lock.json showed v4.17.19 - apparently .21 includes a fix.

@laktak's method works for me, but could somebody explain why we have to add this dependency now?

**Comment by electerious** [comment] 2021-06-22 09:07
Had the same error with `apollo-server` and it turned out that `apollo-server-express` strictly uses 4.17.19 instead of 4.17.21:

https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-express/package.json#L35

**Comment by didiermun** [comment] 2021-06-22 11:12
> Had the same error with `apollo-server` and it turned out that `apollo-server-express` strictly uses `4.17.19` instead of `^4.17.19` or `4.17.21`:
> 
> https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-express/package.json#L35

which is about the version that you are using. Some versions are not fixed on types

**Comment by zustmornah** [comment] 2021-06-30 12:19
> I got it working after adding
> 
> ```
>     "@types/express-serve-static-core": "^4.17.21",
> ```
> 
> before package-lock.json showed v4.17.19 - apparently .21 includes a fix.

adding "@types/express-serve-static-core": "^4.17.21" to dependencies worked for me @aljoshakoecher submission on .21 fixing this issue proves to be true.

skipLibCheck is not a good idea.

**Comment by fastfedora** [comment] 2021-07-14 11:15
Since the issue is the wrong nested dependency, instead of adding `@types/express-serve-static-core` as a direct dependency, you can add it as a resolution instead:

```
  "resolutions": {
    "@types/express-serve-static-core": "^4.17.21"
  },
```

Then run `yarn install` to update your `yarn.lock` file with the new version for the nested dependencies.

**Comment by keyten** [comment] 2021-07-30 10:12
The bug appeared after installing @types/node (yep I had an express server without it).

skipLibCheck didn`t work, and it`s a dirty solution by the way.
Adding @types/express-serve-static-core to the modules worked.

**Comment by jirevwe** [comment] 2021-08-20 12:17
Installing both `@types/express` and `@types/express-serve-static-core` worked for me. Didn't need to use the `skipLibCheck` workaround

**Comment by vschoener** [comment] 2021-08-25 07:35
> @types/express-serve-static-core

Works for me :) Thanks !

**Comment by universalhandle** [comment] 2021-09-23 23:45
Is it possible this is a bug in `npm` per se? (My version: 7.5.6)

In my case the dependency tree looks like:
```bash
$ npm ls @types/express-serve-static-core
redacted@2.1.4 /path/redacted
└─┬ @types/koa-multer@1.0.1
  └─┬ @types/koa@2.11.6
    └─┬ @types/cookies@0.7.6
      └─┬ @types/express@4.17.9
        └── @types/express-serve-static-core@4.17.17
```

I checked `package.json` in each of the indicated `@types` directories, and the versions of the `dependencies` in question were always set to `*`. I would expect this to result in the latest version being downloaded.

**Comment by sabakhilji** [comment] 2021-09-24 13:47
After upgrading @types/express and @types/express-serve-static-core to ^4.17.12 and ^4.17.21, still getting this typescript error. My project dependencies are:

"@types/express": "^4.17.12",
"@types/express-serve-static-core": "^4.17.21",
"@types/node": "^15.12.4",
"bcrypt": "^5.0.1",
"body-parser": "^1.19.0",
"db-migrate": "^0.11.12",
"db-migrate-pg": "^1.2.2",
"dotenv": "^10.0.0",
"express": "^4.17.1",
"jasmine": "^3.7.0",
"pg": "^8.6.0",
"typescript": "^3.9.7"
  
and dev dependencies are:
"@types/bcrypt": "^5.0.0",
"@types/jasmine": "^3.6.3",
"@types/pg": "^7.14.11",
"cross-env": "^7.0.3",
"jasmine-spec-reporter": "^6.0.0",
"jasmine-ts": "^0.3.0",
"ts-node": "^9.1.1",
"tsc-watch": "^4.2.9"
 

Also, my skipLibCheck is "true"
Please help me in this regard.

**Comment by wassafr** [comment] 2021-11-05 17:11
> rm -rf node_module; rm yarn.lock; yarn install;
> 
> And it worked correctly.

This is the best and simplest answer. You don't even have to add @types/express-serve-static-core

**Closed** 2021-11-09 09:59 UTC

**Comment by rafkhan** [comment] 2021-11-18 18:22
still seeing the following:
```
node_modules/@types/express/node_modules/@types/express-serve-static-core/ts4.0/index.d.ts:279:18 - error TS2430: Interface 'Request<P, ResBody, ReqBody, ReqQuery, Locals>' incorrectly extends interface 'IncomingMessage'.
  Types of property 'body' are incompatible.
    Type 'ReqBody' is not assignable to type '{ [key: string]: unknown; }'.
```

I'm also using
```
  "resolutions": {
    "@types/express-serve-static-core": "^4.17.21"
  }
```

It seems that enabling `skipLibCheck` works, but I'd rather not do that if possible. Any ideas?

**Comment by sabakhilji** [comment] 2021-11-18 18:36
Yes, me too still getting the same error, don't know how to solve it.
skipLibCheck doesn't work for me.:(

**Comment by i5on9i** [comment] 2021-12-04 03:02
I had a same issue so I remove the `@types/node` and run `tsc`. 

It works well without `@types/node`

- typescript version : 4.5.2

**Comment by arthare** [comment] 2021-12-06 18:24
I was doing `import {something} from '../sibling-project'` from another project that still had the package-lock dependency set to the `4.17.18` broken version.

Going through the sibling project's package-lock.json and making sure it was also updated fixed it for me.  Before I changed the other project's package-lock.json, I verified in its node_modules that the broken express-serve-static-core version was present, so this was definitely where the issue was coming from.  `cd ../sibling-project && rm -rf node_modules && npm install` and everything worked.

**Comment by contributorpw** [comment] 2021-12-08 15:13
@arthare You're right. Thanks for the suggestion. I was able to solve this in your way.

Cheers! :fireworks:

**Comment by carlosingles** [comment] 2021-12-21 03:56
This is still an issue for me, I cannot seem to type `res.locals` myself, I have tried with the following:

```ts
interface ResLocals {
  correlationId: string;
  logger?: any;
}

declare module "express" {
  export interface Response {
    locals: ResLocals;
  }
}
```

I have made a code sandbox showing the behaviour, you will need to Ctrl+Click on the `Response` import and navigate to the express type to see the error.

https://codesandbox.io/s/agitated-montalcini-egmct?file=/src/index.ts

Is there something that I'm doing wrong here?

**Comment by contributorpw** [comment] 2021-12-21 04:04
> I cannot seem to type res.locals myself

It works for me fine

![1640059377590](https://user-images.githubusercontent.com/5027939/146869034-0f67ba76-e21d-4653-a35c-5dc4a8112664.png)

**Comment by carlosingles** [comment] 2021-12-21 04:08
The error is only visible if you inspect the type for `Response` OR if you run `npm run build` in the terminal:

`Response` type:
![image](https://user-images.githubusercontent.com/1631343/146869412-4de8c4a4-b86f-4e71-97ca-722ca41fc4d2.png)

`npm run build` output:
![image](https://user-images.githubusercontent.com/1631343/146869461-cffb0e92-4c91-4200-94c9-9521a89cf9c1.png)

**Comment by crazafimahatratra** [comment] 2022-03-02 18:41
Remove `node_modules` and `package-lock.json`, then `npm i` worked for me

**Comment by matheusalxds** [comment] 2022-03-09 13:17
> "skipLibCheck": true

It worked perfectly for me.

**Comment by carlosingles** [comment] 2022-04-11 02:11
I still didn't have this working how I would like, so I tried my best to find a way to have this work **without** enabling `skipLibCheck`.

I ended up changing my shim to this instead:

```ts
import core from "express-serve-static-core";

interface ResLocals {
  customProperty: boolean;
  anotherProp: number;
}

declare module "express" {
  // copy from @types/express
  export interface Response<
    ResBody = any,
    Locals extends Record<string, any> = Record<string, any>
  > extends core.Response<ResBody, Locals> {
    // provide locals customization here, ensuring you & Locals
    locals: ResLocals & Locals;
  }
}
```

Now my types are working correctly and I do not have `skipLibCheck` set to `true`.

**Note: When you enable `skipLibCheck`, your types will all be `any` instead of whatever types you defined.**

**Comment by chubukas** [comment] 2022-05-08 16:53
> rm -rf node_module; rm yarn.lock; yarn install;
> 
> And it worked correctly.

This worked for me

**Comment by jdhiro** [comment] 2022-07-14 18:56
I'm not using Yarn, but deleting node_modules and package-lock.json worked for me, and then re-doing `npm i`

express@4.18.1
@types/express@4.17.13

The latest of each. That ended up installing @types/express-serve-static-core@4.17.29

**Comment by ProfXponent** [comment] 2022-08-21 11:32
> I still didn't have this working how I would like, so I tried my best to find a way to have this work **without** enabling `skipLibCheck`.
> 
> I ended up changing my shim to this instead:
> 
> ```ts
> import core from "express-serve-static-core";
> 
> interface ResLocals {
>   customProperty: boolean;
>   anotherProp: number;
> }
> 
> declare module "express" {
>   // copy from @types/express
>   export interface Response<
>     ResBody = any,
>     Locals extends Record<string, any> = Record<string, any>
>   > extends core.Response<ResBody, Locals> {
>     // provide locals customization here, ensuring you & Locals
>     locals: ResLocals & Locals;
>   }
> }
> ```
> 
> Now my types are working correctly and I do not have `skipLibCheck` set to `true`.
> 
> **Note: When you enable `skipLibCheck`, your types will all be `any` instead of whatever types you defined.**

Only real solution in this entire thread.

**Comment by eliobricenov** [comment] 2023-06-08 20:00
My error was that I had installed `express-session` and `iron-session` packages, they were collading.

**Comment by MikeDabrowski-EQM** [comment] 2023-12-20 14:23
My error was that I wanted to specify types for the headers like this:

```typescript
import type { RequestType } from './request-type';

declare global {
  namespace Express {
    export interface Request {
      type: RequestType | null;
      product: any | null;
      caller: {
        id: string;
      } | any | null;
      permissions: null;
      openapi: any;
      // Headers can have 'data' header in my case, but due to typing issues it has to be removed from here
      headers: {
        data: string;
        [key: string]: any;
      }
    }
  }
}
```
