### ISSUE TITLE
[@types/react-big-calendar] TypeError: Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by joeplaa** [DefinitelyTyped/DefinitelyTyped#50692] opened 2021-01-18 15:29 UTC
- [x] I tried using the `@types/react-big-calendar` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mathieumg (as the last one to merge something), @piotrwitek, @paustint, @pikpok @eps1lon, @strongpauly 

We're trying to migrate our DragAndDrop calendar to TypeScript, but we keep getting the error: `TypeError: Class extends value #<Object> is not a constructor or null`. A Google search suggests it's probably a circular reference, but when searching none are found. In the end we started from scratch using the example in `react-big-calendar-tests.tsx`, but here too we get the same error. 

```
140 | class MyCalendar extends Calendar<CalendarEvent, CalendarResource> { }
    |                         ^
141 | const DnDCalendar = withDragAndDrop<CalendarEvent, CalendarResource>(MyCalendar);
142 | 
143 | const DnD = ({ localizer }: Props) => (
```

Our test component:
```
import React from 'react';
import { Calendar, dateFnsLocalizer, View, DateLocalizer, ToolbarProps, EventProps, EventWrapperProps } from 'react-big-calendar';
import withDragAndDrop from 'react-big-calendar/lib/addons/dragAndDrop';
import { Card, CardBody, Row, Col } from 'reactstrap';
import { format, parse, startOfWeek, getDay } from 'date-fns';
import { locales } from '../functions/userLocale';

const localizer = dateFnsLocalizer({
    format,
    parse,
    startOfWeek,
    getDay,
    locales
});

// Test fixtures
function getEvents(): CalendarEvent[] {
    const events: CalendarEvent[] = [
        new CalendarEvent('All Day Event', new Date(2015, 3, 0), new Date(2015, 3, 0), true),
        new CalendarEvent('Long Event', new Date(2015, 3, 7), new Date(2015, 3, 10)),
        new CalendarEvent('DTS STARTS', new Date(2016, 2, 13, 0, 0, 0), new Date(2016, 2, 20, 0, 0, 0)),
        new CalendarEvent('DTS ENDS', new Date(2016, 10, 6, 0, 0, 0), new Date(2016, 10, 13, 0, 0, 0)),
        new CalendarEvent('Some Event', new Date(2015, 3, 9, 0, 0, 0), new Date(2015, 3, 9, 0, 0, 0)),
        new CalendarEvent('Conference', new Date(2015, 3, 11), new Date(2015, 3, 13), undefined, 'Big conference for important people'),
        new CalendarEvent('Meeting', new Date(2015, 3, 12, 10, 30, 0, 0), new Date(2015, 3, 12, 12, 30, 0, 0), undefined, 'Pre-meeting meeting, to prepare for the meeting'),
        new CalendarEvent('Lunch', new Date(2015, 3, 12, 12, 0, 0, 0), new Date(2015, 3, 12, 13, 0, 0, 0), undefined, 'Power lunch'),
        new CalendarEvent('Meeting', new Date(2015, 3, 12, 14, 0, 0, 0), new Date(2015, 3, 12, 15, 0, 0, 0)),
        new CalendarEvent('Happy Hour', new Date(2015, 3, 12, 17, 0, 0, 0), new Date(2015, 3, 12, 17, 30, 0, 0), undefined, 'Most important meal of the day'),
        new CalendarEvent('Dinner', new Date(2015, 3, 12, 20, 0, 0, 0), new Date(2015, 3, 12, 21, 0, 0, 0)),
        new CalendarEvent('Birthday Party', new Date(2015, 3, 13, 7, 0, 0), new Date(2015, 3, 13, 10, 30, 0)),
        new CalendarEvent('Alice\'s break', new Date(2015, 3, 14, 20, 0, 0, 0), new Date(2015, 3, 14, 21, 0, 0, 0), undefined, undefined, "alice"),
        new CalendarEvent('Bob\'s break', new Date(2015, 3, 15, 7, 0, 0), new Date(2015, 3, 15, 10, 30, 0), undefined, undefined, "bob"),
    ];
    return events;
}

function Event(props: EventProps<CalendarEvent>) {
    return (
        <span>
            <strong>{props.event.title}</strong>
            {props.event.desc && ':  ' + props.event.desc}
        </span>
    );
}

function EventWrapper(props: EventWrapperProps<CalendarEvent>) {
    const { continuesEarlier, event, label, accessors = {}, style } = props;
    return (
        <div style={style}>
            <div>{continuesEarlier}-{label}-{accessors.title && event && accessors.title(event)}</div>
        </div>
    );
}

declare const allViews: View[];
class CalendarEvent {
    title: string;
    allDay: boolean;
    start: Date;
    endDate: Date;
    desc: string;
    resourceId?: string;
    tooltip?: string;

    constructor(_title: string, _start: Date, _endDate: Date, _allDay?: boolean, _desc?: string, _resourceId?: string) {
        this.title = _title;
        this.allDay = _allDay || false;
        this.start = _start;
        this.endDate = _endDate;
        this.desc = _desc || '';
        this.resourceId = _resourceId;
    }
}

class CalendarResource {
    title: string;
    id: string;

    constructor(id: string, title: string) {
        this.id = id;
        this.title = title;
    }
}

class Toolbar extends React.Component<ToolbarProps<CalendarEvent, CalendarResource>> {
    render() {
        const { date, label, view } = this.props;
        return (
            <div>
                <div>{date.toJSON()}-{label}-{view}</div>
            </div>
        );
    }
}

class EventAgenda extends React.Component<EventProps<CalendarEvent>> {
    render() {
        // const { label } = this.props;
        return (
            <div>
                <div>Calendar Events</div>
            </div>
        );
    }
}

// Basic Example Test
interface Props {
    localizer: DateLocalizer;
}

const Basic = ({ localizer }: Props) => (
    <Calendar
        events={getEvents()}
        views={allViews}
        step={60}
        showMultiDayTimes
        defaultDate={new Date(2015, 3, 1)}
        localizer={localizer}
    />
);

class MyCalendar extends Calendar<CalendarEvent, CalendarResource> { }
const DnDCalendar = withDragAndDrop<CalendarEvent, CalendarResource>(MyCalendar);

const DnD = ({ localizer }: Props) => (
    <DnDCalendar
        events={getEvents()}
        views={allViews}
        step={60}
        showMultiDayTimes
        defaultDate={new Date(2015, 3, 1)}
        localizer={localizer}
        selectable={true}
        resizable={true}
        onEventDrop={console.log}
        onEventResize={console.log}
        onDragStart={console.log}
        onDropFromOutside={console.log}
        draggableAccessor={() => true}
        resizableAccessor={() => true}
        elementProps={{ id: 'myCalendar' }}
        components={{
            event: Event,
            agenda: {
                event: EventAgenda,
            },
            toolbar: Toolbar,
            eventWrapper: EventWrapper,
        }}
    />
);

class CalendarComponent extends React.Component {
    render() {
        return (
            <Row>
                <Col xs="12" xl="8" className="mx-auto no-horizontal-padding-mobile">
                    <Card className="shadow">
                        <CardBody className="min-horizontal-padding-mobile min-vertical-padding-mobile">
                            <Basic localizer={localizer} />
                        </CardBody>
                        <CardBody className="min-horizontal-padding-mobile min-vertical-padding-mobile">
                            <DnD localizer={localizer} />
                        </CardBody>
                    </Card>
                </Col>
            </Row >
        );
    }
}

export default CalendarComponent as any;
```

We are working in Next.js 10, React 16.14, TypeScript 4.1.3, @types/react-big-calendar 0.24.8, react-big-calendar 0.30.0.

What are we missing?

**Comment by orta** [comment] 2021-08-03 13:25
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-08-03 13:25 UTC

**Comment by jeetmehta** [comment] 2022-04-22 17:43
@joeplaa Did you end up figuring out what the issue is? I'm facing the same problem.

**Comment by joeplaa** [comment] 2022-04-23 06:59
@jeetmehta unfortunately not. I never got an answer before this ticket got closed. And I didn't bother mentioning it on Discord as @orta commented above (I don't like Discord and can't get used to it).

I had to look it up as I'm not actively working on it anymore and somebody else took over. However, we still have this as an internal open issue and might investigate in the future, but for now we ignore it:
```typescript
// ----
// The two lines below are how it should be according to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-big-calendar/react-big-calendar-tests.tsx
// However we get stuck with: 'TypeError: Class extends value #<Object> is not a constructor or null' => [LINK TO INTERNAL ISSUE REDACTED]
// class MyCalendar extends Calendar<ICalendarEvent> {}
// const DnDCalendar = withDragAndDrop<ICalendarEvent>(MyCalendar);
// added note: This might have to do with 'object' being the second generic type parameter
// ----
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const DnDCalendar = withDragAndDrop<ICalendarEvent>(Calendar);
```

**Comment by jeetmehta** [comment] 2022-04-23 19:11
@joeplaa Aw damn, ok good to know. Agreed with your thoughts on Discord lol, it's really janky. I tried asking there too and no one replied to me.

Appreciate the reply, we'll add a `@ts-ignore` for it as well! 🙏🏽

**Comment by samarai-jk** [comment] 2023-08-14 01:53
another year later... same problem here. Solved with @ts-ignore ... did anyone figure out how to do this properly? 🙏
