### ISSUE TITLE
[aws-lambda] Claims property is missing for Authorizer

### ISSUE THREAD

**Issue by bykka** [DefinitelyTyped/DefinitelyTyped#34059] opened 2019-03-21 08:34 UTC
According to the documentation "https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html" AuthResponseContext class can also contain property "claims".

So, an idea is to introduce a new interface Claims and to add it to the possible values of AuthResponseContext

`
export interface Claims {
[name: string]: boolean | number | string;
}
`
`
export interface AuthResponseContext {
    [name: string]: boolean | number | string | Claims;
}
`

Authors: @darbio, @buggy, @MichaelMarner

**Comment by simonbuchan** [comment] 2020-02-14 00:20
Going back through `aws-lambda` issues, since they seem to be being neglected.

Those docs are more detective work than authoritative on what can be in the context, since they are for the mapping templates, not the proxy integration, but that's fine if its confirmed by experimentation. Unfortunately I'm pretty suspicious of tightening the context, at least without end developer request, given #33437 got reverted, and AWS are happy to let their own authenticator break the rules on lambda authenticaros.

I'm instead thinking the change should be making the context a type parameter, so you can reliably expect things from a custom lambda authenticator or declare you are using a cognito authenticator, e.g. something like:

```ts
// handlers.ts
import { APIGatewayProxyHandler, CustomAuthorizerHandler, CognitoAuthContext } from "aws-lambda";

export const cognitoUsername: APIGatewayProxyHandler<CognitoAuthContext> = async (event) => {
  return event.authorizer.claims.username;
};

interface MyAuthContext {
  token: string;
}

export const customAuthorizer: CustomAuthorizer<MyAuthContext> = async (event) => {
  return { ..., context: { token: "123" } };
};

export const getCustomToken: APIGatewayProxyHandler<MyAuthContext> = async (event) => {
  return event.authorizer.token;
};
```

With appropriate defaults for compatibility. I'm a bit concerned that `APIGatewayProxyHandler<T>` implies that `T` is the *body* type (which is actually, of course, stringified and thus untypable), so maybe this is better:

```ts
export interface APIGatewayProxyHandlerWithAuthorizer<TAuthContext> {
  ... as before
  authorizer: TAuthContext;
}
export type APIGatewayProxyHandler = APIGatewayProxyHandlerWithAuthorizer<any>;
export type APIGatewayProxyHandlerWithCognitoAuthorizer = APIGatewayProxyHandlerWithAuthorizer<CognitoAuthrContext>;
```

I will look into PRing this at some point.

**Comment by simonbuchan** [comment] 2020-02-22 10:46
As mentioned in #42421, I'll be adding the `...WithAuthorizer` version to my current open PR for the authorizer types #42420, probably on Monday.

**Comment by orta** [comment] 2021-06-07 13:36
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:36 UTC
