### ISSUE TITLE
node_modules/@types/node/index.d.ts(6213,64): error TS2304: Cannot find name 'Symbol'.

### ISSUE THREAD

**Issue by Yanga93** [DefinitelyTyped/DefinitelyTyped#25793] opened 2018-05-15 12:38 UTC
Any ideas on how to solve this error. `tsc -v ` Version: 2.8.3

**Comment by Flarna** [comment] 2018-05-16 22:38
I solved this by adding `"es2015.symbol"` to `lib` in tsconfig.json. Or you add `es2015`.

**Comment by JaCraig** [comment] 2018-05-18 14:38
The "es2015.symbol" lib fixed it.

**Comment by Yanga93** [comment] 2018-05-22 15:19
Thanks guys. `es2015` solved it.

**Comment by Yanga93** [comment] 2018-05-24 13:40
Hey grahamlutz, 
Change the target instead of `es5` use `es2015`

**Comment by grahamlutz** [comment] 2018-05-24 13:44
@Yanga93 still same error!  Where can I even read about what's going on here?

**Comment by Yanga93** [comment] 2018-05-24 13:50
I'm not sure where u can find a solution except here. 

By the way, try to empty lib array ` "lib": [ "dom", "es2015", "es2016", "es2017" ],` to be `"lib": [ ]", then use `es2015` as target hope it will work.

**Comment by grahamlutz** [comment] 2018-05-24 14:08
Same issue.

**Comment by Flarna** [comment] 2018-05-24 14:17
Have you tried to use plain typescript instead awesome-typescript-loader?

**Comment by MurhafSousli** [comment] 2018-05-29 09:38
fixed it by using` "@types/node": "7.0.7"`

**Comment by stefan-van-de-vooren-work** [comment] 2018-06-06 15:06
I also encountered some problems with the @types/node": "10.0.8" version. Upgrate to "10.3.1" did fixed it for me

**Comment by baurine** [comment] 2018-06-08 06:14
fixed it by `npm i -D @types/node` and the `@types/node` version is 10.3.2

**Comment by Bakanych** [comment] 2018-07-30 12:35
Facing it with tsc 2.9.2. Tried all described above with no success.

**Comment by mihailik** [comment] 2018-10-11 12:04
Changing `target` is not and CANNOT be a fix here.

Typings for node should work regardless of the target `tsc` uses to compile.

It's barely acceptable  'meh' to require fancy new `lib` settings, but absolutely NOT right to require projects to abandon down-transpilation for such miniscule tiny bug. It should be fixed properly.

Especially given the importants of `@types/node` typings in the ecosystem.

**Comment by Flarna** [comment] 2018-10-11 14:05
Using target es6 "fixes" the problem because it causes that typescript automatically imports lib es6 which is not the case for target es5.
Please note that this is about node 10 typings so es6 is definitely not "fancy new" as es2018 features are already supported.
Typescript team already works on solutions here so soon such issues should be history.

**Comment by mihailik** [comment] 2018-10-11 16:12
You're confusing `target` which drives how much code transformation TypeScript compiler needs to perform, and `lib` which introduces typings and DOES NOT affect he final code generated by tsc.

While the latter may at times be excused as a requirement, typings should be very wary of asking projects to change their target level.

A library may be targeting both up- and downloaded runtimes. It is not only acceptable, it is a good practice to do so.

**Comment by mihailik** [comment] 2018-10-11 16:15
I think the best fix here would be to interface-merge `Set<T>` and avoid depending on EITHER `lib` or `target`:

```typescript
interface Set<T> {
}
```

**Comment by TizioFittizio** [comment] 2018-10-19 20:49
I tried the above with no avail, any news on this?

**Comment by mihailik** [comment] 2018-10-19 21:36
Add this in a file called say `node-extra.d.ts` anywhere in your project:

```typescript
interface Set<T> {
}
```

That way you fix the error, and it will still be fine when the fix rolls out in @types/node official package.

The `lib` fix should work too, but in complex cases the root of the problem is in the way `tsconfig.json` is processed/interpreted with your tooling. The worst cases include Webpack, whose notoriously arcane setup may include gazillion plugins fighting so many endless config battles with each other you could easily comission 6 episodes of Star Wars off George Lucas from that, and still have vibrant fan community of utter webpack thriving on resale of XII generation of merchandise in 'almost mint' condition on whatever they will have for eBay in 2160s.

**Comment by RobotCharlie** [comment] 2019-05-29 18:50
First of all you need "@types/node" in your `package.json`
Then make sure you have these in your tscongif.json under `compilerOptions`
```
    "target": "es2015",
    "lib": [ "dom", "es2015" ],
```

**Comment by pragnakalpdev** [comment] 2019-10-16 07:26
> I also encountered some problems with the @types/node": "10.0.8" version. Upgrate to "10.3.1" did fixed it for me

This worked for me. Thanks.

**Comment by iAbhinav** [comment] 2020-05-12 17:30
Solve this issue with:

```
npm i typescript@2.7.2 --save
```

**Comment by orta** [comment] 2021-06-07 13:38
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:38 UTC

**Comment by vijay9514** [comment] 2024-01-14 08:48
final solution is here got to "signature_pad.d.ts" file and then add any insted of this "GlobalCompositeOperation"

this is the final solution worked for me 
thank you..
