### ISSUE TITLE
FunctionComponent cannot return undefined

### ISSUE THREAD

**Issue by sveyret** [DefinitelyTyped/DefinitelyTyped#33908] opened 2019-03-15 07:50 UTC
As an exercise, I am currently transforming some class components into FunctionComponent, using the new hook style. But I faced a strange problem: class components can render undefined (and so, will not display anything), stateless function components can render undefined, but if we need the new FunctionComponent to render nothing, it can only return null, and not undefined (same for RefForwardingComponent).

I think this is a bug, and it will be annoying as my policy (and I know it is the same in many companies) is to avoid usage of null, and prefer undefined.

The correction is trivial, so if you confirm this is an issue, I can make a PR.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @eps1lon @Jessidhia @johnnyreilly @threepointone (sorry did not retrieved all authors' git name)

**Comment by eps1lon** [comment] 2019-03-15 08:09
Duplicate of #18912

> That is because the compiler is still dumb in this respect and thinks function components have to return JSX.Element | null.
> -- https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18912#issuecomment-446238418

`forwardRef` is affected by this as well because we have to trick the type checker into thinking that is a function. Same goes for `memo` or `lazy`

**Comment by sveyret** [comment] 2019-03-15 08:16
Thank you. Can be closed as duplicate, then.

**Comment by orta** [comment] 2021-06-07 13:36
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:36 UTC
