### ISSUE TITLE
[styled-components] Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by thany** [DefinitelyTyped/DefinitelyTyped#42829] opened 2020-03-04 13:47 UTC
After upgrading to styled-components 5.0.1 from 4.1.9, we're getting these errors.

```
TS2589: Type instantiation is excessively deep and possibly infinite.
```

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Jessidhia @JKillian @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2 

Here's a [playground link](http://www.typescriptlang.org/play/index.html?downlevelIteration=true&noUnusedLocals=true&noUnusedParameters=true&jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHKjAJ4A2WAJnERLl23PgFpcJSADss0mKlqNGAegQJGiOABEsqXFGAAjPXBgALLGawAPQtBRxJ4CLPkA6TQhWNg8rFAEeFYAktrAAG7AvAFwAN6aKKgA-ABccADWWBwQBHAAUgDKABruIfKG0qjAuACiPCByCvQMcNZ2aWwwlQDmLQC+ygxqGq1IAEJoVlgNTXAA7sAWXdx+PShgYFzAfJ5jPgySVfCTqFYAvCs8vO68kQA8YZHRAQB8AAaJd6hbyBzpBB4NhabWQ2x60jESywIFQ6SMU22shaiQAZKlUiYCNAsAAaNEY5AEGCxBKtNpOVwk+TpMhKcltb6-f5wIxcCC4DIgimQaowYCudKULjIfkRLDctowCBgdJidwAVlskrglmAPXMMHSAEYwMDEm1FrwLDqAAymgCkKoRnJ6xAArtJeOlcPaoJR5ABhCDsqDcwbk9GYrDYyjxA1wEDIKA9PxiQwarVwAAcev9BNSRJJUHDDMj0djkJ4xPSqf15ID7xRh1c7DgABVbPBLiJru4fshpJ9yYDbDq4KaUPbpS0q0MRl4dM8YjnnDI5hZRXAPTP0J24DMYXNFss7lEZ1c1hstjsbl4Dkc6+F9wF0tg8DB3AAxT2Pa8vKCvOCXAAUcXaMC4nA7ggZQdb9AAlN+X4-ok9ynFYJJ2OccRITA-TxCB7hgehy4+lg5wAERnGA0aitAhGvBG9yNnYryoU2-T3CotEwFR5LMQh7EQdWtgsPAMRBPaXDwO+M4tEAA) that **_DOESN'T_** show the error, but this error in an actual project will definitely show. In our case, in many multiple files. Everything was fine before the update.

The error shows on `text={text} {...rest} role="separator"` and disappears when removing `{...rest}`.

All is well if I don't upgrade this package, even when I *do* upgrade styled-components itself.

It might help to know as well that we're on Typescript 3.8.3. Perhaps a newer typescript is stricter in some magical way, although I seriously doubt they'd introduce such impressively strange breaking changes.

**Comment by alloy** [comment] 2021-01-19 13:12
Seems a duplicate of https://github.com/microsoft/TypeScript/issues/34933. Adding a link and closing this for future readers.

**Closed by alloy** 2021-01-19 13:12 UTC
