### ISSUE TITLE
README.md Common Mistakes - questionable guideline

### ISSUE THREAD

**Issue by RandScullard** [DefinitelyTyped/DefinitelyTyped#12321] opened 2016-10-28 15:24 UTC
In README.md, in the Common Mistakes section, the last item says:

> getMeAT<T>(): T: If a type parameter does not appear in the types of any parameters, you don't really have a generic function, you just have a disguised type assertion. Prefer to use a real type assertion, e.g. getMeAT() as number. Example where a type parameter is acceptable: function id<T>(value: T): T;. Example where it is not acceptable: function parseJson<T>(json: string): T;. Exception: new Map<string, number>() is OK.

IMO this is a questionable guideline at best. I've found the `getMeAt<T>()` pattern very useful for years, and I've never run into a problem with it. Which of these jQuery expressions is easier to read?

```
($(".foo").first().data("bar") as number).toFixed(2)

$(".foo").first().data<number>("bar").toFixed(2)
```

I find the second one much easier to read and a very good fit with the call-chaining pattern. No extra parentheses to work your head around, and all it requires is declaring the data function as `data<T>()`. (If you declare both generic and non-generic versions, you preserve the option to call it without a type parameter and get "any", if that's what you prefer.)

I'm curious what prompted this guideline to be added. What problem are we trying to solve here?

**Comment by vvakame** [comment] 2016-10-28 16:16
cc/ @andy-ms

**Comment by RyanCavanaugh** [comment] 2016-10-28 19:44
The problem is that you find / write some code like this:
```ts
let x = foo<number>(y, z, q, p);
console.log(x.toFixed());
```
and then you get a runtime error
```ts
(some string).toFixed is not a function(…)
```
And you're like hey, what gives, I did a generic function invocation and specified the type I expected, *and I got no checking at all?* Surely I should have gotten an error on `y` or `z` or `q` or `p`. But then you look at the function implementation and the implementation is like "I hope the caller specified the right type parameter! Anyway here's some value I found `¯\_(ツ)_/¯`". It makes it look like the type system, or the function, is providing a level of safety that it actually doesn't exist.

Conversely, if you wrote / found code like this:
```ts
let x = <number>foo(y, z, q, p);
console.log(x.toFixed());
```
Whoa, what's the cast about? It's clear from this code that *you* are the one who is in charge of knowing what the type actually is, not the type system.

The difference here is about *who is responsible* for the correctness of the result type. If the type parameter is unconsumed, it's necessarily the case that the type system is not providing any level of enforcement. If it's a type assertion, it's 100% clear that it is *you the caller* who is determining what the correct type is.

In terms of parentheses, sure, shorter is always better, but intent matters.

**Comment by RandScullard** [comment] 2016-10-28 20:10
The thing is that there are certain functions where you're always going to have a cast -- my example of jQuery's data function is one of those cases. So you just come to expect that for every call to data, you'll see a type being specified. You won't say "whoa, what's the cast about" because there's always a cast. It just becomes part of the idiom, and our team has found that the `data<T>` syntax is a good pattern in this context -- one that _reinforces_ intent and doesn't just eliminate parentheses.

(And part of this pattern is knowing that that _you_ are in charge of knowing what the type actually is, not the type system.)

**Comment by syberen** [comment] 2019-10-29 15:22
I'm currently working on typings for a package, and would like to clarify: 
When writing types for a function which returns an object of unknown shape, is it then preferable not to add a return type at all, and leave it to the user to assert the type, instead of having a generic return type?

**Comment by naeim249** [comment] 2020-05-10 06:20
Github.com

**Comment by naeim249** [comment] 2020-05-10 06:20
Md naeim
naeim249@gmail.com

**Comment by naeim249** [comment] 2020-05-10 06:21
Duplicate of #

**Comment by orta** [comment] 2021-06-07 13:28
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:28 UTC
