### ISSUE TITLE
[@types/mongodb] Generic TSchema type not accepted by insert methods

### ISSUE THREAD

**Issue by g-pascal** [DefinitelyTyped/DefinitelyTyped#46375] opened 2020-07-27 17:13 UTC
Hi, I'm trying to build a generic Typescript DAO on top of mongodb, but I can't figure if the typings are simply incompatible with generic `TSchema` types, or if I'm doing something wrong.

A simple example:
```ts
import { Collection, MongoClient, ObjectId } from 'mongodb';
export class AbstractDao<T extends { _id: ObjectId }> {
    private mongoClient: MongoClient;

    public async create(entity: T): Promise<void> {
        const collection: Collection<T> = this.mongoClient.db('test-db').collection('test-collection');

        // Argument of type 'T' is not assignable to parameter of type 'OptionalId<T>'.
        // Type '{ _id: ObjectId; }' is not assignable to type 'OptionalId<T>'.
        await collection.insertOne(entity);
    }
}
```

I'm expecting `Collection.insertOne` to accept `entity`, but I can't get `T extends { _id: ObjectId }` to be accepted as a valid `OptionalId<T>`. I tried various constraints for `T` but I never got this class to compile. 

- Authors: @CaselIT @alanmarcell @Dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @Denys-Bushulyak @sindbach @geraldinelemeur @various89 @angela-1 @lirbank @hector7 @floric @erikc5000 @Manc @jloveridge @Ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly

**Comment by g-pascal** [comment] 2020-07-28 07:35
So I've dug into it and it boils down to my `T extends { _id: ObjectId }` not being assignable to the `OptionalId<TSchema>` expected by `Collection.insertOne`, because `OptionalId` is defined as a conditional type, in which type constraints are not resolved because of a language limitation better explained in [this typescript issue](https://github.com/microsoft/TypeScript/issues/29225).

I'm not sure exactly what case the `OptionalId` type is meant to handle, I think it's trying to enforce that the type of the `_id` property of an `OptionalId<TSchema>` must either be `typeof TSchema['_id']` if it exists, or `ObjectId` otherwise? 

The previous definition of OptionalId (before the commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e19dc99582cd3d64cb7cbcde24625e2af5d6cdb8) worked well with generic TSchema types, because it did not use a conditional type, so TSchema constraints were properly resolved. But it did not enforce any specific type for the _id property in `OptionalId`, so that's a tradeoff.

**Comment by CaselIT** [comment] 2020-07-28 10:23
Since the issue in typescript seems to be by design I think we could revert the `OptionalId` definition to the previous one. Could you open a pr for it?

**Comment by HosseinAgha** [comment] 2020-09-06 10:02
@CaselIT @g-pascal 
Please also take look at this issue before merging anything: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39358  
IMHO opening up the types for a special very abstract/generic use case usually results in more runtime bugs.

**Comment by dattannguyen** [comment] 2020-10-22 03:17
Hi @HosseinAgha, I came here after reading #39358 and your issue on [microsoft/TypeScript#35647](https://github.com/microsoft/TypeScript/issues/35647), also [microsoft/TypeScript#35077](https://github.com/microsoft/TypeScript/issues/35077).
TypeScript said it works as expected so they has nothing to do, it brings the matter back to `@types/mongodb`. So now we just do workarounds, e.g `{} as FilterQuery<Schema>` or do you have any plan to fix in `@types/mongodb`?

**Comment by rnbrady** [comment] 2020-12-04 14:26
This workaround worked for me:

```typescript
await collection.insertOne(entity as OptionalId<T>);
```

**Comment by mariocalin** [comment] 2021-02-13 19:23
Same here. Trying also to create a generic DAO.

**Comment by ravshansbox** [comment] 2021-05-29 20:09
Experiencing the same problem. Any plans on resolving the issue?

**Comment by wuriyanto48** [comment] 2022-08-05 14:36
try this
```
`collection.insertOne(entity as any);`
```

**Comment by adriana47** [comment] 2023-04-03 14:15
Just ran into the same problem. Can't work without type safety in a strict codebase. Casting it as `any` or `unknown` is a dangerous and ugly workaround. The PR above has been abandoned, any chance of reopening?

**Comment by LinusU** [comment] 2023-07-24 10:47
The `@types/mongodb` packages has been removed and typings are now shipped upstream as part of the `mongodb` package, so this issue can be closed...

**Comment by peterblazejewicz** [comment] 2023-07-24 19:49
Closing as per last comment, thx!

**Closed by peterblazejewicz** 2023-07-24 19:49 UTC
