### ISSUE TITLE
[TS 2] React Props are incompatible with strictNullChecks: true

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#10388] opened 2016-08-01 02:58 UTC
Issue with `react.d.ts` with typescript 2.0+. I'm not entirely sure how JSX typechecking works, so this might be a TS 2.0 bug more than a `react.d.ts` bug, but at least some of the issues can be fixed in `react.d.ts` itself.

When the TS 2.0 feature `strictNullChecks` are enabled, the type of JSX attributes changes from `IntrinsicAttributes & MyComponentProps` to `IntrinsicAttributes & (MyComponentProps | undefined)`; because of the possibility of `IntrinsicAttributes & undefined` being true, only the `IntrinsicAttributes` are allowed to be specified (e.g. I can put `key='a-key'` and it will typecheck that).

The following code will typecheck with `strictNullChecks` disabled, but will complain with `Property <<prop>> does not exist on type 'IntrinsicAttributes & (Props | undefined)'` when enabled:

``` ts
import React from 'react'
import ReactDOM from 'react-dom'

interface Props {
    size: number
    icon: string
}

// The type of Props had to be over-specified
// Not specifying `Props` as the first argument type makes it `Props | undefined`,
// which doesn't allow destructuring as it is not necessarily an Object.
// ({size, icon} = {size: 0, icon: ''}) doesn't clear the | undefined for
// the destructuring itself either, but that case is probably a TS bug.
const MyComponent: React.SFC<Props> = ({size, icon}: Props) => (
  <i className={`icon size-${size} icon-${icon}`}/>
)

ReactDOM.render(
  // size, icon do not exist with strictNullChecks enabled
  <MyComponent size={12} icon='iconName'/>,
  document.querySelector('#my-component')
)
```

**Comment by vvakame** [comment] 2016-08-02 15:31
please send a pull request for `types-2.0` branch. I'll review it.

**Comment by Kovensky** [comment] 2016-08-03 03:55
Not sure I know enough typescript or react to be able to make it fully correct, but I can try when I have some more time. #10421 is a partial solution that fixes this particular case, but there likely are a lot more places where the types are incorrect when strictNullChecks are enabled.

**Comment by bezreyhan** [comment] 2016-08-09 20:09
I'm getting an error from the second argument of ReacDOM.render. I'm using `getElementById` to find the target element. Since `getElementById` can be null this throws the following error:
```
error TS2345: Argument of type 'HTMLElement | null' is not assignable to parameter of type 'Element'.
  Type 'null' is not assignable to type 'Element'.
```

Here is the code:
```
ReactDOM.render((
 ...SomeJSX
), document.getElementById('root'));
```

I'm not sure what would be the best way to fix this issue. One fix I found is to add a `!`, like this: `document.getElementById('root')! `

This may be expected behavior since there is no way for the compiler to know about the state of the  HTML and therefor we need to explicitly tell the compiler that `#root` exists...

**Comment by orta** [comment] 2021-06-07 13:28
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:28 UTC
