### ISSUE TITLE
@types/react/index.d.ts error TS2300: Duplicate identifier 'as'.

### ISSUE THREAD

**Issue by tianyingchun** [DefinitelyTyped/DefinitelyTyped#20818] opened 2017-10-22 13:25 UTC
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/react 16.0.17` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....
 interface LinkHTMLAttributes<T> extends HTMLAttributes<T> {
        as?: string;
        href?: string;
        hrefLang?: string;
        integrity?: string;
        media?: string;
        rel?: string;
        sizes?: string;
        type?: string;
        as?: string;
    }

**Comment by dawnmist** [comment] 2017-10-22 13:29
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20812

**Comment by orta** [comment] 2021-06-07 14:10
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:10 UTC
