### ISSUE TITLE
[styled-components] React Native types are being imported through Styled Components and overriding native methods

### ISSUE THREAD

**Issue by davejlane** [DefinitelyTyped/DefinitelyTyped#47953] opened 2020-09-22 19:46 UTC
When installing @types/styled-components, it appears that [types for React Native](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native) get pulled in too.  [This commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/eaf827fcc3ef334a2ecce2f3b8fe4d334a77e947) by @newyankeecodeshop   introduces a new `URL` class, and the native method `createObjectURL` appears to be getting clobbered by it, causing type errors as the methods take different arguments.

Is it possible to separate out any types in Styled Components so that the React Native ones are not included where ever there is a window object? @sandersn?

**Comment by newyankeecodeshop** [comment] 2020-09-22 19:56
@davejlane I see that my type signature for that method is more restrictive, but also has a mistake. The return type should be `string` and not `URL`. Is the issue that the TypeScript DOM lib has the object argument as `any` while the React Native one restricts it to `Blob`?

**Comment by davejlane** [comment] 2020-09-22 20:01
@newyankeecodeshop I *think* you're correct. Here's the error:

```
Argument of type 'URL' is not assignable to parameter of type 'string'.
```

**Comment by newyankeecodeshop** [comment] 2020-09-22 20:13
@davejlane Sorry! I can do a PR to fix. What about the argument? The React Native implementation only supports Blob. Is that causing friction?
FWIW, I would argue that these types should not be forcing the dependency on react native types. I imagine that only a percentage of styled components users are React Native applications?

**Comment by davejlane** [comment] 2020-09-22 20:19
@newyankeecodeshop no problem. tbh I didn't get past figuring out the arguments. I would imagine that we'd want to at least honor the original arguments for this to work in a browser context.

The issue I have is that I discovered this in a web app. Ideally, I'd like for the react native types to not be included at all in that environment, but the react native types are a dependency of styled component types. I'm not sure how feasible that is though.

**Comment by newyankeecodeshop** [comment] 2020-09-22 20:25
@davejlane Well the issue is that I want the React Native types to reflect what React Native implements, which is only `Blob` support. Otherwise React Native users will get the impression they can do more with that method than is really supported.
Let me fix the return type and see where that gets us.

**Comment by newyankeecodeshop** [comment] 2020-09-22 20:29
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47957

**Comment by davejlane** [comment] 2020-09-22 20:48
@newyankeecodeshop I think that this is more restrictive than the native web method, which accepts more types than `Blob` as an argument. https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL. 

I completely understand wanting to restrict the method to types that will work for React Native, that makes total sense. The part that doesn't work well is that these types are affecting environments that aren't React Native whenever someone wants to use Styled Components in a web context.

**Comment by paulmelnikow** [comment] 2020-09-22 21:25
>The issue I have is that I discovered this in a web app. Ideally, I'd like for the react native types to not be included at all in that environment, but the react native types are a dependency of styled component types. I'm not sure how feasible that is though.

> The part that doesn't work well is that these types are affecting environments that aren't React Native whenever someone wants to use Styled Components in a web context.

This is a long-standing issue with @types/styled-components. See #33311.

**Comment by davejlane** [comment] 2020-09-22 22:36
@paulmelnikow thanks for the insight. I did go issue-diving but didn't find this. That's unfortunate for sure.

**Comment by alloy** [comment] 2020-09-28 13:59
There’s also https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015

**Comment by orta** [comment] 2021-06-07 13:04
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:04 UTC
