### ISSUE TITLE
highcharts.d.ts yAxis / xAxis array

### ISSUE THREAD

**Issue by erfangc** [DefinitelyTyped/DefinitelyTyped#7502] opened 2016-01-06 03:53 UTC
Not sure if this is a TypeScript issue or a `.d.ts` problem, but if you try to create a HighchartsOption object with 

``` json
yAxis: { .... }
```

the compiler complains that the yAxis object's shape does not conform to the `HighchartsAxisOption[]` interface due to missing property `length`, which shouldn't be an error because `.d.ts` file has the declaration `yAxis?:HighchartsAxisOption|HighchartsAxisOption[]`

Same is happening for xAxis ... not sure what is going on here ....

**Comment by vvakame** [comment] 2016-01-11 12:47
please send a pull request. I'll review it.

**Comment by damianog** [comment] 2016-08-12 12:27
@vvakame I made some test but no errors for me consider #7502 closed due to non reproducible issue.

@erfangc feel free to reopen if necessary.

A suggestion, sometimes with highcharts any or multitype assignements, it is simplier if you cast your object: ex.  xAxis : <HighchartsAxisOptions>{...}

**Comment by orta** [comment] 2021-06-07 14:12
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:12 UTC
