### ISSUE TITLE
@types/react - Invalid definition of children

### ISSUE THREAD

**Issue by michalbundyra** [DefinitelyTyped/DefinitelyTyped#49876] opened 2020-11-30 20:52 UTC
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @eps1lon, @johnnyreilly, @bbenezech, @disjukr

The original issue report is here: https://github.com/mui-org/material-ui/issues/23792

I've been told there that the issue is not with TypeScript nor Material-UI but the problem is in `@types/react` that's why I am creating that issue. To be completely honest I did not even suspect that and I have no idea how to fix it. I just know that my code does not work when I try latest stable TypeScript (4.1.2).

Errors I am getting are as follows:

```
Type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | ReactElement<...>[]' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.
  Type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>[]' is missing the following properties from type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>': type, props, key(2322)
```

**Comment by eps1lon** [comment] 2020-12-01 16:13
The part that `@types/react` is not correctly implementing:

> React.Children.map could narrow the item a bit but that's an issue for @types/react

In `React.Children.map(children, mappingFunction)` `mappingFunction` is only invoked with `null | ReactElement | number | string`. `React.Children.map` flattens arrays.

**Comment by michalbundyra** [comment] 2020-12-02 14:50
@eps1lon thanks for your response. Is there any way we can easily fix it? Thanks

**Comment by eps1lon** [comment] 2020-12-02 15:08
We would need to update the typings.

**Comment by michalbundyra** [comment] 2020-12-02 15:16
@eps1lon not sure if I understand... so the problem is not on `@types/react` but in my code?
I am not sure what I should change, as it was working on TypeScript < 4.1... Thanks

**Comment by eps1lon** [comment] 2020-12-02 15:18
> @eps1lon not sure if I understand... so the problem is not on @types/react but in my code?

The problem is in `@types/react`. I was referring to the typings of `@types/react` which need to be updated.

**Comment by michalbundyra** [comment] 2020-12-02 18:55
I've tried several different combinations on:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3412ebec046057873e05162126a6f0a7e1cf5589/types/react/index.d.ts#L2881-L2882
but honestly I have no idea how to fix it in the correct way... 😕

**Comment by orta** [comment] 2021-06-07 13:00
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:00 UTC
