### ISSUE TITLE
@types/d3 dependency versions

### ISSUE THREAD

**Issue by jcelletti** [DefinitelyTyped/DefinitelyTyped#34475] opened 2019-04-04 17:49 UTC
We have been using the @types/c3 0.5.0 for a year or so now which is dependent on @types/d3 ^4 but in the package.json for @types/d3 the dependencies for all the other packages (ie @types/d3-array) are version *, this causes issues when there are major version changes to the other packages and my product needs to be on the previous versions.

recently version 2.0.0 of @types/d3-array was released and we are having to modify all of our packages to compensate.

**Comment by iansan5653** [comment] 2019-08-19 13:39
I'm not completely clear on what the issue is here. It's possible that the latest version of `@types/c3` may fix your dependency problem. Can you try it and verify?

**Comment by orta** [comment] 2021-06-07 13:13
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:13 UTC
