### ISSUE TITLE
@types/d3-hexbin and @types/d3 coexistence as global libraries

### ISSUE THREAD

**Issue by hugoferreira** [DefinitelyTyped/DefinitelyTyped#19402] opened 2017-08-28 20:41 UTC
- [x] I tried using the `@types/d3-hexbin` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have [a question](https://stackoverflow.com/questions/45805742/d3-and-d3-hexbin-in-typescript-as-global-libraries) that is ignored in StackOverflow (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @uncovertruth, @tomwanzek

------

So, I'm using `d3` and `d3-hexbin` as global libraries:

    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/d3-hexbin.v0.2.min.js"></script>

... and referencing them in `.ts` as:

    /// <reference types="d3" />
    /// <reference types="d3-hexbin" />

However, although this works:

    const svg = d3.select('#hitmap')

... this:

    const hexbin = d3.hexbin()

... fails with a :

    Property 'hexbin' does not exist on type 
      'typeof "/Users/bytter/node_modules/@types/d3/index"'

By looking at the [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-hexbin/d3-hexbin-tests.ts), I can see that:

    import * as d3Hexbin from 'd3-hexbin';

Would export the `hexbin()` function directly into the `d3Hexbin` namespace, but I'm unable to figure out how to conciliate this with `d3-hexbin` as a global library.

**Comment by tomwanzek** [comment] 2017-08-31 17:07
Unfortunately, you are running into a known limitation of the TypeScript compiler.

When creating a TS definition file which is meant to export a **global**, one adds a line such as:

```ts
export as namespace d3;
```

In the [definitions for D3](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/60a99976ead7cb087e75d40b591482417607cb4a/types/d3/index.d.ts#L6), this line is added to the definition file that re-exports all the constituent modules of the "standard" bundle.

As a matter of TS compiler design, this statement can only be added once. Adding it a second time, e.g. in **d3-hexbin**, because D3 convention is to export into the same `d3` global, will create a TS compiler error `duplicate variable declaration`. There is a lengthy discussion of this known issue in the DefinitelyTyped and TypeScript repos. See [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9936#issuecomment-234574459) and most importantly Microsoft/TypeScript#9681.

_Workaround:_

So, I am afraid, the only suggestion I can make, is to write and use a custom definition file in your project which re-exports the D3 modules you require similar to the current [D3 bundle definitions file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3/index.d.ts) and includes
```ts
export * from 'd3-hexbin';
```
Then you have only one `d3` global which exposes the functionality you require.

**Comment by tomwanzek** [comment] 2017-09-06 20:38
@hugoferreira Just checking in to see what the status of the issue is on your side?

**Comment by tomwanzek** [comment] 2017-09-26 13:21
@hugoferreira Any update from your side? Can this issue be closed given the TS limitations/workaround outlined above, or do you require further issues management? Cheers, T

**Comment by tomwanzek** [comment] 2017-10-04 01:37
Is this still an issue or can it be closed? Thx for a status confirmation.

**Comment by tomwanzek** [comment] 2017-10-13 23:21
@andy-ms As a matter of maintaining open issues, could you kindly close this issue? There has been no update despite several inquiries. Thx in advance.

@hugoferreira Feel free to provide any new status/information to trigger a re-opening.

**Closed** 2017-10-16 14:46 UTC
