### ISSUE TITLE
so sad...Subsequent variable declarations must have the same type.  Variable 'a' must be of type 

### ISSUE THREAD

**Issue by txiaocao** [DefinitelyTyped/DefinitelyTyped#20863] opened 2017-10-23 08:20 UTC
- I tried using the `@types/react@latest` package and had problems.
- I tried using the latest stable version of tsc. 
npm run tsc -v
3.10.10

## the console
```shell
> @kemao-node-basis/project-tools@1.5.0 tsc /disk0/repository/kemao-node-basis/project-tools
> tsc "-p" "src"

node_modules/@types/react-dom/index.d.ts(16,43): error TS2305: Module '"/disk0/repository/kemao-node-basis/project-tools/node_modules/@types/react-dom/node_modules/@types/react/index"' has no exported member 'ReactPortal'.
node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(3464,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(3465,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'abbr' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(3466,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'address' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
```

## about the react tree
```text
├── @types/node@7.0.46
├── @types/react@16.0.18
├─┬ @types/react-dom@16.0.2
│ ├── @types/node@8.0.46
│ └── @types/react@16.0.5
├─┬ @types/react-router@4.0.16
│ └── @types/history@4.6.1
├─┬ @types/tape@4.2.30
│ └── @types/node@8.0.46
├─┬ @types/uglify-js@2.6.29
│ └── @types/source-map@0.5.1
├─┬ @types/webpack@3.0.13
│ ├── @types/node@8.0.46
│ ├── @types/tapable@0.2.4
│ └── @types/uglify-js@2.6.28
```
I use  `yarn outdated` `yarn upgrade` and deleted yarn.lock and use install `@types/react@latest` `@types/react-dom@latest` but not resolve the problem

**Comment by txiaocao** [comment] 2017-10-23 08:23
use `npm remove @types/react-dom --save-dev` is okay....
maybe the @types/react-dom had the same @types/react???

**Comment by ehrencrona** [comment] 2017-11-24 03:38
The problem is that you are using a different version of `@types/react` from `@types/react-dom`. I can reproduce this issue e.g. using the following versions:

```
    "@types/react": "^15.6.7",
    "@types/react-dom": "^16.0.3",
```

Upgrading `@types/react` to 16.0.3 solves the issue.

**Comment by kajmagnus** [comment] 2017-11-27 12:37
Also see this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20942 — I had to add a `resolutions: ...` and tell Yarn to only use 16.0.x, because otherwise Yarn wanted to keep 15.x alongside with the new 16.0.x I'm upgrading to, and then Typescript found 99999 errors.

**Comment by dengue8830** [comment] 2018-01-08 17:01
in my case if fix it with

```
"@types/react": "16.0.34",
"@types/react-dom": "16.0.3"
```

**Comment by orta** [comment] 2021-06-07 14:10
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:10 UTC
