### ISSUE TITLE
[@types/styled-components]  Performance issues on compiler

### ISSUE THREAD

**Issue by voliva** [DefinitelyTyped/DefinitelyTyped#34391] opened 2019-04-02 08:05 UTC
Adding the latest version of @types/styled-components to an existing project causes build times to go up by about 1-2 minutes, by using the latest tsc@3.4.1.

By using [this seed repo](https://github.com/voliva/sc-types-build), I've tested the following versions:

```
w/o     2.3s
4.0.0   5.6s
4.1.0   8.0s
4.1.5   8.0s
4.1.10  10.1s
4.1.11  90.1s
4.1.12  97.1s
```

My machine is a Linux 4.18.0 (Ubuntu 18.10) laptop, with a i7-6700HQ CPU @ 2.60GHz

It seems clear that the release 4.1.11 is what's causing this performance issue. The PR for this release is #33061. As of why, I really don't know - I tried to dig into the internals of the compiler to see where it was getting stuck at, but I couldn't understand it.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @eps1lon @Igorbek @Jessidhia

**Comment by philipyun** [comment] 2019-04-03 00:02
Myself and @colinbr96 are also seeing this issue

**Comment by eps1lon** [comment] 2019-04-03 00:21
Does this also happen with typescript 3.3?

**Comment by DylanJu** [comment] 2019-04-03 00:50
I experienced same issue

package.json
`"devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-async-to-generator": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.3.3",
    "babel-jest": "^24.5.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-styled-components": "^1.10.0",
    "css-loader": "^2.1.1",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^24.5.0",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.11.0",
    "react-svg-loader": "^2.1.0",
    "regenerator-runtime": "^0.13.2",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "ts-loader": "^5.3.3",
    "typescript-tslint-plugin": "^0.3.1",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1"
  },
  "dependencies": {
    "@babel/polyfill": "^7.4.0",
    "@loadable/component": "^5.7.0",
    "@types/loadable__component": "^5.6.0",
    "@types/react": "^16.8.10",
    "@types/react-dom": "^16.8.3",
    "@types/react-router-dom": "^4.3.1",
    "@types/styled-components": "4.1.5",
    "axios": "^0.18.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "styled-components": "^4.2.0",
    "styled-normalize": "^8.0.6",
    "typescript": "^3.4.1"
  }`

My problem is that it looks like webpack & webpack-dev-server can not parse @types/styled-components. Because when use just styled-components, there was no problem. It always happen when use @types/styled-components@4.1.12 same time.

Before seeing issue of @voliva, I found infinite loop problem of webpack because it use cpu resource 100%.

After changing @types/styled-compoents version to 4.1.5, it looks like everything is ok.

**Comment by michsa** [comment] 2019-04-03 05:14
@eps1lon: Nope, typescript 3.3 is fine; specifically, it looks like the issue starts under release **3.4.0-dev.20190226**. 

Using @voliva's seed repo, I believe I've pinpointed the issue to the usage of `OmitU`, as added in release 4.1.11. Here are both the places it's used in `index.d.ts`:

[Definition of `WithOptionalTheme`](https://github.com/eps1lon/DefinitelyTyped/blob/6605356eb7ca1b9ef54c3f3ad00bfd4479188a1e/types/styled-components/index.d.ts#L352):
```ts
type WithOptionalTheme<P extends { theme?: T }, T> = OmitU<P, "theme"> & {
    theme?: T;
};
```

[Usage of `WithOptionalTheme` (definition of `StyledComponentProps`)](https://github.com/eps1lon/DefinitelyTyped/blob/6605356eb7ca1b9ef54c3f3ad00bfd4479188a1e/types/styled-components/index.d.ts#L68):
```ts
WithOptionalTheme<
    OmitU<
        ReactDefaultizedProps<
            C,
            React.ComponentPropsWithRef<C>
        > & O,
        A
    > & Partial<PickU<React.ComponentPropsWithRef<C> & O, A>>,
    T
>
```

Something about the union-distributed `OmitU` mapping over another `OmitU` seems to be tripping up the compiler. If either or both of these instances is replaced with a regular `Omit` that does not distribute over unions, the compile time is reduced to a reasonable 10 seconds or so under typescript 3.4.1. 

To test this, I swapped out one or both of the distributed `OmitU`s with one of the following:

```ts
type OmitPickU<T, K extends keyof T> = PickU<T, Exclude<keyof T, K>>;
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```

Here is `time yarn tsc` run against typescript **3.4.1**, 3.4.0-dev.2019**0226**, and the immediate prior release, 3.4.0-dev.2019**0223**:

| `WithOptionalTheme` definition | `WithOptionalTheme` usage | Running time 3.4.1 | Running time 3.4.0-dev.20190226 | Running time 3.4.0-dev.20190223 |
| --- | --- | --- | --- | --- |
| `OmitU` | `OmitU` | **1m28.984s** | **0m55.853s** | 0m6.031s |
| `OmitU` | `OmitPickU` | **2m49.492s** | **1m49.457s** | 0m5.961s |
| `OmitPickU` | `OmitU` | **1m10.313s** | **0m35.278s** | 0m6.125s |
| `OmitPickU` | `OmitPickU` | 0m10.501s | 0m6.947s | 0m6.055s |
| `OmitU` | `Omit` | 0m9.611s | 0m6.781s | 0m6.102s |
| `Omit` | `OmitU` | 0m10.471s | 0m7.451s | ...etc |
| `OmitPickU` | `Omit` | 0m9.654s | 0m6.796s |  |
| `Omit` | `OmitPickU` | 0m8.990s | 0m6.485s | |
| `Omit` | `Omit` | 0m9.730s | 0m6.815s | |

Running times for typescript **3.3.3** and **3.3.4000** are consistent with 3.4.0-dev.20190223 -- roughly 6 seconds across the board.

I'm not familiar enough with styled-components to propose a solution, but I hope this data helps!

**Comment by flut1** [comment] 2019-04-03 07:44
I can confirm I have the same issue. Downgrading @types/styled-components to 4.1.5 worked for me as well.

**Comment by eps1lon** [comment] 2019-04-03 08:33
I was expecting some reduction but not a 10x. Since this was introduced in typescript 3.4 could you open an issue in the typescript repo as well? I would like to make sure we don't revert a bug fix if it's a regression that should be fixed in typescript.

**Comment by voliva** [comment] 2019-04-03 09:34
Sorry I initially didn't search in typescript's github, I found this issue they are currently investigating: https://github.com/Microsoft/TypeScript/issues/30663

**Comment by mjbvz** [comment] 2019-04-05 02:19
@weswigham @RyanCavanaugh Can we please look into quickly publishing a revert to the styled components types that does not have the perf issues on 3.4. 

With the VS Code 1.33 release, a lot of js users are going to be downloading the bugged types through automatic type acquisition. Once this happens, to get out of the bad state, I believe that you either have to clear your automatic type acquisition cache or install the fixed `@types/styled-components`. Neither are good experiences for js users

**Closed** 2019-04-05 20:23 UTC

**Comment by AndrewMorsillo** [comment] 2019-09-11 21:24
This seems like it may still be an issue with @types/styled-components 4.1.19 and TS 3.6.3. TS completion and error highlighting taking 5-10+ seconds on 2018 i7 macbook pro 15. Need to do some more investigation.

**Comment by weswigham** [comment] 2019-09-11 21:48
Erm, the OP is talking about 90s compilations (a 9x jump in time form the prior styled components version), seeing as both later version of TS have mitigations in place and later version of styled components were simplified to not have so much of a perf issues, 5-10s is maybe just your project and deps behaving normally.

**Comment by AndrewMorsillo** [comment] 2019-09-11 22:07
I hope not! It's frustratingly slow now when it wasn't in the past. I'm going to look into it further and report back here if it appears to be related to this issue.

**Comment by sregg** [comment] 2019-11-01 08:00
My VSCde is unusable (ts errors appear and disappear after few seconds instead of instantly) as soon as I add @types/styled-components.

I'm using TS 3.6.4 and types 4.1.20.

**Comment by weswigham** [comment] 2019-11-01 21:35
@sregg go blame this PR that reverted the mitigation in `@types/styled-components`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39323

**Comment by weswigham** [comment] 2019-11-01 21:37
(And roll back to v `4.1.19` to fix the issue locally)

**Comment by smockle** [comment] 2019-11-02 01:48
@typescript-bot gathers performance metrics to “gauge whether [PRs] might negatively affect compile times or editor responsiveness”. In PR 39323, @typescript-bot concluded [“It looks like nothing changed too much.”](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39323#issuecomment-545026384).

@sregg, can you think of a reason why @typescript-bot’s existing metrics would fail to highlight the editor performance issue you observe?

(Sidebar: [“go blame this PR”](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391#issuecomment-548959084) is not a constructive suggestion @weswigham. Please be constructive.)

**Comment by smockle** [comment] 2019-11-02 02:10
Here’s some additional context:

@sregg has reported poor performance while using TypeScript 3.6.4: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391#issuecomment-548701239

But from @weswigham’s reply in https://github.com/microsoft/TypeScript/issues/30663#issuecomment-507406245, I understood that TypeScript versions ≥3.5 would no longer incur the performance penalty that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34499 was merged to avoid.

So, with that understanding, I opted to (more-or-less) revert https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34499 in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39323.

**Comment by weswigham** [comment] 2019-11-02 03:14
The bot's perf metrics are based on what's in the tests and, unfortunately, the styled components tests are pretty far from a real app, both in size and (complex) usage. It's doing the best it can with what it's got, however it doesn't always find _every_ perf issue.

**Comment by smockle** [comment] 2019-11-02 14:29
That makes sense, thanks @weswigham!

Until we can catch this performance regression in tests, I think the best course of action is to revert PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39323, so I’ve opened PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40095 to do so.

Next week, I’ll work to add a test based on the reports (e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39323#issuecomment-549015652) that were shared. Once that’s working, we can ex ante evaluate other solutions like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39323.

**Comment by kachkaev** [comment] 2020-02-02 12:52
@smockle have you tried running the latest version (4.4.2)? Seems like the performance bug is back again, downgrading to 4.1.19 helps.

**Comment by JeGwan** [comment] 2020-06-23 06:23
@sregg 
Me too!!!

My VSCode(*Actually TS-SERVER) is slower than before. after using styled-components.
`
"@types/styled-components": "^5.1.0",
"styled-components": "^5.1.1"
"typescript": "^3.9.5"
`

**Comment by joaopaulobdac** [comment] 2020-07-03 04:19
After downgrading TS from 3.9.6 to 3.8.3 performance went back to normal again for me.

**Comment by Andrew1431** [comment] 2020-07-13 15:24
Thanks @joaopaulobdac, I have been working on one project that is substantially slower at typescript evaluation than the other, and it took me so long to realize Styled Components was the culprit. Your fix got'r done for me. Didn't seem to be using any of the 3.9x features of typescript so it was a pretty painless switch!

**Comment by fabb** [comment] 2020-07-13 15:29
Should we create a new issue then? Not upgrading is only a short-term solution.

**Comment by BjMrq** [comment] 2020-07-13 22:01
I am experiencing the same problem with latest June 2020 (version 1.47) and "@types/styled-components": "^5.1.1"

**Comment by lakaniemi** [comment] 2020-07-16 10:58
Using typescript `3.9.3` with the styled-components types version `5.1.1` absolutely destroys my VSCode TS server performance. It is absolutely unusable :D Downgrading to typescript `3.8.3` seems to restore at least some of the performance, but this indeed could use some more attention.

**Comment by fabb** [comment] 2020-07-16 11:21
@RyanCavanaugh reopen?

**Comment by seklyza** [comment] 2020-07-24 20:48
Can confirm, experiencing the same issue.

**Comment by mmahalwy** [comment] 2020-07-30 05:46
Same here, worth reopening!

**Comment by gromov-io** [comment] 2020-08-20 15:27
I confirm that my VSCode has started to choke.

**Comment by AndrewMorsillo** [comment] 2020-08-20 16:04
I ended up removing styled-components, it didn't provide a ton of benefit on react-native for us anyway. Plain old JS objects with spread operator and inline styles works great with no TS perf issues, IMO ends up being easier to read code than with styled-components anyway at least on RN.

**Comment by hilezir** [comment] 2020-08-24 23:42
I'm experiencing the hell in the CSS-in-JS haven when I am coding with VSCode.

**Comment by joaopaulobdac** [comment] 2020-08-24 23:50
@AndrewMorsillo @hilezir  I switched from styled-components to styletron, using TS 4. Performance in styletron is much better both in vscode and in the browser.

**Comment by Andrew1431** [comment] 2020-08-28 14:00
> @AndrewMorsillo @hilezir I switched from styled-components to styletron, using TS 4. Performance in styletron is much better both in vscode and in the browser. But I don't know about styletron on React Native.

Is too late for us to make this change but I haven't heard of styletron and definitely like the looks of it more than styled components.

**Comment by JulianLang** [comment] 2020-08-30 12:46
Will there be a new issue or will this issue be reopened? There are still great performance issues with @types/styled-components 5.1.2 and TS 3.9.7

**Comment by nfarina** [comment] 2020-10-05 05:06
Spent a whole day trying to figure out how to speed up VSCode and _finally_ figured out it was `@types/styled-components`. When that's installed, just typing anything in the editor would cause `tsserver.js` (as shown via VSCode Process Explorer) to spike >100% CPU and grow unbounded in memory. Simply removing `@types/styled-components` fixed this.

I was using TypeScript 4.0.3 and `@types/styled-components` 5.1.3.

**Comment by prabhuignoto** [comment] 2020-10-07 09:19
can someone suggest a better alternative to styled-components. my vscode completely freezes.

**Comment by hilezir** [comment] 2020-10-07 09:51
> can someone suggest a better alternative to styled-components. my vscode completely freezes.

try this?

1. https://material-ui.com/zh/styles/basics/#material-ui-styles

2. https://emotion.sh/docs/styled#styling-elements-and-components

**Comment by bdelaforest** [comment] 2020-10-07 11:13
There is actually a Pull Request open to improve `styled-components`' types performance: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46510.

Until it gets merged, you can try the changes introduced by this PR on your project by running this command: 
(⚠️ Note that this command will break once the PR gets updated)
```
yarn add -D @types/styled-components && curl https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/11857de1edf92b9e4f5728763ccde99ce5704930/types/styled-components/ts3.7/index.d.ts > ./node_modules/@types/styled-components/index.d.ts
```

**Comment by pierpo** [comment] 2021-07-07 14:30
I am still experiencing _very slow_ type checks with `tsserver` 😢 

I compared on the following component : 

```tsx
<Title variant="header">Hello</Title>
```

If I remove the `e` from `"header"`, it becomes a type error. But my editor takes **10 seconds** to show it to me! If I try to autocomplete, it takes like ~5 seconds.

I tried to switch to `emotion` and did the same experiment... It takes **less than 1 second** for both type check and autocompletion to work!

I asked some colleagues and they had the same issue on other projects.
Any idea?

**Comment by Allohamora** [comment] 2021-07-12 10:51
> I am still experiencing _very slow_ type checks with `tsserver` 
> 
> I compared on the following component :
> 
> ```tsx
> <Title variant="header">Hello</Title>
> ```
> 
> If I remove the `e` from `"header"`, it becomes `"hader"` with is a type error. But my editor takes **10 seconds** to show it to me! If I try to autocomplete, it takes like ~5 seconds.
> 
> I tried to switch to `emotion` and did the same experiment... It takes **less than 1 second** for both type check and autocompletion to work!
> 
> I asked some colleagues and they had the same issue on other projects.
> Any idea?

Yesterday i have the same issue. I fix it by removing styled-normalize from project and import normalize.css directly. Maybe also you have broken styled-components dependencies?

**Comment by Allohamora** [comment] 2021-07-12 10:56
Yesterday i had vscode tsserver performance issue in next.js typescript styled-components project. I fix it by removing styled-normalize from project and import it directly by link tag in _app.tsx.

**Comment by pierpo** [comment] 2021-07-15 12:10
Unfortunately I do not use `styled-normalize` :disappointed: so it can't be the issue!

**Comment by naor555666** [comment] 2021-07-23 17:48
I had the same issue, switched to emotion and it works actually much better

**Comment by Adryel123** [comment] 2021-07-27 00:53
My intelisense is extremally slow when using the 5.1.9 version. Errors were taking over 10 seconds to show up and the intelisense was taking over 5 seconds.

The issue disappeared when downgrading to 4.0.3 version. Not the best solution but worked for me.

**Comment by pierpo** [comment] 2021-09-21 09:28
We should identify what's changed, then!

Also, we could take inspiration from emotion's types. They work really well, and the API is the same.

**Comment by Foxhoundn** [comment] 2021-11-01 13:41
A little bump here - removing `@types/styled-components` 5.1.15 fixed a lot of perfomance issues in my VSCode.

**Comment by emiomacollins** [comment] 2022-05-30 19:41
Hi Everyone I've been having this issue for a while now. Downgrading @types/styled-components worked for me.

yarn add @types/styled-components@4.0.3

**Comment by lin2006yuo** [comment] 2022-07-23 18:40
`@types/styled-components` 5.1.25 still slow🙁

**Comment by djskinner** [comment] 2022-08-24 13:36
I have discovered that, for us at least, a lot of the performance issues stem from the types deriving massive unions of all the valid JSX elements. Such large unions can be a performance issue as described here: https://github.com/microsoft/TypeScript/wiki/Performance#preferring-base-types-over-unions

So I created custom types that replace usages of `JSX.IntrinsicElements` with `JSXIntrinsicElementsMinimal`:

```
type JSXIntrinsicElementsMinimal = Pick<
  JSX.IntrinsicElements,
  | 'div'
  | 'span'
  | 'img'
  | 'p'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'header'
  | 'footer'
  | 'section'
  | 'input'
  | 'time'
  | 'button'
  | 'label'
  | 'nav'
  | 'svg'
  | 'hr'
  | 'ul'
  | 'ol'
  | 'li'
>;
```

I just define the element types I actually use and add them as necessary. I'm never going to do `styled.audio`, for example, so there's no need to have it in there contributing to the slowness. 

It makes a noticeable and worthwhile difference and I haven't needed to sacrifice any typing capabilities.

**Comment by yleflour** [comment] 2022-09-30 14:29
@djskinner Do you have the steps to achieve the replacements?
Did you have to clone the entire styled-components typings in your source code or did you find a way to override its usage in @types/styled-components?

**Comment by djskinner** [comment] 2022-09-30 15:14
I created a file called `styled-components-fast.ts` and changed all imports to use this file instead:

```diff
- import styled from 'styled-components'
+ import styled from 'styled-components-fast'
```

Note: the way the project is set up with webpack module resolution allows for this type of absolute import. You may need to do something like `import styled from './styled-components-fast'` depending on your setup.

`styled-components-fast.ts` mostly just re-exports types and implementations from `styled-components` but anywhere any type refers to `JSX.IntrinsicElements` either explicitly or implicitly then the type is copied into this file and changed to refer to `JSXIntrinsicElementsMinimal`, instead of direct re-exporting. It looks like this currently: https://gist.github.com/djskinner/515d96af8d8b59bd6304bcddd7a26bc6

Note:
- I have only re-exported the things currently being used so you may need to re-export more stuff as necessary
- I think I removed some deprecated APIs from some of the modified types
- You should update the `JSXIntrinsicElementsMinimal` union to only include the elements you use with `styled` for the best performance

**Comment by vavra7** [comment] 2022-10-28 18:54
Please open this. Still a big problem...
