### ISSUE TITLE
Unable to run lint

### ISSUE THREAD

**Issue by akdor1154** [DefinitelyTyped/DefinitelyTyped#17792] opened 2017-07-06 03:22 UTC
- Authors: @andy-ms 

When cloning DefinitelyTyped from GitHub and installing dependencies, I can't lint. I get errors:
```
TypeError: ts.isExportAssignment is not a function
    at isExportEquals (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/bin/rules/exportJustNamespaceRule.js:36:15)
    at Array.find (native)
    at walk (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/bin/rules/exportJustNamespaceRule.js:22:41)
    at Rule.AbstractRule.applyWithFunction (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/bin/rules/exportJustNamespaceRule.js:7:21)
    at Linter.applyRule (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:180:29)
    at /Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:122:85
    at Object.flatMap (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/utils.js:153:29)
    at Linter.getAllFailures (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:122:32)
    at Linter.lint (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:75:33)
TypeError: ts.isModuleDeclaration is not a function
    at walk (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/bin/rules/noSingleDeclareModuleRule.js:29:16)
    at Rule.AbstractRule.applyWithFunction (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/bin/rules/noSingleDeclareModuleRule.js:7:21)
    at Linter.applyRule (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:180:29)
    at /Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:122:85
    at Object.flatMap (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/utils.js:153:29)
    at Linter.getAllFailures (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:122:32)
    at Linter.lint (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/node_modules/tslint/lib/linter.js:75:33)
    at Object.<anonymous> (/Users/jarrad/src/personal/DefinitelyTyped/node_modules/dtslint/bin/lint.js:29:20)
    at Generator.next (<anonymous>)
```

To reproduce:
```sh
git clone github.com/DefinitelyTyped/DefinitelyTyped
cd DefinitelyTyped
npm install
npm run lint node
```

I am using `npm 5` and as a shot in the dark I reckon its changed install logic is where the problem is coming from. `node_modules/.bin/tsc` reports `Version 2.2.0-dev.20161128`.

Results of `npm list` attached.
[list.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1126674/list.txt)

**Comment by andy-ms** [comment] 2017-07-06 14:03
I tested this with npm `5.0.3` and `5.1.0` and couldn't reproduce that. It seems like an NPM bug since we've never had a dependency on `typescript@2.2.0-dev.20161128`, only on `typescript@next`.

**Comment by tiagoefmoraes** [comment] 2017-10-18 18:38
@akdor1154 I "resolved" this issue by adding `"typescript": "next"` to my local `packages.json` and running `npm install`.

My npm version was 5.5.1

**Comment by orta** [comment] 2021-06-07 13:23
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:23 UTC
