### ISSUE TITLE
Canvas is not a constructor

### ISSUE THREAD

**Issue by levsa** [DefinitelyTyped/DefinitelyTyped#16948] opened 2017-06-04 12:05 UTC
- [x] I tried using the `@types/fabric` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic, @joewashear007, @mrand01

I get this error in js console:

```
ERROR TypeError: __WEBPACK_IMPORTED_MODULE_1_fabric__.Canvas is not a constructor
    at AppComponent.webpackJsonp.131.AppComponent.ngOnInit (app.component.ts:21)
```
where app.component.ts:21 looks like:
```
import {Canvas} from 'fabric';
...
    this.canvas = new Canvas('canvas');
```
When I check the declarations in index.d.ts, they look like:
```
export interface Canvas extends StaticCanvas {}
export interface Canvas extends ICanvasOptions {}
export class Canvas {
...
```

I don't know typescript very well but are these valid declarations?

Using:
```
    "@types/fabric": "^1.5.24",
    "fabric": "^1.5.0",
```
tsc version 2.3.4
node -v : 7.2.1
npm -v : 3.10.9

Also tried latest fabric, 1.7.11.

**Comment by levsa** [comment] 2017-06-04 18:30
I found a way that works.

With the import above, `Canvas` is undefined, hence not a constructor. I've tried 
```
import { fabric } from 'fabric';
```
This doesn't work with the npm module `@types/fabric`. But it works with 
```
typings install fabric --source dt
```
or 
```
typings install fabricjs --global --source dt
```
In both cases `fabric.Canvas` is defined and works as expected if importing with `import { fabric } from 'fabric'` (even though e.g. PyCharm complains that fabric has no exported member fabric). But still importing as `import { Canvas } from 'fabric';` doesn't work.

**Comment by smatthews1999** [comment] 2017-07-28 00:02
It works but the resulting variables have no type...which kind of defeats the whole purpose of using typescript definition files.

**Comment by kl4n4** [comment] 2017-09-13 15:43
@andy-ms do you have any idea what's going on here? I am also running into this issue in one of my angular 4 project and it renders these typings not usable and I have to fall back to go with:
`import 'fabric';
declare const fabric: any;` 
to use fabric since otherwise the above mentioned exception is thrown.

**Comment by andy-ms** [comment] 2017-09-13 15:53
So what works for you in JS at runtime, ignoring compile errors for now?

**Comment by kl4n4** [comment] 2017-09-13 16:04
yeah, sorry - I should have clarified: compiling the typescript file works fine in both versions (with typings and without) but when the typings are used it will result in this runtime error.

so this works:
```typescript
import 'fabric';
declare const fabric: any;

const canvas = new fabric.Canvas('c');
```

while this doesnt:
```typescript
import * as fabric from 'fabric';

const canvas = new fabric.Canvas('c');
```
I also tried: 
```typescript
import { Canvas } from 'fabric';

const canvas = new Canvas('c');
```
but same result: runtime error:
```
DashboardComponent_Host.html:1 
ERROR TypeError: __WEBPACK_IMPORTED_MODULE_1_fabric__.Canvas is not a constructor
    at DashboardComponent.webpackJsonp.../../../../../src/app/dashboard/dashboard.component.ts.DashboardComponent.ngOnInit (dashboard.component.ts:15)
    at checkAndUpdateDirectiveInline (core.es5.js:10848)
    at checkAndUpdateNodeInline (core.es5.js:12349)
    at checkAndUpdateNode (core.es5.js:12288)
    at debugCheckAndUpdateNode (core.es5.js:13149)
    at debugCheckDirectivesFn (core.es5.js:13090)
    at Object.eval [as updateDirectives] (DashboardComponent_Host.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13075)
    at checkAndUpdateView (core.es5.js:12255)
    at callViewAction (core.es5.js:12620)
```

**Comment by andy-ms** [comment] 2017-09-13 16:51
`@types/fabric` does include `export as namespace fabric;`, so you should be able to `/// <reference types="fabric" />` and use the first style without the `declare const`.
However, it seems like you haven't found an *import* style that works in JS -- until then it seems like a webpack config issue rather than a type declaration issue.

**Comment by kputh** [comment] 2017-10-20 17:16
I think I have a similar problem. What does the `fabric` object look like at runtime?

In my case, the `Canvas` class was at `fabric.fabric.Canvas`, so `new fabric.Canvas(...)` failed at runtime.

**Comment by stewartmatheson** [comment] 2017-10-21 11:13
@kputh Confirmed. It would seem that the type def defines fabric.Canvas instead of fabric.fabric.Canvas. Fabric it's self exports ```module.fabric = fabric``` so I would expect the type import to work like

```js
import { fabric } from "fabric";

**Comment by orta** [comment] 2021-06-07 13:43
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:43 UTC
