### ISSUE TITLE
"adal" package

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12586] opened 2016-11-09 16:21 UTC
- [X] I want to talk about `adal/index.d.ts`.
  - The authors of that type definition are cc/ @mmaitre314

This does `declare module 'adal'` but `npm info adal` turns up nothing. Did you mean `"adal-node"`?
(If so, we should deprecate this and move to `@types/adal-node`.)

Also, if you want `adal-angular` published it should be in its own directory or listed in the `tsconfig`.

**Comment by craxal** [comment] 2016-11-12 08:35
I agree. The types package name needs to match the npm package name.

**Comment by mmaitre314** [comment] 2016-11-15 16:44
The definition matches the structure of the adal-angular package. There is no 'adal' package.
https://github.com/AzureAD/azure-activedirectory-library-for-js

**Comment by mmaitre314** [comment] 2016-11-16 05:40
Is that what breaks `typing install`?
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/61

Splitting the files should be simple but it is weird to have the type package not match the npm package.

**Comment by andy-ms** [comment] 2016-11-17 18:13
Looks like this was called `adal-angular` on master but got changed to `adal` during conversion.
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9

I assume it we have no typings for "adal-node" at the moment.

If we're really just defining `adal-angular`, we should have a single file `adal-angular/index.d.ts`, and not have `declare module "adal"`. @mmaitre314, if this is correct, could you make a PR for this and see if it still works with your code? Then I'll deprecate the `@types/adal` package as being renamed to `@types/adal-angular`.

**Comment by maitre-matt** [comment] 2016-11-18 05:35
A single type file would break ADAL's layering. The `adal-angular` package contains two JS files: a core layer (`adal.js`) that does not depend on AngularJS and a top layer (`adal-angular.js`) that depends on AngularJS. 
https://github.com/AzureAD/azure-activedirectory-library-for-js/tree/dev/lib
Apps can include either depending on the functionalities they need.

One could argue that ADAL should ship two NPM packages, but at the moment this is not the case. If the type package needs to match the NPM package, it needs to be a single package with two .d.ts files.

**Comment by andy-ms** [comment] 2016-11-18 14:22
So how are these packages imported? Does one do `import adal = require("adal-angular/lib/adal");` and `import adalAngular = require("adal-angular/lib/adal-angular");`?

**Comment by mmaitre314** [comment] 2016-11-18 15:55
They are typically loaded via `<script>`:

```
<script src="scripts/adal.js"></script>
<script src="scripts/adal-angular.js"></script>
```
I got them to load as AMD once (in JS, haven't tried TS for that) but that required shims:

```
require.config({
  paths: {
    'adal': 'bower_components/adal-angular/dist/adal.min',
    'adal-angular': 'bower_components/adal-angular/dist/adal-angular.min',
    'angular': 'bower_components/angular/angular.min',
    'angular-route': 'bower_components/angular-route/angular-route.min',
  },
  shim: {
    'adal-angular': ['adal', 'angular'],
    'angular': {
      exports: 'angular'
    },
    'angular-route': ['angular']
  },
});
```

**Comment by craxal** [comment] 2016-12-06 18:18
I don't think this is related just to Angular. The adal.d.ts declaration file appears to describe the same shapes defined in the adal-node package on the npm page.

**Comment by eamodio** [comment] 2017-02-02 06:15
Any chance this will get resolved? Not having the @types package match the npm package name basically makes the types package useless.

**Comment by craxal** [comment] 2017-02-02 16:40
Typescript has a `/// <reference types="..." />` directive now. Perhaps we can use this to reference the misnamed `adal` types package as a workaround. See https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html.

**Comment by aciccarello** [comment] 2017-08-16 00:00
As far as I can tell, the following changes are needed:

- [ ] ADAL definitions need to be published under `@types/adal-angular` to match npm package name
- [ ] `adal-angular.d.ts` needs to be included with `index.d.ts` (possibly under a "adal.angular" namespace?)
- [ ] adal-node definitions should be written under a separate package (see AzureAD/azure-activedirectory-library-for-nodejs#142)
- [ ] Configuration properties should include jsdoc (see source for adal.js)
- [ ] Add `callback: (errorDescription?: string, token?: string, error?: any) => void` to config interface
- [ ] Add `callback`, `popup`, `isAngular`, `REQUEST_TYPE`, and `CONSTANTS` properties to authentication context interface

**Any suggestions for PRs to fix the main issue of renaming the `@types` package and linking the `adal-angular.d.ts` file?**

For reference, I am importing the library with the following imports:

```TypeScript
import AuthenticationContext from 'adal-angular/';
import 'adal-angular/lib/adal-angular';

// The AuthenticationContext needs to be globally available for adal-angular
window['AuthenticationContext'] = AuthenticationContext;
```

**Comment by amarzavery** [comment] 2017-11-02 23:55
This PR https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/pull/176 adds type definitions for the node.js specific adal library (adal-node)

**Comment by amarzavery** [comment] 2017-11-06 22:32
as of version 0.1.25 [adal-node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/releases) supports type definitions.

**Comment by husseinkorly** [comment] 2018-03-23 15:00
I'm using adal-angular type definition, and when I try to import `AuthenticationContext`, it compiles fine but the browser keep giving me this error `ERROR TypeError: adal_angular_1.default is not a constructor` !!!  
I'm importing like this:  
`import AuthenticationContext from 'adal-angular';`

**Comment by aciccarello** [comment] 2018-03-23 16:25
@husseinkorly That's not a type definition issue. It is actually a [TypeScript compiler change](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop). You'll need to do the following import.

```TypeScript
import * as AuthenticationContext from 'adal-angular';
```

**Comment by husseinkorly** [comment] 2018-03-23 17:26
@aciccarello this makes everything available under `AuthenticationContext` name space, but I still cannot access to the `AuthenticationContext` in the index.d.ts !  
I'm trying to do something like this `new AuthenticationContext(config)`

**Comment by aciccarello** [comment] 2018-03-23 17:58
I am able to create an instance of `AuthenticationContext` using that import.
```TypeScript
    this.context = new AuthenticationContext(config);
```

Then to access the `AuthenticationContext` type I use the `adal` namespace.
```TypeScript
  protected context: adal.AuthenticationContext;
```

What are you trying to do with `new AuthenticationContext(config)` in a `d.ts` file?

**Comment by husseinkorly** [comment] 2018-03-23 18:05
Here's what I'm trying to do: I'm writing an auth service using adal-angular:  
 `private _config: AuthenticationContextOptions;`
`private _context: AuthenticationContext ;`
`constructor(){ this._config = environment.adalConfig; this._context = new AuthenticationContext(this._config); }`  
and i'm using your import !!! what i'm doing wrong here ?

**Comment by craxal** [comment] 2018-03-23 21:18
I would think you'd want something like this:
```ts
// Import the AuthenticationContext constructor from the `adal-angular` module.
import { AuthenticationContext } from "adal-angular";
...
this.context = new AuthenticationContext(config);
```
or
```ts
// Import everything from the `adal-angular` module into a variable.
import * as adal from "adal-angular";
...
this.context = new adal.AuthenticationContext(config);
```

**Comment by husseinkorly** [comment] 2018-03-23 21:25
@craxal do you mean importing from `adal-angular` or `@types/adal-angular` ?

**Comment by craxal** [comment] 2018-03-23 22:35
@husseinkorly Either/or, it should work for both Typescript and your module loader. The key is knowing how the module exports what you need.

By looking at the `@types/adal-angular` package, the default export is the `AuthenticationContext` class (constructor), so you'll want to import like this:
```ts
import { AuthenticationContext } from "adal-angular";
...
this.context = new AuthenticationContext(config);
```

The module has other exports, so you'll want to import them as needed like this:
```ts
// If you want everything:
import * as adal from "adal-angular";

// ...or just specific things:
import { LoggingLevel } from "adal-angular";
```

To be sure, you can use a debugger. Drop a breakpoint before you first use the import and examine the import variable's value.

**Comment by aciccarello** [comment] 2018-03-23 23:31
Okay, so I was using the old `@types/adal` types. I've tried to use the `@types/adal-angular` definition and run into some problems. The `adal-angular` project defines the `AuthenticationContext` as the export if used as a module or it defines a global variable.

https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/c306c17e46c108ae680bd90829e8e98fb65416a1/lib/adal.js#L1930-L1935

This does not seem to work with the `import * as AuthenticationContext` syntax. Importing the `AuthenticationContext` as the default export throws a runtime error. I believe this is related to the [`--allowSyntheticDefaultImports`](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-default-import-interop-with-systemjs) flag.

## Attempt 1
```TypeScript
import * as AuthenticationContext from 'adal-angular';

const config: any = {};
const context = new AuthenticationContext(config);
```

TypeScript throws the following:

>error TS2351: Cannot use 'new' with an expression whose type lacks a
call or construct signature.

## Attempt 2
The `adal-angular` module does export an `inject` helper. However, this is not defined in the type definition.

```TypeScript
import { inject, AuthenticationContextOptions } from 'adal-angular';

const config: AuthenticationContextOptions = {};
const context = inject(config);
```

> error TS2305: Module `'"C:/Users/username/Documents/project/node_modules/@types/adal-angular/index"'` has no exported member 'inject'.

## Proposed Solution
Update the type definition to export `AuthenticationContext` as the export and as a namespace.

```TypeScript
// In module contexts the class constructor function is the exported object
export = AuthenticationContext;

// This class is defined globally in not in a module context
declare class AuthenticationContext {
  constructor(config: AuthenticationContext.Config) {}
  // ...
}

declare namespace AuthenticationContext {
  export interface Config {}
  // any other interfaces to export
}
```

### Other changes
- [x] `redirectUrl` should be optional in the config options
- [x] add config to `AuthenticationContext` class
- [x] export `import` helper
- [x] define global `Logging` config object

I came up with an initial [implementation](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...aciccarello:patch-1) these changes (following the [module-class.d.ts template](http://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-class-d-ts.html)). They need to be improved and testing added before I can open a PR.

**Comment by unindented** [comment] 2018-03-26 15:50
@aciccarello yeah, the problem is that `adal-angular` exports the `AuthenticationContext` with `module.exports = AuthenticationContext`, which can't be expressed with ES2015 modules.

Instead of your proposed solution, TypeScript 2.7 seems to be pushing users to use the `--esModuleInterop` flag:

> Under the new --esModuleInterop these two issues should be addressed:
> 
> A namespace import (i.e. import * as foo from "foo") is now correctly flagged as uncallabale. Calling it will result in an error.
> Default imports to CommonJS/AMD/UMD are now allowed (e.g. import fs from "fs"), and should work as expected.
> Note: The new behavior is added under a flag to avoid unwarranted breaks to existing code bases. We highly recommend applying it both to new and existing projects. For existing projects, namespace imports (import * as express from "express"; express();) will need to be converted to default imports (import express from "express"; express();).

**Comment by aciccarello** [comment] 2018-03-26 16:40
@unindented I hadn't seen that information so thanks for highlighting it.

I still wonder if the the type definition should be changed to match the module implementation. While using the flag may fix things, I don't think developers should be required to use it. I haven't tested it but I assume you should be able to still import the `AuthenticationContext` if the type definition was `export = AuthenticationContext;` and if the `--esModuleInterop` flag is enabled .

**Comment by amarzavery** [comment] 2018-03-26 17:21
I think if adal-angular can add a default export in the source code over [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/c306c17e46c108ae680bd90829e8e98fb65416a1/lib/adal.js#L1930-L1935).

```javascript
if (typeof module !== 'undefined' && module.exports) {
        module.exports = AuthenticationContext;
        module.exports.default = AuthenticationContext; // This extra line would be helpful
        module.exports.inject = function (conf) {
            return new AuthenticationContext(conf);
        };
}
```

This should enable `import AuthenticationContext from "adal-angular"`

**Comment by aciccarello** [comment] 2018-04-05 00:44
@amarzavery While I agree that they should also add it as a default export, I think the DefinitelyTyped repo should match the existing implementation.

According to the [DefinitelyTyped README](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default)
> For an NPM package, `export =` is accurate if `node -p 'require("foo")'` is the export, and `export default` is accurate if `node -p 'require("foo").default'` is the export.

I've created #24727 with this change and some missing properties.

**Comment by aciccarello** [comment] 2018-04-11 20:38
The `@types/adal` package has been updated. Types are now defined on the `AuthenticationContext` namespace (e.g. `AuthenticationContext.Options`).

The only other issue with the type definitions that I am aware of are the missing angular service types that were removed in 87ad3c1.

**Comment by orta** [comment] 2021-06-07 13:27
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:27 UTC
