### ISSUE TITLE
Ioredis is not compatible with CompatibleRedisClient[]

### ISSUE THREAD

**Issue by asrulsibaoel** [DefinitelyTyped/DefinitelyTyped#23637] opened 2018-02-14 10:38 UTC
I tried using the `@types/redlock` package and had problem:
 ```Argument of type 'Redis' is not assignable to parameter of type 'CompatibleRedisClient[]'. Property 'push' is missing in type 'Redis'.```
I'm using ioredis 3.1.4 as my Redis package. 
cc @andy-ms @BendingBender any ideas how to solve this? Thank you.

**Comment by andy-ms** [comment] 2018-02-14 16:01
@asrulsibaoel Could you provide a code sample that reproduces that error?

**Comment by asrulsibaoel** [comment] 2018-02-15 04:25
@andy-ms sure.
```
import * as Redis from "ioredis";
import { using } from "bluebird";
import * as Redlock from "redlock";

// this class is my own implementation
export default class RedisRepo {
    constructor(protected redisClient: Redis.Redis) {
        // my others code
    }

   public async lockEvent(key: string, ttl: number, unlockErrorHandler: Function): Promise<any> {
        // return await ]
        const redlock = new Redlock(this.redisClient, {}); // this line produced the error above
        
    }
}
```

**Comment by andy-ms** [comment] 2018-02-15 15:11
@asrulsibaoel I think that would be fixed by changing this line from `types/redlock/index.d.ts` from:
```ts
constructor(clients: Redlock.CompatibleRedisClient[], options?: Redlock.Options);
```
to:
```ts
constructor(clients: Redlock.CompatibleRedisClient | Redlock.CompatibleRedisClient[], options?: Redlock.Options);
```
Could you check that this works for you in your build and at runtime?

**Comment by asrulsibaoel** [comment] 2018-02-17 02:58
@andy-ms Thanks for the answer. 
Its working properly on my code. But for a temporal solution, I've changed my code to be like this.
```const redlock = new Redlock([this.redisClient], {});```

**Comment by andy-ms** [comment] 2018-02-20 17:11
@asrulsibaoel Looking at the [source code](https://github.com/mike-marcacci/node-redlock/blob/f8c696a07dfe0ded923ee3d05fceb6ec559c7d01/redlock.js#L95) it looks like this was only intended to work on arrays -- I see a lot of accesses to `servers.length` and no place where it converts a single client to an array.

**Comment by orta** [comment] 2021-06-07 13:20
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:20 UTC

**Comment by ganezdragon** [comment] 2022-11-21 19:25
any fix on this?

**Comment by HaileyesusZ** [comment] 2023-03-29 11:24
@ganezdragon I've encountered the same issue, and it seems like the latest stable version of redlock - [4.2.0](https://www.npmjs.com/package/redlock/v/4.2.0), doesn't support the latest stable version of ioredis - https://www.npmjs.com/package/ioredis/v/5.3.1

So downgrading ioredis to v4.28 solves the issue
