### ISSUE TITLE
[@types/react]: Type inference with `ComponentClass` breaks when a constructor is declared

### ISSUE THREAD

**Issue by samijaber** [DefinitelyTyped/DefinitelyTyped#26518] opened 2018-06-13 19:30 UTC
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa

If you do not mention the authors the issue will be ignored.

This bugs currently exists with the latest version of `@types/react`, and can be reproduced by instantiating the component's `constructor`. Here's an example:

```tsx
type Props = { foo: string }
class Foo extends Component<Props> {
  constructor(props) {
    super(props)
  }

  render() {
    return <div />
  }
}

function func<P>(base: React.ComponentClass<P>): React.ComponentClass<P> {
  return base;
}

// const Bar: React.ComponentClass<any>
const Bar = func(Foo);
```

One way to fix this is to make sure to annotate the `constructor`'s argument, i.e. 

```tsx
class Foo extends Component<Props> {
  constructor(props: Props) {
    super(props)
  }

  render() {
    return <div />
  }
}
```
This makes `ComponentClass`'s type inference work correctly.

Might be related to #14176. Moved to a separate issue since the other one was closed a long time ago and is inactive.

**Comment by ferdaber** [comment] 2018-06-25 01:49
This should be the intended behavior (it's not isolated to React types) for how constructors behave. 
Since constructors are a specific case of class methods, its parameters need to be annotated as they are not inferred but rather implemented, if you have `noImplicitAny` enabled the error should pop up in the implementation of `Foo`:

![image](https://user-images.githubusercontent.com/12239873/41826571-107c8e1a-77f0-11e8-889d-312a03e3f042.png)

**Comment by orta** [comment] 2021-06-07 13:17
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:17 UTC
