### ISSUE TITLE
@types/chroma-js: Generic type 'Scale<OutType, Color>' requires 2 type argument(s).

### ISSUE THREAD

**Issue by ruffiem** [DefinitelyTyped/DefinitelyTyped#16979] opened 2017-06-05 23:03 UTC
I tried using @types/chroma-js v1.3.0 with typescript v2.2.0 and v2.3.0 and both crash while compiling with this output:

```
ERROR in /usr/local/var/www/projects/ztrim/node_modules/@types/chroma-js/index.d.ts (290,29): ',' expected.

ERROR in /usr/local/var/www/projects/ztrim/node_modules/@types/chroma-js/index.d.ts (202,66): Generic type 'Scale<OutType, Color>' requires 2 type argument(s).

ERROR in /usr/local/var/www/projects/ztrim/node_modules/@types/chroma-js/index.d.ts (204,38): Generic type 'Scale<OutType, Color>' requires 2 type argument(s).

...

ERROR in /usr/local/var/www/projects/ztrim/node_modules/@types/chroma-js/index.d.ts (352,18): Generic type 'Scale<OutType, Color>' requires 2 type argument(s).
```

Anyone to confirm ?

**Comment by diiq** [comment] 2017-06-07 14:05
I can confirm this is also happening to me; chroma-js@1.3.4, @types/crhoma-js@1.1.32

**Comment by diiq** [comment] 2017-06-07 14:24
Works with typescript@2.3.4 -- and should work back as far as 2.3; the 'comma expected' is due to the default generic, which was added in 2.3 (see https://github.com/Microsoft/TypeScript/issues/2175).

@ruffiem are you sure that, when you tried with Typescript 2.3.0, your build system was genuinely using it?

**Comment by ruffiem** [comment] 2017-06-08 21:06
Actually, it was bugged on TypeScript 2.3.2 but not 2.3.4 👍

**Comment by orta** [comment] 2021-06-07 13:43
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:43 UTC
