### ISSUE TITLE
Problems with @types/node, `util.promisify`, and latest version

### ISSUE THREAD

**Issue by molant** [DefinitelyTyped/DefinitelyTyped#20497] opened 2017-10-11 17:06 UTC
- [X] I tried using the `@types/node` package (**8.0.34**) and had problems.
- [X] I tried using the latest stable version of tsc (**2.5.3**). https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Hello all,
At https://github.com/sonarwhal/sonar we are using the package `@types/node` but are currently blocked in version `8.0.14` (I'm not sure in what version after this one things broke). With the latest versions we have issues when compiling the project and all seem related to `util.promisify`. Most of them report the following error:

> `error TS2554: Expected 2 arguments, but got 1.`

Here goes an example of the code we have:

```typescript
    import * as request from 'request';
    import { promisify } from 'util';
 
    const res = await promisify(request)({
        auth: {
            pass: answers.password,
            user: answers.username
        },
        body: {
            body: releaseBody,
            name: `v${version}`,
            tag_name: version // eslint-disable-line camelcase
        },
        headers: {
            'User-Agent': 'Nellie The Narwhal',
            'X-GitHub-OTP': answers.code
        },
        json: true,
        method: 'POST',
        url: 'https://api.github.com/repos/sonarwhal/sonar/releases'
    });
```

Full code [here](https://github.com/sonarwhal/sonar/blob/7b9d9cf4a017f75e513c48143520ae713af6842e/scripts/release.ts#L98)

You can check the error output in [Travis](https://travis-ci.org/sonarwhal/sonar/jobs/286141766)

Mentioning a few people I hope can help with this problem or point me to the right person:
@rbuckton, @andy-ms, @RyanCavanaugh, @mhegazy, @sheetalkamat, @weswigham 

Thanks!

**Comment by Flarna** [comment] 2017-10-12 20:20
I don't know why but it seems if you add `"strict": true` in your tsconfig.json this problem is gone.

**Comment by molant** [comment] 2017-10-12 20:48
Looks like the key is `"strictNullChecks": true` (enabled also via `"strict": true`). Enabling that feature in the compiler makes these errors disappear while creating a few new ones 🙄

Hope this helps find a fix for the declaration file. 

Thanks @Flarna!

**Comment by Flarna** [comment] 2017-10-13 08:45
I'm not sure if this is really an issue in the typings or if it is in typescript itself.
@rbuckton: I think you did quite some work on promisify. Maybe you can you give some hints here?

**Comment by droooney** [comment] 2018-08-23 16:13
The issue is still there. With both typescript 2 and 3. @types/node - v10.7.1.

**Comment by slavafomin** [comment] 2018-11-25 16:29
I'm having the same issue trying to promisify the `S3`: `promisify(s3.getObject)({})`.

> `TS2554: Expected 0 arguments, but got 1.`

```
typescript 3.1.6
@types/node 10.12.10
```

tsconfig.json:

```
{
  "compilerOptions": {
    "lib": ["es2015"]
  }
}
```

I think something is wrong with the typings.

**Comment by G-Rath** [comment] 2018-12-10 01:39
It seems that issues with `promisify` have been popping up all over the place:

https://stackoverflow.com/questions/49086442/typescript-node-promisify-expected-2-arguments-but-got-1
https://github.com/Microsoft/TypeScript/issues/28020
https://github.com/Microsoft/TypeScript/issues/26048

From my understanding, typescript is picking the "first best fit", which happens to be the overload with the same number of parameters as the function you're passing takes (when really it should be the overload with one less than the number of parameters as the function you're passing takes, as the last parameter of that function should be the callback).

I find it interesting that if I navigate to the function definition in WebStorm, it takes me to the *correct* overload that typescript should be using.

From my understanding of the comments on the linked issues, this *may* relate to the order the overloads are defined. I can't say that'll fix it, but it *might*.

[This is](https://github.com/Microsoft/TypeScript/issues/26190) also a possible solution that could be used in the future, once the feature is landed.

**Comment by G-Rath** [comment] 2018-12-10 01:50
Interestingly, looking at the `typescript` handbooks "[does and don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)" page, they say:

> Don’t put more general overloads before more specific overloads:
> Do sort overloads by putting the more general signatures after more specific signatures:

Looking at the code for `promisfy`, to me, the more general overloads are before the more specific ones. I think this is what's causing the problem here, and so the solution is to just flip them all around.

**Comment by MKuranowski** [comment] 2020-06-02 23:46
Is this issue still active?
I'm running TS 3.9.3 and @types/node 12.12.42 and ran into a similar issue, with promisify incorrectly recognizing the number of accepted arguments.

Like @G-Rath mentiones; [typescript](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering) docs advise to put more specific overloads _before_ the generic ones.

Swapping the order of definitions at: <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/000c8aff3889702d3f92b093210aa3f43b3d07e3/types/node/util.d.ts#L96>
seems to resolve this issue.

**Comment by guanzo** [comment] 2020-09-25 06:23
Getting the same issue trying to promisify `zlib` functions, like `const brotliCompress = promisify(zlib.brotliCompress)`

**Comment by orta** [comment] 2021-06-07 14:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:11 UTC
