### ISSUE TITLE
[@types/pino] Clean a bad version on NPM

### ISSUE THREAD

**Issue by Pegase745** [DefinitelyTyped/DefinitelyTyped#43481] opened 2020-03-30 11:22 UTC
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

![image](https://user-images.githubusercontent.com/1678801/77907032-40b65a80-7289-11ea-89ae-81d468ca5c8d.png)

The `latest` version of `@types/pino` is `5.17.0` which is similar to `pino@5.17.0`.

For an unknown reason, there's a `@types/pino@5.20.0` that is present on NPM and that holds a last commit dating `Last updated: Thu, 23 Aug 2018 17:24:04 GMT`.

I wonder if this isn't the possible source of error I stumbled upon, when `@types/pino@*` is required as peerDep.

cc @amcasey @AdamVig

**Comment by AdamVig** [comment] 2020-03-30 14:36
Looks like you're correct. I think a maintainer will need to manually remove that version, if that's possible.

In case it helps, I usually pin `@types/` packages like so:
```json
"@types/pino": "~5.17.0"
```
(with `pino` pinned like `^5.17.0)

**Comment by Pegase745** [comment] 2020-03-30 15:29
It is pinned, and `latest` is linked to `5.17.0` but for some reason I had a colleague who installed the `5.20.0` by mistake.

Do you know who's a maintainer that we can ping for this ?

**Comment by amcasey** [comment] 2020-03-30 17:15
@Pegase745 I'm not familiar with this particular library, but I'd probably start with their GH page: https://github.com/pinojs/pino.  It looks like they have a gitter.

**Comment by ravangen** [comment] 2020-03-30 21:12
This looks to be a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33289

**Comment by Pegase745** [comment] 2020-03-30 22:16
@amcasey it's a definitely typed maintainer we need, not a pino one :)

**Comment by amcasey** [comment] 2020-03-30 22:22
@Pegase745 oh, then it's just the people at the top of the file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts#L3

**Comment by orta** [comment] 2021-06-07 13:33
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:33 UTC
