### ISSUE TITLE
[@types/lodash] Version 4.14.99 causes slow compilation

### ISSUE THREAD

**Issue by DnJealt** [DefinitelyTyped/DefinitelyTyped#23344] opened 2018-02-01 14:14 UTC
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @ericanderson, @Ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

Since the new version, released on 31-1-2018, my webpack build time has increased from 6 seconds to about 35. I came across this problem while updating from TypeScript version 2.6.2 to 2.7.1. 
TypeScript v2.7.1 will raise a syntax error while using types/lodash version 4.14.74. Updating to the latest v4.14.99 fixes this error, but causes the slow loading times. 
Right now my options are either:
- Roll back to TypeScript v2.6.2 and types/lodash v4.14.74, or
- Uninstall types/lodash completely.

I hope you are able to look into this. If you require any more information, feel free to ask :)

**Comment by aj-r** [comment] 2018-02-04 13:07
@andy-ms could this be related to splitting lodash into multiple files?

**Comment by aj-r** [comment] 2018-02-04 13:26
Actually for me, running `tsc` with `@types/lodash@4.14.99` and `typescript@2.7.1`, the compile time is a fraction of a second. Can you give some more details about your setup?

**Comment by DnJealt** [comment] 2018-02-05 13:43
Thanks for replying. npm
At the moment I'm developing a quite large project with TypeScript. It uses webpack with the `ts-loader` plugin to compile all those files into a single bundle.js. I also tried rolling back to `typescript@2.6.2` with `@types/lodash@4.14.99` and it still compiles very slow

**Comment by andy-ms** [comment] 2018-02-05 15:58
Could you try with `4.14.93` which was the last release before it was split into multiple files? Also please test the TypeScript and lodash version updates separately in case it's the new TypeScript version that's slowing you down.

**Comment by DnJealt** [comment] 2018-02-06 09:45
Okay, I have tried to compile this with the following versions.

**With TypeScript** `2.7.1`
- `@types/lodash@4.14.93` - OK. 6 seconds
- `@types/lodash@4.14.94` - OK. 6 seconds
- `@types/lodash@4.14.95` - OK. 6 seconds
- `@types/lodash@4.14.96` - ERROR. 32 seconds and console giving me an ocean full of errors
- `@types/lodash@4.14.97` - SLOW. 31 seconds
- `@types/lodash@4.14.98` - SLOW. 31 seconds
- `@types/lodash@4.14.99` - SLOW. 35 seconds 

I've also done a small test and rolling back to **TypeScript** `2.6.2`:
- `@types/lodash@4.14.95` - OK. 6 seconds
- `@types/lodash@4.14.96` - ERROR. 31 seconds and ocean of errors.
- `@types/lodash@4.14.97` - SLOW. 30 seconds

I'm thinking that the fix that was introduced in `@types/lodash@4.14.97` has caused this slow compilation to happen.
I hope I'm leading you folks in the right direction here :)

**Comment by DomiR** [comment] 2018-02-06 11:22
Just a guess, but this seems to be a webpack configuration error:
@types/lodash@4.14.95 - splitting up files (using namespace) (8b292ec78a8260ec9f76c9b49a1c179a0f66e12a)
@types/lodash@4.14.96 - use module augmentation (0f4014dbf9fc47a372e3471964d12f374772bcfd)
@types/lodash@4.14.97 - using classical style imports (745420a23e9de39bfa0a924d7867a7f0bd26da1d)

Can you look into the webpack output file and see if lodash is imported a bunch of times?
Presumably you are using: `awesome-typescript-loader` did you make sure to add `exclude: /node_modules/,` [Reference](http://marcobotto.com/compiling-and-bundling-typescript-libraries-with-webpack/)? Or maybe just `exclude: /node_modules/@types` when building for the browser.

**Comment by DnJealt** [comment] 2018-02-06 12:52
@DomiRnope, we're using `ts-loader` and not `awesome-typescript-loader`. I did add `exclude: /node_modules/` to the `module.rules` section of the webpack config.

**Comment by wuyiw** [comment] 2018-02-07 06:42
i got the same problem and tested a lot to find out that switching between `@4.14.81` and `@4.14.82` makes a great difference in code autocompletion (yep, both vscode and webpack are inffected), almost instantly vs 3 secs, in vue SFC with only `pick` of `lodash` and skeleton code (reload vscode after switching).
and as i update my dependencies (also `typescript`, `ts-loader`, etc.) to fix lodash type error (now `@4.14.101`) and other bugs, my webpack prod compilation time has increased from ~80s to ~220s, finally i had to set `transpileOnly' in prod build conf and make it done in ~30s, but developing still suffers...

**Comment by wuyiw** [comment] 2018-02-07 08:32
i created a reproduction repo with simplest code, wish it could help:
[https://github.com/wuyiw/ts-lodash](https://github.com/wuyiw/ts-lodash)

**Comment by andy-ms** [comment] 2018-02-07 15:38
@aj-r @DomiR I don't think we have to go back to a single file, but maybe the way we are now goes too for -- for example, `prototype.value.d.ts` and `prototype.valueOf.d.ts` don't really deserve separate files -- they are just two separate methods on the same interface. Having many declarations of the same interface may be making it slow.

**Comment by aj-r** [comment] 2018-02-07 16:11
@andy-ms before, we had the same number of declarations of each interface as we do now - each function re-declared the `LoDashStatic` interface.

Could the performance hit be due to loading more files than before? Or possibly having many declarations of the same `"../index"` module?

By any chance could we improve performance by inverting how the types are defined? i.e. instead of declaring a module in `index.d.ts` and augmenting it, could we have each function's file declare its own interface, and have `index.d.ts` import all of those files and merge them? Something like this:

```ts
// some.d.ts
import common = require("../common");

declare namespace Lodash {
    interface Some {
        <T>(predicate: common.ListIterateeCustom<T, boolean>, collection: _.List<T> | null | undefined): boolean;
       // ... and other overloads
    }
}

declare const some: Lodash.Some;
export = some;
```

```ts
// index.d.ts
import some = require("./some");
// ... and other imports

export = _;
export as namespace _;

declare const _: _.LoDashStatic;
declare namespace _ {
    interface LoDashStatic {
        some: typeof some;
        // ...etc
    }
}
```

I suspect this would at least improve performance of importing a single function (e.g. `"lodash/some"`), since we wouldn't need to load the types for all functions just to get one. I'm not sure if it will improve importing the monolith, though. Also not sure if this would break things for some people.

**Comment by andy-ms** [comment] 2018-02-07 16:23
@aj-r Not sure if that would improve performance. You actually wouldn't need `interface Some` in that case, and could just `declare function some`. Though it might be nice to keep the `LoDashImplicitWrapper` and `LoDashExplicitWrapper` versions of `some` in that same file, and those would still have to be augmentations.

**Comment by aj-r** [comment] 2018-02-07 17:27
I think I'm reproducing the same issue just by running `npm run lint lodash` in the `DefinitelyTyped` repo. I've added `lodash-fp-tests.ts` to test the `lodash/fp` types I'm working on. Here's the interesting part:

- If I modify `tsconfig.json` so it only excludes `lodash-fp-tests.ts`, the task takes a normal amount of time (~1 minute).
- If I modify `tsconfig.json` so it only includes `lodash-fp-tests.ts`, but excludes `lodash-tests.ts`, the task takes about 10 seconds.
- If `tsconfig.json`  contains both test files, the task runs for an extremely long time (~30 minutes) before finally succeeding
- If `tsconfig.json`  contains both test files BUT none of the `.d.ts` files (`index.d.ts`, `add.d.ts`, etc.), the task runs for ~1 minute.

I'll do some testing and see if I can find any way to cut the time down.

**Comment by andy-ms** [comment] 2018-02-07 18:22
@DnJealt Could you get a sample project using ts-loader that has slow load times? Want to be able to see if changes I make would have any effect

**Comment by andy-ms** [comment] 2018-02-07 19:13
@wuyiw In `4.14.81` `_({} as any).pick(['foo', 'bar', 'baz']).value()` was `any`. Now it returns a `Pick` type. It makes sense that this would slow things down as `any` basically turns off type checking. You might still file a bug on typescript if you can find a simple case that's particularly slow.

**Comment by DnJealt** [comment] 2018-02-08 13:17
@thorn0 Can confirm, 41 seconds now.

**Comment by aj-r** [comment] 2018-04-14 20:47
@DnJealt try `v4.14.105`. We have greatly reduced the number of files which should hopefully improve build time.

**Comment by DnJealt** [comment] 2018-04-16 11:14
Sorry for my late reply and not providing a github link even though I said I would do so.

That being said... **Hooray@!**. This did indeed do the trick! Build times are down to 7000milliseconds again! 

Thanks a lot :)

**Comment by aj-r** [comment] 2018-05-19 14:42
@DnJealt glad to hear it :). Want to close this issue then?

**Comment by DnJealt** [comment] 2018-05-22 08:02
Yes please! I'm not seeing the issues coming back now. Thanks for the effort people!
Have a beer :) :beers:

**Comment by aj-r** [comment] 2018-05-22 11:41
@DnJealt you have the power to close it not me :)

**Closed** 2018-05-23 07:42 UTC

**Comment by kelly-tock** [comment] 2019-05-26 14:44
i'm seeing a similary issue to this for @types/lodash@4.14.132. anyone else?

**Comment by kelly-tock** [comment] 2019-05-26 14:46
this commit is pretty large, could it be it?  it was pretty close to the time when my projects build started slowing wayyy down.

**Comment by kelly-tock** [comment] 2019-05-26 14:47
@sandersn  any ideas on if this would cause any slowdown in build times?

**Comment by kelly-tock** [comment] 2019-05-26 14:49
looks like since 4.14.125 something has been slowing down for TS 3.4.x

**Comment by sandersn** [comment] 2019-05-28 16:40
@kelly-tock lodash was often unusably slow on TS3.4. e4f9fd1 was intended to fix that. I expected compile times to be much faster on 3.4 and somewhat faster on 3.3 and 3.5.

Can you open a separate issue and ping me on it there? The next step is to do a 2D comparison of `@types/lodash` versions vs typescript versions, and that will take enough space to describe that it should be on a new bug.

It's also possible that one of the new definitions is actually slower for some usage pattern. Do you use `_.chain` (or other chaining methods) heavily? Those are the only ones that I changed.

**Comment by DnJealt** [comment] 2019-05-29 12:12
I could re-open this issue and rephrase the title if needed

**Comment by sandersn** [comment] 2019-05-29 16:00
@DnJealt It turns out @kelly-tock already did. I just didn't see it until after posting this comment. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35750
