### ISSUE TITLE
Subsequent property declarations must have the same type...

### ISSUE THREAD

**Issue by eluleci** [DefinitelyTyped/DefinitelyTyped#25145] opened 2018-04-19 21:18 UTC
Latest changes by @jacobwgillespie @RyanCavanaugh  may have caused this issue. "@ types/react": "^16.3.11" causes this error because it loads 16.3.12 which breaks. Removing ^ from the version like "16.3.11" fixes the problem.

The TS starter kit of Microsoft fails too. https://github.com/Microsoft/TypeScript-React-Starter

**Comment by jacobwgillespie** [comment] 2018-04-19 22:37
Also as a side note, you may want to check that you don't have multiple versions of `@types/react` inside your `yarn.lock`.  Yarn can incorrectly resolve the package when upgrading: #24711.

There are some fixes mentioned there in that thread, or you can manually edit your `yarn.lock`, remove all the instances of `@types/react` and then re-run `yarn install` to make it re-resolve.

**Comment by allada** [comment] 2018-04-19 23:35
I am running into the same problem. I am pinned to:
"react": "16.3.1",
"react-dom": "16.3.1",
"@types/react": "16.3.9",
"@types/react-dom": "16.0.5",

The build is clean on every run (no package-lock.json file used, instead package.json on every build).

If I had to guess a sub dependency broke it?

**Comment by jacobwgillespie** [comment] 2018-04-20 01:37
@allada I was able to reproduce with your pinned versions using yarn (are you using yarn?) - here's what's going on.

This is the `package.json`:

```json
{
  "dependencies": {
    "@types/react": "16.3.9",
    "@types/react-dom": "16.0.5",
    "react": "16.3.1",
    "react-dom": "16.3.1",
    "typescript": "^2.8.3"
  }
}
```

So you'll get `@types/react` at version 16.3.9 and `@types/react-dom` at version 16.0.5, because you explicitly asked for those.  However, `@types/react-dom` lists a dependency on `@types/react` as the following:

```json
"@types/react": "*"
```

Yarn interprets this as "the latest version of `@types/react`", so it installs an additional version of the package.  You can see this in the resulting `yarn.lock`:

```
"@types/react-dom@16.0.5":
  version "16.0.5"
  resolved "https://registry.yarnpkg.com/@types/react-dom/-/react-dom-16.0.5.tgz#a757457662e3819409229e8f86795ff37b371f96"
  dependencies:
    "@types/node" "*"
    "@types/react" "*"

"@types/react@*":
  version "16.3.12"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.3.12.tgz#68d9146f3e9797e38ffbf22f7ed1dde91a2cfd2e"
  dependencies:
    csstype "^2.2.0"

"@types/react@16.3.9":
  version "16.3.9"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.3.9.tgz#15be16b53c89aac558cf6445774502b2792555ff"
  dependencies:
    csstype "^2.2.0"
```

So you will have versions v16.3.9 and v16.3.12 of the types package simultaneously being used, which causes the error.

There's two ways I know of to fix this:

1. Update to the latest version of the `@types/react` package in your `package.json`
2. Add a resolutions section to your `package.json` to tell Yarn to resolve the dependency differently:

    ```json
	{
	  "resolutions": {
	    "@types/react": "16.3.9"
	  },
	  "dependencies": {
	    "@types/react": "16.3.9",
	    "@types/react-dom": "16.0.5",
	    "react": "16.3.1",
	    "react-dom": "16.3.1",
	    "typescript": "^2.8.3"
	  }
	}
    ```

I tried npm v5.6.0 and it does not seem to have the same problem as it interprets a dependency on `*` as "any".

This is being tracked as an issue with Yarn at yarnpkg/yarn#4489.

**Comment by natew** [comment] 2018-08-06 22:06
@jacobwgillespie I'm still having the issues, even with this:

```
  "resolutions": {
    "@types/react": "16.4.7"
  },
  "devDependencies": {
    "@types/react": "16.4.7",
    "@types/react-dom": "16.0.6"
  },
```

**Comment by jacobwgillespie** [comment] 2018-08-08 01:11
@natew can you post your `yarn.lock` file as a Gist?  (alternatively just look in the `yarn.lock`, remove the duplicate entries for `@types/react` and run `yarn` again)

**Comment by derduher** [comment] 2018-08-29 20:37
I think I figured out a bit of what's going on. I have a `this.onChange = debounce(this.onChange, 1000)` in my constructor but the property function declaration a couple lines down.

**Comment by KharamanV** [comment] 2018-09-12 13:06
> Also as a side note, you may want to check that you don't have multiple versions of `@types/react` inside your `yarn.lock`. Yarn can incorrectly resolve the package when upgrading: #24711.
> 
> There are some fixes mentioned there in that thread, or you can manually edit your `yarn.lock`, remove all the instances of `@types/react` and then re-run `yarn install` to make it re-resolve.

I deleted `yarn.lock`, installed all modules again, and it worked for me, thanks!

**Comment by hughxie** [comment] 2018-10-17 18:32
Fixed by adding resolutions to `package.json` as suggested by @jacobwgillespie
```
"resolutions": {
  "@types/react": "16.3.18"
},
```

**Comment by jacobwgillespie** [comment] 2018-10-22 13:44
> as suggested by @jacobwgillespie

Note that most of the time, what's going on is you have a particular dependency like `@types/react` duplicated in your `yarn.lock`.  For instance if you have a version of the package that is depended on by two other packages, then you upgrade one of those packages, Yarn will oftentimes add a second entry for the shared dep.

The fix for me is usually manually removing the resolutions for `@types/react` from the `yarn.lock` file, then re-running `yarn` so that it's re-locked as a single dependency.

**Comment by mikehardy** [comment] 2020-11-26 11:22
This is an old issue but popped up again just now for me because react went to a semver range that matches ^17 but does not match ^16 that many other dependencies are constrained to.

The 'resolutions' block above does fix it (thank you!)

I'm posting to show the quick-n-dirty linux/bash command line I used to conclusively show this was the problem, and then that it was fixed afterwards:

`for REACT in `find node_modules/|grep '@types/react/package.json'|grep package.json`; do echo $REACT; cat $REACT|grep version; done`

Note that if you are in a monorepo you will need to add the resolutions block in `package.json` at multiple levels perhaps.

Cheers

**Comment by orta** [comment] 2021-06-07 13:39
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:39 UTC

**Comment by stefanpl** [comment] 2021-06-10 08:26
My problem when hitting this error was the following:

I had a `node_modules` folder with a different version of `types/react` in a parent folder (my home directory, actually) of the project. Must have run some npm commands in the wrong place at some point.
Actually the error message was pretty helpful, indicating that `../../node_modules/` was causing the problem. Only took me some minutes to believe it.

Leaving this here, hoping to save somebody some time at some point.

**Comment by mrozsz** [comment] 2021-09-13 20:09
```
npm dedupe
```

For some projects could be helpful this solution for **npm 6 & 7**. Instead of manual update of `package-lock.json` you can just run `npm dedupe`, which will transform your dependency graph and dependencies with "*" are correctly resolved to the one in the `package.json`.

https://docs.npmjs.com/cli/v7/commands/npm-dedupe

**Comment by jzxchiang1** [comment] 2022-01-29 03:05
> ```
> npm dedupe
> ```
> 
> For some projects could be helpful this solution for **npm 6 & 7**. Instead of manual update of `package-lock.json` you can just run `npm dedupe`, which will transform your dependency graph and dependencies with "*" are correctly resolved to the one in the `package.json`.
> 
> https://docs.npmjs.com/cli/v7/commands/npm-dedupe

This worked for me in npm 8.
