### ISSUE TITLE
q: Export declarations are not permitted in a namespace.

### ISSUE THREAD

**Issue by SET001** [DefinitelyTyped/DefinitelyTyped#15573] opened 2017-04-01 20:37 UTC
- [x] I tried using the `@types/q` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (Version 2.3.0-dev.20170401)
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention] @bnemetchek, @AndrewGaspar, @johnnyreilly

using this definitions I'm getting an error:

`../node_modules/@types/q/index.d.ts(187,5): error TS1194: Export declarations are not permitted in a namespace.`

**Comment by andy-ms** [comment] 2017-04-04 15:01
This package has a minimum TypeScript version of 2.2.

**Comment by blacknight811** [comment] 2017-04-07 21:39
@andy-ms thanks for that response. I'm having the same issue.

**Comment by SET001** [comment] 2017-04-08 14:17
My version of `tsc` is `2.3.0-dev.20170401`.
I have replaced file from npm with the one from git repository and now everything works just fine so I suppose this problem related to npm package

**Comment by andy-ms** [comment] 2017-04-10 15:13
Combining this with #15739 it looks like you may not be compiling with the tsc version you think.

**Comment by SET001** [comment] 2017-04-10 19:51
```
set@set:~/www/avalon_express/gameServer$ tsc -v
Version 2.3.0-dev.2017
```

I'm using sublime text2 plugin to compile it but I think it uses same tsc version

**Comment by andy-ms** [comment] 2017-04-10 19:53
Try using the command line compiler to be sure?

**Comment by SET001** [comment] 2017-04-10 20:01
It gives much more errors even with 
```
"typeRoots": ["./node_modules/@types/"]
```
in tsconfig.json
Non of them related to `q` or `lodash`

**Comment by SET001** [comment] 2017-04-10 20:02
`set@set:~/www/avalon_express/gameServer$ cat tsconfig.json 
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "watch": true,
    "types": ["reflect-metadata"],
    "typeRoots": ["./node_modules/@types/"]
  },
  "include": [
    "spec/*.spec.ts",
    "index.ts"
  ]
}
set@set:~/www/avalon_express/gameServer$ ll node_modules/@types/
total 60
drwxr-xr-x  10 set set  4096 Apr  9 12:28 ./
drwxr-xr-x 421 set set 16384 Apr  9 13:16 ../
drwxr-xr-x   2 set set  4096 Apr  1 20:31 jasmine/
drwxr-xr-x 290 set set 12288 Apr  9 12:28 lodash/
drwxr-xr-x   2 set set  4096 Apr  2 11:13 mongodb/
drwxr-xr-x   2 set set  4096 Apr  2 18:10 mongoose/
drwxr-xr-x   2 set set  4096 Apr  1 18:31 node/
drwxr-xr-x   2 set set  4096 Apr  1 23:12 q/
drwxr-xr-x   2 set set  4096 Apr  1 18:44 socket.io/
drwxr-xr-x   2 set set  4096 Apr  1 20:54 socket.io-client/
set@set:~/www/avalon_express/gameServer$ tsc -v
Version 2.3.0-dev.20170401
set@set:~/www/avalon_express/gameServer$ tsc index.ts 
node_modules/inversify/dts/syntax/constraint_helpers.d.ts(3,37): error TS2304: Cannot find name 'PropertyKey'.
services/basicGame.ts(7,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/basicGame.ts(13,3): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/fileStorage.ts(6,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/fileStorage.ts(13,14): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
services/mongoStorage.ts(12,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/mongoStorage.ts(15,14): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
services/mongooseStorage.ts(8,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/mongooseStorage.ts(11,3): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/mongooseStorage.ts(15,26): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
services/tokenAuth.ts(7,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/tokenAuth.ts(10,3): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/tokenAuth.ts(15,14): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
services/websocketMultiplayer.ts(13,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/websocketMultiplayer.ts(17,3): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
services/websocketMultiplayer.ts(18,3): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
`

**Comment by andy-ms** [comment] 2017-04-10 20:16
Clearly, your sublime text plugin is doing something that TypeScript isn't. You need to set up a [`tsconfig.json`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) with appropriate compiler options (in this case, `experimentalDecorators`).

**Comment by SET001** [comment] 2017-04-10 20:33
experimentalDecorators is set up in tsconfig.json. You can see it from my output in previous post.

**Comment by andy-ms** [comment] 2017-04-10 20:34
I think the problem is that you are using `tsc index.ts` instead of just `tsc`.

**Comment by SET001** [comment] 2017-04-10 20:42
Shouldn't it be the same?

**Comment by andy-ms** [comment] 2017-04-10 20:43
`tsc index.ts` compiles one file using the default settings.

**Comment by orta** [comment] 2021-06-07 13:24
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:24 UTC
