### ISSUE TITLE
[@types/react-native] Property 'geolocation' must be of type 'Geolocation', but here has type 'GeolocationStatic'.

### ISSUE THREAD

**Issue by luizvidoto** [DefinitelyTyped/DefinitelyTyped#24573] opened 2018-03-27 23:51 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @timwangdev @kamal @nelyousfi
  
I started a brand new project, installed the newest versions and when I try to compile it gives this error:  
  
`
node_modules/@types/react-native/index.d.ts(8731,18): error TS2717: Subsequent property declarations must have the same type.  Property 'geolocation' must be of type 'Geolocation', but here has type 'GeolocationStatic'.
`
  
My dependencies are:   
  
"dependencies": {  
    "react": "^16.2.0",  
    "react-native": "^0.54.3"  
  },  
"devDependencies": {  
    "@ types/react": "^16.1.0",  
    "@ types/react-native": "^0.52.20",  
    "concurrently": "^3.5.1",  
    "rimraf": "^2.6.2",  
    "tslib": "^1.9.0",  
    "typescript": "^2.8.1"  
  }  
  

os: Windows 10
node: v8.2.1

**Comment by iRoachie** [comment] 2018-03-28 01:15
As a temporary workaround set `skipLibCheck` to true in your tsconfig

**Comment by zhengjingt** [comment] 2018-03-29 02:44
downgrade typescript to '2.7.1' fixed it

**Comment by timwangdev** [comment] 2018-03-29 03:02
remove `dom` types from tsconfig should bypass this.

**Comment by vovkasm** [comment] 2018-04-02 05:36
@timwangdev If I remove `dom` from libs, then many types will be undefined, e.g. `FormData`, `XMLHttpRequest`, `ProgressEvent`, `WebSocket`, ...
So, also I think it right direction to do, this is not solution currently. We should first add full RN environment in `react-native.d.ts`

**Comment by VincentLanglet** [comment] 2018-04-06 23:01
Does anyone have a clue about how to correctly fix the error without use `skipLibCheck` ?
I can take time to make the PR.

**Comment by Javascript-Ninja** [comment] 2018-04-12 11:12
@VincentLanglet  `typescript@2.7.2`  [lib.dom.d.ts](https://github.com/Microsoft/TypeScript/blob/v2.7.2/lib/lib.dom.d.ts#L3907)  declare Geolocation, but `@types/react-native` also declare Geolocation too.

**Comment by tonyxiao** [comment] 2018-04-12 23:43
Current testing workaround via removing from react native via patch-package https://github.com/ds300/patch-package

**Comment by Slessi** [comment] 2018-04-27 15:15
further to @tonyxiao 's comment, the follow patch works:

```patch
patch-package
--- a/node_modules/@types/react-native/index.d.ts
+++ b/node_modules/@types/react-native/index.d.ts
@@ -8533,8 +8533,9 @@ export type Clipboard = ClipboardStatic;
 export var DatePickerAndroid: DatePickerAndroidStatic;
 export type DatePickerAndroid = DatePickerAndroidStatic;
 
-export var Geolocation: GeolocationStatic;
-export type Geolocation = GeolocationStatic;
+// https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24573
+// export var Geolocation: GeolocationStatic;
+// export type Geolocation = GeolocationStatic;
 
 /** http://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html */
 export var I18nManager: I18nManagerStatic;
```

**Comment by josauder** [comment] 2018-05-08 12:53
I am having the same issue but unfortunately the error persists with either (or both) `"typescript": "2.7.2"` and `"skipLibCheck": true`:

My dependencies:
``` 
 "dependencies": {
    "@types/jest": "^22.2.0",
    "@types/react": "^16.3.13",
    "@types/react-native": "^0.52.16",
    "concurrently": "^3.5.1",
    "react": "^16.3.2",
    "react-art": "16.3.2",
    "react-dom": "^16.3.2",
    "react-native": "0.55.0",
    "react-native-scripts": "1.14.0",
    "react-native-web": "0.6.0",
    "react-scripts": "1.1.4",
    "typescript": "^2.7.2"
  },
```

What am I missing? I also could not find which versions of `@types` are recommended with which versions of the actual libraries. 

Thanks for you help!

**Comment by fbartho** [comment] 2018-05-23 22:58
`skipLibCheck: true` worked for our repo, however I'm subscribing to this thread so I hear when it's fixed in `@types/react-native` 😉

**Comment by henrikra** [comment] 2018-07-06 09:59
Please people DO NOT 🔴  use `"skipLibCheck": true` it your `tsconfig.json` file! It will make your TypeScript less useful!

The problem in this case is that BOTH dom and react-native types have global `Navigator` object. This is correct BUT TypeScript added `geolocation` object to `Navigator` object between TS version 2.7.2 and 2.8.1. So now when BOTH dom and react-native are trying to set different type for geolocation object inside of Navigation the whole thing breaks ⚠️ 

I honestly don't know solution for this problem at the moment. This is because react-native types depends on dom types. So you can't take dom types away from your project. But at the same time you can't type globally marked object's properties to different type later 😢 

The problem is now debugged but now we need more help to get proper solution.

**Comment by iRoachie** [comment] 2018-07-06 10:15
How does `skipLibCheck` make typescript less useful?

**Comment by binki** [comment] 2018-07-07 15:15
@iRoachie If you use any types from definitions which are broken, certain parts of those APIs will return and accept `any`. If you run type checks are part of CI to increase your confidence that your program will run and reduce the amount of debugging to trace down issues, any code using such APIs will not be marked as incorrect by TypeScript. You will not know that this is happening if you enable `skipLibCheck`.

**Comment by henrikra** [comment] 2018-07-16 10:08
Am I still only one trying to solve this? 🤔

**Comment by henrikra** [comment] 2018-07-16 10:13
I can't think of any other solution that React Native should move their geolocation api as import and not global. This way we can type the exported navigator anything we want. But this requires JS changes and it will be breaking change

**Comment by henrikra** [comment] 2018-07-20 11:30
I have made possible solution for this in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27436 🎉

**Comment by henrikra** [comment] 2018-07-21 08:45
Looks like the solution is to 
1. remove `dom` from `lib` array at `tsconfig.json` file.
2. update `@types/react-native` to `0.56.4`
3. fix compile errors
4. profit! 🎉

**Comment by ex3ndr** [comment] 2018-07-23 11:01
@henrikra For some reason removing dom and adding right typings fro react-native doesn't solve problems since now dom bindings are missing.

**Comment by jcyh0120** [comment] 2018-07-24 14:07
Does this require updating react-native to 0.56.x ? or just update the type definition.

**Comment by henrikra** [comment] 2018-07-24 14:30
No it requires only to update the types like I wrote ;)

**Comment by seanyu4296** [comment] 2018-07-30 08:51
Do you maybe have a sample tsconfig.json for a react-native project? @henrikra I'm pretty new to typescript and i can't seem to figure out how to remove "dom" from the lib array since it is part of most lib config.

**Comment by iRoachie** [comment] 2018-07-30 12:35
@seanyu4296 You can follow the steps in this guide https://github.com/ds300/react-native-typescript-transformer

**Comment by seanyu4296** [comment] 2018-07-30 14:53
thank you @iRoachie im currently using that right now and its working. Not sure if this is the right place to ask but i noticed when i used the tsc in vscode it does not work. Is it possible to configure vscode to use react native ts transformer?

**Comment by iRoachie** [comment] 2018-07-31 01:25
I didn't have to do any additional setup with VSCode. What issues are you having?

**Comment by henrikra** [comment] 2018-08-25 09:13
@luizvidoto This can be closed btw

**Comment by alloy** [comment] 2018-08-26 10:36
@henrikra Thanks, I’ll do so now 👍

**Closed by alloy** 2018-08-26 10:36 UTC
