### ISSUE TITLE
How to use feature of TypeScript 2.8 in @types/node

### ISSUE THREAD

**Issue by KSXGitHub** [DefinitelyTyped/DefinitelyTyped#25866] opened 2018-05-18 11:09 UTC
I was trying to create a pull request ([this one](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25864)). In this pull request, I used conditional types (which is only available in TypeScript 2.8 and above) to _strictly determine whether `SpawnSyncReturns.stdout` is `null`, `Buffer` or `string` base on `options.inherit` and `options.encoding`_.

It was simple in the beginning, but linter told me that it isn't compatible with TypeScript version 2.6, so I added `// TypeScript Version: 2.8` to `types/node/index.d.ts`, this in turn caused other packages that depend on earlier TypeScript version fail, I then proceed to add that header to every packages present, and it still fails.

I want to ask:
1. Is there any other solution that doesn't require TypeScript 2.8?
2. If not, how else should I implement this feature?

**References:**
* First commit: https://github.com/KSXGitHub/DefinitelyTyped/commit/37c4d43a7f4a7ae83fee7db6803d9b3547050913
* Commit before adding `// TypeScript Version: 2.8` to everything: https://github.com/KSXGitHub/DefinitelyTyped/commit/5418fa60464e035530b6db5e8c17f76c9335d2d0
* Commit which adds `// TypeScript Version:2.8` to all packages: https://github.com/KSXGitHub/DefinitelyTyped/commit/5418fa60464e035530b6db5e8c17f76c9335d2d0 — This commit also blocks me from accessing it in GitHub site (I see unicorn every time I try to).

---

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @Alorel @parambirs @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @DeividasBakanas @kjin @alvis @OliverJAsh @eps1lon @Hannes-Magnusson-CK @jkomyno @hoo29 @n-e @ajafff

If you do not mention the authors the issue will be ignored.

**Comment by KSXGitHub** [comment] 2018-05-18 11:26
@zspitz I cannot access the old pull request for some reason so let's discuss here. The reason for update TypeScript version for all packages is as explained above.

**Comment by zspitz** [comment] 2018-05-20 19:39
@KSXGitHub I've noticed that pull requests with a large number of @-mentions often cause timeouts, this is probably why you can't access the pull request.
I was surprised because the type definitions that I contribute to (`activex-*`) have no dependencies on other packages, and should therefore not need to be modified.
I think you'll have no choice but to go through every package error and fix it, as it makes sense that many other packages would depend on the NodeJs types package, and thus also require a version bump.
The DefinitelyTyped repo has an `npm run test` task which you can run locally and which tests all the changed modules and their dependencies, and flags any errors. You may find that the problem is unrelated to the version bump.

**Comment by KSXGitHub** [comment] 2018-05-21 03:00
@zspitz 

> I was surprised because the type definitions that I contribute to `(activex-*)` have no dependencies on other packages, and should therefore not need to be modified.

It is because I don't actually open each and every package to edit them but use a [script](https://gist.github.com/KSXGitHub/d20b8162266e36fea3243ba4e0efd052) to do it automatically.

> I think you'll have no choice but to go through every package error and fix it

Too much work, I rather find an alternate solution.

**Comment by orta** [comment] 2021-06-07 13:18
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:18 UTC
