### ISSUE TITLE
@types/knex pg Connection Config missing

### ISSUE THREAD

**Issue by nihiluis** [DefinitelyTyped/DefinitelyTyped#18920] opened 2017-08-13 20:38 UTC
@tkqubo @baronfel 
Judging from knex Config pg Connection config is missing.

```
connection?: string | ConnectionConfig | MariaSqlConnectionConfig |
            MySqlConnectionConfig | MsSqlConnectionConfig | Sqlite3ConnectionConfig | SocketConnectionConfig;
```

is thisa bug or perhaps correct?

**Comment by baronfel** [comment] 2017-08-25 19:51
It looks like they just haven't been contributed yet. Can you take a look at the thread [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15488) and see if you'd be willing to submit a PR?

**Comment by nihiluis** [comment] 2017-08-25 22:01
I couldn't find anything Postgres specific beyond ConnectionConfig in either Node postgres or Knex

version can be used to specify the postgres version for non standard dbs, it's missing in `Config`. I don't feel comfortable making a PR with this kind of repo, sorry.

```
    interface Config {
        debug?: boolean;
        client?: string;
        dialect?: string;
        version?: string;
        connection?: string | ConnectionConfig | MariaSqlConnectionConfig |
            MySqlConnectionConfig | MsSqlConnectionConfig | Sqlite3ConnectionConfig | SocketConnectionConfig;
        pool?: PoolConfig;
        migrations?: MigratorConfig;
        acquireConnectionTimeout?: number;
        useNullAsDefault?: boolean;
        searchPath?: string;
    }
```

**Comment by 100GPing100** [comment] 2018-06-22 17:25
It's unclear for me wether this is fixed with #20584 or not, seems like it is, but the issue is open, what's missing here?

**Comment by taybin** [comment] 2019-06-12 13:04
This can be closed as knex provides its own definitions now.

**Comment by nihiluis** [comment] 2019-06-14 10:48
sorry for not responding.

**Closed** 2019-06-14 10:47 UTC
