### ISSUE TITLE
@types/react Make it possible to render a string from a functional component

### ISSUE THREAD

**Issue by janb87** [DefinitelyTyped/DefinitelyTyped#20544] opened 2017-10-13 08:00 UTC
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, ...

With current typings it is not possible to create a stateless component which returns a string, number, boolean... (new in React 16)

```typescript
import React from 'react'

const TestString = () => {
    return 'Test String Component'
}

const Component = () => (
    <div>
        <TestString/>
    </div>
)
```

Error I get:
```
JSX element type 'string' is not a constructor function for JSX elements.
```

The first problem is that currently in the typings a stateless component cannot return anything else besides an instance of a `React.Element`. This should be changed to (I think, I've based it upon the changes on the `render`method, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L422)

```
interface StatelessComponent<P = {}> {
        (props: P & { children?: ReactNode }, context?: any): ReactElement<any> | Array<ReactElement<any>> | string | number | null;
        propTypes?: ValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
}
```

Second problem is that behind the scenes the compiler will convert the jsx to `React.createElement('Test String Component', null)``

I get a compiler error that is saying that this is not a valid value. Seems that it has to be one of the values specified in following list: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L3465.

Any thoughts on how this can be fixed?

**Comment by janb87** [comment] 2017-10-13 08:27
@DovydasNavickas @sandersn @tkrotoff @andy-ms @ddwwcruz @apexskier @devrelm @RyanCavanaugh @richseviora @onigoetz @minestarks @yuit @sboehler @plantain-00 @p-jackson @miracle2k @voxmatt @morcerf @janechu @gaspard @vbfox @ericanderson @dyst5422 @rapilabs @cynecx @newyankeecodeshop

**Comment by apexskier** [comment] 2017-10-16 15:24
We could probably define [stateless](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L320) and [class based](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L287) components as returning [`ReactNode`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L164) now. I haven't migrated to v16 yes, so that would need testing.

Looks like there's already a PR open. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20097/files

**Comment by Levino** [comment] 2017-10-30 13:25
Is this being worked on atm?

**Comment by polco** [comment] 2018-02-05 03:52
I tried changing it but it breaks the JSX parser if the return type is `string` `boolean` or `undefined`.

**Comment by vbfox** [comment] 2018-02-05 12:04
There is a TypeScript PR in progress about it : https://github.com/Microsoft/TypeScript/pull/20239

**Comment by polco** [comment] 2018-02-05 14:53
Cool, thanks for the update!

**Comment by jasonrhodes** [comment] 2018-08-29 18:35
What's the latest on this? I see the TS PR mentioned above (https://github.com/Microsoft/TypeScript/pull/20239) is now closed/locked. I ran into the same thing today, new to typescript + react, and wondering why my components can't return strings suddenly...

**Comment by sonnyp** [comment] 2018-10-30 08:40
A workaround is to return a fragment.

`return <>0</>`

**Comment by zheeeng** [comment] 2018-11-03 08:07
Any news on this issue?

**Comment by eltonio450** [comment] 2019-01-18 15:32
Hello, any update or hints on this please :) ?

**Comment by eps1lon** [comment] 2019-02-01 09:46
This is essentially a duplicate of #18912. Once  Microsoft/TypeScript#21699 is resolved we should be able to use `ReactNode` as a valid return type for function components which includes `string` and `boolean`.

**Comment by monfera** [comment] 2019-04-23 13:51
To generalize the issue, why should it even assume what's legit for React? With the `@jsx` / `@jsxFrag` Babel pragmas, an approach like [this](https://medium.com/@bluepnume/jsx-is-a-stellar-invention-even-with-react-out-of-the-picture-c597187134b7) JSX can work with whatever functions. So it's not even that only strings should be admitted; any return value can be legit, constrained only by the specific use. React is important but it's just a specific rendering library.

**Comment by bryanrasmussen** [comment] 2019-07-24 09:46
This has been open for nearly a couple years now, is there any solution?

About the suggested return a fragment <>StringValue goes here</> - I guess I am having trouble understanding how I get the string  value, or any other type of value that is not a React.Element really to use in my code - for example if I have a function named Howdy returning <>"hello"</> and inside of componentDidMount I have 

const whatSays = <Howdy/>

how would I get the string value out of the fragment. I'm not seeing a way, it feels like any way to get around this is an extremely ugly hack and considering that the Hooks api is often used with returning just strings or other non React Element values - for example https://github.com/pankod/react-hooks-screen-type/blob/master/src/index.js
it seems to me that this bug really makes the Hooks api unusable, and as such makes Typescript a poor fit for React.

**Comment by eps1lon** [comment] 2019-07-24 10:05
> This has been open for nearly a couple years now, is there any solution?

@bryanrasmussen See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544#issuecomment-459665668 for the last update.

**Comment by leidegre** [comment] 2020-02-27 12:22
This issue is making us write a-typical React code to work around limitations imposed by TypeScript. The only way to squash these errors in a sinable TypeScript way is to introduce additional DOM elements and/or React.Fragments these add overhead (generate garbage) and they aren't needed.

This isn't always a problem by it crops up every now and is triggered when you return valid things from React components that aren't exactly JSX.Element, for example, an array.

I'd be happy with a sensible type annotation to help things along but I have to squash these with imperfect things like additional layers and/or `any`. Not good.

**Comment by BoogalooJB** [comment] 2020-06-04 07:31
Wrapping with an unnecessary `React.Fragment` has a (insignificant) cost at runtime.

Could this be another work around with no runtime penalty ?
```tsx
import React, { ReactElement } from 'react'

const TestString = () => {
  return ('Test String Component' as unknown) as ReactElement
}

const Component = () => (
  <div>
    <TestString />
  </div>
)

export default Component
```

**Comment by leidegre** [comment] 2020-06-04 08:23
> Wrapping with an unnecessary `React.Fragment` has a (insignificant) cost at runtime.

It's a compromise. Still, would like to see better typing for this. Also, not insignificant, depends on context. A few fragments don't hurt, a lot of them will.

**Comment by Levino** [comment] 2020-06-04 11:31
> Wrapping with an unnecessary `React.Fragment` has a (insignificant) cost at runtime.
> 
> Could this be another work around with no runtime penalty ?
> 
> ```tsx
> import React, { ReactElement } from 'react'
> 
> const TestString = () => {
>   return ('Test String Component' as unknown) as ReactElement
> }
> 
> const Component = () => (
>   <div>
>     <TestString />
>   </div>
> )
> 
> export default Component
> ```

Yeah, but then I also lose the type checking for the function. I mean I can also remove TS from my project without any runtime penalty but then I have no type checking. So your workaround is surely working but just breaks the purpose of TS. Casting to `any` is like saying "Okay, then lets throw out the breaks. Who needs this anyhow?".

**Comment by vadimyen** [comment] 2020-08-28 12:30
So, any news on fix?

**Comment by orta** [comment] 2021-06-07 14:11
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 14:11 UTC

**Comment by adamdicarlo** [comment] 2021-06-28 18:40
This discussion thread is relevant: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/53846

I don't see any other discussion threads for this topic.

(I'm hoping GitHub will cross-link the discussion back here like it does when mentioning PRs/issues. 🤞🏼)

**Comment by Levino** [comment] 2021-06-29 05:56
> (I'm hoping GitHub will cross-link the discussion back here like it does when mentioning PRs/issues. 🤞🏼)

Did not work.
