### ISSUE TITLE
@types/jquery Cannot find name 'JQuery'.

### ISSUE THREAD

**Issue by justforuse** [DefinitelyTyped/DefinitelyTyped#24473] opened 2018-03-23 07:24 UTC
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu 

Hi leonard, I use `@types/jquery` like this way:
```
import {JQuery} from 'jquery';
const filterPathItems: JQuery = $(this.elementRef.nativeElement).find('.filter-path-item');
```
But there is an error: `Cannot find name 'JQuery'.`
and the `JQuery` is not in `jquery`.
I wonder what is the type of jquery element.

We are not allowed use `any` type definition...

hope your replys.

**Comment by leonard-thieu** [comment] 2018-03-24 19:20
`JQuery` is available globally. I cannot reproduce your issue (https://github.com/leonard-thieu/DefinitelyTyped-issue-24473).

Could you post a minimal and complete repro?

**Comment by orta** [comment] 2021-06-07 13:41
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Closed by orta** 2021-06-07 13:41 UTC
